### ISSUE TITLE
[BUG]: Clicking outside of selection field does not auto-close dropdown

### ISSUE THREAD

**Issue by PiotrKrzyzek** [activepieces/activepieces#1003]
**Describe the bug**
On fields where I can select data from a previous step, the dropdown modal shows everything nicely but it does not close if I click outside of it. The (X) does close it, but that's about it. This runs contrary to expected bevior seen in other similar modals in this system and others.

Example screenshot of a field where this happens: 
<img width="371" alt="Screenshot 2023-04-04 at 8 16 35 PM" src="https://user-images.githubusercontent.com/602636/229956755-3097387c-3dee-4e65-906c-eeb4b717a5d4.png">

If I click that X icon, that modal closes. But clicking anywhere in the whiteboard area or even on another selection field does not close the current one. Here is a screenshot of the field above the task list showing above the currently 'stuck open' modal:
<img width="416" alt="Screenshot 2023-04-04 at 8 18 50 PM" src="https://user-images.githubusercontent.com/602636/229956885-b78d5435-073f-4482-afd2-4320a1d36937.png">

**To Reproduce**
1. Create any step that can access previous step data
2. Open one of the fields that accesses previous step data
3. Click on any other selection field or anywhere in the screen

**Expected behavior**
Modal should close when clicking away from it.

**Comment by ashrafsamhouri** [comment]
@abuaboud @AbdulTheActivePiecer I am receiving increasing feedback about this. Can we fix it today?
