### ISSUE TITLE
[BUG]: launching activepieces from docker instructions displays confusing connection information

### ISSUE THREAD

**Issue by PiotrKrzyzek** [activepieces/activepieces#1006]
**Describe the bug**
When launching Activepieces from the console (or in other ways where you can see the output log), it shows connection information that can be potentially wrong or is confusing.

This is a double bug issue report.

First, Activepieces lists two seperate connection info. Before the big ASCII ACTIVEPIECES logo in the log, there is a bit of text that says something similar to the service is active on http://localhost:3000

Then after the ASCII logo, it prints out the enviroment variable set for the url. Though I believe it is by default setup by the tools/deploy.sh script. Though my guess it many won't test it locally. Though it saying localhost isn't the problem, it is that it assumes the default port will be '8080' rather than the port 80 that the service runs on. It would be good if we add some qualifier or explanation text around this to help users understand that it was (initially) an auto-set url and/or where to find it to get a better idea on where to change it.

**To Reproduce**
1. Follow docker install instructions
2. Launch with `docker compose up` (NOT in deamon mode)
3. See console output

**Comment by abuaboud** [comment]
Edited the message on the attached PR.
