### ISSUE TITLE
[BUG]: Clicking the CONNECT button on a new connection uses secrets.activepieces.com as the redirect URL for apps rather than the APP_URL

### ISSUE THREAD

**Issue by PiotrKrzyzek** [activepieces/activepieces#1011]
**Describe the bug**
In this particular case, I wanted to connect ClickUp to my app. Though, upon trying to add a new Clickup connection I'm greated with the standard Connect modal. So far so good. Though, upon clicking the connect button (let us ignore the "I would like to use my own app credentials" link and feature), it properly opens Clickup to authorize the connection, though it seems to be using a ActivePieces domain as the redirect instead of our own.

Example URL used (with secret date hidden out):

`https://app.clickup.com/api?response_type=code&client_id=[some client id stuff here]&redirect_uri=https:%2F%2Fsecrets.activepieces.com%2Fredirect&access_type=offline&state=[fun hash]&prompt=consent&scope=`

We, the gentle open-source community folk, don't know nor control this `secrets` subdomain, so we don't know if it's secure. This domain is also not mentioned in the docs. 

If for certain apps, like ClickUp, we HAVE to use an ActivePieces hosted app (because Clickup requires that) for automated authentication and connection, then it would be good to know this ahead of time and in the docs.

Though if this automatic authentication and connection can be handled in a self-hosted environment, then it should automatically use the redirect URL that uses our APP_URL as the base.

**To Reproduce**
Steps to reproduce the behavior, and in this case it's ClickUp Step trigger:
1. Go to a Workflow
2. Click on a Trigger or step and click on Add Connection for the authentication selection area
3. Click CONNECT
4. See the URL in the pop-up window which uses secrets.activepieces and nor our APP URL.

**Comment by abuaboud** [comment]
@PiotrKrzyzek, this is a technical limitation. Using activepieces apps requires a secrets service to prevent the exposure of activepieces app secrets. There is no data stored in this service; it simply acquires the token and sends it back to the self-hosted environment.

I suggest that adding a note to the connection dialogue could help people make a decision. However, we found that this might be confusing for most users. What do you think? Do you have any suggestions for the text?

**Comment by abuaboud** [comment]
Added option to disable the cloud oauth option from the configurations.

Thank you for opening the suggestion.
