### ISSUE TITLE
[BUG]: can't save SMTP authentication settings

### ISSUE THREAD

**Issue by dennis-tra** [activepieces/activepieces#1012]
**Describe the bug**

Can't save SMTP settings.

**To Reproduce**
1. Go to a flow
2. Create an SMTP action
3. Try to configure an authentication
4. Fill in details
5. click on save

**Expected behavior**

It should save the details and close the dialogue.

**Actual behavior**

The "save" button does nothing.

**Screenshots**

<img width="483" alt="image" src="https://user-images.githubusercontent.com/11836793/230023011-ad75db61-7dbc-43d9-bed2-4573c5ccff16.png">

**Additional context**

Maybe the reason is that the [`port`](https://github.com/activepieces/activepieces/blob/c2ba97de769ce719601f510bc99b8e4b96070e3c/packages/pieces/smtp/src/lib/actions/send-email.ts#L26) field is required but not visible in the dialogue.

**Comment by abuaboud** [comment]
The number property is not showing in custom authentication, I pushed a temporary fix for the smtp piece, remove it and try to add it again to get the new version.

https://github.com/activepieces/activepieces/pull/1016

In the meantime will keep this issue open to track number property in custom auth.
