### ISSUE TITLE
[BUG]: Shopify Connection Fails

### ISSUE THREAD

**Issue by Wingman3434** [activepieces/activepieces#1020]
**Describe the bug**
When creating a new Shopify connection I get an error in the pop-up window.
"Oops, something went wrong.
What happened?
Oauth error invalid_request: The redirect_uri is not whitelisted"

**To Reproduce**
1. Create new Shopify flow with new order
2. New connection, enter shop name
3. Click connect
4. Error is in popup window

**Expected behavior**
AP requests access from shopify.

**Screenshots**
![Screenshot 2023-04-06 144355](https://user-images.githubusercontent.com/1365628/230273966-c788d640-c55d-4af6-be1a-b8c4b1ff1fee.png)

**Additional context**

**Comment by abuaboud** [comment]
Thank you for reporting the issue, Fixed, It should be working now.

I will close the issue, feel free to reopen If it's not working.
