### ISSUE TITLE
Atlassian Jira Cloud

### ISSUE THREAD

**Issue by mTrax-** [activepieces/activepieces#1024]
**Describe your usecase.**
We would like to use different services from Jira (Jira Software, Jira Service Management, ...) and get notification (to Discord for example) when a new issue / ticket / ... is created or updated. 
It would be a nice to have to create directly issue / ticket from a channel in Discord.

**Describe alternatives you've considered**
We are currently using Zapier with integrated connectors and also legacy webhook.

**Comment by abuaboud** [comment]
Thank you for raising the issue!  There is a similar issue added to the board.

https://github.com/activepieces/activepieces/issues/608

We have been receiving numerous requests lately, but we are working hard to create as many pieces as possible. 🙌 Hopefully, contributors can also pick this up and join in on the fun! 

I am closing this issue to keep the discussion on this ticket: https://github.com/activepieces/activepieces/issues/608
