### ISSUE TITLE
UX Improvement: Data To Insert Dropdown

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#1034]
**Is your feature request related to a problem? Please describe.**
I recently encountered an issue in which the Data to Insert dropdown menu can become to small to use: https://img.shaypunter.co.uk/h4KCLkF.png

This can be solved by scrolling on the side, but I think there is a better solution to be had.

**Describe the solution you'd like**
I believe a better solution would be to introduce some form of a larger editor, which would enable you to allocate more elements into it.

For an idea on how it could look, please refer to my bad drawing: https://img.shaypunter.co.uk/1rDQYWb.png

I could see this having several improvements such as:
- Helping to navigate larger 'Data to Insert' trigger dropdowns given it'll have a dedicated sidebar
- Helping users to write out more longer form content easily instead of on a smaller box

**Comment by ashrafsamhouri** [comment]
Thanks @ShayPunter I'll work on this with our designer, there are a couple of issues with the current automcomplete dropdown, you're right.

**Comment by ashrafsamhouri** [comment]
@abuaboud I'll check this next week with our designer
