### ISSUE TITLE
[BUG]: isolate cannot proxy

### ISSUE THREAD

**Issue by stephenc01** [activepieces/activepieces#1037]
**Describe the bug**
Docker on Debian

      "type": "Error",
530
      "message": "Command failed: /usr/src/app/packages/backend/src/assets/isolate --dir=/usr/bin/ --dir=/etc/=/usr/src/app/packages/backend/src/assets/etc --share-net --box-id=998 --processes --wall-time=600 --meta=/var/local/lib/isolate/998/box/meta.txt --stdout=_standardOutput.txt --stderr=_standardError.txt --run  --env=AP_ENVIRONMENT /usr/local/bin/node activepieces-engine.js EXECUTE_TRIGGER_HOOK\nCannot run proxy, clone failed: Operation not permitted\n",

**To Reproduce**
Saving

**Expected behavior**
works

**Screenshots**

**Additional context**

**Comment by abuaboud** [comment]
Are you using docker compose file? It happens when the docker is not running at privileged mode

**Comment by stephenc01** [comment]
Hey, i am. i put the privileged=true back in the compose file. Its for testing right night, ill purge and rebuild and see if it resolved it.

`version: '3.4'
services:
  app:
    privileged: true
    image: activepieces/activepieces:latest
    deploy:
      placement:
        constraints:
          - "node.Labels.worker==true"
      mode: replicated
      replicas: 1
      update_config:
        order:
          stop-first
    restart: unless-stopped`

**Comment by abuaboud** [comment]
@stephenc01 Sad to hear that, privileged is requirement for us to make sure flows are running in sandbox environment.

**Comment by abuaboud** [comment]
@stephenc01 Let me know your thoughts:

https://github.com/activepieces/activepieces/issues/1170
