### ISSUE TITLE
[BUG]: Step auto naming misbehavior

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1069]
**Describe the bug**
In some cases, the autonaming of the step in the flow relapse and shows a generic name like "Trigger". I was able to reproduce one case but I'm unsure if it's the only one or only a symptom of something deeper.

**To Reproduce**
1. Add a Schedule trigger.
2. Choose "Every 1 hour".
3. Change to cron expression.
4. Start typing your cron expression.
5. The name of the step will go back from "Every 1 hour" to "Trigger".

**Expected behavior**
It should show maybe "Cron expression".

**Screenshots**
<img width="1680" alt="Screenshot 2023-04-16 at 01 07 03" src="https://user-images.githubusercontent.com/97393596/232256798-c86a76dd-4b09-4c12-946f-4f7052bf8d29.png">

**Comment by abuaboud** [comment]
This should be fixed now.
