### ISSUE TITLE
[BUG]: Autocomplete goes under the fold of the Sample Data pane

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1071]
When the "Insert Data" dropdown is open, it goes under the Generate Sample Data pane as in the screenshot. It should always be on top of everything else.

<img width="402" alt="Screenshot 2023-04-16 at 01 57 20" src="https://user-images.githubusercontent.com/97393596/232259125-a65a258d-dc6b-4d44-977b-46fd02152eda.png">

**Comment by abuaboud** [comment]
@ashrafsamhouri I think the root issue is the resolution here, I think we should move load data to somewhere else.

**Comment by ashrafsamhouri** [comment]
@abuaboud Full perspective (this is from my screen, but the screenshot was partial):
<img width="412" alt="Screenshot 2023-04-16 at 02 04 02" src="https://user-images.githubusercontent.com/97393596/232259217-79375e03-bc4f-4b5d-9eb9-bad7b66dd514.png">

**Comment by ashrafsamhouri** [comment]
And to confirm, the user who saw the issue had a screen height of 1010, so the issue is independent from the resolution issue.

**Comment by abuaboud** [comment]
Do you know  if the user has dragged the testing bar all the way up, @ashrafsamhouri? I'm curious about how the view would appear if the trigger had two or more text fields.

**Comment by ashrafsamhouri** [comment]
Yes they did @abuaboud

**Comment by ashrafsamhouri** [comment]
Actually, here is what happened:
The user tested the trigger, and the pane increased height automatically although its content was short.
Ideally, the pane shouldn't expand in height further than its content's height.
