### ISSUE TITLE
Approval Step

### ISSUE THREAD

**Issue by nileshtrivedi** [activepieces/activepieces#1078]
Business Processes are real-world workflows spanning multiple actors. They are like programs, running on multiple processors which might be individual humans, or groups of people or computer systems. People can be outside the org (eg: customers, vendors).

Here is an example workflow where people and systems collaborate to achieve something: 
![image](https://user-images.githubusercontent.com/19304/232374942-f2f7d1f0-a4af-491c-a5c3-277073d4d610.png)

In this frame of thinking, a [company is like an operating system for business processes](https://youtu.be/gXep-LwPvw8). 

Because these workflows can have branches, loops, events etc, they are very much like programming languages. There exist standards like BPMN, SMMN, DMN etc and various software like jBPM, Camunda, Flowable to model and execute these.

It would be really great to be able to create workflows like these in ActivePieces because so much of the required work has already been done.

Essentially, the system should support new worker types which represent people/groups of people identified by a communication channel like email/SMS/API call etc and to which tasks can be delegated. These workers are slow, so the system should not spend resources while waiting for an event. For eg: "A ticket should be escalated to the manager if it is not solved in 7 days". 

This will make it possible to embed ActivePieces based automations right inside actual business processes while making use of ActivePieces's existing infra that supports branching/looping/delay and a canvas-based workflow editor.

**Comment by nileshtrivedi** [comment]
Some useful resources:

- http://www.workflowpatterns.com/patterns/control/
- http://www.workflowpatterns.com/patterns/resource/
- https://mainthing.ru/item/813/
- https://raw.githubusercontent.com/bokmann/stonepath/master/docs/stonepath.pdf

**Comment by abuaboud** [comment]
Hi @nileshtrivedi, I am considering a new feature for the piece framework that could be useful. 

To elaborate, suppose you wish to proceed with a task based on approval, within the framework, you can incorporate a function inside framework like `context.waitForApproval()`. This will generate two URLs - one for continuing the flow and the other for canceling it. These links can be used in emails.

For instance, you can create an Approval Email Piece that sends an email with two buttons. If the user selects the cancel URL, the flow will stop. If they select the continue option, the flow will proceed.

I think once this is completed, we can model such flows.

@nileshtrivedi What do you think?

**Comment by nileshtrivedi** [comment]
@abuaboud This is a good start but a YES/NO, APPROVE/REJECT flow fundamentally, is about collecting a single bit of data from a human actor. IMHO, a more general and powerful flow would be sending an incomplete JSON object - to be rendered as an HTML form - and receiving a completed one from the person.

**Comment by abuaboud** [comment]
@nileshtrivedi this is decent, maybe we could extend it for something like this

`context.waitForAction(['submit', 'cancel'])` It will generate an URL for each action and you can use the response from their http body, in the piece you could construct the form and send in the email.

**Comment by nileshtrivedi** [comment]
I don't fully understand what you're proposing. So will leave it to your judgment. :)

[This PDF](http://docenti.ing.unipi.it/m.cimino/gpa/res/BPMN_by_example.pdf) has some examples of BPMN workflows.

Here is how ChatGPT summarizes the various elements in business workflows (as BPMN defines it):

<img width="763" alt="image" src="https://user-images.githubusercontent.com/19304/234629957-93dffd6e-f9d3-47fa-aa6c-0f3d03f7c3f3.png">

**Comment by LinusInnovator** [comment]
I think this would be great as well. I’m thinking it would also be great with a “standard” for showing where the user are in such a process, like a “baseplate” way to show a multistep process.

**Comment by abuaboud** [comment]
Done and will be released in 0.5.0
