### ISSUE TITLE
"Authentication" field needs to become "Connection"

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1093]
For consistency across the app and the UI, we need to change "Authentication" in the step settings panel to "Connection".

Especially that the button says "+ New Connection", so there is inconsistency and confusion there.

**Comment by abuaboud** [comment]
Each package has it's own naming, I was thinking of unifying this as part of piece level.

I will mark it as chore, because it requires a lot of efforts so maybe i can do it with above task on the right time.
