### ISSUE TITLE
[BUG]: autocomplete UI has additional space from the input

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1099]
Example: 
<img width="410" alt="Screenshot 2023-04-19 at 17 26 43" src="https://user-images.githubusercontent.com/97393596/233124683-297848c9-578f-45f6-b8a8-2a9006269c1b.png">

**Comment by abuaboud** [comment]
Certainly! Here's a version with corrected grammar and spelling:

After examining the code, I can see that this component was hardcoded and created by our team. Unfortunately, it has caused many issues in the past and is full of edge cases. My suggestion is to redesign this area in a way that solves these issues:

https://github.com/activepieces/activepieces/issues/1101
https://github.com/activepieces/activepieces/issues/1071

We also need to resolve the issues related to laptops with HD resolution.

I suggest finding a new design or way to use native material components.

@AbdulTheActivePiecer, that's my suggestion, but I will leave the decision up to you.

**Comment by ashrafsamhouri** [comment]
I agree that we have to adjust the design to solve for smaller screens if that's what you mean.

However, let's fix the bugs first even if it requires hardcoding as this will improve the experience until we have a solid suggestion for responsiveness.

Please note that these issues are unrelated to the resolution issue since. For example, regardless of your resolution, if the dropdown is going to touch the bottom, it needs to go up as it is today. So I recommend fixing the bugs and stabilizing the current version so that we don't delay improving the experience.

@AbdulTheActivePiecer let me know if you'd like to discuss any changes to the design if you'd like to move to another component type.

**Comment by abuaboud** [comment]
The dropdown is revamped now, this is no longer valid.
