### ISSUE TITLE
[BUG]: Gmail send email plain text should take newlines

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1102]
I sent an email using Gmail piece (Text) not HTML. My input looked like this:
<img width="394" alt="Screenshot 2023-04-19 at 23 48 58" src="https://user-images.githubusercontent.com/97393596/233207901-c97963d4-59f0-4eb0-b527-f3ca86e12475.png">

But the received email looked like this:
<img width="1290" alt="Screenshot 2023-04-19 at 23 49 05" src="https://user-images.githubusercontent.com/97393596/233207904-b398923d-8a1b-4d7a-83ba-08e092af50b5.png">

To my understanding, the goal of plain text is to write without taking formatting into consideration and the email will look fine (as written). But in my case, the newlines were automatically removed.

**Comment by abuaboud** [comment]
Marked as good first issue.

Here is the code for the action: https://github.com/activepieces/activepieces/blob/main/packages/pieces/gmail/src/lib/actions/send-email-action.ts
