### ISSUE TITLE
[BUG]: Shopify App Needs Review

### ISSUE THREAD

**Issue by Wingman3434** [activepieces/activepieces#1103]
**Describe the bug**
Unable to add Shopify authentication 

**To Reproduce**
1. Go to Authentication
2. Enter Details
3. Click Add
4. See error in Shopify Popup window

**Expected behavior**
Expect to click accept in Shopify Popup to allow access and add the Authentication 

**Screenshots**
![image](https://user-images.githubusercontent.com/1365628/233222125-b5ef921b-4c88-4f8e-a803-3ee2a96d96cb.png)

**Additional context**

**Comment by abuaboud** [comment]
We have instructions how to use shopify without verification now.
