### ISSUE TITLE
AutoGPT + Activepieces

### ISSUE THREAD

**Issue by Lauren-ED209** [activepieces/activepieces#1105]
Hello, this is our project CasaOS "https://github.com/IceWhaleTech/CasaOS". It helps enthusiasts to self hosting their own servers with just one-click and manage personal data, smart devices and automation services. 

We have always been interested in the consumer value of process automation products. Mainstream process automation tools focus on the B2B scenario and commercialization, and use a no-code interactive approach. However, ultimately, no-code is a fixed process event, making the entire system very rigid and mechanical. 

LLM have changed all industrial logic. All processes and mechanisms will become smarter. APIs play a crucial role in this. 

My question is, has the ActivePieces team considered embracing AutoGPT-like products and deploying them through cloud and private cloud/NAS? I am very optimistic about the imaginative space of LLM+ActivePieces and private deployment, whether it is 2C or 2B.

Look forward to your suggestion. My email: lauren@icewhale.org

**Comment by ashrafsamhouri** [comment]
Thanks @Lauren-ED209 I added you on LinkedIn, let's discuss possible directions for this
