### ISSUE TITLE
[BUG]: Activepieces not functioning correctly when installed via "EasyPanel" method

### ISSUE THREAD

**Issue by volneanschi** [activepieces/activepieces#1117]
**Describe the bug**
Impossible to run & sometimes even to publish a flow on a clean EasyPanel (Hetzner VPS, Ubuntu22.04) install. Issue persists using different docker image versions of AP (.6; .9; .11).

**To Reproduce**
1. Spin a Hetzner CPX11 VPS with Ubuntu 22.04 (Probably, not related to the issue)
2. Run `curl -sSL https://get.easypanel.io | sh` as stated on https://easypanel.io/ & enter the dashboard.
3. Change domain name for EasyPanel's Dashboard (EP).
4. Create AP project from the official template.
5. Enter the AP dashboard, create a flow.
6. Add RSS as a trigger, telegram bot as an action. (Just an example)
7. Click "Publish".
8.1 Experience the error.
8.2 I've managed to publish a webhook+telegram flow on a different EP+AP setup but it was running infinitely (not sure if related to the issue) and didn't track the error log output.

**Expected behavior**
Flow publishing & working with no issues =)

**Additional context**
Container error output:
[12:37:57 UTC] ERROR: Command failed: /usr/src/app/packages/backend/src/assets/isolate --dir=/usr/bin/ --dir=/etc/=/usr/src/app/packages/backend/src/assets/etc --share-net --box-id=99 --processes --wall-time=600 --meta=/var/local/lib/isolate/99/box/meta.txt --stdout=_standardOutput.txt --stderr=_standardError.txt --run /usr/local/bin/node activepieces-engine.js EXECUTE_TRIGGER_HOOK
Cannot run proxy, clone failed: Operation not permitted

`docker info | grep "Privileged"` gives nothing in the output.

**Comment by abuaboud** [comment]
Unfortunately EasyPanel doesn't support privileged docker, we should remove the installation from the documentation until we figure out the solution.
