### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by mabumusa1** [activepieces/activepieces#112]
In Mautic we implement an automated way to tag and release our versions, I can help you implement a similar process, I just need to have a conversation with @abuaboud about the releasing process

Files for reference 
https://github.com/mautic/mautic/blob/5.x/.github/workflows/release.yml
https://github.com/mautic/mautic/blob/5.x/.github/workflows/generate-release-notes.yml

**Comment by abuaboud** [comment]
Thank you, I think this is done now!

https://activepieces.com/docs/changelog
https://github.com/activepieces/activepieces/releases
