### ISSUE TITLE
[BUG]: tab in property fields shouldn't indent, should move to next field

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1123]
When you press "Tab" on your keyboard when the cursor is in a step field, it indents the cursor instead of moving to the next input. It doesn't make sense to me, and if there is agreement on this, we should give it the default tab behavior that moves the cursor to the next input.

Example:
<img width="394" alt="Screenshot 2023-04-22 at 20 54 04" src="https://user-images.githubusercontent.com/97393596/233799539-57527b5f-9628-45d2-baef-917c41ebe1c9.png">

**Comment by abuaboud** [comment]
Note: It's now rich text editor, it do some formatting like bullet points, we should remove that as well i guess.
