### ISSUE TITLE
[BUG]: piece webhook trigger is still running when flow is disabled

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1129]
I built a flow starting with a GitHub New Issue trigger (Instant trigger), published it then immediately turned it off, I'm still receiving messages on Slack from it.

This is the flow and the Slack messages I'm receiving:
<img width="282" alt="Screenshot 2023-04-23 at 02 13 01" src="https://user-images.githubusercontent.com/97393596/233811435-9363dd6b-642e-4e83-8cd5-8b1432846dc1.png">
<img width="1680" alt="Screenshot 2023-04-23 at 02 13 12" src="https://user-images.githubusercontent.com/97393596/233811437-c0750552-2355-4879-a486-6a4b2a104223.png">

If it helps with debugging, the collection ID is: p852vokY8wc4N45pPJg4N

**Comment by abuaboud** [comment]
Closing https://github.com/activepieces/activepieces/issues/1129
