### ISSUE TITLE
Update a page in a Notion database

### ISSUE THREAD

**Issue by Suriteka** [activepieces/activepieces#1134]
Hello 👋

**Describe your usecase.**
Currently there is only a Notion trigger. We should add a Notion action to update a page in a database for example. 

**Example workflow**
When a Notion Page is created in a database, then a request to the Wikipedia API is made, finally the Notion Page is updated with these informations.

I'll try to investigate and maybe make my first PR in this project.
Have a good day!

**Comment by abuaboud** [comment]
Thanks for bringing up the issue! I've transferred it to the pieces board.

We've been inundated with requests lately, but we're striving to produce as many pieces as we can. 🙌 With any luck, contributors will jump in and take part in the excitement!

For developers, here's a tutorial link on how to construct a piece on ActivePieces: https://www.activepieces.com/docs/contributing/building-pieces/create-action.

**Comment by bibhuty-did-this** [comment]
@abuaboud I would like to take this up

**Comment by kishanprmr** [comment]
@abuaboud  I would like to take this up.
