### ISSUE TITLE
Add button to duplicate piece in the flow

### ISSUE THREAD

**Issue by Willianwg** [activepieces/activepieces#1139]
Add a button like the delete step button, but to duplicate the step, keeping all the set properties.

Doing this the user will be able to create a new step and configure a piece present in the flow faster than looking for it in the search bar and copying properties that could be the same.

**Comment by webserviceXXL** [comment]
Good one. Would also be helpful (a workaround) for the missing feature of moving a piece like explained here https://github.com/activepieces/activepieces/issues/838

**Comment by Ozak93** [comment]
This would be a helpful feature, In my case i receive a large JSON body with lots of data from a form, and sometimes the values need some adjustment before sending them to an API or inserting them into a data store.

in this flow pictured below 
![image](https://github.com/activepieces/activepieces/assets/31257994/37975dd8-99e0-46cb-b6e2-870a8979680c)

i use the Code piece to make these adjustment and usually the only difference between each Code piece is just the key of the JSON value. but i have to create and copy paste code/parameters manually for each copy which can be frustrating.

having a "clone" or "duplicate" button beside the "delete piece" icon button would be best! 

![image](https://github.com/activepieces/activepieces/assets/31257994/92a6ab9a-7c4e-4108-8dd4-6034a2432400)
