### ISSUE TITLE
[BUG]: AP_SIGN_UP_ENABLED flag fails to change to true unless quotations are used

### ISSUE THREAD

**Issue by Siutan** [activepieces/activepieces#1142]
**Describe the bug**
Deployed Activepieces on a Digital Ocean basic droplet running Ubuntu (LTS) 20.04, Activepieces 0.3.11 installed though Docker. Tried to set AP_SIGN_UP_ENABLED flag to true in the env file which didnt change anything. Value only changed when AP_SIGN_UP_ENABLED="true" was set.

**To Reproduce**
1. Set up Digital Ocean droplet and install Activepieces
2. Sign up with an account and log out
3. Set AP_SIGN_UP_ENABLED flag to true
4. Run docker compose 

**Expected behavior**
going to /api/v1/flags should show:
SIGN_UP_ENABLED: true
instead shows:
SIGN_UP_ENABLED: false

**Comment by abuaboud** [comment]
I was unable to replicate the issue across several machines. Could you confirm if the latest version resolves the problem? I will mark this as closed for the time being, but feel free to reopen.
