### ISSUE TITLE
Mautic CRM

### ISSUE THREAD

**Issue by quadcom** [activepieces/activepieces#1158]
**Describe your usecase.**
Currently using Zapier to push Stripe and Square transactions to Mautic. Mautic is a CRM Marketing Automation platform, which is also an OpenSource project. Would love to get off of Zapier and manage this and other automations myself. 

**Describe alternatives you've considered**
The only alternative currently is Zapier. There are other automation platforms out there, but they are all missing something that makes them unsuitable.

Thanks for considering!

**Comment by abuaboud** [comment]
@quadcom Thank you for opening the issue.

What actions/triggers do you need in Mautic for your use case?

**Comment by quadcom** [comment]
Currently, just create/update contact I think.

I do have Mautic campaigns which I feed currently from a contact field, but if there is a method to add a contact to a campaign, that would be useful.

My current concern with Zapier is the free level does not allow for multistep actions. Querying the value or existence of a field is considered a step so I have to perform the logic inside of Mautic.

**Comment by abuaboud** [comment]
Thanks for bringing up the issue! I've transferred it to the pieces board.

We've been inundated with requests lately, but we're striving to produce as many pieces as we can. 🙌 With any luck, contributors will jump in and take part in the excitement!

For developers, here's a tutorial link on how to construct a piece on ActivePieces: https://www.activepieces.com/docs/contributing/building-pieces/create-action.

**Comment by bibhuty-did-this** [comment]
@abuaboud I would like to take this up.

**Comment by abuaboud** [comment]
@bibhuty-did-this that would be great!


Let me know if you encounter any issues, I am here to help!

**Comment by bibhuty-did-this** [comment]
@quadcom 
As of now I am adding support of these fields.
          firstname,
          lastname,
          email,
          tags,
          company

Hope that will do the job?

**Comment by quadcom** [comment]
> 
@abuaboud 

Hmm, so there's no way to use custom contact/company fields?

I didn't realize that you must define the fields before creating the integration. I have created a few and use them regularly. So would pretty much any other user of any CRM system.

Not to knock your efforts, but limiting the integration to use only these predefined fields will not be received well by potential adopters.

**Comment by abuaboud** [comment]
@quadcom Sorry I am not familiar with Mautic,

**Comment by bibhuty-did-this** [comment]
@abuaboud I understand what the requirement is.

@quadcom Give me by the end of this week. I'll get it done. 
One piece of info I want from your side. What's the typical no of custom fields you generally use?

Just to reiterate:
1. You want functionality for company creation
2. You want custom field functionality both for company and contact.
Right?

**Comment by abuaboud** [comment]
@quadcom, based on my understanding, it seems that @bibhuty-did-this has made an outstanding contribution, and the requested changes have been successfully merged.

To fetch the latest changes, please remove the existing step of mautic (if you have any) and add it again.

Let us know your feedback

**Comment by abuaboud** [comment]
Closing this issue, as the changes according to my understand is done.

Feel free to reopen If they are not.
