### ISSUE TITLE
MailChimp first and last names (optional inputs)

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1164]
I'm writing an article about lead generation with Google Forms, MailChimp and HubSpot. When the user enters their info in the form, I can only add their email to MailChimp today.

I'd like to add the first name and last name too. Maybe more optional inputs as well.

**Comment by abuaboud** [comment]
Marked as good first issue.

Here is the code for the action: https://github.com/activepieces/activepieces/blob/main/packages/pieces/mailchimp/src/lib/actions/add-member-to-list.action/add-member-to-list.action.ts

Just in general how to edit pieces:
https://www.activepieces.com/docs/contributing/building-pieces/create-action

**Comment by therealron** [comment]
Is this still open? I'd like to start contributing to this project. Thanks!

**Comment by abuaboud** [comment]
Hey @therealron, do you require this?

The PR is currently open, and I plan to review it sometime this week. We were waiting for a few changes to be merged first, I will start merging & reviewing prs this week.
