### ISSUE TITLE
I can not connect to Monday.com

### ISSUE THREAD

**Issue by ipapel** [activepieces/activepieces#1167]
Can not connect to Monday.com through New Conection. 

It opens a popup with the message: 

{"error":"invalid_scope","error_description":"Invalid scope param"}

I need help. 
Thanks.

**Comment by abuaboud** [comment]
Hi @ipapel,

Currently, our Monday task needs to be submitted to the Monday team for review. You can find the relevant issue at: https://github.com/activepieces/activepieces/issues/1127

I would suggest creating your application on Monday and clicking on "Use my own credentials" to copy the client ID and client secret.

When creating the Monday application, make sure to include the following OAuth scopes:

'workspaces:read',
'boards:read',
'boards:write',
'updates:read',
'updates:write'

@ashrafsamhouri  let's take look in this

**Comment by abuaboud** [comment]
I have removed the option to use activepieces Monday app at this moment until our app is reviewed. I am closing this ticket but will keep the issue tracked in https://github.com/activepieces/activepieces/issues/1127."

**Comment by ipapel** [comment]
Thanks for replying! I will wait for it be reviewed. Monday is my core for now, if I can get it connect with Activepieces I would be awesome! Nice work anyway! Keep it up!
