### ISSUE TITLE
[Help Wanted] Run Code in Self hosted environment without privileged docker

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#1170]
## Context

Activepieces allows users to run code snippets. To ensure security, we use [Isolate](https://github.com/ioi/isolate), which creates lightweight sandboxes to run the code. However, Isolate requires a privileged container, which can be problematic for some users. For example, **EasyPanel** and **DockerSwarm**  and many other platforms do not support privileged containers.

We are exploring options to remove the privileged requirement in Docker. Our requirements include support for external NPM, a timeout for infinite loops, and no dependency on privileged mode.

## Option 1:
Since self-hosted instances typically only have a single user, we could run the code without sandboxing, assuming that the code is trusted. This means that the code pieces would have access to environment variables and the file system.

## Option 2:
We could use a separate worker in another Docker container as a way to isolate the code. This container would be unprivileged, but that would make activepieces harder to setup.

We have considered options such as [isolated-vm](https://github.com/laverdet/isolated-vm) and [vm2](https://github.com/patriksimek/vm2). However, these options may not support all NPM packages or provide adequate restrictions for important items like environment variables.

**Please let me know your thoughts!**

**Comment by adhami3310** [comment]
It's possible to compiler NodeJS tool chain to a WASM file, then it's possible to run the user code with the WASM binary and setting the appropriate flags/environment variables. This will ensure security as WASM is formally proven to be safe. I believe you don't need privileged container to do any of the above!

**Comment by adhami3310** [comment]
To elaborate, WASM is a low level language that uses determinism to be executed safely in any environment (including the browser!). There even exists formally proven runtime for WASM that ensures security. 

It's possible to compile statically compiled languages to WASM format, and then run the WASM file using a WASM runtime (and you can specify the permissions as you like). This is really easy in Rust, and even easy in C: https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm  

You would need to compile NodeJS (from its source code) into a WASM file. Then, you can use that file to execute any JS code you would like (just like using NodeJS!), but now you can set the permissions as you like, to ensure your program is sand-boxed enough.

This approach is used by https://webcontainers.io/. I believe their implementation is closed-source. If you dig enough you might find someone who have already done it!

**Comment by abuaboud** [comment]
Open PR https://github.com/activepieces/activepieces/pull/1171 with option #1 , It's not the default option for now.

But my biggest concern is what is the proper way to notify the user about the downsides of such option, specially when the user using pre-made templates, or following tutorial.

**Comment by OsamaHaikal** [comment]
https://www.figma.com/blog/how-we-built-the-figma-plugin-system/

**Comment by abuaboud** [comment]
@OsamaHaikal  Super interesting article, I think this is designed for javascript on the browser and not node.

Another option is to allow the use of VM2 as a sandbox, but this requires some setup if the user wants to use external libraries. The user will be controlled by two environment variables: ALLOWED_BUILTIN_MODULES and ALLOWED_EXTERNAL_MODULES. 

As a result, templates can be created that restrict external library usage and require the user to specifically allow built-in and external modules. However, this comes with a risk that the user should be aware of.

**Comment by stephenc01** [comment]
IMO, I like the idea of Option 2. Thinking of my docker swarm. I can see 1 container as a management layer and multiple workers on the swarm. 

If this option is chosen, the system would have to be able to deploy with a single docker compose file. I do not like the idea of scripts to have to deploy multiple containers.
