### ISSUE TITLE
Openai chatGPT - add system role text field

### ISSUE THREAD

**Issue by Barqawiz** [activepieces/activepieces#1188]
**Is your feature request related to a problem? Please describe.**
Current chatGPT action supports only question input and does not include the **system** role functionality.
The system input tunes the model output based on the user's request.
For example, using the system role, we can put the model in the mode to extract specific data.

**Describe the solution you'd like**
Add another optional text field called system role for "Ask ChatGPT", which allow the user to guide the model response style.
`System: [text field]`

**Describe alternatives you've considered**
- either text field like the question.
- or extra added item when clicking on add input (preferred).

**Additional context**
When calling the API, the role is the first thing in the message stack.
Role default example:
`{"role": "system", "content": "You are a helpful assistant."},`
Example of custom roles (the user will input the content):
`{"role": "system", "content": "Provide the answer in json format, {answer: <answer>}."},`

Standard chatGPT inpit:
```
messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
```

**Comment by abuaboud** [comment]
Now you can specify previous messages with an optional property called `Roles`. It has been merged and is now available for use.

Make sure you remove the OpenAI step if you already have one and add it back again, so you can get the latest version.

**Comment by Barqawiz** [comment]
Great Mohammed, that fast and clean update.
Will test it and update you if noticed any issue.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
