### ISSUE TITLE
hide activepieces instance information

### ISSUE THREAD

**Issue by MyWay** [activepieces/activepieces#1209]
**Describe the bug**
Not exactly a bug, but when you are not logged in, you are still able to leak some info of the running instance, because activepieces reports the availability of new updates before logging in, in the login screen and via the flags api page. 

**To Reproduce**
1. Logout if you are logged in 
2. Go to the login page or GET the flags endpoint 

**Expected behavior**
I shouldn't be able to get any info about the installation, such as the current version, or the availability of updates. 

**Screenshots**
No need to. 

**Additional context**
None.

**Comment by abuaboud** [comment]
The web address "https://localhost:8080/api/v1/flags" shows the version of activepieces being used. This could be a problem if there's a security vulnerability.

Attackers people could use automated tools to scan for instances with the vulnerability after they been discovered and attack them.

**Comment by abdullahranginwala** [comment]
Does that mean that we completely remove the current and latest version in the `/v1/flags` route?

**Comment by MyWay** [comment]
You can keep it with auth, imho.
