### ISSUE TITLE
Control Date / Time of the add google calendar piece

### ISSUE THREAD

**Issue by scottwegner** [activepieces/activepieces#1210]
When the current google calendar piece creates an event - it does it at the current date and time.  It would be cool if I could specify the date and time I want it to created at... or better yet - if it could be based on data from the trigger that created it.

So if I have a flow that triggers based on things created on one calendar - and have a piece that creates another event based on that trigger, it would look at the trigger data and use date info for where to create the new event.

**Comment by bibhuty-did-this** [comment]
@abuaboud I am taking this up.
