### ISSUE TITLE
Add page indicator in the flow pagination

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1226]
I always feel lost while browsing pages because it doesn't tell me where I am and how many pages are yet to come.

This is the current view:
<img width="456" alt="Screenshot 2023-05-06 at 21 54 55" src="https://user-images.githubusercontent.com/97393596/236641899-7c194ed5-a1b4-4f13-91e1-e7d678377d90.png">

I suggest turning it into the full view like this:
<img width="659" alt="Screenshot 2023-05-06 at 21 57 00" src="https://user-images.githubusercontent.com/97393596/236641901-78fe3321-cecc-4599-88a6-e65e0b0077aa.png">

This might need some bottom padding for the page so that the snackbar won't touch the pages or hide them

**Comment by abuaboud** [comment]
This is not feasible because our pagination follows a Seek-based approach, similar to Stripe's implementation.

Example:
![image](https://github.com/activepieces/activepieces/assets/1812998/c0c67fb8-eaf6-4282-8d3d-6275a47df661)

Closing this ticket, feel free to reopen
