### ISSUE TITLE
Bulk Actions (Delete Flows / Delete Connections / Rerun)

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#1234]
**Is your feature request related to a problem? Please describe.**
It can get quite annoying when you need to delete several flows that are no longer required anymore

**Describe the solution you'd like**
It would be good to implement a bulk-selector on the all-flows page which enables us to select and then perform bulk actions (such as delete and move to actions)

**Comment by abuaboud** [comment]
**Runs Table**

** Select All **
  - Select All Matching Filter
  - Select This Page Only

**Retry:**
- Show "Retry" on the latest version directly when not all runs have failed.
- Show "Retry" with options only if all runs have failed.

Do not show the actions column (no three dots / no icon).

**Comment by abuaboud** [comment]
Connections:

Select All
* Select Page Only

Actions
Three dots in Actions to Delete

Delete for Bulk only should show when any selected.

**Comment by abuaboud** [comment]
Flow Table

Select All:
* Select Page

Bulk Actions:
- Move To
- Delete
- Export

**Comment by abuaboud** [comment]
feat/replay-run
