### ISSUE TITLE
Customise webhook + add functions without coding

### ISSUE THREAD

**Issue by Adatik** [activepieces/activepieces#1237]
Hello guys, I have suggestions that will really help us in Activepieces, if anyone who can help or improve this, it will let activepieces  to be in another level:

1-webhook: let the webhook has customise name, https://webhook .com/name

Because, in this case we can create our own Api documents with more professional look.

More details in Api documents: if we want to create public webhook with our domain that required some workflow. For example:

Post: https://webhook. com/create

Headers:
Authraztion - Bearer access token to let third party access to webhook
Content-type - application/json

Parameters:

name: Ali
Age: 30
email: example@example.com

So, in workflow we can add to database based on some conditions, like age must be great than 27

Or

connection with third party app and send these data to third party and return value to webhook.

There is many many cases it can be used.

And that's why it's really important we can customise our webhooks with our domain and bath name.

Also, create authentic webhook that only run if it's authentic which is more save.

Create customise parameters, for public access which these parameters can be optinal or required.

Return customise date to webhook, like ID or success message and so on.

2-add customise function without coding:

For example, calculate functions "sum,average,count, max, min and so on.

Date/time function, which the date can be customise like the format or time zone and so on.

Also, in conditions it can be added if this date is greater than this date or smaller

encode/decode functions:

hash, base and so on

For example, almost any advertising platform api required to send sensitive information like phone or email in base format, other wise the request will be rejected

Find and replace: this will be really helpful.

best example out of many you do find + in phone number and replace it with blank.

I know maybe some of these can be written in the code, but for people who are with no code experience will make really big difference.

For function, the best example you can look how make.com did this

**Comment by abuaboud** [comment]
Returning data is possible with HTTP (Return Response), and closing the inline functions (currently tracked https://github.com/activepieces/activepieces/issues/1018)
