### ISSUE TITLE
[BUG]: the code piece fails - Request failed with status code 429 - when trying to connect google sheets and chatgpt

### ISSUE THREAD

**Issue by aimorality** [activepieces/activepieces#1252]
i'm following these steps :

https://www.activepieces.com/blog/automate-blog-writing-with-ai-a-step-by-step-guide-using-openai

and on the step where i ask chatgpt to write a title it shows this issue:

how to solve it?

![image](https://github.com/activepieces/activepieces/assets/133503883/b4278497-1616-4598-adcc-49f27281f310)

"Request failed with status code 429"

thank you

**Comment by ashrafsamhouri** [comment]
Hi @aimorality Does your OpenAI account have a valid credit card on? ChatGPT replies with this usually when you are not paying them for your requests

**Comment by abuaboud** [comment]
This issue is not related to Activepieces. However, we're happy to help. Please feel free to reopen the issue if the above suggestion doesn't work.
