### ISSUE TITLE
[bug]: stability.ai

### ISSUE THREAD

**Issue by aimorality** [activepieces/activepieces#1260]
hey, so as i unerstand u recently added stability.ai to the flow, but it doesnt really work correctly, and also what can i do with the output of it?
a quick guide could be very helpful

**Comment by abuaboud** [comment]
Thank you for opening the issue, @aimorality. This is very interesting feedback. Images are transferred in a certain format (base64) as text.

We always aim for a low learning curve on this platform. We should brainstorm a more intuitive way. Could you please provide us with details on what specific things you would like to do with it?

**Comment by aimorality** [comment]
> Thank you for opening the issue, @aimorality. This is very interesting feedback. Images are transferred in a certain format (base64) as text.
> 
> We always aim for a low learning curve on this platform. We should brainstorm a more intuitive way. Could you please provide us with details on what specific things you would like to do with it?

i wanted to upload it to  my wordpress site / facebook page. 
but somehow can't do that. for example on z apier they output dall-e's img link which can be used later..
maybe its my lack of knowledge in coding? 
but i tried some python and it has some issues with converting the base64 to png..
what would u suggest?

**Comment by ShayPunter** [comment]
Might perhaps be a nice idea to perhaps have a 'converter' piece which could achieve this among other converter functions @abuaboud

**Comment by abuaboud** [comment]
@ShayPunter looks promising, what would this converter do exactly?

**Comment by abuaboud** [comment]
Thank you reporting the issue, I am tracking the issue in this ticket:

https://github.com/activepieces/activepieces/issues/784
