### ISSUE TITLE
[BUG]: AI generated triggers don't show "Invalid"

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1262]
Check this out:
<img width="1677" alt="Screenshot 2023-05-15 at 02 39 49" src="https://github.com/activepieces/activepieces/assets/97393596/ee3e2741-8521-4d7f-a792-2a5d3262ca94">

The trigger is actually invalid, but the step is not showing that

**Comment by abuaboud** [comment]
Fixed
