### ISSUE TITLE
[BUG]: AI uses a piece and says it's not up-to-date

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1263]
AI used Google Sheets and it says it's not up to date. It's just been added by AI.

<img width="1680" alt="Screenshot 2023-05-15 at 02 41 40" src="https://github.com/activepieces/activepieces/assets/97393596/2610d8c4-6a2a-4d7c-a959-c310911491d3">

**Comment by abuaboud** [comment]
Fixed
