### ISSUE TITLE
[BUG]: AI building is not bound to a specific flow

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1279]
- Create a new flow.
- Use AI builder.
- While it's building, go out, create a new flow.
- Wait a little bit and the AI-generated from the previous flow will show up here.

**Comment by abuaboud** [comment]
Fixed.

**Comment by AbdulTheActivePiecer** [comment]
This issue was solved when we introduced Draft/Published version switch #1265
