### ISSUE TITLE
[BUG]: Test action takes forever

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1293]
When I use the Stability AI action, it keeps loading without returning a response when I test the step individually.

When I test the flow, it works.

I encountered the same issue with other actions, and a user has noticed this today and reported it on Discord.

**Comment by abuaboud** [comment]
Note: This is due to cloudflare timeout connection after X seconds, some testing steps like OpenAI takes so long such the connection timeout and testing stays loading for ever

**Comment by abuaboud** [comment]
This should notify the user in such case at this moment.
