### ISSUE TITLE
[BUG]: "Success" to "Succeeded"

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1311]
It's inconsistent with Failed:
<img width="545" alt="Screenshot 2023-05-22 at 20 34 30" src="https://github.com/activepieces/activepieces/assets/97393596/f9574ae0-8e3c-47b1-a473-40f8af5d0503">

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue
