### ISSUE TITLE
[BUG]: piece deps are linked multiple times by pnpm

### ISSUE THREAD

**Issue by khaledmashaly** [activepieces/activepieces#1331]
**Describe the bug**
When running a flow in development with multiple steps using the same piece, pnpm links the pieces dependency multiple times which makes execution slow

**Comment by JanHolger** [comment]
I'm not sure if that's related but when having 2 dynamic props on a piece I run into a 500 on the /options endpoint because of a race condition where pnpm link runs twice at the same time resulting in filesystem errors like this one:
```
Command failed: pnpm link /usr/src/app/dist/packages/pieces/common\npnpm: EPERM: operation not permitted, open '/usr/src/app/.pnpm-store/v3/files/6e/cedca2fa7c81261ccd03840d5523ceeb334cf005db8d38a07587012408cf56441848dd09f631f6b99b7fa20ae713bbf811d50883b7570a3f4e5d08f3163c86'
```

**Comment by abuaboud** [comment]
> I'm not sure if that's related but when having 2 dynamic props on a piece I run into a 500 on the /options endpoint because of a race condition where pnpm link runs twice at the same time resulting in filesystem errors like this one:
> 
> ```
> 
> Command failed: pnpm link /usr/src/app/dist/packages/pieces/common\npnpm: EPERM: operation not permitted, open '/usr/src/app/.pnpm-store/v3/files/6e/cedca2fa7c81261ccd03840d5523ceeb334cf005db8d38a07587012408cf56441848dd09f631f6b99b7fa20ae713bbf811d50883b7570a3f4e5d08f3163c86'
> 
> ```

I dont think it's related, How do you run activepieces in development mode? using docker compose or dev containers?

My current best guess it's related  to permissions.

**Comment by JanHolger** [comment]
I'm running in docker compose and it did work fine until I added the second property. I'm actually trying to implement a piece for Jira and fetching the sites worked just fine but after adding the second dynamic prop for selecting the project it stopped working failing in this pnpm link error for both props.

**Comment by abuaboud** [comment]
> I'm running in docker compose and it did work fine until I added the second property. I'm actually trying to implement a piece for Jira and fetching the sites worked just fine but after adding the second dynamic prop for selecting the project it stopped working failing in this pnpm link error for both props.

That's odd a new issue for me. try docker compose down and compose it up to clean up the pnpm cache.
```
docker compose -f docker-compose.dev.yml down
```

then
```
docker compose -f docker-compose.dev.yml up
```

According to this issue https://github.com/pnpm/pnpm/issues/3699"

**Comment by JanHolger** [comment]
docker compose down and up will not clean the pnpm cache since the directory is mounted and is kept. Only deleting dist manually is working but it's still pretty. Using the dev containers instead of compose also made it less error prone for some reason. Those issues I had definitely are not directly related to this one though.
