### ISSUE TITLE
Add "Append" to Storage

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1354]
In many cases, I had to get a Storage value and append a new value to it, it was two steps and the input wasn't clean. I suggest adding an "Append" action to storage that concatenates the original value with the new one I add there. If the value didn't exist, it can also create it and in that case it does the Put job.

**Comment by chriswg1** [comment]
not sure if this will help, but I did have an issues like this with AWS S3 in the past and this Javascript did allowed me to append new value to the storage.
`const AWS = require('aws-sdk');

AWS.config.update({
  accessKeyId: 'YOUR_AWS_ACCESS_KEY',
  secretAccessKey: 'YOUR_AWS_SECRET_KEY',
  region: 'YOUR_AWS_REGION'
});

const s3 = new AWS.S3();
const bucketName = 'your-bucket-name';
const key = 'path/to/your/file.txt';
const newData = 'This is the data you want to append.';

s3.getObject({ Bucket: bucketName, Key: key }, (err, data) => {
  if (err) {
    console.error('Error reading the file:', err);
    return;
  }

  const fileContent = data.Body.toString('utf-8');
  const updatedContent = fileContent + newData;
  const updatedBuffer = Buffer.from(updatedContent, 'utf-8');

  s3.putObject({ Bucket: bucketName, Key: key, Body: updatedBuffer }, (err, result) => {
    if (err) {
      console.error('Error uploading the file:', err);
      return;
    }

    console.log('File updated successfully:', result);
  });
});
`
