### ISSUE TITLE
Public facing URL for flows with webhooks

### ISSUE THREAD

**Issue by mazloumi** [activepieces/activepieces#1356]
**Is your feature request related to a problem? Please describe.**
We ingest data from various providers and need to document for them what data structure is expected when the post data to us. Currently, a webhook has an internal representation of what the expected format is but I need to manually create a document that describes what is expected. 

**Describe the solution you'd like**
It would be good if I could share with the data provider a link that just shows them what the webhook expects.

**Describe alternatives you've considered**
Manually creating a document that I share with the data provider

**Additional context**
N/A

**Comment by abuaboud** [comment]
@mazloumi Thank you opening this feature request and sorry for late reply, It went under my radar.

This is an new use case for me, are you using activepieces as api builder? what data do you expect in this generated document?

**Comment by mazloumi** [comment]
I wouldn’t show a sample request and response that the user can if needed edit in case they need to be sanitized. And I would organize the APIs based on the folders they are in. This way a developer can see all APIs available and what is expected.On Jul 15, 2023, at 17:32, Mohammed Abu Aboud ***@***.***> wrote:﻿
@mazloumi Thank you opening this feature request and sorry for late reply, It went under my radar.
This is an new use case for me, are you using activepieces as api builder? what data do you expect in this generated document?

**Comment by abuaboud** [comment]
@mazloumi I believe https://hoppscotch.io/ or https://www.postman.com/ would do a better job at documenting APIs, as it look like this is outside scope of activepieces and If we did it, It won't match the postman or hoppscotch experience.
