### ISSUE TITLE
Build Selective Pieces During Development

### ISSUE THREAD

**Issue by JanHolger** [activepieces/activepieces#1358]
**Is your feature request related to a problem? Please describe.**
Currently while developing new pieces the build of all pieces can take some time while none of the other pieces are required for testing the individual piece you are working on. I can also see a use-case for this to disable pieces that might come with security flaws in shared environments like activepieces cloud or to increase the speed and user experience in self-hosted environments that might not need all pieces.

**Describe the solution you'd like**
Some way to disable pieces during the build process. Maybe also an option to disable pieces via environment variables at runtime (if possible).

**Comment by abuaboud** [comment]
I suggest the following action item:


Enhance the development experience by focusing on avoiding complete rebuilds of the backend and frontend whenever an edit is made. Additionally, prevent unnecessary builds of pieces unless the developer explicit choose to build piece locally.
