### ISSUE TITLE
File Property

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#1361]
The idea for supporting File Property is to allow the frontend to accept multiple file formats and then convert them into a unified format within the piece framework. This unified format can then be used to provide utilities for working with other formats.

Related Issues:
https://github.com/activepieces/activepieces/issues/1330
https://github.com/activepieces/activepieces/issues/784
https://github.com/activepieces/activepieces/issues/633

**Comment by AbdulTheActivePiecer** [comment]
This sprint, we agreed on supporting a URL input that downloads/uploads the binary file needed.
