### ISSUE TITLE
[BUG]: Removing the value from an optional number property makes validation fail

### ISSUE THREAD

**Issue by JanHolger** [activepieces/activepieces#1362]
**Describe the bug**
Removing the value from an optional number property doesn't actually remove the property, instead it sets the value to an empty string making the type validation fail afterwards.

**To Reproduce**
1. Create a step using an action that features an optional number property
2. Add the optional property and set it to some value
3. Remove the value
4. Run the flow
5. See the following error
```
{
  "your_property": "expected number, but found value: "
}
```

**Expected behavior**
The property value should be undefined when removed. This would also stop the validation from failing.

**Comment by abuaboud** [comment]
What do you think about this as a possible solution: [link to the issue on GitHub](https://github.com/activepieces/activepieces/issues/1082)? Alternatively, do you believe we should treat empty strings as null?

**Comment by abuaboud** [comment]
As discussed offline, Let's start with https://github.com/activepieces/activepieces/issues/1082 and then we can evaluate if this is still issue. 

Closing the issue, feel free to reopen :D
