### ISSUE TITLE
Make trigger interval configurable

### ISSUE THREAD

**Issue by JanHolger** [activepieces/activepieces#1364]
**Is your feature request related to a problem? Please describe.**
Right now the trigger interval is hardcoded to 5 minutes in a cron expression in trigger-helper.ts. It would be great if this could be configured per trigger within limits that can be configured per instance. This would allow shorter or longer intervals depending on what the individual use-case requires.

**Describe the solution you'd like**
Have 2 global env settings
- AP_TRIGGER_MIN_POLL_INTERVAL (default: 5)
- AP_TRIGGER_DEFAULT_POLL_INTERVAL (default: 5)

and a setting on polling triggers to set the poll interval within in the configured min limit.

**Describe alternatives you've considered**
Permanently setting the interval to 1 minute but this could lead to a lot of overhead because some applications could easily work with 5 minutes or even way longer.

**Comment by JanHolger** [comment]
@abuaboud made me aware that the context in the setup hooks has a setSchedule method that allows to specify the interval as cron expression. This basically fixes this issue.

**Comment by abuaboud** [comment]
@JanHolger That's true, but this is important because we should make the polling trigger is always configurable by the end user by default.

Reopening this ticket to the track the following.

Thank you for suggesting this!

**Comment by briannezhad** [comment]
How can I trigger Cron Expression every 10 second?

**Comment by JanHolger** [comment]
> How can I trigger Cron Expression every 10 second?

You can't with standard cron expressions. The smallest possible interval right now is 1 min. You can already set it in the trigger setup on the context

**Comment by abuaboud** [comment]
This is added and merged to main, will be released in 0.5.0

`AP_TRIGGER_DEFAULT_POLL_INTERVAL`
