### ISSUE TITLE
Support for NumberProperty in CustomAuth

### ISSUE THREAD

**Issue by JanHolger** [activepieces/activepieces#1384]
**Is your feature request related to a problem? Please describe.**
Right now the NumberProperty is not being supported by the renderer for CustomAuth. In #1032 it got removed but somehow this commit is not on main anymore (seems like it collided with some refactoring work that was done at the same time).

**Describe the solution you'd like**
Instead of removing it from the supported list of props I'd rather like to see it implemented so we can use for things like ports.

**Describe alternatives you've considered**
Remove it from the supported properties so new devs don't fall for this hickup

**Comment by abuaboud** [comment]
Thank you for reporting the issue, this is now fixed in main.
