### ISSUE TITLE
Facebook Leads as a trigger

### ISSUE THREAD

**Issue by Lieb777** [activepieces/activepieces#1391]
Zapier has a Facebook Leads Ads Trigger, we need the same on Activepieces. How soon can this be done?

**Comment by abuaboud** [comment]
We have received numerous requests, and this particular one is a high priority. However, we do not currently have a scheduled release date for it.

We are optimistic that one of our contributors will take it up soon from the task board.

To avoid duplication, I am closing this issue and will continue tracking it at the following link: [GitHub Issue #933](https://github.com/activepieces/activepieces/issues/933)

Thank you for your understanding.
