### ISSUE TITLE
Google Sheets: Lookup Row

### ISSUE THREAD

**Issue by SFoskett** [activepieces/activepieces#1484]
I would like to add an Action to the Google Sheets piece to lookup row based on cell content. This is a very frequently-used action in my Zapier automations.

Ideally it would read the entire contents of a row in a specific Google Sheet based on the value of a single cell in a specified content. Properties would be a row (described by the heading) to search and a value to search for. Output would include the values in that row as a hash, identified by the header, as well as the row number, which is useful for the Update Row Action.

A more advanced option would be to create a row if a matching row is not found, with all of the columns described by their headers.

As mentioned, this is one thing I do a lot of in Zapier and would be very helpful!

**Comment by abuaboud** [comment]
Lookup row is added now
