### ISSUE TITLE
Delay: Return Release Timestamp

### ISSUE THREAD

**Issue by SFoskett** [activepieces/activepieces#1490]
**Describe your usecase.**
It is often useful to have the current time in a flow. For example, when logging it is nice to be able to have a timestamp. Although it would be nice to have a "Now" Action, or even a "When" action that can add zero or more seconds to now, the Delay function is commonly used in other automation systems both to delay and to return the release time.

It would be a simple matter to add an Output to Delay with the timestamp for the release.

**Describe alternatives you've considered**
I have not spotted another way to do this in Activepieces.

**Comment by abuaboud** [comment]
@SFoskett Closing the ticket, feel free to reopen If the above solution is not what you are looking for.

**Comment by SFoskett** [comment]
I apologize for not getting back to you quicker. What I was asking is for it to return the timestamp after the delay, just that.Stephen Foskett
+1(508)451-9532
***@***.*** Jun 14, 2023, at 7:34 AM, Mohammed Abu Aboud ***@***.***> wrote:﻿
@SFoskett I am not sure If i understand correctly, but I think you want delay until and delay for which is already supported.
https://www.activepieces.com/docs/pieces/apps/delay
What am i missing?
