### ISSUE TITLE
[BUG]: -Send HTTP request- action  fails as not returning the full body of the response but a chunked version of it making a content evaluation fail

### ISSUE THREAD

**Issue by quotenerds-dev** [activepieces/activepieces#1493]
**Describe the bug**

-Send HTTP request- code piece action fails as http request is not returning the full body but a chunked version of it

**To Reproduce**
1. Use any website that returns "transfer-encoding": "chunked" in the header and lots of data
2. Use Send HTTP request to GET
3. Output section will say content is (truncated)
4. Evaluation fails as it does not find the contents as it was truncated

**Expected behavior**
Get the full contructed  body of a truncated http call

**Screenshots**

**Additional context**
Checking parsed content of any website

**Comment by abuaboud** [comment]
This the frontend is truncating the log to prevent website crashing, clicking on the enlarge button will able to see more of output.

Confirmed it's working according to our convo in discord.
