### ISSUE TITLE
[BUG]: Schedule block with "cron expression" not triggering

### ISSUE THREAD

**Issue by elpaxel** [activepieces/activepieces#1507]
**Describe the bug**
Schedule block with "cron expression" not triggering.

**To Reproduce**
1. Create "Cron Expression" trigger: `1 2,5,8,11,14,17,20,23 * * *`
2. Connect to "Code" block
3. Wait

**Expected behavior**
Expect it to trigger.

**Screenshots**
Nope.

**Additional context**
1. It was working 2 days ago. 
2. When I press "Test flow" everything working fine.
4. I have 500+ free tasks
5. Schedule block version: v0.0.4
6. I have tried deleting flow and creating it again.
7. Flow is on.
8. Flow is published.

**Comment by abuaboud** [comment]
Thank you @elpaxel for opening the issue, I will take look and get back to you

**Comment by abuaboud** [comment]
One of the worker deployments experienced a failure, resulting in certain jobs not being initiated. However, the issue has now been resolved.

This is the first occurrence of such a problem, and we are setupping more close monitoring this particular area, to detect such issues.

Thank you. The problem has been resolved, and I am now closing the issue.
