### ISSUE TITLE
Run context should have information about the project/user

### ISSUE THREAD

**Issue by nileshtrivedi** [activepieces/activepieces#1527]
My custom piece calls an internal HTTP API. We want to track which user is calling which APIs. 

One option is build an entire Oauth user flow so the user would be setting up a connection. Another option is to add a property that asks for a user-specific API key. But both of these options are less user-friendly than what we are aiming for.

It would be nice if pieces can have access to some additional run-time information available in the context, such as user's email address. This is particularly useful when invoking outgoing HTTP requests.

**Comment by abuaboud** [comment]
@nileshtrivedi I am not sure if i understand this is correctly, but the flow here belongs to project an not an user.

Can you explain more about the usecase? any suggested solutions?

**Comment by nileshtrivedi** [comment]
Projects have a single ownerId which is a reference to `user.id`. So, in effect, a flow is owned by a user.

This is our use case: My custom piece calls an internal HTTP API. At that API, we want to be able to know which user has invoked this piece from their flow.

This can be achieved with having user's id available in the `context` that is passed to an action's `run()` implementation. The piece can then pass it along to the API.

**Comment by abuaboud** [comment]
Hey @nileshtrivedi, I find that use case quite interesting. Alright, now I completely understand your suggestion!

But if you were to send the project ID to the internal API, it means the internal API doesn't have any authentication mechanism. Doesn't that make it insecure? So, wouldn't you need an authentication mechanism like an API key or bearer token to secure it?

You also brought up an important point in discord. I was thinking that if you leave the secrets within the piece code, they could be exposed to anyone who can create a flow with that piece. They could utilize a code piece executed within the same flow sandbox to access the node_modules and print them out.

The methods you mentioned API Key seems the current option to do it.

The other option to change the implementation in the engine to separate **code pieces** in another sandbox, we used to do that but it had **huge performance overhead** for example when you have loop that iterate 1000 time and code piece inside that loop then the engine would need to create sandbox for each code piece, the communicate and creating sandbox overhead is so large, making it infeasible to do such flows.

What do you think?

**Comment by nileshtrivedi** [comment]
You're right. flowid/projectid/userid being available in the run context doesn't solve the security issues. Thus, a piece needs user-specific key which must be collected from the user.

**Comment by nileshtrivedi** [comment]
I found a way to do this for now. In `piece-action-handler.ts`, before running the `action.run()`, I store the flowIn in storage which the piece can read and pass to the API:

`await store.put('flowId', globals.flowId);`

It's a hack and a bit wasteful, because it really needs to happen only once per flow run, not once per piece, but it solves my problem for now.

**Comment by abuaboud** [comment]
Closing this for now, Let's talk more about the usecase in the call.

Feel free to reopen.

**Comment by abuaboud** [comment]
This is done.
