### ISSUE TITLE
GoogleSheet New Row Trigger Timer

### ISSUE THREAD

**Issue by briannezhad** [activepieces/activepieces#1553]
**Is your feature request related to a problem? Please describe.**
Yes, as of now, Google Sheets check every 5 minutes for the new row. It would be great if we could set this timer ourselves. for example, every 1 second.

**Describe the solution you'd like**
Check GoogleSheet for new changes every 1 second.

**Describe alternatives you've considered**
None as of now.

**Additional context**
<img width="767" alt="Screenshot 2023-06-26 at 6 33 41 AM" src="https://github.com/activepieces/activepieces/assets/10551124/cdb9095e-4877-4c65-b644-b75d8106843d">

**Comment by abuaboud** [comment]
Thank you for opening the issue:

Linking this as it's related -> https://github.com/activepieces/activepieces/issues/1364

**Comment by abuaboud** [comment]
The changes are merged and will be released in 0.5.0

@briannezhad You should be able to modify this from the environment variables, please take look at the documentation :D
