### ISSUE TITLE
Google Calendar Create Event Date Time Instructions

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1566]
When I create an event on Google Calendar, there are no instructions to how to type the date time to start and end the event.

The instructions should guide me on:
1- The formatting of the date time.
2- The timezone.

Screenshot:
<img width="603" alt="Screenshot 2023-06-28 at 23 04 20" src="https://github.com/activepieces/activepieces/assets/97393596/986dd36a-790d-4b5a-a6ec-cf6852eaa780">

**Comment by abuaboud** [comment]
@ashrafsamhouri It should accept any format, and timezone will be parsed from the format?

Was this a problem?
