### ISSUE TITLE
[BUG]: http body editor is not properly aligned.

### ISSUE THREAD

**Issue by tolgaulas** [activepieces/activepieces#1597]
**Describe the bug**
The texts are not justified in the body editor of "send http request"

**To Reproduce**
1. Create an HTTP request, set type post and edit body to be send.

**Expected behavior**
The editor lines should properly displayed after the line numbers. 

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/1431106/0cdd67c5-7054-4817-89d9-f47b6b5ffbb6)
**Additional context**
Tried both on chrome, firefox and brave browsers.

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer Can you please take look

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer I have seen you mentioned this issue, Is it solved?

**Comment by AbdulTheActivePiecer** [comment]
No it was a mistake, that got mentioned, will check it out today.
