### ISSUE TITLE
[BUG]: OpenAI sample fails

### ISSUE THREAD

**Issue by bright-spark** [activepieces/activepieces#1623]
**Describe the bug**
OpenAI ChatGPT Tweet fails with : Request failed with status code 429

**To Reproduce**
I opened the sample and entered my API key
I then ran the steps as is
I selected my API key
When I try and test the ChatGPT step it fails
The error message is : Request failed with status code 429

**Expected behavior**
It should have given me a sample Tweet

**Screenshots**
none

**Additional context**
I tried my own prompt but the same happened

**Comment by ashrafsamhouri** [comment]
Hi @bright-spark Do you have a credit card in your OpenAI account? Are you on a paid tier? The 429 error usually comes out of being on the free plan.

**Comment by abuaboud** [comment]
Marking this as resolved, please reopen if @ashrafsamhouri didn't answer your issue.

Thank you for opening the issue, feel free to reopen.
