### ISSUE TITLE
Floating Label & Dropdown Placeholder

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#1626]
**Describe the bug**
After upgrading to Angular 16, dropdown place holder no longer shows.

Labels floating is set to always as temporary fix, otherwise the value will show below the label even if it's marked as touched.

**Comment by Ozak93** [comment]
I found this issue in Google Sheets piece, with action Update Row specifically.

[here's a video demo ](https://veed.io/view/74f27419-d8ff-481b-82be-8896a1ba2b33)

**Comment by AbdulTheActivePiecer** [comment]
@Ozak93, I cannot get this to happen on cloud, is this on an open source image you are showing this from ?

**Comment by Ozak93** [comment]
> @Ozak93, I cannot get this to happen on cloud, is this on an open source image you are showing this from ?

I'm running version 0.4.0 of ActivePieces in a selfhosted docker deployment, If you want i can give you access to it in a private message
