### ISSUE TITLE
Support Multiple Branches (Router Piece) 

### ISSUE THREAD

**Issue by findzhangio** [activepieces/activepieces#1664]
**Is your feature request related to a problem? Please describe.**
Branch nodes support if-elseif-elseif-else, rather than just if-else

**Describe the solution you'd like**
When I use branch nodes, I often need multiple branch operations, such as if-elseif-else, but our branch nodes only support if-else, so I need to drag and drop multiple branch nodes to achieve functionality. This is not redundant for my process, and the limitations of branch nodes are also very significant. When I want to use this node, I can write code like if-elseif-else, which will be very useful for me to edit this process

**Describe alternatives you've considered**
There is a good experience with the retool-workflow branch node

**Additional context**

**Comment by abuaboud** [comment]
DONE :)
