### ISSUE TITLE
[BUG]: Move flow to Uncategorized not working

### ISSUE THREAD

**Issue by Ozak93** [activepieces/activepieces#1666]
I was trying to move a flow from a custom folder to Uncategorized, the folders count were updated as if the flow was moved but the flow wasn't actually moved.

[Video demoing the issue ](https://www.veed.io/view/0a9dccf4-22d6-4017-9b58-ab702fecb11b?panel=share)

**Comment by AbdulTheActivePiecer** [comment]
Much Appreciated @Ozak93, going to open a PR to fix the issue, will get it released on Sunday.
