### ISSUE TITLE
Property that is a collection of fields

### ISSUE THREAD

**Issue by MoShizzle** [activepieces/activepieces#1682]
**Is your feature request related to a problem? Please describe.**
When working with complex inputs (e.g physical address) that take in multiple inputs that are a part of the same property (e.g street name input, zip code input, city input), and having some inputs required and some not required, it is sometimes limiting separating all these inputs into different properties, especially when it comes to validation. As the "parent" property is optional, but if you want to add it, you have 2 required fields and 2 optional fields for example.

**Describe the solution you'd like**
Creating a new kind of property that is a collection of other properties, with different required values, where if the user from the Optional inputs clicks e.g Address, multiple inputs are automatically added instead of adding them one by one.

**Describe alternatives you've considered**
Manually adding each input, and validating after the trigger or action runs.

**Comment by sheldondz** [comment]
would be great to have a prop to support an array of objects. Currently JSON is the only option for this.

**Comment by abuaboud** [comment]
It's now supported
