### ISSUE TITLE
[BUG]: Can't edit HTTP header key if large value entered

### ISSUE THREAD

**Issue by dennisklappe** [activepieces/activepieces#1684]
**Describe the bug**
If a large value is given to an HTTP request piece, it is no longer possible to see or edit the key without removing the value first.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a "Send HTTP request."
2. Enter a key
3. Enter a large value
4. Try to see or edit key

**Expected behaviour**
Be able to change the key or extend the container's width.

**Screenshots**
<img width="346" alt="chrome_w8pFnzwaPJ" src="https://github.com/activepieces/activepieces/assets/35347995/0fb2c07e-6c72-4c35-9037-ac738a8da9fb">

**Additional context**
no

**Comment by Ozak93** [comment]
Hi! You can expand the side panel to view the content more clearly, but i do agree the Flex factor should be relative to the available size of the row e.g the  key always has atleast 1/4 the row and the value takes 3/4
![catto_http](https://github.com/activepieces/activepieces/assets/31257994/2dcd4a21-445a-49aa-a3de-3a2465614fe7)

**Comment by abuaboud** [comment]
Should be fixed now
