### ISSUE TITLE
[Suggestion] display Duration for each Piece in the Run Duration panel

### ISSUE THREAD

**Issue by Ozak93** [activepieces/activepieces#1694]
When you have a large flow with complex pieces 30+ like some of my flows, total flow duration becomes relevant. especially with Code pieces involved or external API calls in the flow. having to click each individual piece AFTER a run/test is cumbersome and inefficient when flows are complex.

The solution is simple, Display the duration of each piece next to it's pass/fail status checkmark in the Run Details panel. and a total run duration of the entire flow would be useful!

**Comment by abuaboud** [comment]
Hi @Ozak93 

I think it's usually not important information for the usual use case as most of the flows are not time intensive and it would clutter the interface for most of the cases, I believe it should stay on the left sidebar.

I am closing this issue, feel free to reopen.
