### ISSUE TITLE
[Suggestion] Test flow Run Details real-time results

### ISSUE THREAD

**Issue by Ozak93** [activepieces/activepieces#1695]
When a flow is being tested or triggered and is running. It would be most helpful to make the Run Details side panel more interactive by updating it with the the current step and it's result once it's done "real-time" instead of waiting x period of time and then get the whole flow results in one go.

this is desirable for two main reasons:

1. When the flow is taking long i don't get suspicious that something is wrong with my flow and end it prematurely, **or think its stuck because i'm not getting any visual feedback that it's not stuck and things are happening**

  to demo this here's a [video of me testing one of my flows](https://www.veed.io/view/26cb4dcc-6131-4f12-a937-4cdeeea90648?panel=share)
  Notice the video is over a minute long! and almost nothing happens in the video except past the minute mark ,that's when the flow ends and i get the entire Run Details result in one go.
  but before that i had to keep waiting, wondering if it's really running or just stuck!

2. It would provide me a direct way to gauge the speed of each flow when i get real-time results in the Run Details as soon they finish, e.g "Oh my code piece number two took 5 seconds long to finish i should optimize my code!"

This suggestion would build upon my other suggestion ( #1694 ) to display the Duration of each piece in their run details row

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/3107
