### ISSUE TITLE
Display version # on the main screen of GUI

### ISSUE THREAD

**Issue by phestvik** [activepieces/activepieces#1704]
Would it be possible to display the version number of the software on the main screen of the window?

I am using the self hosted docker image and as a relative newbie to self hosting, I wasn't able to check whether the container updated from 0.4.0 to 0.5.0.

Just a thought. Thanks :)

![image](https://github.com/activepieces/activepieces/assets/88210985/7f189811-f0ee-43d8-9dd4-7872cec47cc9)

**Comment by abuaboud** [comment]
@allcontributors please add @phestvik for ideas

**Comment by abuaboud** [comment]
@phestvik Great Suggestion, Labeled It and added it backlog

In mean time you can visit `/api/v1/flags` and you will find the current version

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/pull/4482#issuecomment-2060015613
