### ISSUE TITLE
New row add in google sheet trigger is not triggering

### ISSUE THREAD

**Issue by alfmarkel** [activepieces/activepieces#1709]
**Describe the bug**
New row add in google sheet trigger is not triggering

**To Reproduce**
I have 2 tabs in my google sheet.  
Tab 1 is labeled written and selected in the trigger
when I copy from tab 2 labeled to do and paste in tab 1 as a new row
nothing happens

 **Expected behavior**
I expected to have results from trigger for step 2 to use for chatgpt

I'm trying to leverage the blog post template you provided.

**Comment by abuaboud** [comment]
@alfmarkel Discord is best support for such usecases, but can you provide more information for example.

The way it works after you press publish, It will run every 5 minutes and fetch the new rows. 

Is your flow published?
