### ISSUE TITLE
[BUG]: Approval piece generates localhost links

### ISSUE THREAD

**Issue by mnbro** [activepieces/activepieces#1711]
**Describe the bug**
Approval piece (Action: Create Approval Links) generates links containing localhost:

`{
  "approvalLink": "http://127.0.0.1:3000/v1/flow-runs/qp5GyDCZ02DR51Ep4NsAT/resume?action=approve",
  "disapprovalLink": "http://127.0.0.1:3000/v1/flow-runs/qp5GyDCZ02DR51Ep4NsAT/resume?action=disapprove"
}`

**Expected behavior**
The generated links should use fqdn setup by env variable AP_FRONTEND_URL

**Comment by abuaboud** [comment]
Thank you for reporting this issue, @khaledmashaly can you please take look

**Comment by abuaboud** [comment]
Thank you, @mnbro  should be fixed in next release :D
