### ISSUE TITLE
Base64 for SFTP

### ISSUE THREAD

**Issue by FlorinBuffet** [activepieces/activepieces#1714]
**Is your feature request related to a problem? Please describe.**
Base64 is available for Amazon S3 but not for FTP

**Describe the solution you'd like**
Can the option to store a Base64 String as a file also be available for FTP (and maybe dropbox?)
Or would it be easier to create a piece to convert base64 to file and then process the file further?

**Comment by abuaboud** [comment]
🎉 Thank you for opening the issue! labeled it and added it to the project board.

Our team always tries to prioritize tasks based on feedback, and contributors usually love taking them up. 🚀 Your input is valuable to us!

**Comment by FlorinBuffet** [comment]
@abuaboud What is required to push this a little to the front in the feature request section?

**Comment by abuaboud** [comment]
@FlorinBuffet Should be done
