### ISSUE TITLE
Matrix configuration for flows

### ISSUE THREAD

**Issue by x7airworker** [activepieces/activepieces#1721]
**Is your feature request related to a problem? Please describe.**
I have the situation where I have a flow but need several variants with only a few configuration changes (e.g. auth, some checkboxes etc.).

**Describe the solution you'd like**
Some kind of matrix configuration which you can refer to in the flow and change several variables outside the editor.

**Describe alternatives you've considered**
 I could clone my flow several times, but this makes editing the flow logic afterwards much harder.

**Comment by abuaboud** [comment]
@x7airworker Interesting, is this use case where you want to deploy the flow for multiple users but with different configuration.

This is doable for certain use cases, where do another flow that calls the flow with webhook and provide all configuration in the webhook, what is the the exact use case?

**Comment by x7airworker** [comment]
@abuaboud I basically sync data from one system to another using a flow with a schedule trigger and some filters etc.. But now I have different credentials for different instances of these systems. And I expect that I need to do some changes to the logic in the future, so thats why I want some kind of matrix configuration just like you can do in github actions configuration for example. This would allow me to make changes to the flow once and have them applied for 10+ systems.

**Comment by abuaboud** [comment]
@x7airworker We used to have something for this use case (pre opensource), but I am open for suggestion how this could fit without complicating the system for normal use case
