### ISSUE TITLE
Button to Rerun Flows from Run

### ISSUE THREAD

**Issue by Ozak93** [activepieces/activepieces#1725]
It would be very helpful in the "Runs" page to have a button to re-run a flow regardless if it was success/fail. 

use cases:

1- a flow that was triggered remotely via a irreproducible action but the flow failed and you would like to re-run the flow.
2- Debugging a specific flow with specific input conditions.
3- process failed flows.

Currently when i get a failed flow, i have to find that flow, open it in View Only, copy the trigger's input body, use Postman to POST to my webhook trigger to effectively re-run the flow with the same data. this can be frustrating and time consuming. a rerun button would solve this issue!

**Comment by AbdulTheActivePiecer** [comment]
https://community.activepieces.com/t/retry-after-fail/342/2

**Comment by abuaboud** [comment]
https://community.activepieces.com/t/retry-after-fail/342/2

**Comment by abuaboud** [comment]
It's great if we can make it run from same failed step, otherwise it might be not useful for certian customers.
