### ISSUE TITLE
IMAP connection should have presets

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1748]
I didn't know if Gmail will require TLS or not, and I thought it used the default port so it took me a couple of attempts until I realized the correct settings to connect to Gmail.

If there is a dropdown as the first option in the IMAP connection that lets me choose the provider and autofill the next fields, it will make our lives much easier.

Screenshot of the settings that worked for me:
<img width="491" alt="Screenshot 2023-07-24 at 14 49 31" src="https://github.com/activepieces/activepieces/assets/97393596/89ed4752-4e53-460f-a280-b3c037fa6a06">

**Comment by abuaboud** [comment]
I added instructions + auth validation
