### ISSUE TITLE
Global keys for arrays

### ISSUE THREAD

**Issue by BastienMe** [activepieces/activepieces#1754]
**Is your feature request related to a problem? Please describe.**
I find it difficult for users who are not familiar with tools like ActivePieces or IT in general to manipulate arrays.

**Describe the solution you'd like**
If a piece returns an array of objects like this 
```
[
    {
        "email" : "first@mail.com",
        "message" : "first mail"
    },
    {
        "email" : "second@mail.com",
        "message" : "second mail"
    },
    { 
        "email" : "third@mail.com",
        "message" : "third mail"
    }
]
```

I think it would be interesting to add global keys, for example in this array, one global key for the email and one for the message
So, if I want to send an email via the Gmail piece to these 3 people in my table, I'd just have to mention the global key email in the "recipient's email" field and message in the "body" field of the Gmail piece, which would loop over all the indexes in the table.

**Additional context**
So we'll have something like this :
![image](https://github.com/activepieces/activepieces/assets/71411115/8edf9fc8-51a7-43ff-83b1-fdd7c4a2e5be)
Instead of this : 
![image](https://github.com/activepieces/activepieces/assets/71411115/dd7ba890-0c6e-4abc-b991-a8a3cc7c2d67)

**Comment by BastienMe** [comment]
If you like it, I would like to work on it

**Comment by abuaboud** [comment]
Hi @BastienMe, thank you for opening the issue.

I think the issue with this approach is that it's way too implicit, It took me while to understand what this feature do even after reading the issue description.

The alternative there is to put loop piece which iterate of the array and send the gmail which is longer but explicit (in other words you can understand what's going on from first look)
