### ISSUE TITLE
[BUG]: Private registry

### ISSUE THREAD

**Issue by BastienMe** [activepieces/activepieces#1755]
**Describe the bug**
I created a custom piece "khub-heroes" that I have published on a private local registry with Verdaccio. 
When I try to import my piece in the "My Pieces" page,  I get the error : 
```
[API] [09:21:05 UTC] ERROR: Error: Cannot find module '@activepieces/piece-khub-heroes'
[API] [09:21:05 UTC] ERROR:     at webpackEmptyContext (webpack://activepieces/engine/src/%20sync:2:1)
[API] [09:21:05 UTC] ERROR:     at <anonymous> (webpack://activepieces/engine/src/main.ts:73:53)
[API] [09:21:05 UTC] ERROR:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[API] [09:21:05 UTC] ERROR:     at extractInformation (webpack://activepieces/engine/src/main.ts:73:25) {
[API] [09:21:05 UTC] ERROR:   code: 'MODULE_NOT_FOUND'
[API] [09:21:05 UTC] ERROR: }
```

**To Reproduce**
1. Publish a piece on a private registry
2. Import it in the page "My pieces"

**Expected behavior**
The piece should be imported

**Additional context**
The error occurs at the line `const pieceModule = await import(input.pieceName)` in the file packages/engine/src/main.ts

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/2802
