### ISSUE TITLE
[BUG]:   npmignore: invalid argument.

### ISSUE THREAD

**Issue by Freebase394** [activepieces/activepieces#1778]
**Describe the bug**
I just want to test this system. 
It seems to be quite interesting! 

**To Reproduce**
1.I try to install inside of docker container: sudo docker run -d -p 8080:80 -v ~/.activepieces:/root/.activepieces -e AP_QUEUE_MODE=MEMORY -e AP_DB_TYPE=SQLITE3 -e AP_FRONTEND_URL="http://192.168.50.91:8080" activepieces/activepieces:latest

2. Gives-me this error:
root@dockeraio:~# /usr/src/app/node_modules/buffer-equal-constant-time/.npmignore: invalid argument.^C
root@dockeraio:~# sudo docker run -d -p 8080:80 -v ~/.activepieces:/root/.activepieces -e AP_QUEUE_MODE=MEMORY -e AP_DB_TYPE=SQLITE3 -e AP_FRONTEND_URL="http://192.168.50.91:8080" activepieces/activepieces:latest
Unable to find image 'activepieces/activepieces:latest' locally
latest: Pulling from activepieces/activepieces
32fb02163b6b: Pull complete
167c7feebee8: Pull complete
d6dfff1f6f3d: Pull complete
e9cdcd4942eb: Pull complete
ca3bce705f6c: Pull complete
4f4cf292bc62: Pull complete
054111693acb: Pull complete
6ebdc2485ae0: Pull complete
63aedd7b9a0f: Pull complete
5fcc51c38fda: Pull complete
13781ec03e0c: Pull complete
b12ae7fa86a4: Pull complete
b970a6259568: Pull complete
75fa67929515: Pull complete
17a3d214ff14: Pull complete
0e248b3a8227: Pull complete
23ed038e206f: Pull complete
ae4af4943300: Extracting [==================================================>]  433.5MB/433.5MB
78554ae5be01: Download complete
232e7421965a: Download complete
33558499678b: Download complete
f1f80142a4a5: Download complete
docker: **failed** to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /usr/src/app/node_modules/buffer-equal-constant-time/.npmignore: **invalid argument**.
See '**_docker run --help_**'.

**Expected behavior**
with the above command it should be possible to have the container run successfully

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/19652056/64e8a82d-3a64-4693-8fb1-7f83e7a7a078)

**Additional context**
My system of my docker machine: 
NOTE: (It's a LXC container) Is there a problem with this?
![image](https://github.com/activepieces/activepieces/assets/19652056/2bc41a09-b67a-4b96-a8a9-987bf28a16cf)

**Comment by abuaboud** [comment]
I have seen this issue before, try build the docker image in same machine by running 'docker build .'


Please let me know if that works

**Comment by abuaboud** [comment]
Closing, please let me know if you still have this issue
