### ISSUE TITLE
[BUG]: Unable to connect to mysql db

### ISSUE THREAD

**Issue by yipfram** [activepieces/activepieces#1780]
**Describe the bug**
When I try to add an action to my mysql action, but when i add the connection I go to tables list this is the message I receive :  "An unxpected error occured please contact our support" but I tested the credentials i inputed in the connection section, everything works
**To Reproduce**

1. Create new flow
2. add an trigger (Google sheets in my case)
3. add mysql as an action
4. add new connection profil with "localhost" as host and "3306" as port
5. go to "tables", and see the error message "An unxpected error occured please contact our support"

**Expected behavior**
I excpected to see a list of tables (1 in my case)
**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/46826777/ed4b9ac4-8e22-4bb1-be4a-e5b8303cc15d)

**Additional context**
My server is self hosted in a vps..

**Comment by abuaboud** [comment]
@yipfram can you please provide the information, on which installation mode did you use? And what is activepieces version?

Can you please try to use 127.0.0.1 instead of localhost and see if that's fix it

**Comment by JanHolger** [comment]
@yipfram Try @abuaboud 's answer if you are running in sandboxed mode.

If you are running in unsandboxed mode (default) with docker compose you need to find out the docker network's address or more specificly the address of the host in that network. You can do that using `docker network inspect activepieces_activepieces | grep Gateway`. You can then use this address to connect to the mysql server. If the mysql server is also running inside a docker container and the port is exposed to the host (-p 3306:3306) it should work out of the box. If the mysql server is running directly on the host itself you need to change the address mysql is listening to (`bind-address` option in the mysql config) to either `0.0.0.0` (keep in mind to set up a firewall in this case) or in newer versions of mysql you can also use a comma separated list `127.0.0.1,172.x.0.1`

**Comment by yipfram** [comment]
hello,
i used the docker install with a db provided by cloudpanel.changing to localhost idn't changed the issue

**Comment by abuaboud** [comment]
@yipfram I think the database url is not correct, as I assume easypanel creating the database in different containers, you need to provide the internal
