### ISSUE TITLE
Linear Piece

### ISSUE THREAD

**Issue by calebadcock** [activepieces/activepieces#1791]
**Is your feature request related to a problem? Please describe.**
No integration with Linear yet.

**Describe the solution you'd like**
Add Issue
Update Issue

**Describe alternatives you've considered**
I have a custom code block that works fine, but the piece could be useful for other users

**Additional context**
They have a typescript SDK
https://developers.linear.app/docs/sdk/getting-started

**Comment by abuaboud** [comment]
I'm a huge fan of Linear! It's great to see that it's been added to the Pieces dashboard.
 
I hope one of contributors / Developers pick this up :D

The documentation link provided (https://www.activepieces.com/docs/developers/overview)

**Comment by kishanprmr** [comment]
@abuaboud  I would like to take this up. You can assign it to me.

**Comment by abuaboud** [comment]
@kishanprmr Let's do it! :D done
