### ISSUE TITLE
Internal Connection error, failed please check your console.

### ISSUE THREAD

**Issue by MacRichardson** [activepieces/activepieces#1822]
Not sure what this means. Is there a way to fix this?

**Comment by abuaboud** [comment]
Thank you for opening this issue, @MacRichardson Can you please tell me how to reproduce this?

**Comment by MacRichardson** [comment]
Hi, yeah it happened when I tried adding my API key to the OpenAI plug in. Everything I tried to add it, this error would pop up.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abuaboud** [comment]
Thank you, I am working on fix.

Will update this ticket soon

**Comment by abuaboud** [comment]
@MacRichardson Fixed and released to the cloud, please let me know if you still have this issue.

Thank you a lot and Sorry for the problem
