### ISSUE TITLE
Trigger Request on Google Calendar: Reminder System

### ISSUE THREAD

**Issue by adambagaskara** [activepieces/activepieces#1829]
I tried to find an alternatives to create a more like SlackBot that could provide my team their flexible schedule based on some calendars on Google Calendar

The connection between Activepieces and Google Calendar is clear, but there's a problem: the trigger just allow us to get notification when the event is created or updated. Nothing more.

I wish Activepieces developer could provide another trigger such as reminder before the event start, and else.

**Comment by abuaboud** [comment]
I believe this is better to be achieved through the delay step, currently you can use Delay Until with Date Utility piece to subtract / add to the date, and then send the reminder, while the trigger stay Event Created.

@adambagaskara I think this is valid solution, let me know if you have any other thoughts / question, closing this ticket feel free to reopen.
