### ISSUE TITLE
Support dynamic dropdown inside OAuth2 props

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#1830]
This issue was created by @kishanprmr  in [Activepieces Discord](https://discord.gg/2jUXBKDdP8)

I would like to request support for dynamic dropdowns inside OAuth2 props. For example, in the Amazon Seller OAuth2 configuration, the first dropdown should allow selecting a region, and the second dropdown should dynamically populate with the countries available in that region. This would greatly improve the user experience and make the integration more flexible. Thank you!

**Comment by partnerpro-uk** [comment]
This would be great, because then we can configure pieces to have a drop down to select custom scopes for our OAuth 2 API connections!
