### ISSUE TITLE
[BUG]: New video in Youtube Channel - text contains - keyword: does not work

### ISSUE THREAD

**Issue by spinnaker1** [activepieces/activepieces#1850]
**Describe the bug**
Using the "new video in channel" youtube node to check wether the keyword banana is contained in the video title, always returns the condition false. Which is wrong, because it actually is part of the video title.
Using rss-feed reader instead to do the same, produces the same result.

**To Reproduce**
1. Create 'New Video in Channel" node
2. Create 'Branch: Decide what happens based on an if condition result'
2.a. First Value: ' `1. New Video In Channel title `'
2.b. Condition: (Text) Contains
2.b. Second Value: '`Banana`'
3. See error: 
```
Output: {
  "condition": false
}

```
**Expected behavior**
Output condition of IF node, must return true.

**Additional**
- If use first value: ' `1. New Video In Channel title `' and second value: ' `1. New Video In Channel title `' it returns true.
- If use first value 'banana' and second value 'banana' it returns true.

**Comment by abuaboud** [comment]
@spinnaker1 can you please use Test flow instead of the step, and click on branch and copy the input and output section?

That would make it easier to debug.

**Comment by spinnaker1** [comment]
> @spinnaker1 can you please use Test flow instead of the step, and click on branch and copy the input and output section?

### Input:

`{"conditions":[[{"firstValue":"Facebook Sold me this Antivirus USB","secondValue":"Facebook","operator":"TEXT_CONTAINS","caseSensitive":false}]],"inputUiInfo":{"currentSelectedData":{"condition":false},"lastTestDate":"Sat Aug 12 2023 xx:xx:xx GMT+xxxx (xxx xxx)"}}
`

---------------------

### Output:
`{"condition":true}`

**Comment by abuaboud** [comment]
@spinnaker1 The flow should work correctly I assume with test flow, It seems bug with test step I will mark it as bug and check it soon

Thank you!

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/2016
