### ISSUE TITLE
Could you design a stop date and time? Can the setting for every five minutes be modified? Thank you.

### ISSUE THREAD

**Issue by av8dtop** [activepieces/activepieces#1853]
Could you design a stop date and time? Can the setting for every five minutes be modified? Thank you.

**Comment by abuaboud** [comment]
@av8dtop What do you mean by stop date and time? can you explain the exact usecase?

**Comment by abuaboud** [comment]
You can change the default five minutes from `AP_TRIGGER_DEFAULT_POLL_INTERVAL`

Check it here https://activepieces.com/docs/install/configurations/environment-variables

Feel free to reopen the ticket with more information
