### ISSUE TITLE
[BUG]: edit connection , output : Internal Connection error, failed please check your console.

### ISSUE THREAD

**Issue by av8dtop** [activepieces/activepieces#1854]
Internal Connection error, failed please check your console.

i use docker 0.6.0 => 0.7.0

"level":30,"time":1691840144511,"pid":8,"hostname":"5556a0673855","reqId":"req-n4","req":{"method":"POST","url":"/v1/app-connections","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":40464},"msg":"incoming request"}

\{"level":50,"time":1691840144970,"pid":8,"hostname":"5556a0673855","msg":"[errorHandler]:"}

e{"level":50,"time":1691840144970,"pid":8,"hostname":"5556a0673855","err":{"type":"Error","message":"{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"querystring/version must match pattern \\\"^([~^])?[0-9]+\\\\.[0-9]+\\\\.[0-9]+$\\\"\"}","stack":"Error: {\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"querystring/version must match pattern \\\"^([~^])?[0-9]+\\\\.[0-9]+\\\\.[0-9]+$\\\"\"}\n at <anonymous> (webpack:///src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts:21:15)\n at Generator.next (<anonymous>)\n at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:164:62)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"querystring/version must match pattern \\\"^([~^])?[0-9]+\\\\.[0-9]+\\\\.[0-9]+$\\\"\"}"}

{"level":50,"time":1691840145010,"pid":8,"hostname":"5556a0673855","reqId":"req-n4","req":{"method":"POST","url":"/v1/app-connections","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":40464},"res":{"statusCode":500},"err":{"type":"Error","message":"{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"querystring/version must match pattern \\\"^([~^])?[0-9]+\\\\.[0-9]+\\\\.[0-9]+$\\\"\"}","stack":"Error: {\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"querystring/version must match pattern \\\"^([~^])?[0-9]+\\\\.[0-9]+\\\\.[0-9]+$\\\"\"}\n at <anonymous> (webpack:///src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts:21:15)\n at Generator.next (<anonymous>)\n at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:164:62)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"querystring/version must match pattern \\\"^([~^])?[0-9]+\\\\.[0-9]+\\\\.[0-9]+$\\\"\"}"}

�{"level":30,"time":1691840145011,"pid":8,"hostname":"5556a0673855","reqId":"req-n4","res":{"statusCode":500},"responseTime":500.2085090018809,"msg":"request completed"}

**Comment by av8dtop** [comment]
0.6.0 is ok

**Comment by abuaboud** [comment]
Fixed and released 0.7.1
