### ISSUE TITLE
ASk ChatGPT piece trough MS Azure OpenAI API key

### ISSUE THREAD

**Issue by iokinpardo** [activepieces/activepieces#1855]
**Requirement description:**
I wanted to check with you if there is posible to run with **MS Azure OpenAI API key** in parallel to OpenAI in the "**ASk ChatGPT**" piece? Many companies and businesses run in a secure way under Azure account, so this could be **something critical.**

Many thanks in advance.

**Alternatives considered:**
- **Image 1** shows the **final-full information** that is required to set on a **LLM Node** for Flowise. 
- In the **Image 2**, you can see that just setting that information the AI based Flow runs properly. 
- **Image 3** is the updated version for the same Azure LLM Node. 
- In the **Image 4**, you can see the **created Deployments** list on **Azure AI Studio** where you can get required infromation

More detailed information you can see in this link: 
https://docs.flowiseai.com/chat-models/azure-chatopenai

Please let me know if you find this information helpful.

Image 1:
![image](https://github.com/activepieces/activepieces/assets/6673107/11b0940f-4732-47fd-895e-73e5b65f27e1)

Image 2:
![image](https://github.com/activepieces/activepieces/assets/6673107/480c0cb7-e9fa-4c82-9de6-e81b34c0bb6e)

Image 3:
![image](https://github.com/activepieces/activepieces/assets/6673107/4a164551-3654-45f1-86f5-09fae3d9f73a)

Image 4:
![image](https://github.com/activepieces/activepieces/assets/6673107/d23dc5e5-2886-49ff-9cc9-f48136e7ffae)

**Comment by zjawj** [comment]
模型越多，选择越多！ 💡https://code.mayoubang.cn  免费 AI 代码工具，多种模型满足你的各种编程需求！
