### ISSUE TITLE
Google My Business

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#1891]
For automation Google Maps

**Comment by dongphuchaitrieu** [comment]
Please update this piece!

**Comment by ashrafsamhouri** [comment]
We have to fill in the partnership form with Google regarding this first. I'll do this work and update this issue accordingly.

**Comment by ashrafsamhouri** [comment]
I submitted the form, they say it needs ~2 weeks to get back to us🤞

**Comment by ashrafsamhouri** [comment]
Google rejected our application because we don't manage listings for businesses. I'll un-assign this ticket from me and show them the demand we have from businesses on the roadmap

**Comment by ashrafsamhouri** [comment]
We got approved for Google Business Profile API, we'll proceed with this piece!

**Comment by ludoja** [comment]
My use case is this: If there is a review of X stars => reply with a text taken from poole of predefined replies (I d not want send the same reply for lets say all 5 stars reviews, I want to vary them).

Will it be possible?

**Comment by ashrafsamhouri** [comment]
@ludoja Hopefully yes! Let's see.

**Comment by dexter7wolf** [comment]
I would integrate this pieces with a chatbot ai, to interact withGoogle Business Chat and answer reviews on google maps. It will be possible? Thanks

**Comment by ashrafsamhouri** [comment]
Yes @dexter7wolf It should be possible, @ShayPunter will give us updates on this piece soon

**Comment by ashrafsamhouri** [comment]
@ShayPunter I unassigned the issue to give clarity on it on the roadmap, as long as it's assigned it will show "In Progress". Please let me know when you'd like to take it back!

**Comment by dexter7wolf** [comment]
> Yes @dexter7wolf It should be possible, @ShayPunter will give us updates on this piece soon

Awesome! So for this type of pieces the integration chat bot ai-Google My Business, how it words? API? WebHook?
Thanks in adavance!

**Comment by ashrafsamhouri** [comment]
I don't know the details of the implementation, @ShayPunter is implementing it

**Comment by dongphuchaitrieu** [comment]
> > Yes @dexter7wolf It should be possible, @ShayPunter will give us updates on this piece soon
> 
> Awesome! So for this type of pieces the integration chat bot ai-Google My Business, how it words? API? WebHook? Thanks in adavance!

I'm using one on Pabbly; it's pretty cool to automate customer replies on GMB, create new images about the testimonials and publish them on social media. I can't wait to see ActivePieces implement GMB.
