### ISSUE TITLE
[Piece]: Go High Level

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#1905]
https://gohighlevel.com/

**Comment by achieve1** [comment]
Please ensure it works with High Level sub accounts as well!

**Comment by Maxxeen** [comment]
In case there is any confusion...

HighLevel/GoHighLevel/GHL is also LeadConnector.  That is GHL's white label name.  If you look at Zapier integrations you won't find GHL - it is called LeadConnector to protect GHL's white labeled users..

**Comment by abuaboud** [comment]
This is done https://community.activepieces.com/t/lead-connector-gohighlevel-piece-available-on-activepieces/1396/3
