### ISSUE TITLE
[Piece]: TidyCal

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#1916]
Connect with TidyCAL

**Comment by ashrafsamhouri** [comment]
Hey everyone. It looks like TidyCal's API doesn't have any access to webhooks. Do you mind sharing what use cases would you like to achieve between TidyCal and other apps? This task might be blocked due to this limitation.

**Comment by ashrafsamhouri** [comment]
We decided to implement the triggers with polling rather than webhooks since that's the current Zapier implementation as well. @Salem-Alaa will be on it!
