### ISSUE TITLE
WhatsApp for Business

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#1918]
would be great to connect WA

**Comment by ashrafsamhouri** [comment]
This is currently blocked by Meta's verification since they revoked our business verification and we can't apply to verify the scopes requested by the piece.

**Comment by ashrafsamhouri** [comment]
I'm considering doing this through Plivo (https://www.plivo.com/), even if we get direct access to WhatsApp later, it will be great to have a Plivo piece too. I'll post updates here

**Comment by daerol** [comment]
> I'm considering doing this through Plivo (https://www.plivo.com/), even if we get direct access to WhatsApp later, it will be great to have a Plivo piece too. I'll post updates here

I'm also considering of doing this through Twilio, writing on top of the existing Twilio piece.

**Comment by javix64** [comment]
Is there any way to implement another third library like: 

- https://github.com/pedroslopez/whatsapp-web.js/ or 
- https://github.com/WhiskeySockets/Baileys ??

Or can it issue legal problems?

**Comment by abuaboud** [comment]
Hi @javix64 Great Idea, can you create an piece? 

Please shoot me an email at support@activepieces.com / discord 

We would love to send you a swag for that!

**Comment by javix64** [comment]
Hey @abuaboud I have send an email to support, we can keep in touch via discord!
Let's see what we achieve

**Comment by abuaboud** [comment]
This should be done https://github.com/activepieces/activepieces/pull/4639
