### ISSUE TITLE
[Piece]: Facebook comments

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#1936]
New facebook comment, so we can trigger it and use chatGPT to answer it

**Comment by IwanGlainPro** [comment]
Would be amazing

**Comment by ashrafsamhouri** [comment]
This piece is blocked by [Facebook Verification](https://community.activepieces.com/t/facebook-revoked-our-business-verification/25)

**Comment by ashrafsamhouri** [comment]
I deleted our business accounts, once they're totally deleted I'll try to create a new one after some days and see if we can verify ourselves
