### ISSUE TITLE
Redirect URL + Webhook URL is wrong on Demo Instance

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#195]
Currently the fronend redirect url is localhost, we should derive it using system variable.
 
The webhook trigger is url is http (not https) also missing s (after webhook)

**Comment by AbdulTheActivePiecer** [comment]
open a branch issue-195 => fixed the issues, but the http/https is a variable coming from .env inside the backend root directory.

**Comment by abuaboud** [comment]
Moving to @khaledmashaly  to fix the environment variable on the deployment for demo instnace.

**Comment by khaledmashaly** [comment]
Done
