### ISSUE TITLE
Send custom requests in pieces

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1977]
To give users a big relief from being limited in the actions just defined in a piece, and according to a user I just chatted with, it will be great to be able to send custom requests in any piece.

This will be the same as the HTTP piece but with predefined fields like Base URL and the ability to choose a connection.

This default action can also have a direct link to the 3rd party's docs so users can get the endpoints they'd like to use.

**Comment by kishanprmr** [comment]
@ashrafsamhouri This custom requests can be used as action in any piece. For reference, make.com has that functionality
![Screenshot 2023-08-18 092400](https://github.com/activepieces/activepieces/assets/135701940/276f580e-027e-471e-974b-0b8ac27211ef)
![Screenshot 2023-08-18 092558](https://github.com/activepieces/activepieces/assets/135701940/a24ef4aa-04b7-47e4-b390-e3cec315584f)
Both REST and GraphQL custom requests are available.
