### ISSUE TITLE
Port Issue + Unable to setup SSL for frontend and backend perhaps.

### ISSUE THREAD

**Issue by yourbrandmate** [activepieces/activepieces#2006]
Path: /install/options/docker-compose

I was trying to self host on AWS using Docker compose.
However it feels there are a few knowledge gap in my mind that's leading to following error:

1) Unable to setup SSL for frontend, Whenever I visit my https://subdomain.website.in:8080, It shows ssl connection error.
I made sure to follow all guidelines for setting up Certbot for apache 2. It opens the app frontend when i replace https with http.

2) I cannot directly open app frontend using url subdomain.website.in, it only opens when I mention Port in following format: http://subdomain.website.in:8080

I understand that these are not really bugs, But will be helpful if there's any documentation that i can go through to fix these issues.

**Comment by abuaboud** [comment]
We have basic tutorial now

https://www.activepieces.com/docs/install/setup-ssl
