### ISSUE TITLE
[BUG]: Dynamic dropdowns unknown server happened

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#2257]
Many dropdowns show this error at random times. Happened to me and other users. The below screenshot is from a user's Google Sheets step:

![image](https://github.com/activepieces/activepieces/assets/97393596/7465d094-91cf-4e12-b235-0a9a8ca7b696)

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/2299
