### ISSUE TITLE
[BUG]: Sample data fails to select

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#2259]
I have a flow, only a Telegram Bot trigger (New Message).

I tested the trigger 3 times, sent 3 messages, so there are 3 data samples.

When I click on 1 and 2, they keep returning me to 3. This is what I see:

<img width="727" alt="Screenshot 2023-08-26 at 01 26 07" src="https://github.com/activepieces/activepieces/assets/97393596/a4b7323b-9d2e-4f4e-b4fb-6ed3a5b2b893">

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/1217
