### ISSUE TITLE
Mautic Piece (Not showing fields)

### ISSUE THREAD

**Issue by FerBD** [activepieces/activepieces#2313]
**Describe the bug**
Then the Output to Mautic does not contain the data to create the new contact.

**To Reproduce**
1- Trigger: Webhook created ok (pass test flow)
2- Steep 1: Connection to Mautic. Is ok (Pass test flow ok)
Input: 
{
"auth":"**CENSORED**",
"fields":{}
}
Output:
{"status":201,"headers":{"server":"nginx-rc","date":"Mon, 28 Aug 2023 16:29:32 GMT","content-type":"application/json","transfer-encoding":"chunked","connection":"close","mautic-version":"4.0.1","cache-control":"max-age=0, must-revalidate, private","pragma":"no-cache","expires":"Mon, 28 Aug 2023 16:29:32 GMT","vary":"Authorization","location":"/api/contacts/36075","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff"},"body":{"contact":{"isPublished":true,"dateAdded":"2023-08-28T16:29:32+00:00","dateModified":null,"createdBy":1,"createdByUser":"Fernando León","modifiedBy":null,"modifiedByUser":null,"id":36075,"points":0,"color":null,"fields":{"core":{"custom_field_activepieces":{"id":58,"group":"core","label":"custom_field_Activepieces","alias":"custom_field_activepieces","type":"text","properties":[],"value":null,"normalizedValue":null},"calendly__tipo_consultori":{"id":52,"group":"core","label":"Calendly - Tipo Consultoría","alias":"calendly__tipo_consultori","type":"text","properties":[],"value":null,"normalizedValue":null},"calendly__descripcion_de":{"id":51,"group":"core","label":"Calendly - Descripción de la consulta","alias":"calendly__descripcion_de","type":"text","properties":[],"value":null,"normalizedValue":null},"calendly__situacion_actua":{"id":50,"group":"core","label":"Calendly - Situación Actual","alias":"calendly__situacion_actua","type":"text","properties":[],"value":null,"normalizedValue":null},"etq2":{"id":49,"group":"core","label":"ETQ2","alias":"etq2","type":"text","properties":[],"value":null,"normalizedValue":null},"curso_comprado":{"id":57,"group":"core","label":"Curso Comprado","alias":"curso_comprado","type":"multiselect","properties":{"list":[{"label":"Affiliatekers","value":"Affiliatekers"},{"label":"Monetiza Tu Pasión","value":"MTP"},{"label":"Gestor de Afiliados","value":"GASTART"},{"label":"Top Afiliación","value":"TOPAffiliacion"},{"label":"Ecomkers","value":"Ecomkers"}]},"value":null,"normalizedValue":""},"fecha_ultima_compra":{"id":56,"group":"core","label":"Fecha última compra","alias":"fecha_ultima_compra","type":"date","properties":[],"value":null,"normalizedValue":null},"etq1":{"id":48,"group":"core","label":"ETQ1","alias":"etq1","type":"text","properties":[],"value":null,"normalizedValue":null},"politica_privacidad":{"id":46,"group":"core","label":"GDPR","alias":"politica_privacidad","type":"boolean","properties":{"no":"No","yes":"Sí"},"value":0,"normalizedValue":"No"},"admite_ads":{"id":54,"group":"core","label":"Admite ADS","alias":"admite_ads","type":"boolean","properties":{"no":"No","yes":"Sí"},"value":0,"normalizedValue":"No"},"title":{"id":1,"group":"core","label":"Title","alias":"title","type":"lookup","properties":{"list":["Mr","Mrs","Miss"]},"value":null,"normalizedValue":null},"firstname":{"id":2,"group":"core","label":"First Name","alias":"firstname","type":"text","properties":[],"value":null,"normalizedValue":null},"lastname":{"id":3,"group":"core","label":"Last Name","alias":"lastname","type":"text","properties":[],"value":null,"normalizedValue":null},"company":{"id":4,"group":"core","label":"Primary company","alias":"company","type":"text","properties":[],"value":null,"normalizedValue":null},"position":{"id":5,"group":"core","label":"Position","alias":"position","type":"text","properties":[],"value":null,"normalizedValue":null},"email":{"id":6,"group":"core","label":"Email","alias":"email","type":"email","properties":[],"value":null,"normalizedValue":null},"mobile":{"id":7,"group":"core","label":"Mobile","alias":"mobile","type":"tel","properties":[],"value":null,"normalizedValue":null},"phone":{"id":8,"group":"core","label":"Phone","alias":"phone","type":"tel","properties":[],"value":null,"normalizedValue":null},"points":{"id":9,"group":"core","label":"Points","alias":"points","type":"number","properties":[],"value":null,"normalizedValue":null},"fax":{"id":10,"group":"core","label":"Fax","alias":"fax","type":"tel","properties":[],"value":null,"normalizedValue":null},"address1":{"id":11,"group":"core","label":"Address Line 1","alias":"address1","type":"text","properties":[],"value":null,"normalizedValue":null},"address2":{"id":12,"group":"core","label":"Address Line 2","alias":"address2","type":"text","properties":[],"value":null,"normalizedValue":null},"city":{"id":13,"group":"core","label":"City","alias":"city","type":"text","properties":[],"value":null,"normalizedValue":null},"state":{"id":14,"group":"core","label":"State","alias":"state","type":"region","properties":[],"value":null,"normalizedValue":null},"zipcode":{"id":15,"group":"core","label":"Zip Code","alias":"zipcode","type":"text","properties":[],"value":null,"normalizedValue":null},"country":{"id":16,"group":"core","label":"Country","alias":"country","type":"country","properties":[],"value":null,"normalizedValue":null},"preferred_locale":{"id":17,"group":"core","label":"Preferred Locale","alias":"preferred_locale","type":"locale","properties":[],"value":null,"normalizedValue":null},"timezone":{"id":18,"group":"core","label":"Preferred Timezone","alias":"timezone","type":"timezone","properties":[],"value":null,"normalizedValue":null},"last_active":{"id":19,"group":"core","label":"Date Last Active","alias":"last_active","type":"datetime","properties":[],"value":null,"normalizedValue":null},"attribution_date":{"id":20,"group":"core","label":"Attribution Date","alias":"attribution_date","type":"datetime","properties":[],"value":null,"normalizedValue":null},"attribution":{"id":21,"group":"core","label":"Attribution","alias":"attribution","type":"number","properties":{"roundmode":4,"scale":2},"value":null,"normalizedValue":null},"website":{"id":22,"group":"core","label":"Website","alias":"website","type":"url","properties":[],"value":null,"normalizedValue":null}},"social":{"facebook":{"id":23,"group":"social","label":"Facebook","alias":"facebook","type":"text","properties":[],"value":null,"normalizedValue":null},"foursquare":{"id":24,"group":"social","label":"Foursquare","alias":"foursquare","type":"text","properties":[],"value":null,"normalizedValue":null},"instagram":{"id":25,"group":"social","label":"Instagram","alias":"instagram","type":"text","properties":[],"value":null,"normalizedValue":null},"linkedin":{"id":26,"group":"social","label":"LinkedIn","alias":"linkedin","type":"text","properties":[],"value":null,"normalizedValue":null},"skype":{"id":27,"group":"social","label":"Skype","alias":"skype","type":"text","properties":[],"value":null,"normalizedValue":null},"twitter":{"id":28,"group":"social","label":"Twitter","alias":"twitter","type":"text","properties":[],"value":null,"normalizedValue":null}},"personal":[],"professional":[],"all":{"id":"36075","custom_field_activepieces":null,"calendly__tipo_consultori":null,"calendly__descripcion_de":null,"calendly__situacion_actua":null,"etq2":null,"curso_comprado":null,"fecha_ultima_compra":null,"etq1":null,"politica_privacidad":false,"admite_ads":false,"title":null,"firstname":null,"lastname":null,"company":null,"position":null,"email":null,"mobile":null,"phone":null,"points":0,"fax":null,"address1":null,"address2":null,"city":null,"state":null,"zipcode":null,"country":null,"preferred_locale":null,"timezone":null,"last_active":null,"attribution_date":null,"attribution":null,"website":null,"facebook":null,"foursquare":null,"instagram":null,"linkedin":null,"skype":null,"twitter":null}},"lastActive":null,"owner":null,"ipAddresses":[],"tags":[],"utmtags":null,"stage":null,"dateIdentified":null,"preferredProfileImage":null,"doNotContact":[],"frequencyRules":[]}}}

**Expected behavior**
Create Contact in Mautic via WebHook

**Screenshots**
![Captura de pantalla 2023-08-28 a las 18 35 58](https://github.com/activepieces/activepieces/assets/143431719/500d7eaa-f04a-4b5a-8279-639c510f6a26)
![Captura de pantalla 2023-08-28 a las 18 36 25](https://github.com/activepieces/activepieces/assets/143431719/996c7e1a-cf02-45a0-a3ae-b8df8d8091ce)

**Additional context**
Versión Mautic v4.0.1
The API is only available as OAuth 2

![Captura de pantalla 2023-08-26 a las 18 38 50](https://github.com/activepieces/activepieces/assets/143431719/6f0f9790-10e9-4aae-9c14-d2f7fdcaff66)

**Comment by abuaboud** [comment]
This is fixed now
