### ISSUE TITLE
[Piece]: Brevo integration

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#2365]
Brevo is a popular email marketing provider (formerly known as Sendinblue).
For example, trigger when a contact is added to a specific list, automation or atribute, or action that updates a contact's details such as list, atribute, automation, etc

**Comment by abuaboud** [comment]
It's already there, please also check this bug

https://community.activepieces.com/t/new-ghost-member-not-added-to-brevo-list/121
