### ISSUE TITLE
Filter Runs By Flow

### ISSUE THREAD

**Issue by Vitalini** [activepieces/activepieces#2377]
1. Add a piece for fields validation
2. Add a setting with backup. + Add a piece for auto backup.
3. Export/import pieces config
4. For the "runs" page add more stats: 
- Show the amount of runs for 24h/30d/total
- Show runs per flow
- General stats banner on the top of the page: All/Success/Failed
- Filters for flow
- Execution time
5. Add history for the piece changes (not only Draft/Published). Save the last X published versions
6. Use humanize app name for webhook URL + add button edit

**Comment by abuaboud** [comment]
@Vitalini Can you please explain the first two points?

Regarding point 3, exporting flows is already possible

**Comment by Vitalini** [comment]
@abuaboud 
1. For example I have a webhook as a trigger, and then I need to validate inputs (email, phone number, age) and return stop the flow with an error message.
2. Add a setting menu where I can import/export all flows using one file. Add a piece that can create a backup file (the same file as from setting using export) to put it somewhere (like Google Drive)
3. Yes, found it. Thanks!
