### ISSUE TITLE
Hubspot Extra Properties

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#2407]
Please add the following two properties to "Create Contact" for "Hubspot" piece:
1) A multiselect dropdown to choose which extra properties the user would like to enter for their contacts.
2) A dynamic property that depends on the multiselect dropdown to show selected properties.

here is a document that might help in the API https://developers.hubspot.com/docs/api/crm/properties

![Image](https://user-images.githubusercontent.com/106555838/264580341-07c96d88-2022-4220-8645-86a8c79d84e6.png)

**Comment by abuaboud** [comment]
I think the best way to go with to use Dynamic Properties and list all of them as Optional Properties.
