### ISSUE TITLE
[Question] Clarification on what features are & are not supported vs cloud

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#2409]
Doesn't seem to be documented anywhere that I can see. 
For people setting up the solution for the first time, it would be great  to know in advance what is and isn't included. 
E.g. it would have been nice to know that there is no settings page, that there's only one account etc.

**Comment by abuaboud** [comment]
Done, please take look here 

https://www.activepieces.com/docs/install/editions
