### ISSUE TITLE
Enable piece debug in VSCode

### ISSUE THREAD

**Issue by hkboujrida** [activepieces/activepieces#2428]
**Is your feature request related to a problem? Please describe.**
As of now, it's impossible to debug pieces in the IDE and that makes the development process a bit hard.
@abuaboud explained to me that every piece runs on a separate node process.
With this VITAL information, i went into the rabbit hole and after some digging, i found a way.

**Describe the solution you'd like**
So the principal suspect is sandbox.ts, this code spawn a separate process for every piece so a generated a random port number and if the environment is set to dev will launch the piece process in debug mode
![image](https://github.com/activepieces/activepieces/assets/14313648/90b4463c-b16a-448b-bdc6-d1b97832f960)

the you grab the random port number associated with the piece node process, and attach to it
![image](https://github.com/activepieces/activepieces/assets/14313648/6b5b5c01-543e-4e0a-a792-8106ef6ea03e)

and voila, you are able to hit you breakpoint
![image](https://github.com/activepieces/activepieces/assets/14313648/21fa6358-efdc-4706-aa08-5c2325fbf5ad)

Hope you'll like it
the changes are in the my fork : https://github.com/hkboujrida/activepieces/tree/feat/enable-ide-piece-debugging
i can pull request if you like

**Comment by abuaboud** [comment]
We should merge this PR, let me get look and get back to you!

**Comment by hkboujrida** [comment]
So, i pulled the latest code from main, and found that the code has been refactored,
and i found out that some piece process terminated before i was able to attach to it,
so i added a new environment variable to set debug types, now the piece process will wait at start until a debugger is attached

https://github.com/hkboujrida/activepieces/tree/feat/enable-piece-debug
export PIECE_DEBUG_MODE=at_start 
to enable piece debug and wait for a debugger to attach

**Comment by abuaboud** [comment]
Hii @hkboujrida Can you please Open PR?

I totally missed getting back to this issue.

**Comment by abuaboud** [comment]
It should be working on the most recent version
