### ISSUE TITLE
[Documentation] Add example AWS deploy config 

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#2429]
The docker compose steps are great but it would be really helpful to add some instruction on deploying the solution into AWS. Potentially using IaC like CloudFormation, Terraform, Pulumi etc. 

E.g. creating an ECS cluster and task, redis and postgreSQL, along with the other standard prerequisites like VPC, subnet etc. 

Basically whatever's needed just to get up and running as quickly as possible to take the solution for a proper, real-world test drive without needing to rely on tools like ngrok.

**Comment by abuaboud** [comment]
@GFoley83 This is would be amazing.

Did you deploy activepieces successfully on AWS? Do you mind contributing to the docs?

**Comment by GFoley83** [comment]
I didn't actually @abuaboud. I just resorted to testing locally with docker as provisioning infra definitely isn't my strong suit.

**Comment by GFoley83** [comment]
Hey @abuaboud. I actually took a stab at this the weekend using Pulumi typescript for IaC and have gotten it deploying pretty cleanly into AWS using the activepieces image, direct from Docker Hub. Solution uses ECS Fargate, and optionally Elasticache Redis + PotsgreSQL, for a more production-ready setup. 

I'm happy to share/write up what I've done if you'd like, just let me know how you'd like me to do it if so.

**Comment by abuaboud** [comment]
That would be amazing. You can open a pull request; there is a 'docs' folder where we can add it. 

The syntax is Markdown. I can take it from here, but if you want to test it end-to-end, you need to install 'mintlify' from https://www.npmjs.com/package/mintlify. After that, navigate to the 'docs' directory and run 'mintlify dev'.

**Comment by GFoley83** [comment]
Hey @abuaboud. I've take a stab at some documentation and added some code to the solution to support deploying to AWS for the following three scenarios w/ Pulumi:

- 1-click deploy in the browser using Pulumi Cloud w/ the Activepieces Docker Hub image (no need to git clone the solution)
- Deploying from a local env using the Activepieces Docker Hub image (no need to git clone the solution)
- Deploying a locally built  Docker image of Activepieces to AWS (git clone required)

The solution supports deploying Activepieces into AWS as a standalone container using SQLite3 and in-memory, or optionally with a PostgreSQL RDS Db, a Redis Cluster and a fully qualified domain name w/ SSL. See the docs for more. I also wrote and tested the docs using mintlify as you suggested. 

You can have a look at what I've done on my fork here:
https://github.com/GFoley83/activepieces/tree/feature/aws-pulumi-deploy
https://github.com/activepieces/activepieces/compare/main...GFoley83:activepieces:feature/aws-pulumi-deploy?expand=1

Note the docs contain a reference to my forked repo. This is just to test and make sure everything is working e.g. for 1-click deploy. Once I open a PR I'll update these reference to point to the Activepieces repo. 

Let me know if you'd like me to tweak anything. Cheers.

**Comment by GFoley83** [comment]
Closing as resolved by #2580. Cheers.
