### ISSUE TITLE
[BUG]: Flow has been in "running" status for 2 days

### ISSUE THREAD

**Issue by Vitalini** [activepieces/activepieces#2430]
**Describe the bug**
Flow has been in "running" status for 2 days. How to reboot it?

**To Reproduce**
I don't have them, I accidentally found it

**Screenshots**
![2023-08-31-21-57-27](https://github.com/activepieces/activepieces/assets/1262526/be3b95fe-ad97-4d46-a4e3-68f81983198e)

**Comment by abuaboud** [comment]
Hi @Vitalini 

How did you install activepieces? is this a the single docker image or docker compose? Do you know if the instance were turned off during the execution?

**Comment by Vitalini** [comment]
Hey @abuaboud, I've used Docker Compose. 
The instance did not shut down but was heavily loaded, and as a result, I believe, one of the flows fell off.
Is it possible to somehow reload or resume it?

**Comment by abuaboud** [comment]
Hi @Vitalini , can you confirm the AP_QUEUE environment variable is based on Redis?

**Comment by Vitalini** [comment]
Hey @abuaboud I don't have `AP_QUEUE` in .env file, but I have 
```
AP_REDIS_HOST=redis
AP_REDIS_PORT=6379
```

**Comment by Vitalini** [comment]
Hi @abuaboud, any updates? How to relaunch/cancel the flows? Thanks!

**Comment by Vitalini** [comment]
up

**Comment by abuaboud** [comment]
@Vitalini Sorry I need to setup better notifications for github, feel free to ping me at discord if you didn't get reply here.

This is odd because if you are using Redis as queue method, they should at least marked internal error if they fail to execute, currently there is no way to rerun these flows (unless they are internal error) which is not the case for you.

What is the version of activepieces do you use?

**Comment by Vitalini** [comment]
Hey @abuaboud I'm using 0.8.0 version, It is still in running status 
![2023-09-19-11-45-04](https://github.com/activepieces/activepieces/assets/1262526/123e3396-4046-41e6-8571-553b0e4af933)
Is it possible to kill the flow via the console?

**Comment by abuaboud** [comment]
HI @Vitalini Sorry just saw this, does this flow contains code piece and do you still have this issue in 0.11.0?

**Comment by Vitalini** [comment]
@abuaboud I cloned the flow and removed the old one. It resolves the issue. Thanks!
