### ISSUE TITLE
Test Account for all the pieces

### ISSUE THREAD

**Issue by bibhuty-did-this** [activepieces/activepieces#2437]
**Is your feature request related to a problem? Please describe.**
Whenever a developer wants to develop a piece or solve a bug on a piece they have to rely on their own test accounts, which is always not a feasible option. 

**Describe the solution you'd like**
I would like Activepieces to own all kinds of developer accounts in all the pieces they are currently supporting or the pieces they intend to develop. Use tools like LastPass/Bitwarden to share it with the developer working on the relevant problem statement.

**Additional context**
AirbyteHQ does that.

**Comment by abuaboud** [comment]
Good point, I will close this issue as there is no direct action item other than keeping list interanlly of credentials
