### ISSUE TITLE
API for triggering self hosted workflows

### ISSUE THREAD

**Issue by mrmianbao** [activepieces/activepieces#2479]
**Describe the solution you'd like**
To build workflows for my app that I can call via API.

**Describe alternatives you've considered**
Building it myself

**Comment by abuaboud** [comment]
@mrmianbao You can specify the trigger to be webhook, which you will be able to call via HTTP, since it will give you a unique endpoint.

Marking this as complete, please reopen if this doesn't solve your issue.
