### ISSUE TITLE
[BUG]: Code piece fails to load in "Send ChatGPT welcome email to MailChimp new subscribers" template

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#2483]
**Describe the bug**
The code step in the "Send ChatGPT welcome email to MailChimp new subscribers" template hangs forever. Tested in cloud and locally with hosted docker image.

**To Reproduce**
1. Add a new flow with the "Send ChatGPT welcome email to MailChimp new subscribers".
2. Click on "Code" flow.
3. Scroll down to the code editor. It stays spinning forever. Regardless of enabling the previous step and loading sample data.

**Expected behavior**
You should be able to see the contents of the code editor.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/838788/02ef7830-02b5-4d51-9427-1c8ad38fc9ea)

**Additional context**
Ad block is disabled. Test in Chrome v116.0.5845.141 (Official Build) (64-bit)

**Workaround**
Replace the blocken code piece with a new one, and add the following:
```js
export const code = async (inputs) => {
    return JSON.parse(inputs.chatgpt);
};
```

**Comment by abuaboud** [comment]
Thank you, Should be fixed now.
