### ISSUE TITLE
Autocomplete for passed data from previous steps and from configs

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#252]
Data from previous steps and from configs should be capable of being used in any step by clicks on the UI instead of writing syntax.

**Comment by abuaboud** [comment]
I am signing off this feature as first version, this should be addressed in next releases:

1. The mention tag should contain the icon.
2. Sample data must be stored in the backend, (code piece, webhooks)
3. Allow to customize the variable, auto complete is forcing the choices rather allow me to input json path.
