### ISSUE TITLE
[BUG]: All dropdowns for a given action/trigger execute simultaneously once the action/trigger is chosen

### ISSUE THREAD

**Issue by khaledmashaly** [activepieces/activepieces#2552]
**Describe the bug**
All dropdowns for a given action execute simultaneously once the action is chosen

**To Reproduce**
1. Choose the google sheets trigger
2. Choose `new row` trigger
3. Notice that `spreadsheet_id` and `sheet_id` dropdowns execute simultaneously once the trigger is choosen

**Expected behavior**
Dropdowns should only execute when all dependencies are available, i.e. if a dropdown depends on the connection, it should wait for the connection to execute and so on.

**Comment by abuaboud** [comment]
It requires to fetch the message and this should be no longer an issue after sandbox optimizations
