### ISSUE TITLE
IMAP Sample Data bug

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#2560]
Using the existing IMAP piece, I can successfully connect to a non-google IMAP account, but when I click "Load Data," it says "No results found" and "Testing data failed. Please ensure that the settings are correct or try again." I have sent myself test emails within the hour. I have tried to use no filters as well as the exact "from" and "subject" filters as my test emails, but nothing works. My IMAP email provider is titan email, which actually uses google mail as their backend. The IMAP account connects successfully, but it doesn't work after that.

**Comment by tanoggy** [comment]
hi @abuaboud, I can progress this issue
