### ISSUE TITLE
[BUG]: the docker keeps restarting

### ISSUE THREAD

**Issue by itzmestar** [activepieces/activepieces#2627]
i am using `docker compose -p activepieces up -d` command to create the docker images on ubuntu 22.04.3 LTS. But activepieces  container keeps restarting.

<img width="558" alt="image" src="https://github.com/activepieces/activepieces/assets/23387154/c52e687b-b0f1-4ac1-be65-bfaf958548ca">

logs shows this:
{"level":50,"time":1694550006286,"pid":8,"hostname":"770d28ad0010","err":{"type":"DatabaseError","message":"password authentication failed for user \"postgres\"","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/dist/packages/backend/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/usr/src/app/dist/packages/backend/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/usr/src/app/dist/packages/backend/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/usr/src/app/dist/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":104,"name":"error","severity":"FATAL","code":"28P01","file":"auth.c","line":"335","routine":"auth_failed"},"msg":"password authentication failed for user \"postgres\""}

**Comment by itzmestar** [comment]
@javix64 if I remember correctly I think issue happened because I created docker then removed it and created again. It worked fine first time but started to give this issue on subsequent docker create.

Solution: I used this command `sh tools/reset.sh
` to delete the docker images and started the docker again and it worked.

**Comment by javix64** [comment]
@itzmestar many thanks for sharing, I will try it!
