### ISSUE TITLE
Shopify Piece

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#267]
- Triggers:
    - New Paid Order.
    - New Customer.

Action:
    - Create Customer

**Comment by sabuto** [comment]
Out of interest why is the shopify piece blocked? I wouldn't mind trying to make this?

**Comment by abuaboud** [comment]
@ashrafsamhouri Please split them into triggers and actions.

Only the triggers is blocked because they are app webhooks, which means we need a routing logic to know which users to route the events to.
