### ISSUE TITLE
Tidycall Auth Validation

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#2727]
We need to add authentication validation to prevent misleading the user

https://community.activepieces.com/t/tidycal-to-a-gmail-auto-response-email/253

**Comment by Salem-Alaa** [comment]
I need an active api key to test the correct case


![Image](https://github.com/activepieces/activepieces/assets/71246000/d80e1b88-4e80-4243-b5ee-95898fb6e3c2)
