### ISSUE TITLE
Digital Ocean Droplet

### ISSUE THREAD

**Issue by Kynson** [activepieces/activepieces#2860]
It would we good if we have an action that is able to manage (create/ update/ destroy) droplets hosted on Digital Ocean.

**Describe your usecase.**
- Destroy a Droplet automatically after a certain period of time (with the delay action)

**Describe alternatives you've considered**
The HTTP Request action can be used. Yet, the API call is quite complex as the request body JSON contains quite a number of fields. https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_create

Thank you!

**Comment by abuaboud** [comment]
That's super interesting, what is the end to end use case I am curious!

**Comment by Kynson** [comment]
My personal use case would be allow me to host something, for instance, a demo web app & its backend, temporary on Digital Ocean and have it destroy itself automatically after a period of time. This control the cost effectively, just in case I forgot to do it.

Another similar use case I can think of is to use it a "droplet schedule" automation, which creates and destroys (stop) droplets based on a schedule, like what GCP offers: https://cloud.google.com/compute/docs/instances/schedule-instance-start-stop.

**Comment by abuaboud** [comment]
Thank you for opening the issue, Could you please post it here: https://community.activepieces.com/c/feature-requests/9? 

For pieces, we prioritize our internal resources based on the number of votes and then add it to our roadmap. If there is a developer reading this, you can skip the roadmap as welcome contributions and love them. ❤️

You can check out our guide at https://www.activepieces.com/docs/developers/overview.
