### ISSUE TITLE
[BUG]: Community: No options available for Slack trigger (Docker)

### ISSUE THREAD

**Issue by greyvugrin** [activepieces/activepieces#2862]
**Describe the bug**

**To Reproduce**
1. Start with  `docker run -d -p 8080:80 -v ~/.activepieces:/root/.activepieces -e AP_QUEUE_MODE=MEMORY -e AP_DB_TYPE=SQLITE3 -e AP_FRONTEND_URL="http://localhost:8080" activepieces/activepieces:latest`
2. Sign up or sign in
3. Create a new flow
4. Select Slack as trigger. No options are available in dropdown

**Expected behavior**
Expected to be able to select new message etc as an option.

**Screenshots**
![Screen Shot 2023-09-30 at 1 41 55 PM](https://github.com/activepieces/activepieces/assets/3294460/ef9c0445-0afb-449f-887b-6295415f1fcc)

**Additional context**
Thought this had to do with not having the AP_FRONTEND_URL set so I re-ran it with ngrok up and updated the env var. Same result

**Comment by abuaboud** [comment]
Please check https://github.com/activepieces/activepieces/issues/2759

Closing and will keep track here https://github.com/activepieces/activepieces/issues/765
