### ISSUE TITLE
Loki Logger

### ISSUE THREAD

**Issue by devwithadi** [activepieces/activepieces#2877]
**Describe the bug**
I have installed the winston library insted of pino we are using for logging i have replaced it in helper/logger.ts 
after that when i build the docker image and run it in a container it throws me a error module not found
I have declared it in both package.json and lock file whats the issue how i can ???
here you can see the error
![Screenshot from 2023-10-02 15-51-57](https://github.com/activepieces/activepieces/assets/67161169/bef185a0-a032-498b-b735-9cdc74bcfd5a)

as in documentation it says add 3rd part library in package.json is it only for pices ??
am in need to do anything else to add in backend part??
@abuaboud

**Comment by abuaboud** [comment]
Hi,

I am not sure yet where this comes from.

What is the goal behind replacing Pino with Watson, there might be a better workaround.

**Comment by devwithadi** [comment]
@abuaboud The goal is to send logs to grafana so i will be adding a transporter where anyone can put their host and then all logs will be sent to grafna for analysis

**Comment by abuaboud** [comment]
@devwithadi are you using Loki for the logs?

**Comment by devwithadi** [comment]
not yet look forward to it is their any other way ? @abuaboud

**Comment by abuaboud** [comment]
@devwithadi We do use Grafana for logs as well with Pino, We send logs to Grafana Loki.

I can help you with that if it's the same case

**Comment by devwithadi** [comment]
Yes I will be very greatfull you can guide me .

**Comment by devwithadi** [comment]
@abuaboud Can you please guide me with the way to achive it ?

**Comment by abuaboud** [comment]
@devwithadi I merged it here https://github.com/activepieces/activepieces/pull/2878/files

Can you test it and contribute back to our documentation about the environment variables?

**Comment by devwithadi** [comment]
Sure @abuaboud !!

**Comment by devwithadi** [comment]
![Screenshot from 2023-10-02 17-09-47](https://github.com/activepieces/activepieces/assets/67161169/e5fd42a0-6325-4089-ad4d-b53e3bb0512f)
@abuaboud facing this issue any clue?

**Comment by devwithadi** [comment]
@abuaboud Ok I have figure out the way to deal this and now related to pushing logs things are working fine  will be pushing the changes in a while once i will solve the issue related module not found still after including packege.json it only occurs in docker container senario.

**Comment by devwithadi** [comment]
![Screenshot from 2023-10-02 17-54-29](https://github.com/activepieces/activepieces/assets/67161169/5c36a988-f648-4530-a711-616e34944301)
@abuaboud Can you please help me with this issue too is this a issue with redirect uri or what ?

**Comment by abuaboud** [comment]
Hi @devwithadi Can you try to use unsandboxed mode?

**Comment by devwithadi** [comment]
@abuaboud But in that mode i can't use sign Ups right, i want to use that too?

**Comment by devwithadi** [comment]
@abuaboud can you please help me with that ?

**Comment by abuaboud** [comment]
@devwithadi I can take look but we are deprecating sandbox mode in following releases, as it's causing too many issues

How did you find about it? I tried to remove it from docs to avoid further dependencies with this announcement https://www.activepieces.com/docs/install/breaking-changes

Do you mind tell me what is your use case for multiple sign up?

**Comment by devwithadi** [comment]
Oh I have seen about it but in issue i have read about it in issue and for multiple sign up i want to implement aws cognito their for that i have created a adapter called cognito adapter so it will be better if i'll find the code to work upon.

**Comment by abuaboud** [comment]
@devwithadi I am curious to chat about multiple users (https://cal.com/abuaboud) to learn more how it's being used, I am closing this ticket as completed since now ap support loki.
