### ISSUE TITLE
Searching for pieces in the builder UX enhancement

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#2882]
Make it so people can search for actions as well as pieces in the search bar, and show actions that match said search as links that people can click on and instantly choose the action.

**Comment by abuaboud** [comment]
Please check that too:

https://community.activepieces.com/t/browse-pieces-from-within-app/2793/2

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer I do suggest that you make basic simple piece search works first https://github.com/activepieces/activepieces/pull/3785

Let's make the suggestion actions / triggers come up in the following pr.
