### ISSUE TITLE
[BUG]: Existing account does not get an invite email if they are part of another project/team

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#2883]
**Describe the bug**
When a user sends an invitation email out to an existing AP account, the expectation is that they would receive the email invitation, however this is not the case.

**To Reproduce**
1. Create an AP account
2. Get an invite into another project
3. Once joined the other project, create a new team from a different account
4. Invite the OG AP account to the new project

**Expected behavior**
An email invitation to land in my email inbox

**Comment by abuaboud** [comment]
Fixed
