### ISSUE TITLE
[BUG]: the HTTP piece fails a very basic GET request

### ISSUE THREAD

**Issue by Gaket** [activepieces/activepieces#2905]
**Describe the bug**

HTTP piece sending a GET request to Fullstory api started malfunction between Sept 29 and Oct 3.

It may be the case that something changed on the external API. Still, the very basic CURL request works as expected, as well as a Postman call.

It's not clear what exactly goes wrong from the Fullstory API message.

It's a very basic GET request with a param in path. I've tried hardcoding the param - it doesn't work as well.

```
{
  "response": {
    "status": 400,
    "body": "\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>400 Bad Request</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Bad Request</h1>\n<h2>Your client has issued a malformed or illegal request.</h2>\n<h2></h2>\n</body></html>\n"
  },
  "request": {
    "body": {}
  }
}
```

**To Reproduce**

Create a GET HTTP piece calling this curl (test, non-prod data):
```
curl --location 'https://api.fullstory.com/operations/v1/U0VBUkNIX0VYUE9SVDpQa3BsZFZPTGhrUEdQRGNVbk9rNzVVNlE5dTN4Qm5ybnRIVGViTWU5TnAI' \
--header 'Authorization: Basic na1.MTc4WEZRL2FydHVyQGdldHNxdWlyZS5jb206u8+by7/jPBiPrpdyKTOTUuv+tKQzeQjf4ZeKmFCfcOgu/FG8X8SK'
```

**Expected behavior**

Response:

```
{"error":"NotFound"}
```

** Actual behavior**

```
{
  "response": {
    "status": 400,
    "body": "\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>400 Bad Request</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Bad Request</h1>\n<h2>Your client has issued a malformed or illegal request.</h2>\n<h2></h2>\n</body></html>\n"
  },
  "request": {
    "body": {}
  }
}
```

**Screenshots**

<img width="912" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/d78fd131-589d-4849-a8c9-ae2b0c42cc6f">
<img width="708" alt="Screenshot 2023-10-04 at 8 27 49 PM" src="https://github.com/activepieces/activepieces/assets/4466100/ed30ae86-da55-4ad9-bd92-edfa80c71c14">

**Additional context**

I've got a similar issue with a POST request to Fullstory API initially. Eventually, created a workaround by using the Code piece and Axios manually.

**Comment by Gaket** [comment]
Similar step that worked in a Test Run yesterday failed today:
<img width="435" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/8896223a-8450-474c-9466-8fb385210454">

**Comment by abuaboud** [comment]
HTTP 0.3.9 is published, It should be automatically upgraded and fixed.

Thank you for reporting the bug.

**Comment by Gaket** [comment]
Thank you for the prompt fix!
