### ISSUE TITLE
Box.com file/folder creation

### ISSUE THREAD

**Issue by atsepkov** [activepieces/activepieces#2928]
**Describe your usecase.**
I want to be able to move/upload files to my Box account programmatically.

**Describe alternatives you've considered**
Google Drive piece already has the capability to upload files, but my storage on Google Drive is significantly less than on Box. Moreover, there is already a box.com integration for triggers. Would it be possible to extend box.com piece to include additional capability that Google Drive piece already has?

**Comment by abuaboud** [comment]
Thank you for opening the issue, Could you please post it here: https://community.activepieces.com/c/feature-requests/9

For pieces, we prioritize our internal resources based on the number of votes and then add it to our roadmap. If there is a developer reading this, you can skip the roadmap as welcome contributions and love them. ❤️

You can check out our guide at https://www.activepieces.com/docs/developers/overview.
