### ISSUE TITLE
Question: Upload "My pieces" from the UI

### ISSUE THREAD

**Issue by glani** [activepieces/activepieces#2937]
Any thoughts on having this functionality?

Installing from npm private pieces is inconvenient (too many unnecessary steps).

Would be great to have the upload functionality of the tar file.

I made a small P&C without uploading a piece that could be installed from a dedicated directory.

**Comment by abuaboud** [comment]
Hi @glani 

Sorry for late response, I don't understand how it's causing extra steps the difference I see running `npm pack` instead of `npm publish`.

If you can also please give me some context about the use case It would help me understand better.

**Comment by abuaboud** [comment]
Hey @glani I am closing this issue, please reopen when you see this comment 

Thank you very much!
