### ISSUE TITLE
pulumi aws deploy example

### ISSUE THREAD

**Issue by sheldondz** [activepieces/activepieces#2956]
#2429 

We are trying to deploy the infra using the pulumi scripts, and have this recurring issue.

We are building custom docker images using the ap-base and Dockerfile, after pulumi up the ECS container tasks keep terminating and the application never reaches a stable state. Rechecked the environment variables and they seem to be fine.

Are we missing anything here? we are deploying to fargate using arm images.

```
AP_POSTGRES_PORT=5432
AP_ENVIRONMENT=prod
AP_FRONTEND_URL=https://some url
AP_ENCRYPTION_KEY=generated automatically
AP_SIGN_UP_ENABLED=true
AP_TELEMETRY_ENABLED=true
AP_TRIGGER_DEFAULT_POLL_INTERVAL=5
AP_DB_TYPE=POSTGRES
AP_POSTGRES_USE_SSL=false
AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js
AP_POSTGRES_HOST=instance DNS
AP_POSTGRES_USERNAME=activepieces
AP_POSTGRES_DATABASE=postgres
AP_POSTGRES_PASSWORD=auto generated
AP_SANDBOX_RUN_TIME_SECONDS=600
AP_TEMPLATES_SOURCE_URL=https://cloud.activepieces.com/api/v1/flow-templates
AP_EXECUTION_MODE=SANDBOXED
AP_JWT_SECRET=auto generated
AP_QUEUE_MODE=MEMORY
AP_REDIS_USE_SSL=false
```

This is the pulumi config

```
encryptionsalt: v1:6hdVGcbS6mo=:v1:AJuYvXokWiymkKLD:GrFeD+OrWHZsS1j6tUTRg+ckN+n7/Q==
config:
  activepieces-platform:addIpToPostgresSecurityGroup: custom ip address
  activepieces-platform:apEncryptionKey:
    secure: v1:5Q1QON4f+CcBQV2a:6+L8HXHUlDzdST7CZXLixAWutjrqEN+iy2q0gm0dnUo4B+JyrXbOos6BOTLRRl7X
  activepieces-platform:apJwtSecret:
    secure: v1:g9pmHUzlVAKFwVtA:m7KIIdwkJzgUzbCP4JkyADaEjWImMvbTipvkbmHF1rKCBMCAmnX3AhZTxeAKP3rz
  activepieces-platform:containerCpu: "512"
  activepieces-platform:containerInstances: "1"
  activepieces-platform:containerMemory: "1024"
  activepieces-platform:dbInstanceClass: db.t4g.micro
  activepieces-platform:dbIsPublic: "false"
  activepieces-platform:dbPassword:
    secure: v1:J+1W0uqfUl+fnRBu:VntnvFiLDjEGp5TbRsy6ltyGbGXmzSD2FVB9rTnqPAJgOjXQ1qQFPsJM29b0LAdX
  activepieces-platform:dbUsername: activepieces
  activepieces-platform:domain: domain
  activepieces-platform:environment: prod
  activepieces-platform:redisNodeType: cache.t3.micro
  activepieces-platform:subDomain: subdomain
  activepieces-platform:usePostgres: "true"
  activepieces-platform:useRedis: "false"
  aws:region: ap-south-1

```

**Comment by sheldondz** [comment]
just saw this issue #2955 which update and check again.

**Comment by GFoley83** [comment]
I wrote the pulumi scripts and am experiencing the same problem. The issue stems from the recent changes to the dockerfile, from what I can tell.

@abuaboud Can you please confirm the correct docker command to build and/or run the image locally please.

**Comment by abuaboud** [comment]
Hi @GFoley83 It not longer requires build argument, are you running it on latest main but to make this is issue what is the error do you get?

**Comment by GFoley83** [comment]
@abuaboud Just checked with the latest from main (commit ac20ed1 at time of writing) and can confirm that I can build locally and push a new image up via Pulumi. Looks as though you rolled back the need to pass env vars to the docker build/run, which has fixed the issue for me at least.

@sheldondz if you're still seeing an issue with the latest from main, please share the error you're getting.

**Comment by abuaboud** [comment]
@sheldondz @GFoley83 Closing this as fixed.
