### ISSUE TITLE
Trigger utils

### ISSUE THREAD

**Issue by tanansatpal** [activepieces/activepieces#2969]
**Describe the bug**

    function constructEveryXMinuteCron(minute: number) {
    const edition = getEdition()
    switch (edition) {
        case ApEdition.CLOUD:
            return `*/${minute} * * * *`
        case ApEdition.COMMUNITY:
        case ApEdition.ENTERPRISE:
            return `*/$${system.getNumber(
                SystemProp.TRIGGER_DEFAULT_POLL_INTERVAL,
            ) ?? 5} * * * *`
    }
}
in the above function in trigger-utils.ts, the last case of community or enterprise, there are double dollar signs which are preventing it to be saved to the queue.

**To Reproduce**
1. run it as community edition
2. Save a flow like google sheets and try to publish

**Expected behavior**
The flow should get published

**Screenshots**
<img width="1216" alt="Screenshot 2023-10-17 at 12 16 09 pm" src="https://github.com/activepieces/activepieces/assets/20103208/9c740abf-1445-4e7a-b8f9-0f8cdbc4e822">

**Comment by abuaboud** [comment]
Fixed and released 0.11.0 

Thank you
