### ISSUE TITLE
[BUG]: Invalid request URL with parameters

### ISSUE THREAD

**Issue by andchir** [activepieces/activepieces#2993]
**Describe the bug**
If I use a **httpClient** from **@activepieces/pieces-common** with **queryParams**, I'm getting an incorrect final request URL.
Related to #186

**To Reproduce**
I'm creating a piece with code like this:
```js
const API_URL = 'https://example.com/api/items';
const queryParams: Record<string, string> = {
    api_key: params.apiKey
};
const request: HttpRequest = {
    method: HttpMethod.GET,
    url,
    queryParams
};
const response = await httpClient.sendRequest<ChatDataItem[]>(request);
```
When testing the trigger, I see that the request is sent to: **https://example.com/api/itemsapi_key=123456**.
That is, there is no separator "?".

**Expected behavior**
The final request URL should be: **https://example.com/api/items?api_key=123456**.

**Additional context**
This can be fixed like this:

_/packages/pieces/common/src/lib/http/core/base-http-client.ts_
Remove lines 28 -32:
```js
// if (request.queryParams) {
//    for (const [name, value] of Object.entries(request.queryParams)) {
//      url.searchParams.append(name, value);
//    }
// }
```

_/packages/pieces/common/src/lib/http/axios/axios-http-client.ts_
Add line after 32:
```js
params: request.queryParams,
```

**Comment by abuaboud** [comment]
Hi @andchir 


Thank you for opening the issue, do you mind opening PR, i can merge it 😁

**Comment by andchir** [comment]
https://github.com/activepieces/activepieces/pull/2996
