### ISSUE TITLE
Revert to Published Version

### ISSUE THREAD

**Issue by MattCarneiro** [activepieces/activepieces#3004]
If you edit a workflow, even if you don't publish the changes it will change everything automatically. You can't go back. Even if you choose the published version you can't cancel the changes. Even if you donwload the JSON and upload again, it will upload the draft version, not the published one.

**Comment by abuaboud** [comment]
Hi @MattCarneiro 

Thank you for opening the issue, I am not sure If i understand the bug here correctly and what is the expected behavior. 

The flow auto save changes, but they are never published until you press publish why do you think they are auto published? what are steps to reproduce the issue.

**Comment by MattCarneiro** [comment]
Example... Create a flow with some pieces and publish. Now delete any piece of the flow. Try to revert back to the first state. You can't. Even if you don't publish the flow, you can't go back. When you open the flow, it is on the draft. Even If you don't save the flow you can't continue editing from the published state.

**Comment by abuaboud** [comment]
Hi @MattCarneiro 

I think I understand that you want to discard all changes and get back to published, I will mark this feature request.

Totally make sense

**Comment by lan5nl** [comment]
Hi @abuaboud,

For some reason (twice now) my workflow got deleted (all nodes). In the published flow I can see all my nodes with their settings but there is no fast way to restore.

Not sure how to reproduce my issue. This is what I remembered:

- I build my flow (for example: 10 nodes)
- Publish
- Did an edit to a node and got a connection issue saying something about "refresh"
- Refreshed the page (as nothing responded)
- All nodes are gone (node showing Select Trigger) in Draft

Maybe the revert option mentioned above or version history would be very nice to restore a workflow.

**Comment by abuaboud** [comment]
@lan5nl What is the activepieces version? This issue is supposed to be fixed 😳.

Regarding restoring, it is currently possible via API as workaround.

First export the flow, and then look through the network tab for the /api/v1/flows with versionId as the query parameter.

Copy the response and paste it into the template property in the exported JSON.


You can import the flow again.






We will work on a version history soon.

**Comment by lan5nl** [comment]
@abuaboud Thanks! I was able to easily restore the flow with the response. I downloaded the latest version through "git clone https://github.com/activepieces/activepieces.git". In the compose file is says "activepieces/activepieces:0.12.2". In the repo 0.12.0 is the latest. Is there some other info you need?

**Comment by abuaboud** [comment]
Yes `0.12.2` is latest, that's weird :( If you were able to reproduce it please let me know.

I am trying to do that as well.

**Comment by JanHolger** [comment]
> Hi @abuaboud,
> 
> For some reason (twice now) my workflow got deleted (all nodes). In the published flow I can see all my nodes with their settings but there is no fast way to restore.
> 
> Not sure how to reproduce my issue. This is what I remembered:
> 
> * I build my flow (for example: 10 nodes)
> * Publish
> * Did an edit to a node and got a connection issue saying something about "refresh"
> * Refreshed the page (as nothing responded)
> * All nodes are gone (node showing Select Trigger) in Draft
> 
> Maybe the revert option mentioned above or version history would be very nice to restore a workflow.

@abuaboud I just ran into the same issue while showing AP to a colleague. At some point I got a notification that there is a connection issue and I should reload the page so I did. After that all steps incl. the trigger were gone in the draft version but the published version was just fine. Even though this feature request would kind of help in case this bug happens, we should probably track the bug itself in a separate issue. Do you know about any similar issue or should we open a new one for this?

**Comment by abuaboud** [comment]
@JanHolger Just to confiirm that was in  0.13.0 correct? You are right we should track into another issue.

**Comment by abuaboud** [comment]
Version History is Done and Released in 0.16.0

![image](https://github.com/activepieces/activepieces/assets/1812998/9ab099ab-4846-4b24-a95a-508832d6454d)
