### ISSUE TITLE
Run a flow when another flow runs

### ISSUE THREAD

**Issue by CarefulGuru** [activepieces/activepieces#3006]
**Is your feature request related to a problem? Please describe.**
No problem. Just something that would be nice to have

**Describe the solution you'd like**
When one flow runs, the ability to trigger another flow, and pass the data from the first flow to that flow would be nice. The ERP we use has a very clunky system for setting up triggers, so if I could have one flow that I could send data to, and then split off into a bunch of separate flows, with that data, and send it to it's various locations without having to create hundreds of triggers in our ERP to achieve the exact same thing, it would save a ton of time!

**Describe alternatives you've considered**
Creating 100+ triggers in our ERP, to send data to 15 different flows.

**Comment by abuaboud** [comment]
Hi @CarefulGuru 

I think its possible via Webhooks trigger, You can make ERP to triggers one flow.

This flow will trigger rest of flows using HTTP piece.

What do you think of this workaround?

**Comment by CarefulGuru** [comment]
I hadn't thought of that, but that is a perfect workaround. Thank-you @abuaboud!
