### ISSUE TITLE
Get flow count data to integrate into my flow to send data to slack channel

### ISSUE THREAD

**Issue by RilusMahmud** [activepieces/activepieces#3012]
I want to check my total flow count, but I have to log in to the dashboard to check if my limit is exceeded or not. If there is any API or any services inside the flow to integrate with Slack I can make a flow step to send count to my Slack channel.

I want a step to get the flow count so that I can send the data to my Slack channel with the next step of my flow.

**Comment by abuaboud** [comment]
Hi @RilusMahmud,

Thank you for opening the issue. That's interesting. Just to make sure I understand correctly, you mean the number of flows, not their runs or tasks, is that correct?

There is an API endpoint that returns the count of flows inside the account, but how do you exceed the flows? Do you create them programmatically?

If you can give me more context about the end to end usecase I can suggest some workaround / define the requirements better 

Kind regards,
Mo.

**Comment by RilusMahmud** [comment]
Hey @abuaboud,

Yeah kinda like that, there's a view in the dashboard on the top right corner that says, 100/100 tasks per month. I want to access that count and send that data every 6 hours to my Slack.

So, you're saying that there is an API endpoint, can you share or just tell me where to find that API, I couldn't find that.

Thanks in advance.

**Comment by abuaboud** [comment]
Hi @RilusMahmud, Got it. Currently, the API is not documented because there is no way to generate API tokens other than through reverse engineering the JWT token from the frontend that expires every 7 days.

I would love to hear the use case that would help me understand the overall issues. Are your tasks consumed in an unpredictable way? what is the use case are you trying to achive?

**Comment by abuaboud** [comment]
Hello,

We presently support these use cases through the Platform Edition (Commercial Edition). Please check the API at https://www.activepieces.com/docs/endpoints/projects/list.

I believe you can still find a workaround, as I mentioned earlier, by utilizing project JWT and aggregating tasks from the runs table in the list flow runs.

I am closing this issue, but please feel free to reopen it if needed.
