### ISSUE TITLE
[BUG]: The Whole Code fails when i connects an account 

### ISSUE THREAD

**Issue by devwithadi** [activepieces/activepieces#3028]
**Describe the bug**
I have setup the project using tools/set-up.js and used npm run frontent and npm run backend and everything is working fine till i connect my account  using add connection in any pices both side code fails and alot of tons of errors are there and multiple times i tried to install packegs and dependency using multiple ways still facing same stuff
as you can see in screenshot 

I am using version node v18.13.0 and npm 9.2 

**Expected behavior**
it shall connect to account 

**Screenshots**
![Screenshot from 2023-10-25 00-37-03](https://github.com/activepieces/activepieces/assets/67161169/48961021-744a-4ace-8c33-861c74a92086)

![Screenshot from 2023-10-25 00-36-09](https://github.com/activepieces/activepieces/assets/67161169/3b866184-025f-4594-9e3c-08a0e303ca3a)
![Screenshot from 2023-10-25 00-36-54](https://github.com/activepieces/activepieces/assets/67161169/1c53f67c-a121-4bb2-abed-3265a98766ea)

![Screenshot from 2023-10-25 00-36-33](https://github.com/activepieces/activepieces/assets/67161169/4b5c27ba-63d9-429e-8927-f967de39b328)

**Comment by abuaboud** [comment]
Hi @devwithadi 

I assume this is development environment, can you please share your `packages/backend/.env`

**Comment by devwithadi** [comment]
AP_DB_TYPE=SQLITE3
AP_DEV_PIECES="google-sheets,store"
AP_ENVIRONMENT="prod"
AP_FRONTEND_URL="http://localhost:4200"
AP_LOG_LEVEL=debug
AP_LOG_PRETTY=true
AP_QUEUE_MODE=MEMORY
AP_TELEMETRY_ENABLED=true
AP_TRIGGER_DEFAULT_POLL_INTERVAL=1
AP_WEBHOOK_URL="http://localhost:3000"
AP_CACHE_PATH="/tmp"


Thank you  for assisting and can you please also tell me there are two env one in root and one in backend/env so let assume i want to use postgras and reddiss so should i define it in root env or in backend/env is root env is going to overwrite it.
And redirect url is not setting up as you can see i am setting frontend url to localhost or to ngrok but still redirect url is activepices.com it is not changing at time of auth where to define it @abuaboud

**Comment by abuaboud** [comment]
If you are using activepieces for development mode, you should always use packages/backend/.env.

You can define it inside this environment; the one in the root is only used for production. Can you please try deleting the .env in the root, deleting node_modules, and running npm ci again then give a try.

I think this should fix your issue. It seems AP_CACHE_PATH is set to something that is causing all these issues.

I am also curious about the value of AP_CACHE_PATH in your root .env.

**Comment by devwithadi** [comment]
@abuaboud Thank you so much for help so i have a question why we are using different path for env for prod and dev. can you please help me regarding redirect url i have set it using frontend url but still at time of auth it is using something else the default one activepices.com

**Comment by abuaboud** [comment]
@devwithadi Are you using "Use my own credentials"  what the url do you see there?

**Comment by devwithadi** [comment]
Thank you @abuaboud I got it and really thank for help i really appricate your quick response and help.
