### ISSUE TITLE
Verification link in email not working!

### ISSUE THREAD

**Issue by karayakar** [activepieces/activepieces#3033]
Verification link in email not working!

![image](https://github.com/activepieces/activepieces/assets/2394360/9d3b1ee2-2b5b-4883-8e2c-8f5e67c62b8f)

**Comment by abuaboud** [comment]
Hi @karayakar, if you copy the link directly from the email that starts with "cloud.activepieces.com," does it work?

Are you using anything that might affect the DNS? We have updated the DNS in the previous 48 hours, so that might be the issue.

**Comment by abuaboud** [comment]
Closed the ticket, It should be solved.

Please reopen if it's not working
