### ISSUE TITLE
[BUG]: HTTP response headers not being added

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#3052]
**Describe the bug**
Title.

**To Reproduce**
Cloud or hosted (v0.12.0)
1. Create a new flow with webhook and http response pieces
2. Add a header e.g. `test` with value `helloworld`
3. Publish and call the webhook url with `/sync`.
4. View response in Chrome Dev Tools, Postman etc.

**Expected behavior**
Headers added to flow should be present. 

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/838788/f5e6eabc-d45e-442b-b5bf-7e74cc788656)![image](https://github.com/activepieces/activepieces/assets/838788/9a66aa96-4d3b-44df-878b-2d3f49476974)

### Additional context

I was initially trying to see if you could set a custom `Content-Type` header so that I could return some basic HTML after running some pieces in a flow; In my case an email unsubscribe flow. 

This looks like it could work if the `Content-Type` could be set, which was when I realised that no headers were being returned at all. 
I think adding the ability to return something other than JSON as a first class capability of the response piece would be pretty powerful and something that Zapier currently lacks that has been highly requested. I can open a separate feature request for that if you like.

![image](https://github.com/activepieces/activepieces/assets/838788/39e9ad04-49f2-4973-a987-1835b7506167)

**Comment by abuaboud** [comment]
Hi @GFoley83 Thank you for reporting the issue, I attached the fix and will be released with the next release

**Comment by GFoley83** [comment]
@abuaboud I've tried the change that you have open in the PR (as this is holding up some other work for my team) but I'm still not seeing the headers coming through. 

The only difference now is that the response shows `Access-Control-Expose-Headers:  *`, which is still potentially helpful for other reasons:


![image](https://github.com/activepieces/activepieces/assets/838788/030d26fc-f9ce-4d5c-b3fc-2d759bfac5c5)

**Comment by abuaboud** [comment]
@GFoley83 I remember it's working locally seems like I forgot to push the other change

Can you try move headers before send and give it a try, please let me know if it works

https://github.com/activepieces/activepieces/blob/main/packages/backend/src/app/webhooks/webhook-controller.ts#L157

**Comment by abuaboud** [comment]
The PR is now tested and merged.

**Comment by GFoley83** [comment]
Thanks @abuaboud. Have deployed an updated docker image and changes look good.

FYI: I did to to test locally over the weekend but I couldn't get the local dev environment to work on my Windows machine. Seems there are a few steps that are not Windows compatible at the moment. 

Configuring the dev environment via Windows Subsystem for Linux (WSL) works fine however.
