### ISSUE TITLE
[BUG]: Linkedin posts cutting off by the first opening round brackets

### ISSUE THREAD

**Issue by provezano** [activepieces/activepieces#3058]
When you create a new Linkedin post, if your text has any parentheses ( ), the following step will post your text on Linkedin from the beggining of the text until the open parentheses 

![image](https://github.com/activepieces/activepieces/assets/7007069/d39b267c-8466-412f-9196-08e9bdbfe7d3)

For example:

If you want to post this:

> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type **(STOP HERE)** and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

The Linkedin step is actually posting this:

> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type

**Comment by abuaboud** [comment]
Fixed in https://github.com/activepieces/activepieces/pull/3545
