### ISSUE TITLE
[BUG]: Possibly inaccurate guidance in the development getting started documentation

### ISSUE THREAD

**Issue by miqh** [activepieces/activepieces#3065]
**Describe the bug**
The [Getting Started](https://www.activepieces.com/docs/developers/development-setup/getting-started) documentation points out that the `delay, discord, github, hackernews, slack, store` pieces are enabled by default.

I became confused after my initial attempts at poking around with the UI because I didn't see options for these at all.

If I'm not mistaken with how this all works, it turns out there are only two default pieces loaded: `google-sheets, store`.

https://github.com/activepieces/activepieces/blob/5570b9391cf6f48be776211f87e1b60e408efc4c/packages/backend/.env#L4

**To Reproduce**
Follow the aforementioned guide to start Activepieces in development and take note of the loaded pieces.

**Expected behavior**
Either I've misunderstood the documentation, or it hasn't been updated to reflect what's truly the default at the moment.

**Screenshots**
N/A.

**Additional context**
N/A.

**Comment by abuaboud** [comment]
Yes you are correct, The documentation is outdated.

Do you mind if you open a PR that updates the documentation to match the the .env file?

**Comment by abuaboud** [comment]
@allcontributors please add @miqh for docs

**Comment by abuaboud** [comment]
Thank you @miqh It's fixed now
