### ISSUE TITLE
Install error via docker compose

### ISSUE THREAD

**Issue by magicman32** [activepieces/activepieces#3066]
**Describe the bug**
running docker compose up -d
it pulls down, but on extraction file 10 of 13 fails to extract giving following error

failed to register layer: unlinkat /usr/local/lib/node_modules/npm/node_modules/@isaacs/cliui/build/lib: invalid argument

**Expected behavior**
completed install

**Additional context**
Installed via proxmox ubuntu 22.04 LTS  lxc

would love a linux install script

**Comment by abuaboud** [comment]
Hi @magicman32,

I'm not sure how to reproduce this issue, do you know how to do that?

I read one way to fix it is to build the docker image from the source on the same machine by using 'docker build .' and then try running that image. Could you please try this and let me know if it works?

**Comment by abuaboud** [comment]
Closing the issue due no way to reproduce it, feel free to reopen the issue
