### ISSUE TITLE
[BUG]: Google Refresh Token expiration after 7 days / Reconnect not working

### ISSUE THREAD

**Issue by davidgorges** [activepieces/activepieces#3067]
**Describe the bug**
Google Forms/Sheets integration stop working after 7 days, Reconnect does not work

**To Reproduce**
1. Create a Google Sheets connection using your own App ID / Credentials
2. Wait 7 Days
3. Token expires, step will fail
4) Click "Reconnect"
5) redirect URL, etc. are empty.

**Expected behavior**
a) Step succeeds
b) if refresh token expires, must be possible to renew the connection
Reconnect should work, maybe dropping the refresh_token and allowing to re-authenticate via oauth (keep redirect url, client id, client secret).

**Screenshots**
<img width="1125" alt="Screenshot 2023-10-29 at 13 11 05" src="https://github.com/activepieces/activepieces/assets/3885619/7082a34b-697d-4088-88c0-ceee74a2ee70">

**Additional context**
The Google OAuth connection fails after 7 days, when the OAuth app is in "Test" mode / unpublished. Since only Google Workspace users can create internal apps, external apps is the only supported way. Most users will not want to publish their app, therefore running it in "Test" mode. 
In Test Mode, the [Refresh token expires after 7 days](https://developers.google.com/identity/protocols/oauth2#expiration) 
<img width="864" alt="Screenshot 2023-10-29 at 12 59 47" src="https://github.com/activepieces/activepieces/assets/3885619/efda2f4f-b61c-4acc-9bdf-34bce379cd27">

**Comment by abuaboud** [comment]
I marked the issue as a bug. There's one thing I don't understand yet.

I always assume that if you used the token during these 7 days and requested a new access token token, it would return a new access token and new refresh token.

Was this token unused for 7 days, or would the refresh token will always expire in 7 days regardless?

**Comment by davidgorges** [comment]
The flow runs hourly, so it is being used. Not sure if google returns the same refresh_token over and over again.

**Comment by sapnesh-nango** [comment]
I think its expected as per [Google](https://nango.dev/blog/google-oauth-invalid-grant-token-has-been-expired-or-revoked) that test mode app tokens expire after 7 days.

**Comment by davidgorges** [comment]
Yes, the expiration part is expected. The issue is to have to re-wire everything once the connection is repaired.
