### ISSUE TITLE
Refactor Flow Helper

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#3068]
This were major source of bugs, we should rewrite it with tests.

** Details coming soon **

**Comment by algora-pbc** [comment]
💎 **$10** bounty created by @ashrafsamhouri
👉 To claim this bounty, [submit your pull request on Algora](https://console.algora.io/bounties/cloewjaip0006lc0f9eux7udz)
📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to activepieces/activepieces!

**Comment by abuaboud** [comment]
Done
