### ISSUE TITLE
[BUG]: Can't update activepieces using docker-compose

### ISSUE THREAD

**Issue by Vitalini** [activepieces/activepieces#3081]
**Describe the bug**
Can't update activepieces using docker-compose from 0.11.0 version

```
Error response from daemon: invalid mount config for type "volume": invalid mount path: '[/usr/src/cache,' mount path must be absolute
```

**To Reproduce**
1. Go to docker-compose.yml
2. Change version from 0.11.0 -> 0.12.1
3. Run `sh tools/update.sh`

**Expected behavior**
Container updated

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/1262526/f4e8bfce-7dde-4b66-a291-3e6e6c0951e7)

**Additional context**
docker-compose.yml is default.
Exactly the same as here https://github.com/activepieces/activepieces/blob/main/docker-compose.yml

pull docker-compose
![image](https://github.com/activepieces/activepieces/assets/1262526/cacb7ff6-c94a-4179-b36c-de2f1b3db1f8)

**Comment by abuaboud** [comment]
I updated the docker-compose.yml to not include single quote, seems running `docker compose down` and `docker compose up` fixed the issue.
