### ISSUE TITLE
[Question] How i can attach debbugger to backend and frontend or to other engines 

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#3084]
I wanted to attach a debugger to the programme but i am unable to as running code from npm run frontend and backend  "frontend": "nx serve ui-core",
"backend": "nx serve backend",
To address this, I would appreciate guidance on how to effectively attach a debugger and introduce breakpoints within this context. Furthermore, I am keen to gain insights into the techniques employed by your team, and I kindly request your assistance in achieving this objective, @abuaboud

**Comment by abuaboud** [comment]
I think the debugger should work default for frontend and backend, diid you face any issues there?
