### ISSUE TITLE
How to run activepieces on Windows?

### ISSUE THREAD

**Issue by devwithadi** [activepieces/activepieces#3086]
I am trying to setup the code on windows and its giving me the error for /bin/bash as by th file system how i can configure and is there any other workaround i am on windows 11. @abuaboud can you please help for same

**Comment by abuaboud** [comment]
Hi @devwithadi 

I assume you are looking for development mode right? I would recommend to use dev containers in VsCode

https://www.activepieces.com/docs/developers/development-setup/dev-container

They are very easy to setup.

Please reopen the issue if that didn't answer your question.
