### ISSUE TITLE
Open Source LLM Support for The Chatbot

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [activepieces/activepieces#3104]
Hello and thanks for this great repo.

Can we find a way to choose an open source LLM like Mistral or OpenLlama? I don't want to use OpenAI.

Best,
Orkut

**Comment by orkutmuratyilmaz** [comment]
I've also seen #1105 and it would be great to have AutoGPT support too:)

**Comment by abuaboud** [comment]
Great Suggestion, Labeled the issue

**Comment by orkutmuratyilmaz** [comment]
@abuaboud thanks for the labeling:)

**Comment by abuaboud** [comment]
Closing this, Chatbots is being deprecated
https://community.activepieces.com/t/important-update-sunsetting-chatbots/1326
