### ISSUE TITLE
Unify Tables Buttons

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#3118]
We should always use same button size across tables

![image](https://github.com/activepieces/activepieces/assets/1812998/cab92d8b-1286-40fa-b0ce-0a088c9cd2b2)

These buttons should be changed
- Platform Project Tables
- Signing Keys Table
- Chatbot Table

Note: Change Create Chatbot -> + New Chatbot

**Comment by AbdulTheActivePiecer** [comment]
Let's discuss this with Yazeed, our UI/UX designer, in the platform dashboard I think we are going to switch from tabs to side nav like normal dashboard.

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer The tales will stay there, so we have to unify the buttons.
