### ISSUE TITLE
[Question]: How Flow runs work at every interval 

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#3131]
Hello @abuaboud 
I am studying the activepices from a long while now i have some quries to learn from your code can you please help .
1) How you guys run pieces every interval can you please mention some files that i can read to learn about the architeture of code 
2) Can you suggest or mark down some of the major code  files that i can read to learn more about how pices works 
3) What are the files where we are interacting with engines and how it works i am so confuesd about it

**Comment by abuaboud** [comment]
Hi @PhoenixMystique,

Thanks for the great issue! To get started, make sure to enable the queue board using environment variables. Also, please confirm that the queue mode is set to Redis.

We're using Redis for scheduling, and the only files that interact with the engine are in engine-helper.ts.

You can check out this package for more information: https://www.npmjs.com/package/bullmq

I'd also recommend taking a look at this PR, as it makes the engine more readable with added tests: https://github.com/activepieces/activepieces/pull/3111

For further guidance, you can visit these links:
- Troubleshooting: https://www.activepieces.com/docs/install/configurations/troubleshooting
- Architecture: https://www.activepieces.com/docs/install/architecture.
