### ISSUE TITLE
Community piece by npm 

### ISSUE THREAD

**Issue by HellDevil** [activepieces/activepieces#3135]
**Describe the bug**
No piece added in list (and in workspace) after install.

**To Reproduce**
1. Go to 'My Pieces'
2. Click on 'Add Piece'
3. Compile 'Piece name' and 'Piece version'
4. Click 'Install'

**Expected behavior**
The item should appear in the 'My Pieces' list and be available as a brick in flows.

**Additional context**
The installation seems to be happening, there is a waiting time with the loader active, at the end the installation completed successfully message appears but the piece does not appear in the list, nor is the piece folder on the filesystem

**Comment by abuaboud** [comment]
Hi @HellDevil 

Can you please give me link to the piece? I tested with open ai piece, It worked for me

https://www.npmjs.com/package/@activepieces/piece-openai?activeTab=versions

**Comment by HellDevil** [comment]
Hi @abuaboud,
[https://www.npmjs.com/package/@netlabsrl/piece-wachat](https://www.npmjs.com/package/@netlabsrl/piece-wachat)
with the free cloud version it works, but with the docker version it doesn't.
I would add that before updating to 0.12.2 (the current version that gives me the problem) 1I had 0.8.0 and I didn't encounter any anomalies

Thanks
H.

**Comment by abuaboud** [comment]
Hi @HellDevil  Are you running activepieces with AP_ENVIRONMENT equal to prod?

**Comment by HellDevil** [comment]
Hi @abuaboud, no I followed the installation guide on this documentation page, there is no reference to the AP_ENVIRONMENT variable. I didn't have this variable set in the old version either.
I'll try to recreate the docker with this variable and let you know.

**Comment by HellDevil** [comment]
I tried the AP_ENVIRONMENT=prod and I get the exact same result, the piece is not loaded

**Comment by abuaboud** [comment]
@HellDevil Going to try to sqlite mode instead of postgres and will post result soon!

**Comment by HellDevil** [comment]
I'm using this docker command, I already use sqlite:

`docker run -d -p 8080:80 -v ~/.activepieces:/root/.activepieces -e AP_QUEUE_MODE=MEMORY -e AP_DB_TYPE=SQLITE3 -e AP_FRONTEND_URL="http://xxx:8080" -e AP_ENVIRONMENT="prod " --name activepieces activepieces/activepieces:latest`

The only changes I made compared to the command on the documentation are AP_FRONTEND_URL and AP_ENVIRONMENT

**Comment by abuaboud** [comment]
Hey @HellDevil,

I've identified the issue, and it seems to be related to typeorm and sqlite3. Let me dig in and figure out how we can resolve this.

The data is getting added, but there's a hiccup with the minimumSupportedRelease comparison in sqlite3.

Check out the screenshot [here](https://github.com/activepieces/activepieces/assets/1812998/b6ceb36c-466b-42f4-859f-4f34a5404d99) for more clarity.

I also recommend considering a switch to Postgres. It aligns better with our testing environment and current cloud setup. 😊

**Comment by abuaboud** [comment]
Hi @HellDevil 

Done we rewrote the pieces metadata service, It should not works for both sqlite3 and postgres

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/pull/4285
