### ISSUE TITLE
[BUG]: The piece is not refreshed until serve:backend is restarted

### ISSUE THREAD

**Issue by Elcaten** [activepieces/activepieces#3143]
**Describe the bug**
Changes to piece's code are not applied until `serve:backend` task is restarted.
 
**To Reproduce**
1. Open any piece action / trigger code file
2. Apply some changes (e.g. change prop's displayName)
3. Go to the browser and refresh the page

**Expected behavior**
I expect that once changes are compiled and "Changes are ready! Please refresh the frontend to see the new updates." message is displayed in the console, one could refresh the page and see the changes.

**Additional context**
It can be reproduced both with the container and local environment.

**Comment by abuaboud** [comment]
Hi @Elcaten just quick question is the piece added to AP_DEV_PIECES environment variable?

**Comment by Elcaten** [comment]
Hi! Thanks for the reply!
I tried it both with the new piece (I set up AP_DEV_PIECES environment) and the default piece (google-sheets).
I both cases I got the same result.

**Comment by abuaboud** [comment]
@Elcaten Can you sync your repository, do you still have the issue?

**Comment by Elcaten** [comment]
Sure!
I synced the repo and made a fresh git clone.
Unfortunately I still have the issue.

**Comment by abuaboud** [comment]
Tested on latest main branch, It should be working now.
