### ISSUE TITLE
Does activepieces cloud expose any APIs to create/manage flows?

### ISSUE THREAD

**Issue by pankaj9296** [activepieces/activepieces#3150]
If yes, any documentation around it?
if not, any plans, or does the self-hosted version expose APIs?

**Comment by abuaboud** [comment]
Hey @pankaj9296,

The API is available on all versions, and there are no restrictions on that. However, there is no documentation about it.

The reason we didn't write documentation is that it never surfaced as a priority, even though they are designed to be public. Also, in the early days, we made a lot of breaking changes, but I think the main endpoints have matured enough.

I'm curious about your use case ?. 

If you're open to contributing, I can help you to add fastify OpenAPI file generator and we can use it to display it on our documentation; We can work together on that.

**Comment by pankaj9296** [comment]
Thanks @abuaboud, I don't have the capacity to contribute as of now, will revisit again.
The idea is to build an HR automation tool that allows HR teams to automate the candidate interview process.
Looking for an automation tool that allows me to create custom automation flows (that involves sending emails, sending prompt to openai, scheduling meetings, exporting data, etc) via APIs.
Activepieces looks like a good candidate though.

**Comment by abuaboud** [comment]
@pankaj9296 No worried there is no need for contribution You can read the controllers directly they have a well-defined schema that you can use and it should be readable.

Let me know if you have any questions
