### ISSUE TITLE
[BUG]: the code piece fails

### ISSUE THREAD

**Issue by vasyan1992** [activepieces/activepieces#3211]
**Describe the bug**
unable to run 0.12.0 in kubernetes doe to volume mount issue 
**To Reproduce**
deploy image in GKE
**Expected behavior**
pod in Running state

**Additional context**
  Warning  Failed     38s                kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: invalid mount {Destination:[/usr/src/cache, Type:bind Source:/var/lib/containerd/io.containerd.grpc.v1.cri/containers/activepieces/volumes/520a909fbfb2533f86a6c2f020a261501d29e4b88cf42d03d2ea77590632fb93 Options:[rbind rprivate rw]}: mount destination [/usr/src/cache, not absolute: unknown

**Comment by abuaboud** [comment]
This is already fixed https://github.com/activepieces/activepieces/issues/3138 It will be be released with 0.13.0
