### ISSUE TITLE
[Question]: MongoDB in Acticepices Backend

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#3231]
Hello @abuaboud 
I was trying to add some of my apps to pieces and was trying to modify something i got an idea that no sql is way more better than sql to store unstructured data of API,
Just an needfull question is there any way to use mongo db in the project already,
Else i want to create a seprate pull request to add a functionality to make project work on mongo db too.
Just have some question what are the important files i need to work upon to do this and where i need to replace the queries?

**Comment by abuaboud** [comment]
Hi @PhoenixMystique,

We do use TypeORM (https://www.npmjs.com/package/typeorm). It abstracts most of the things, though I am not sure if it will be 100% compatible when you switch from PostgreSQL to MongoDB.

However, you can try modifying the `database-connection.ts` file and see how it goes and look into typeorm documentation.

On the other hand, you can always use JSON fields in PostgreSQL. We do that in a couple of places for unstructured data.
