### ISSUE TITLE
[BUG]: Draft version is gone after connection issue error

### ISSUE THREAD

**Issue by JanHolger** [activepieces/activepieces#3251]
**Describe the bug**
2 days ago while working on a flow I got an alert saying that the connection has been lost and that I should refresh the page so I did (on v0.13.0). After that the draft version was wiped entirely (fresh flow with no trigger selected). The production version was still totally fine and I could luckily restore it from that with the help of @abuaboud (see below)

Yesterday this issue happened to one of our customers (on v0.5.0) as well and @lan5nl also reported it in #3004 

**To Reproduce**
Unfortunately I don't know how to reproduce the error as it's really unexpected and happened out of nowhere. I kept the old flow though and restored into a new one so I can provide the data (in discord) or perform checks on it.

**Expected behavior**
Draft doesn't get lost on a "connection issue"

**Additional context**
Trick for everyone who runs into this:
1. Export the template (it will be the empty one but we'll need that for the next steps)
2. Switch to the prod version
3. Open the dev console and switch to the network tab (F12 in chrome)
4. Refresh the page and look for an api request that looks something like /v1/flows/<flow id>
5. Check the payload and look for the "trigger" object and verify that it looks like your prod flow
6. Copy the trigger object into the empty trigger object of the template you downloaded in step 1
7. Import the template

**Comment by abuaboud** [comment]
There is version history to restore for published version, and this should be fixed in https://github.com/activepieces/activepieces/issues/3457
