### ISSUE TITLE
[BUG]: Error module @wwa/fastify-favicon

### ISSUE THREAD

**Issue by Quentin-L-Inge** [activepieces/activepieces#3298]
**Describe the bug**
Hello, I updated the activepiece to the lastest version (0.14.1 I think) and I can't launch it. (I use Docker compose) And when I launch, I have an error of Node.js which cannot find a module (@wwa/fastify-favicon)

**To Reproduce**
1. Update the projet where it is said on the documentation docker compose
2. See error

**Expected behavior**
Just to restart normally. 

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/75664985/d356c417-9d33-4d71-a2d1-3d49c987e668)

**Additional context**
I tried a fresh installation of the git but still have the problem.

**Comment by abuaboud** [comment]
It's been fixed, there were issue in building the image, please run docker compose pull again.

https://github.com/activepieces/activepieces/pull/3297

The 0.14.1 is now rebuild and release.


Sorry for that, thank you!
