### ISSUE TITLE
Return Detailed Webhook Response

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#3363]
Currently webhook timeout returns 408 and failed one returns 400, It should returns the details  as well.

**Comment by b4s36t4** [comment]
Would love to work on this, but need some assistance here :). I have seen `webhook-controller.ts` in which we're returning the response of executing a flow, but not sure if that's where I should be looking or not.

**Comment by abuaboud** [comment]
Hi @b4s36t4,

sorry for late reply I just noticed this message, I think this should be done. It returns 500 for failure, 504 for timeout, and 200 for success, and 204 if there is content.
