### ISSUE TITLE
cau use gpt-crawler?

### ISSUE THREAD

**Issue by av8dtop** [activepieces/activepieces#3391]
**Is your feature request related to a problem? Please describe.**
create piece by https://github.com/BuilderIO/gpt-crawler to crawler any url for flow or tell me how to create or use, thank

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abuaboud** [comment]
I think you can use it to create assistant in OpenAI then call this OpenAI assistant from activepieces using OpenAI piece.

I am closing this issue, let me know if this not what you meant, I am not sure if i fully understand.
