### ISSUE TITLE
[BUG]: facing some issues while running the application locally in windows

### ISSUE THREAD

**Issue by siam1113** [activepieces/activepieces#3405]
When I try to create a new flow I am not able to and getting some error
Refer to this recording: https://jam.dev/c/796e9e16-94a4-498b-9cff-a26b64b261cf

**Comment by abuaboud** [comment]
I think it's related to https://github.com/activepieces/activepieces/issues/3410

@AbdulTheActivePiecer can you please take a look at that

**Comment by AbdulTheActivePiecer** [comment]
Hey, can you please upgrade your image first? I think you have an outdated one .

**Comment by AbdulTheActivePiecer** [comment]
There was a similar bug like this on older versions which was fixed recently.

**Comment by IrzamDawood7** [comment]
But why this issue only persist on windows ?

**Comment by IrzamDawood7** [comment]
And when we are trying to run with dev containers , and add a new sample piece it's giving utils error's

**Comment by siam1113** [comment]
@AbdulTheActivePiecer 
I tried to **debug** the root cause of the errors that we got while setting up `dev env` locally in Windows and by changing couple things running (specially in terms of **commands**) I was able to successfully run the application locally and create new flows 🎉


Refer to this commit to see the changes been to make things work: https://github.com/siam1113/activepieces/commit/4d6a31a873c2ff725640d604343300c531b1707e
