### ISSUE TITLE
[BUG?] Unable to run Activepieces locally following the documentation steps

### ISSUE THREAD

**Issue by jjuannn** [activepieces/activepieces#3410]
Hey guys! :wave: 

Env details: node @18.17, npm @10.1.0, W10 (also tested on Ubuntu VM)

I'm trying to run Activepieces locally to start the development of some custom pieces for personal use. Was trying to follow the documentation steps to run it with docker compose. 

When i run `bash tools/deploy.sh` i get the following output:

![image](https://github.com/activepieces/activepieces/assets/64806950/a7e7c057-39e7-4d36-946e-98378e920776)

And this if i run it on Ubuntu:

![image](https://github.com/activepieces/activepieces/assets/64806950/7960d296-3474-4625-bb6c-bb9105c94b0a)

If i generate the values manually using `openssl` like the script deploy.sh, it gives me an authentication error with the database when i run `docker compose -p activepieces up`:

![image](https://github.com/activepieces/activepieces/assets/64806950/7ec794ac-fca9-49b1-b3f6-37f329ac1906)

Also tried to run it with the --env-file flag to specify the file location manually but isn't working neither.

If i try to run it following the [local environment](https://www.activepieces.com/docs/developers/development-setup/local) steps, it runs the concurrently command and dies without any output.

![image](https://github.com/activepieces/activepieces/assets/64806950/2cafdd52-ad0c-4e5e-9d97-fc830d4ecac4)

If i run the commands manually, `npm:serve:pieces` gives me the following output:

![image](https://github.com/activepieces/activepieces/assets/64806950/964c42be-db25-4eba-bcdd-f2c2d180e26b)

I'm able to go to `localhost:4200` and login with the dev@ap.com account. But when i try to add a step

![image](https://github.com/activepieces/activepieces/assets/64806950/dd258980-288f-4690-8612-b66737d4eb50)

I get the following error in the backend process:

![image](https://github.com/activepieces/activepieces/assets/64806950/15ad3f73-a23b-44a5-88b8-755748d557d2)

If this helps, this is my engine process output:

![image](https://github.com/activepieces/activepieces/assets/64806950/7b5a2722-d077-4de6-9731-3708852a0a6c)

Any hint?

Thanks!

**Comment by abuaboud** [comment]
Are you running WSL inside windows? can you please describe your environment?

**Comment by jjuannn** [comment]
Hi @abuaboud 

Yes, i'm running WSL. 

![image](https://github.com/activepieces/activepieces/assets/64806950/82fa634f-48ca-4d49-89bc-72cf859be27f)

Also i'm using 
- node @18.17 
- npm @10.1.0, 
- Windows 10 Pro, v22H2

**Comment by AbdulTheActivePiecer** [comment]
Hello buddy, Activepieces can only run within a Linux directory, so can you please pull the repo from within your WSL files directory? I recommend downloading the Ubuntu terminal and then getting git configured within that and pull the repo there, then open vscode from the terminal by navigating to the directory and using "code ." then reopen in the dev container, then from within the dev container in vscode open a terminal and run the steps used within the documentation, I will update the docs soon.

**Comment by jjuannn** [comment]
Hi @AbdulTheActivePiecer 

I was able to follow all steps but when i run the  `> Dev Containers: Reopen in Container` i get the following error: 

![image](https://github.com/activepieces/activepieces/assets/64806950/8307feb0-5def-4263-a4bc-2c33b9f76d4b)

I tried to assign more resources to Docker and WSL but it seems not making any difference. Also if i click `Continue` when i run `npm start` and it runs the `npm run dev` command it freezes there.

**Comment by jjuannn** [comment]
Is working now. I just had to change my .wslconfig to 

`[wsl2] memory=9GB` instead of `[wsl2] memory=8GB`.

Thanks guys!

**Comment by jjuannn** [comment]
Hi guys 👋🏻 

I've created a .env in the root usign the `tools/deploy.sh ` but when i start the app using `npm start` it isn't reading the environment variables correctly. I modified the values for AP_DEV_PIECES and AP_FRONTEND_URL but it's using the default ones. Also i'm not seeing where are those default values declarated in the code.

**Comment by abuaboud** [comment]
@jjuannn Sorry, it's hard to notice the comment on a closed issue. AP_DEV_PIECES is only used during DEV mode. The reason it's showing all pieces is that it loads them directly from the npm.

The .env for development mode is already generated at `packages/backend/.env`. This is where you should make modifications during development mode.

Please let me know if you have any questions

**Comment by jjuannn** [comment]
Thanks @abuaboud. I'll take a look on that
