### ISSUE TITLE
[BUG]: Slack Trigger nothing to select

### ISSUE THREAD

**Issue by huseyinkogo** [activepieces/activepieces#3419]
**Describe the bug**
So i want to trigger new channel messages from slack, but there's nothing to select

**Screenshots**
[Screencast from 2023-12-13 18-21-46.webm](https://github.com/activepieces/activepieces/assets/76049382/5251195e-0af9-404f-829c-78998e80c29b)

**Additional context**
I even reinstalled the activepiece instance to anothe vm. same problem.
its the lastest docker-compose install

**Comment by abuaboud** [comment]
Please check:

https://github.com/activepieces/activepieces/issues/2759#issuecomment-1733136462

and this
https://github.com/activepieces/activepieces/issues/765

I can complete the second task but I don't have any time to write the documentation how to setup slack trigger for self hosting, I can guide you on that but is it possible if you can contribute a tutorial or documentation back in the repo for future users?

**Comment by huseyinkogo** [comment]
@abuaboud thanks for the reply.
if thats the case, i will love to contribute.

**Comment by abuaboud** [comment]
@huseyinkogo I created the PR, but things got out of hand will try to push it in upcoming sprint

Closing as duplicate  of https://github.com/activepieces/activepieces/issues/765
