### ISSUE TITLE
Allow branching from a piece action/trigger itself without the need for an extra branch step

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#3420]
We currently have pieces like the approval one that requires the user to add a branch step and a condition after the approval step to properly us it.
Instead of that we are going to support the action/trigger having a branch coming out of it.
This task is going to be divided to two parts:
1) Backend:
We are going to need the engine to know which path to take depending on the step result and also we will need to handle its logs as well, we are also going to be modifying the schema of an action/trigger to tell if it is using branches or not.

2) Frontend: 
We are going to need to show the branches depending on the action trigger being chosen, and also add an extra behaviour for when viewing a run of a flow with such a usecase.

**Comment by AbdulTheActivePiecer** [comment]
Depends on https://github.com/activepieces/activepieces/pull/3111, we can work on it after that's merged.

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/4633
