### ISSUE TITLE
Disable on premise user registration

### ISSUE THREAD

**Issue by tradexsrl** [activepieces/activepieces#3422]
How to disable in on premise opensource dockerized deployment user registration?
i have deployed activpieces but i don't want that anyone over the internet could register to my server
thank's

**Comment by abuaboud** [comment]
It should be disabled by default after first sign up, if not please check `AP_SIGN_UP_ENABLED`

https://www.activepieces.com/docs/install/configurations/environment-variables

Thank you, I am closing the issue feel free to reopen.

**Comment by tradexsrl** [comment]
ok it works, thank's

**Comment by Sutaai** [comment]
Hello @abuaboud,
This environment variable does not appear on https://www.activepieces.com/docs/install/configuration/environment-variables (Your URL has an additional `s` at `configuration`)
Is this intended?
