### ISSUE TITLE
Github trigger when a new release from a repository is published

### ISSUE THREAD

**Issue by tradexsrl** [activepieces/activepieces#3426]
Hi , i'm not able to set an automation for github to check this repository 007revad/Synology_HDD_db to notify me when there is a new release and send me an email
in github trigger i have the only option to select my repository....also tried to star this repository without any luck

**Comment by abuaboud** [comment]
You can use an RSS trigger to listen to the GitHub RSS link. Here's an example link for activepiieces repository:

https://github.com/activepieces/activepieces/releases.atom


I am closing this issue, feel free to reopen if you have other questiions.
