### ISSUE TITLE
[BUG]: the SOAP piece fails with optional attributes

### ISSUE THREAD

**Issue by LK511** [activepieces/activepieces#3432]
**Describe the bug**
I have following WSDL, which mark some attributes as optional (minOccurs=0):
```
<s:element name="SmlouvaPNDAkceptace">
<s:complexType>
<s:sequence>
<s:element minOccurs="0" maxOccurs="1" name="IDpartner" type="s:string"/>
<s:element minOccurs="0" maxOccurs="1" name="kodZi" type="s:string"/>
<s:element minOccurs="0" maxOccurs="1" name="DatumOd" type="s:string"/>
<s:element minOccurs="1" maxOccurs="1" name="list" type="s:boolean"/>
<s:element minOccurs="0" maxOccurs="1" name="IDdotazu" type="s:string"/>
</s:sequence>
</s:complexType>
</s:element>
```
but the SOAP pieces marks all attributes as required

**To Reproduce**
1. Go to 'SOAP piece'
2. Use some WSDL which have optional attributes
3. Scroll down to loaded attributes
4. See that all attributes are marked as required

**Expected behavior**
Attributes defined in WSDL as minOccurs="0" should be optional

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/77941847/f5efeff2-cc99-4181-941c-b77dafed03de)

**Comment by JanHolger** [comment]
@x7airworker Any idea on this?

We built this piece for a pretty specific use-case in a customer project and never tested it outside of this use-case. Most likely the js soap client didn't deliver this information so we always set it to required (see: https://github.com/activepieces/activepieces/blob/main/packages/pieces/soap/src/lib/actions/call-method.ts#L65C25-L65C39)

**Comment by x7airworker** [comment]
If I remember correctly, there was no way to get additional information about the parameters. I will look into this issue and try to find a solution in the next days.

**Comment by x7airworker** [comment]
Unfortunately the [describe method](https://www.npmjs.com/package/soap#clientdescribe---description-of-services-ports-and-methods-as-a-javascript-object) doesn't reveal more than the name and type of the parameter. Seems like the WSDL needs to be parsed separately to gain additional information about the parameters.

**Comment by abuaboud** [comment]
I am closing this as not fixable. Please reopen if I didn't understand correctly.
