### ISSUE TITLE
[BUG]: Checkbox does not use defaultValue

### ISSUE THREAD

**Issue by bigfluffycookie** [activepieces/activepieces#3435]
If you set the defaultValue for a checkbox property it does not get used. 

Can be fixed by  changing " propValue || false" to "propValue || prop.defaultValue || false" in _/workspace/packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts_ where 

```
case PropertyType.CHECKBOX: {
          controls[pk] = new UntypedFormControl(propValue || false);
          break;
}
```

**Comment by abuaboud** [comment]
Hi @bigfluffycookie 

Thank you for opening the issue and the suggestion for the fix, If you can open the PR that would be great.

**Comment by abuaboud** [comment]
@allcontributors please add @bigfluffycookie for bug
