### ISSUE TITLE
[BUG]: Getting 400 error when using the "Create issue" action in Jira Cloud

### ISSUE THREAD

**Issue by fardeenpanjwani-codeglo** [activepieces/activepieces#3476]
**Describe the bug**
When the "priority" option is selected from the "Create issue" action in the Jira Cloud piece, I get the following response:
```json
{
  "response": {
    "status": 400,
    "body": {
      "errorMessages": [],
      "errors": {
        "priority": "Field 'priority' cannot be set. It is not on the appropriate screen, or unknown."
      }
    }
  },
  "request": {
    "body": {
      "fields": {
        "project": {
          "id": "REDACTED"
        },
        "summary": "Test",
        "issuetype": {
          "id": "10010"
        },
        "assignee": {
          "id": "REDACTED"
        },
        "priority": {
          "id": "1"
        },
        "description": {
          "content": [
            {
              "content": [
                {
                  "text": "test",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "type": "doc",
          "version": 1
        }
      }
    }
  }
}
```

**To Reproduce**
1. Add Jira Cloud piece to a flow
2. Select the "Create Issue" action
3. Select app-connection, project, issue type ( bug happens for any type you select ), and fill in the summary
4. Test the step without selecting a priority. This won't cause an issue
5. Now, select a priority, and then test the step again. This returns a 400 error

**Expected behavior**
1. The piece should return 200 when a priority is selected

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/141914308/82dee663-b55e-437c-98dc-e9167c2b9c03)

**Comment by krishnajhapate** [comment]
Hi Can I look into it

**Comment by fardeenpanjwani-codeglo** [comment]
> Hi, Can I look into this issue? 
> 
> And how can I do it

@abuaboud thoughts?

**Comment by krishnajhapate** [comment]
I have completed the setup and followed the provided steps, but I'm unable to identify any issues at the moment.

**Comment by fardeenpanjwani-codeglo** [comment]
> I have completed the setup and followed the provided steps, but I'm unable to identify any issues at the moment.

Hmm..weird that it works for you. Let me test it again. Maybe it was fixed in the recent release..

**Comment by krishnajhapate** [comment]
Yeah you can test it and if you finds let me know .

**Comment by abuaboud** [comment]
Hi @fardeenpanjwani-codeglo Please reopen if you still have the issue.
