### ISSUE TITLE
[BUG]: Monday oauth fails

### ISSUE THREAD

**Issue by fardeenpanjwani-codeglo** [activepieces/activepieces#3477]
**Describe the bug**
When trying to connect Monday using oauth, I get the following error: 
```json
{"error":"invalid_scope","error_description":"Invalid scope param"}
```

**To Reproduce**
1. Add the Monday piece to the flow
2. Click on "New connection" from the connections dropdown
3. Click on "Connect" in the dialog box
4. If you are already logged into Monday, you'll see the error right away, if not, log in and then see the error.

**Expected behavior**
The redirect-endpoint should close without any errors

**Screenshots**
![monday-oauth2](https://github.com/activepieces/activepieces/assets/141914308/01b1c482-6f0b-44a0-89c6-b339878fc35b)

**Comment by AbdulTheActivePiecer** [comment]
Hello
Currently our OAuth2 app on Monday isn't verified, would you mind creating your own OAuth2 app and place it there ? 
You will need the redirect url: https://cloud.activepieces.com/redirect

**Comment by AbdulTheActivePiecer** [comment]
Here are the scopes we use: 
    workspaces:read
    boards:read
    boards:write
    updates:read
    updates:write
    webhooks:write
    webhooks:read

**Comment by AbdulTheActivePiecer** [comment]
![image](https://github.com/activepieces/activepieces/assets/106555838/3515719e-3299-4552-b5c2-bb55e76cb612)

**Comment by fardeenpanjwani-codeglo** [comment]
Ah, okay. Gotcha. Thanks!
