### ISSUE TITLE
Add the ability to use proxy for all requests

### ISSUE THREAD

**Issue by pfernandez98** [activepieces/activepieces#3491]
**Is your feature request related to a problem? Please describe.**
Yes, according to @AbdulTheActivePiecer, your servers are in Europe so Google Gemini won't work.

**Describe the solution you'd like**
Maybe is gonna be good to add some kind of "User proxy for requests" systemwide. 

**Describe alternatives you've considered**
The only alternative right now is to self host

**Additional context**

**Comment by abuaboud** [comment]
Hi @pfernandez98 

I am closing this issue, I think one of future goals is let people bring their runner on the cloud and have the ability to assign workers for users and granular control on where to distribute tasks to which workers.

I don't think we will support the proxy but we will fix it in another way, so I am closing this ticket 


Thank you for the suggestion!
Please feel free to reopen.
