### ISSUE TITLE
[BUG]: Error on new monday connection

### ISSUE THREAD

**Issue by MichaelHinrichs** [activepieces/activepieces#3498]
**Describe the bug**
When i try to make a new connection to monday.com, the OAuth pop-up window just says
`{"error":"invalid_scope","error_description":"Invalid scope param"}`

**To Reproduce**
Make a new monday.com integration, with predefined app credentials.

**Expected behavior**
Show OAuth authentication window.

**Comment by MichaelHinrichs** [comment]
See also #3499.

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/3499
