### ISSUE TITLE
Monday API Token

### ISSUE THREAD

**Issue by MichaelHinrichs** [activepieces/activepieces#3499]
**Is your feature request related to a problem? Please describe.**
When i try to make a new connection to monday.com, the OAuth pop-up window just says
`{"error":"invalid_scope","error_description":"Invalid scope param"}`
#3498

**Describe the solution you'd like**
Connect to monday.com with an API token.

**Describe alternatives you've considered**
Fix the OAuth Authentication.

**Comment by abuaboud** [comment]
Yea I think it's better to switch for API token, great suggestions!
