### ISSUE TITLE
[BUG]: docker image for linux/arm/v8 (raspberry pi)

### ISSUE THREAD

**Issue by avel** [activepieces/activepieces#3527]
Hello,

Related to https://github.com/activepieces/activepieces/issues/2955 , I'd like to test out activepieces on a raspberry pi 4 but it's missing a build for this architecture.

**To Reproduce**

```
pi@raspberrypi:~/activepieces $ docker pull activepieces/activepieces:0.15.0
0.15.0: Pulling from activepieces/activepieces
no matching manifest for linux/arm/v8 in the manifest list entries
pi@raspberrypi:~/activepieces $ arch
aarch64
pi@raspberrypi:~/activepieces $ cat /proc/cpuinfo | grep Model
Model		: Raspberry Pi 4 Model B Rev 1.2
```

It would be nice if this was available.

**Comment by abuaboud** [comment]
@avel please check the latest pre-release 0.16.0-rc

**Comment by avel** [comment]
@abuaboud The image is pulling, with the new release. Congrats on the new release and thank you for such a quick fix! (Will open new issues if I encounter anything).
