### ISSUE TITLE
[BUG]: Notion connection Issue 

### ISSUE THREAD

**Issue by codeWarriors-pro** [activepieces/activepieces#3543]
**Describe the bug**
Notion app connection issue

**To Reproduce**
Select Notion any Trigger
Try to create connection 
Success attempt and then redirect popup is stuck and not closed

**Expected behavior**
Attemp Oauth2 then redirect back to app to store connection.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/114612630/bce2ddd8-723e-4cd8-b675-c59930634363)

**Comment by abuaboud** [comment]
Hi @codeWarriors-pro 

What is the version are you using?

**Comment by abuaboud** [comment]
I believe this issue existed in an older version of ActivePieces. Please upgrade to the latest version and reopen the issue if you're still facing any problems.
