### ISSUE TITLE
LocalAI working, but Model List is empty

### ISSUE THREAD

**Issue by bendreality** [activepieces/activepieces#3544]
**Cant get LocalAI to work**

I run LocalAI in a Docker Container on Port 8080 under Win11. 
I also run Activepieces in a container

What happens:

- I add a LocalAI Node. 
- Action: Ask LocalAI
- Server URL: http://127.0.0.1:8080 or http://localhost:8080
- Access Token: blank
- It tries to load models but the dropdown is empty

The models url (http://localhost:8080/models) is reachable via browser and outputs the expected response: 

```
{"object":"list","data":[{"id":"mistral","object":"model"},{"id":"zephyr-7b-beta.Q5_K_S.gguf","object":"model"}]}
```

In the code of the localai piece I saw it's using `url: (<any>auth).base_url +'/models',`. Seems alright at first sight. So somehow the piece is not able to connect to localhost:8080, but I don't get why.  ^^

I can get a response from LocalAI if I use it directly with the following code:

```
import requests
import json


def send_request_to_llama():
    url = "http://localhost:8080/v1/completions"

    headers = {
        "Content-Type": "application/json"
    }

    data = {
        "model": "zephyr-7b-beta.Q5_K_S.gguf",
        "prompt": "A long time ago in a galaxy far, far away",
        "temperature": 0.7
    }

    response = requests.post(url, headers=headers, data=json.dumps(data))

    if response.status_code == 200:
        return response.json()
    else:
        return f"Fehler: {response.status_code}"


# Rufe die Funktion auf und drucke das Ergebnis
result = send_request_to_llama()
print(result)
```

### Activepieces

If i test the log shows
```
{"level":30,"time":1704229790468,"pid":8,"hostname":"ef81aa9734d2","reqId":"req-1","req":{"method":"POST","url":"/v1/step-run","hostname":"localhost","remoteAddress":"127.0.0.1","remotePort":57856},"msg":"incoming request"}
(node:8) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
{"level":30,"time":1704229793415,"pid":8,"hostname":"ef81aa9734d2","msg":"sandbox, command: cd /usr/src/app/dist/sandbox/0 && env -i AP_PIECES_SOURCE=CLOUD_AND_DB NODE_OPTIONS='--enable-source-maps' /usr/local/bin/node main.js EXECUTE_STEP"}
{"level":30,"time":1704229793528,"pid":8,"hostname":"ef81aa9734d2","reqId":"req-2","req":{"method":"GET","url":"/v1/worker/app-connections/localai?projectId=iZ1ruZGYqlSEmAHDzr7Mp","hostname":"127.0.0.1:3000","remoteAddress":"127.0.0.1","remotePort":57860},"msg":"incoming request"}
{"level":30,"time":1704229793533,"pid":8,"hostname":"ef81aa9734d2","reqId":"req-2","res":{"statusCode":200},"responseTime":4.663796000182629,"msg":"request completed"}
{"level":30,"time":1704229794872,"pid":8,"hostname":"ef81aa9734d2","reqId":"req-1","res":{"statusCode":200},"responseTime":4403.820276000071,"msg":"request completed"}
```

### LocalAI Log

Is empty. There is no request.

**Comment by abuaboud** [comment]
You may want to use the internal Docker container IP for LocalAI. To debug this successfully, SSH into the activepieces container and try to ping or use curl directly inside the container. Check if the LocalAI container is reachable from there.

I am closing this issue as I understand correctly, this related to network issue between docker containers. 

Please feel free to reopen if you can ping the LocalAI container from Activepieces Container then it would be related to Activepieces

**Comment by bendreality** [comment]
Thank you for the suggestion. I'll try that. :)
