### ISSUE TITLE
facebook ads campaigns

### ISSUE THREAD

**Issue by luiis716** [activepieces/activepieces#3547]
I would like it to be possible to see the possibility of how to receive Facebook ads campaigns

possibility of integration and many great integrations with data

**Comment by abuaboud** [comment]
Hi @luiis716,

Thank you for reporting the issue. Could you please post it here: https://community.activepieces.com/c/feature-requests/9? 

For pieces, we prioritize our internal resources based on the number of votes. If there is a developer reading this, we also welcome contributions and love them. ❤️

You can check out our guide at https://www.activepieces.com/docs/developers/overview.
