### ISSUE TITLE
[BUG]: code giving error codePieceModule.code

### ISSUE THREAD

**Issue by luiis716** [activepieces/activepieces#3548]
I'm trying to clean up the phone number when I receive it (99) 9 9999-9999 using the following code

function clearNumber(number: string): string {
// Remove spaces, parentheses, hyphens and other non-numeric characters
const numeroLimpo = numero.replace(/[^\d]/g, '');
return numberClean;
}

// Example of use
const originalnumber = '(99) 9 999-9999';
const CleanNumber = cleanNumber(OriginalNumber);
console.log(clean number); // Output: 99999999999

**Comment by abuaboud** [comment]
![image](https://github.com/activepieces/activepieces/assets/1812998/ae254b91-e214-496f-bc11-e60f9e0eb4ba)

Please keep the original const code function, I think we should add it also the original code as comment.

Thank you for the feedback 
Mo.
