### ISSUE TITLE
[BUG]: Failed to Install Activepieces

### ISSUE THREAD

**Issue by Ulysse2211** [activepieces/activepieces#3556]
**Describe the bug**
On a fresh install Debain 12 LXC VPS with docker option enabled, I tied to install activepices but got an error while pulling the container:

`Failed to register layer: failed to Lchown "/usr/src/app/dist/packages/backend/node_modules/buffer-equal-constant-time/.npmignore" for UID 718322462, GID 454177323 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /usr/src/app/dist/packages/backend/node_modules/buffer-equal-constant-time/.npmignore: invalid argument`

**To Reproduce**
1. Go to 'https://www.activepieces.com/docs/install/options'
2. Click on 'Docker, Docker COmpose or easy panel'
3. Follow the instructions listed there on a debain 12 LXC Docker compatible machine
4. See error while pulling the image

**Expected behavior**
I've expected the image to pull succesfuly without errors, according to the documentation.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/106011457/f7ff9887-6d73-4a19-ab1b-ccface09856b)

Thanks in advance for your help !

**Comment by abuaboud** [comment]
LXC has always been a source of pain for these issues. I would suggest checking out the GitHub repository and building the Docker image using `docker build .` on the same machine (LXC VPS). Then, try using that image and let me know if it works.
