### ISSUE TITLE
Self-hosted Activepieces on EasyPannel cannot connect to OpenAI via API.

### ISSUE THREAD

**Issue by avatarwefa** [activepieces/activepieces#3573]
I use this API and it connects successfully on my Cloud.Activepieces.com, but when i use it on my self-hosted one, it gives the error "Connection failed: Invalid API key" and below are the codes in the F12. (I have tried generated new API secrets, but nothing works)

Path: /install/options/easypanel
![image](https://github.com/activepieces/activepieces/assets/44519372/0ea0dbf0-555b-40dc-84cd-7754a83365be)
![image](https://github.com/activepieces/activepieces/assets/44519372/e5c28bea-6e32-4789-a8a1-f37007ea5642)
![image](https://github.com/activepieces/activepieces/assets/44519372/f4e2ac72-1858-408b-9a17-a3190a5cee1b)

**Comment by abuaboud** [comment]
The image on Easypanel is so old (around 0.5.3) can you please upgrade to (0.16.0) and let me know if the issue persist I tried to open PR for their team but they are slow to merge the PRs

activepieces/activepieces:0.5.3

**Comment by abuaboud** [comment]
I am closing this issue as there is no action items on our team.

Please upgrade to latest version and hopefully Easypanel merge the request soon

**Comment by avatarwefa** [comment]
Thanks so much for the help, just upgraded via this on EasyPanel. And redeployed. Work like a charm! 


![image](https://github.com/activepieces/activepieces/assets/44519372/a4b6e913-67d3-45b0-af97-b6c9008765e1)
