### ISSUE TITLE
Please Give Us Dark Mode In Self-Hosted Version

### ISSUE THREAD

**Issue by dnburgess** [activepieces/activepieces#3587]
**Is your feature request related to a problem? Please describe.**
Staring at a bright white screen for an hour while trying to build things sucks.

**Describe the solution you'd like**
Dark Mode

**Describe alternatives you've considered**
None

**Additional context**
Please? Dark mode? Please?

**Comment by abuaboud** [comment]
Hehe I saw some people did it with chrome extension

**Comment by LINUXADDICT** [comment]
I use a chrome extension to achieve the Dark Mode but it will be nice if this was an actual feature of the app, the white screen is way too bright to stare at for extended periods of time.

**Comment by dnburgess** [comment]
I understand that Chrome has dark mode extensions, but Chrome is already a resource hog as it is and adding more extensions makes it far worse. Also, when moving from one device to another, the extension might not be available for whatever reason.  Like @LINUXADDICT said, the white screen is WAY too bright for extended periods of time.

**Comment by abuaboud** [comment]
wait waiting for this issue since we created activepieces hehe! :heart:

**Comment by abuaboud** [comment]
It's now released on cloud.activepieces.com and soon for self hosters, It will be improved in coming days.

**Comment by abuaboud** [comment]
btw we rewrote our ui to react :")

https://github.com/activepieces/activepieces/pull/5135
