### ISSUE TITLE
Backend compilation fails 

### ISSUE THREAD

**Issue by tdergouzi** [activepieces/activepieces#3590]
**Descirption**
Got an error when i run `npx run serve:backend` in local environment. 

**Error message**
<img width="630" alt="Screenshot 2024-01-10 at 17 01 49" src="https://github.com/activepieces/activepieces/assets/42488870/9778e7c2-8627-4e3f-967d-17fc856b66e9">

**My env**
operation system: MacOS
node version: v18.17.1
npm version: 9.6.7
code version: latest

**Additional context**
I got no error when installing the dependencies. I think this may be a bug in code, waiting for reply, thanks.

**Comment by abuaboud** [comment]
I think you are using `npx run serve:backend` , I think you should run `npm run serve:backend`

**Comment by abuaboud** [comment]
Please let me know if that's the issue

**Comment by abuaboud** [comment]
Closing this, Please reopen if you still have the issue.

**Comment by tdergouzi** [comment]
> I think you are using `npx run serve:backend` , I think you should run `npm run serve:backend`
Sorry for wrong description, actually it's `npm run serve:backend`
