### ISSUE TITLE
Documentation for Pieces 

### ISSUE THREAD

**Issue by darbaz** [activepieces/activepieces#3596]
I am getting frustrated of how to use some of the pieces available. documentation is needed for "how to use" 

I was trying to use the MySQL piece. I did the connection (based on my experience with mysql) but it is difficult to go forward. I was searching online for resources for how to use or what should I do, I couldn't fine any resources or documentation for this piece. at least when you have a page for each page, it should contain some sort of description of how to use and explain the inputs and what is the connections for the output.

take me as an outsider who want to use this service, it is not easy how to know the outputs and inputs and linking each piece and how to use some specific piece.

Best wishes and hope this platform thrive

**Comment by abuaboud** [comment]
Hi @darbaz,

Thank you for your valuable feedback! We've recently introduced markdown properties to enhance our documentation within the actions.

If you have specific suggestions, feel free to contribute directly or share details about any actions you found challenging. Let us know what instructions you believe would be most helpful in those instances.

I closed the issue, as it currently isn't actionable. However, If you have any further suggestions or details to provide, please reopen the issue. This will enable us to transform it into an actionable task for the MySQL piece.

https://github.com/activepieces/activepieces/tree/main/packages/pieces/mysql/src/lib/actions
