### ISSUE TITLE
Discussions for Activepieces

### ISSUE THREAD

**Issue by zaaakher** [activepieces/activepieces#3617]
Hi,

Absolutely love this project ✨

Would the maintainers be willing to enable discussions in this repo? So that we can discuss and ask questions and help each other without cluttering the issues page.

**Comment by kishanprmr** [comment]
Hi @zaaakher ,

I'm glad to hear that you're enthusiastic about the project. 

we have a [community](https://community.activepieces.com/) forum website where users can engage in discussions, ask questions, and propose new features.

Also If you're interested in contributing to our repository, we also have a [Discord channel](https://discord.com/invite/2jUXBKDdP8). Feel free to join and connect with other contributors! .

**Comment by abuaboud** [comment]
Hi @zaaakher,

We appreciate the discussion and feedback! This is the main reason why this product is improving rapidly. Please join our Discord and the community, as Kishan suggests. It's the best place to discuss.

Thank you,
Mo.
