### ISSUE TITLE
Publish Pieces as NPM Packages

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#362]
- move pieces to standalone packages
- endpoint to get pieces and latest versions
- add metadata to flow to declare dependencies on pieces and their versions
- cache pieces packages to avoid installing them on every flow run
- hot-reloading during development
- ensure docs generator works

**Comment by AbdulTheActivePiecer** [comment]
Please open PRs for each step, and mention which step it addresses with the issue number.
