### ISSUE TITLE
Tweaks to Autocomplete UI

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#363]
1. Caret direction needs to be up and down.
2. Hover highlight should always cover the whole row.
3. Collapsables should open on click instead of getting selected.
4. All rows should have “select” to the right side on hover.
5. Non-collapsables should get selected whether the row is clicked or “select” is clicked.
6. Move caret on top-level rows to the left of the label.
7. Revisit indentation in the tree (make it smaller, preferably the width of the caret).
8. Display values next to the property (with a different color, as in the design).
9. Search is not working on the sub-items.

**Comment by ashrafsamhouri** [comment]
@AbdulTheActivePiecer Updated the description here!
