### ISSUE TITLE
[Windows]: Github auth connection fails in local development

### ISSUE THREAD

**Issue by zaaakher** [activepieces/activepieces#3634]
**Describe the bug**
Github auth connection not working in local development (Windows 10 Pro) Build: 19045.3086

**To Reproduce**
1. Clone the repo
2. prepare the dev environment  (via setup-dev.js script)
3. add github to /backend/.env `AP_DEV_PIECES` variable
4. run `npm run start`
5. Visit the frontend in localhost:4200
6. login
7. Create a new flow
8. Select Github as a first step
9. Select "New Issue" as a trigger (or any other option)
10. Create a new github connection and complete the auth steps in the github popup and hit save 
11. Select the connection you just made from the Connections dropdown menu
12. Try to select a repository you'll get the following screen (see attached image)

**Expected behavior**
I should be able to see a list of repositories

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/46135573/c2338421-eb96-44cd-8984-df3452a714cd)

**Additional context**
Here's the error from the terminal:

```
[API] [07:07:48 UTC] ERROR: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dist\packages\pieces\github' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\@activepieces\piece-github'
[API]     reqId: "req-2e"
[API]     req: {
[API]       "method": "POST",
[API]       "url": "/v1/pieces/options",
[API]       "hostname": "localhost:3000",
[API]       "remoteAddress": "127.0.0.1",
[API]       "remotePort": 58109
[API]     }
[API]     res: {
[API]       "statusCode": 500
[API]     }
[API]     err: {
[API]       "type": "Error",
[API]       "message": "EPERM: operation not permitted, symlink 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dist\\packages\\pieces\\github' -> 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\@activepieces\\piece-github'",
[API]       "stack":
[API]           Error: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dist\packages\pieces\github' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\@activepieces\piece-github'
[API]       "errno": -4048,
[API]       "code": "EPERM",
[API]       "syscall": "symlink",
[API]       "path": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dist\\packages\\pieces\\github",
[API]       "dest": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\@activepieces\\piece-github",
[API]       "context": {
[API]         "[SandboxProvisioner#provision]": {
[API]           "pieces": [
[API]             {
[API]               "packageType": "REGISTRY",
[API]               "pieceType": "OFFICIAL",
[API]               "pieceName": "@activepieces/piece-github",
[API]               "pieceVersion": "0.3.4"
[API]             }
[API]           ],
[API]           "codeSteps": [],
[API]           "cacheInfo": {
[API]             "type": "PIECE",
[API]             "pieceName": "@activepieces/piece-github",
[API]             "pieceVersion": "0.3.4"
[API]           }
[API]         }
[API]       }
[API]     }
```

**Comment by zaaakher** [comment]
I was told that's an issue exclusive to Windows and fixed was merged recently so I pulled the latest code and did the same steps and got a different error this time:

![image](https://github.com/activepieces/activepieces/assets/46135573/41c4e77d-e1a2-47ac-ab91-392dc84f581b)

**Comment by zaaakher** [comment]
The error seems to be coming from `packages/backend/src/app/workers/sandbox/file-sandbox.ts`

**Comment by zaaakher** [comment]
I tried deleting `dist` and `cache` folders and used a terminal with administrative access but unfortunately still getting [this](https://github.com/activepieces/activepieces/issues/3634#issuecomment-1892238239) error

**Comment by abuaboud** [comment]
Thank you for the detail response @zaaakher

**Comment by zaaakher** [comment]
Unfortunately I'm still getting an error (freshly cloned repo with a fresh npm install)


```
[09:40:12 UTC] ERROR: [errorHandler]: {"errno":-4048,"code":"EPERM","syscall":"symlink","path":"C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm","dest":"C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm","context":{"[SandboxProvisioner#provision]":{"pieces":[{"packageType":"REGISTRY","pieceType":"OFFICIAL","pieceName":"@activepieces/piece-github","pieceVersion":"0.3.4"}],"codeSteps":[],"cacheInfo":{"type":"PIECE","pieceName":"@activepieces/piece-github","pieceVersion":"0.3.4"}}}}
[API] [09:40:12 UTC] ERROR: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
[API]     err: {
[API]       "type": "Error",
[API]       "message": "EPERM: operation not permitted, symlink 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm' -> 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm'",
[API]       "stack":
[API]           Error: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
[API]       "errno": -4048,
[API]       "code": "EPERM",
[API]       "syscall": "symlink",
[API]       "path": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm",
[API]       "dest": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm",
[API]       "context": {
[API]         "[SandboxProvisioner#provision]": {
[API]           "pieces": [
[API]             {
[API]               "packageType": "REGISTRY",
[API]               "pieceType": "OFFICIAL",
[API]               "pieceName": "@activepieces/piece-github",
[API]               "pieceVersion": "0.3.4"
[API]             }
[API]           ],
[API]           "codeSteps": [],
[API]           "cacheInfo": {
[API]             "type": "PIECE",
[API]             "pieceName": "@activepieces/piece-github",
[API]             "pieceVersion": "0.3.4"
[API]           }
[API]         }
[API]       }
[API]     }
[API] [09:40:12 UTC] ERROR: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
[API]     reqId: "req-2r"
[API]     req: {
[API]       "method": "POST",
[API]       "url": "/v1/pieces/options",
[API]       "hostname": "localhost:3000",
[API]       "remoteAddress": "127.0.0.1",
[API]       "remotePort": 60345
[API]     }
[API]     res: {
[API]       "statusCode": 500
[API]     }
[API]     err: {
[API]       "type": "Error",
[API]       "message": "EPERM: operation not permitted, symlink 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm' -> 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm'",
[API]       "stack":
[API]           Error: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
[API]       "errno": -4048,
[API]       "code": "EPERM",
[API]       "syscall": "symlink",
[API]       "path": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm",
[API]       "dest": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm",
[API]       "context": {
[API]         "[SandboxProvisioner#provision]": {
[API]           "pieces": [
[API]             {
[API]               "packageType": "REGISTRY",
[API]               "pieceType": "OFFICIAL",
[API]               "pieceName": "@activepieces/piece-github",
[API]               "pieceVersion": "0.3.4"
[API]             }
[API]           ],
[API]           "codeSteps": [],
[API]           "cacheInfo": {
[API]             "type": "PIECE",
[API]             "pieceName": "@activepieces/piece-github",
[API]             "pieceVersion": "0.3.4"
[API]           }
[API]         }
[API]       }
[API]     }

```

**Comment by DesertStrom16** [comment]
> Unfortunately I'm still getting an error (freshly cloned repo with a fresh npm install)
> 
> ```
> [09:40:12 UTC] ERROR: [errorHandler]: {"errno":-4048,"code":"EPERM","syscall":"symlink","path":"C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm","dest":"C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm","context":{"[SandboxProvisioner#provision]":{"pieces":[{"packageType":"REGISTRY","pieceType":"OFFICIAL","pieceName":"@activepieces/piece-github","pieceVersion":"0.3.4"}],"codeSteps":[],"cacheInfo":{"type":"PIECE","pieceName":"@activepieces/piece-github","pieceVersion":"0.3.4"}}}}
> [API] [09:40:12 UTC] ERROR: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
> [API]     err: {
> [API]       "type": "Error",
> [API]       "message": "EPERM: operation not permitted, symlink 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm' -> 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm'",
> [API]       "stack":
> [API]           Error: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
> [API]       "errno": -4048,
> [API]       "code": "EPERM",
> [API]       "syscall": "symlink",
> [API]       "path": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm",
> [API]       "dest": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm",
> [API]       "context": {
> [API]         "[SandboxProvisioner#provision]": {
> [API]           "pieces": [
> [API]             {
> [API]               "packageType": "REGISTRY",
> [API]               "pieceType": "OFFICIAL",
> [API]               "pieceName": "@activepieces/piece-github",
> [API]               "pieceVersion": "0.3.4"
> [API]             }
> [API]           ],
> [API]           "codeSteps": [],
> [API]           "cacheInfo": {
> [API]             "type": "PIECE",
> [API]             "pieceName": "@activepieces/piece-github",
> [API]             "pieceVersion": "0.3.4"
> [API]           }
> [API]         }
> [API]       }
> [API]     }
> [API] [09:40:12 UTC] ERROR: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
> [API]     reqId: "req-2r"
> [API]     req: {
> [API]       "method": "POST",
> [API]       "url": "/v1/pieces/options",
> [API]       "hostname": "localhost:3000",
> [API]       "remoteAddress": "127.0.0.1",
> [API]       "remotePort": 60345
> [API]     }
> [API]     res: {
> [API]       "statusCode": 500
> [API]     }
> [API]     err: {
> [API]       "type": "Error",
> [API]       "message": "EPERM: operation not permitted, symlink 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm' -> 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm'",
> [API]       "stack":
> [API]           Error: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\node_modules\.pnpm\isolated-vm@4.6.0\node_modules\isolated-vm' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\isolated-vm'
> [API]       "errno": -4048,
> [API]       "code": "EPERM",
> [API]       "syscall": "symlink",
> [API]       "path": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\NONE-apId-UJnqRBIgyHSizj4ZDOmUw\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm",
> [API]       "dest": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\isolated-vm",
> [API]       "context": {
> [API]         "[SandboxProvisioner#provision]": {
> [API]           "pieces": [
> [API]             {
> [API]               "packageType": "REGISTRY",
> [API]               "pieceType": "OFFICIAL",
> [API]               "pieceName": "@activepieces/piece-github",
> [API]               "pieceVersion": "0.3.4"
> [API]             }
> [API]           ],
> [API]           "codeSteps": [],
> [API]           "cacheInfo": {
> [API]             "type": "PIECE",
> [API]             "pieceName": "@activepieces/piece-github",
> [API]             "pieceVersion": "0.3.4"
> [API]           }
> [API]         }
> [API]       }
> [API]     }
> ```

Any update on this? I am also getting the same error.

**Comment by abuaboud** [comment]
I think it requires running as admin, @DesertStorm16.

Try the "Dev Container" method for Windows; it's much more reliable there.

Please let me know if it works.
