### ISSUE TITLE
[BUG]: Migrations between  1696950789636 and now failed

### ISSUE THREAD

**Issue by glani** [activepieces/activepieces#3636]
**Describe the bug**
The system from latest migration record:
42,1696950789636,AddArchiveIdToPieceMetadata1696950789636 and latest release

**To Reproduce**

Spawn old service create postgres DB and apply the latest one.

[API]
[API] Migration "StoreCodeInsideFlow1697969398200" failed, error: column file.platformId does not exist
[API] [08:58:38 UTC] ERROR: [Main#main]
[API]     err: {
[API]       "type": "QueryFailedError",
[API]       "message": "column file.platformId does not exist",
[API]       "stack":
[API]           QueryFailedError: column file.platformId does not exist
[API]               at PostgresQueryRunner.query (/tmp/self/activepieces/src/driver/postgres/PostgresQueryRunner.ts:331:19)
[API]               at processTicksAndRejections (node:internal/process/task_queues:95:5)
[API]               at SelectQueryBuilder.loadRawResults (/tmp/self/activepieces/src/query-builder/SelectQueryBuilder.ts:3805:25)
[API]               at SelectQueryBuilder.executeEntitiesAndRawResults (/tmp/self/activepieces/src/query-builder/SelectQueryBuilder.ts:3551:26)
[API]               at SelectQueryBuilder.getRawAndEntities (/tmp/self/activepieces/src/query-builder/SelectQueryBuilder.ts:1670:29)
[API]               at SelectQueryBuilder.getOne (/tmp/self/activepieces/src/query-builder/SelectQueryBuilder.ts:1697:25)
[API]       "query": "SELECT \"file\".\"id\" AS \"file_id\", \"file\".\"created\" AS \"file_created\", \"file\".\"updated\" AS \"file_updated\", \"file\".\"projectId\" AS \"file_projectId\", \"file\".\"platformId\" AS \"file_platformId\", \"file\".\"data\" AS \"file_data\", \"file\".\"type\" AS \"file_type\", \"file\".\"compression\" AS \"file_compression\" FROM \"file\" \"file\" WHERE (\"file\".\"id\" = $1) LIMIT 1",
[API]       "parameters": [
[API]         "SmgZfrYZxkKqcgVJkQxnV"
[API]       ],
[API]       "driverError": {
[API]         "type": "DatabaseError",
[API]         "message": "column file.platformId does not exist",
[API]         "stack":
[API]             error: column file.platformId does not exist
[API]                 at /tmp/self/activepieces/node_modules/pg/lib/client.js:526:17
[API]                 at processTicksAndRejections (node:internal/process/task_queues:95:5)
[API]                 at PostgresQueryRunner.query (/tmp/self/activepieces/src/driver/postgres/PostgresQueryRunner.ts:260:25)
[API]                 at SelectQueryBuilder.loadRawResults (/tmp/self/activepieces/src/query-builder/SelectQueryBuilder.ts:3805:25)
[API]                 at SelectQueryBuilder.executeEntitiesAndRawResults (/tmp/self/activepieces/src/query-builder/SelectQueryBuilder.ts:3551:26)
[API]                 at SelectQueryBuilder.getRawAndEntities (/tmp/activepieces/src/query-builder/SelectQueryBuilder.ts:1670:29)
[API]                 at SelectQueryBuilder.getOne (/tmp/self/activepieces/src/query-builder/SelectQueryBuilder.ts:1697:25)
[API]         "length": 114,
[API]         "name": "error",
[API]         "severity": "ERROR",
[API]         "code": "42703",
[API]         "position": "146",
[API]         "file": "parse_relation.c",
[API]         "line": "3656",
[API]         "routine": "errorMissingColumn"
[API]       },
[API]       "length": 114,
[API]       "severity": "ERROR",
[API]       "code": "42703",
[API]       "position": "146",
[API]       "file": "parse_relation.c",
[API]       "line": "3656",
[API]       "routine": "errorMissingColumn"
[API]     }
[API]
[API] >  NX  Process exited with code 0, waiting for changes to restart...
[API]
[GUI] ✔ Browser application bundle generation complete.

**Expected behavior**
Migration should work

**Additional context**
Looks like it is antipattern to use entities in the migration. fileId is created in the future migration scripts. Empty DB can be created without any problems.

**Comment by glani** [comment]
proposed fix would be to add after AddArchiveIdToPieceMetadata1696950789636  AddPlatformIdToFile1701807681821 and change the code with:

```
    public async up(queryRunner: QueryRunner): Promise<void> {
        const r = await queryRunner.query(`SELECT column_name
            FROM information_schema.columns
            WHERE table_name='file' and column_name='platformId'`)
        if (r?.records?.length) {
            await queryRunner.query(`
              ALTER TABLE "file" DROP COLUMN "platformId"
          `)
        }
        await queryRunner.query(`
                ALTER TABLE "file"
                    ADD "platformId" character varying(21)
            `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "file" DROP COLUMN "platformId"
        `)
    }
```

and do the same for AddPlatformIdToFile1701807681821. existing migrations won't be affected in this case typeorm ignores them

**Comment by abuaboud** [comment]
Hi, 

You are correct, This should be fixed in next release / pre-release

https://github.com/activepieces/activepieces/pull/3642
