### ISSUE TITLE
Run results state not being saved

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#3659]
**Describe the bug**
If someone runs/tests a flow and they close the run details left side bar, then open it again, the state (loop indices) aren't restored, they get either reset to 1 if the loop didn't fail or set to the last iteration so the failed step shows.

**Expected behavior**
The state is stored in a state to keep track of it.

**Comment by abuaboud** [comment]
We rewrote to react, this is no longer valid closing
