### ISSUE TITLE
[BUG]: Env broken after 0.17.0 -> 0.18.1 upgrade

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#3695]
**Describe the bug**
Tried upgrading to 0.18.1 but getting a 502s on some endpoints e.g. `api/v1/flags`. 
Downgrading back to 0.17.0 works fine.

No other changes made. Deploying the image directly from Docker Hub so not built locally. 

I didn't see any breaking changes in the release notes so assuming there's something unexpected going on here.

![image](https://github.com/activepieces/activepieces/assets/838788/0d5fcf42-62c5-49bb-bfab-0866c2f474d7)

**Comment by abuaboud** [comment]
Hi @GFoley83 

That's super weird, Is there any error log?

**Comment by abuaboud** [comment]
502 means that the backend didn't go up, was there any errors?

**Comment by GFoley83** [comment]
No errors. Other than some of the endpoints failing to load. The default GET request succeeds but it's just a spinny wheel on screen.
Deploys fine into AWS too. 
I didnt check the logs sorry. I was rushing to get it back online. I can try again out of hours to see if there's anything useful in there to help.

**Comment by abuaboud** [comment]
Hi @GFoley83 

How do you health check? I think it's better to healthcheck /api/v1/flags instead of /

**Comment by GFoley83** [comment]
Yep agreed that's definitely a better way to do it. Just not sure why it's failing currently.

**Comment by cbalbinos** [comment]
I updated to 0.18.1 on Railway, and the same thing happened and without logs, I went back to 0.17.0

**Comment by abuaboud** [comment]
Hi @GFoley83 and @cbalbinos 

How do you specify Redis settings?  Do you use AP_REDIS_URL?

**Comment by cbalbinos** [comment]
Yes, I'm using AP_REDIS_URL

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/pull/3699

I think it's related to breaking change happened after upgrading bullmq, It should be fixed in 0.18.2.

Will try to get release out tonight

**Comment by abuaboud** [comment]
Please use the alternative method to specify Redis in the meantime. The next release will have significant changes, and I want to wait until we have completed enough testing (tonight or tomorrow) 

Refer to https://www.activepieces.com/docs/install/configurations/environment-variables

Define AP_REDIS_USER and AP_REDIS_PASSWORD as raw variables and other redis variables instead of a URL, this method does work.

**Comment by abuaboud** [comment]
Fixed and released in 0.18.2

**Comment by GFoley83** [comment]
Can confirm that upgrading to 0.18.2 works fine. Thanks all.

**Comment by cbalbinos** [comment]
Update to 0.18.2 completed successfully.

Thanks!
