### ISSUE TITLE
[BUG]: the gmail action "Send email" send raw text HTML

### ISSUE THREAD

**Issue by yann120** [activepieces/activepieces#3711]
**Describe the bug**
When using the Gmail Send email action with a body that has multilines, it convert all the line breaks into \<br>.
But the br are not intepreted as HTML, so the email is really ugly, see screenshot

**To Reproduce**
1. create a new flow with whatever trigger
2. use the action Gmail : Send email
3. in the body, write text on multiple lines
4. test the action and check your emails
5. you should see \<br> for every line break

**Expected behavior**
HTML is interpreted, we should not see html and just text with new lines

**Screenshots**
Body of the written email in ActivePieces : 
<img width="370" alt="Capture d’écran 2024-01-21 à 12 43 33" src="https://github.com/activepieces/activepieces/assets/10012140/d6eb6dd1-1445-4039-8801-81054072aa46">
Body received by email : 
<img width="652" alt="Capture d’écran 2024-01-21 à 12 43 39" src="https://github.com/activepieces/activepieces/assets/10012140/e94359fd-464d-4012-be64-4780c6f41521">

**Comment by abuaboud** [comment]
Hi @yann120 

You should use Body(HTML) field instead of Body(Text), that should fix the issue.

Thank you,
Mo.
