### ISSUE TITLE
Google Spread sheet not working in local dev

### ISSUE THREAD

**Issue by Devil-26** [activepieces/activepieces#3727]
I've tried to test the flows on my local environment. I've used google-sheets as the trigger (Only available piece). After making the connection, I was not able to select spread sheet. It shows "An unexpected error occured. Please contact our support".

Following are the backend logs:

  - "Command failed: pnpm link E:\\activepieces\\dist\\packages\\pieces\\community\\google-sheets --config.lockfile=false --config.auto-install-peers=true\n"
  - "EPERM: operation not permitted, symlink 'E:\\activepieces\\dev\\cache\\sandbox\\NONE-apId-wDQbiPTYRNgBCiT1c0UL8\\node_modules\\.pnpm\\isolated-vm@4.6.0\\node_modules\\isolated-vm' -> 'E:\\activepieces\\dev\\cache\\sandbox\\2\\node_modules\\isolated-vm'"

**Comment by abuaboud** [comment]
Hi @Devil-26 

Can you sync fork and check again?

**Comment by abuaboud** [comment]
I am closing this issue, as I think it should be fixed by now.

Please reopen If it's still there.
