### ISSUE TITLE
[BUG]:  ( Schedule )ActivePieces when setting automation "Every X Mintues" It is not triggering at a specified time 

### ISSUE THREAD

**Issue by codeWarriors-pro** [activepieces/activepieces#3728]
**Describe the bug**
ActivePieces when setting automation "Every X Mintues" It is not triggering at a specified time  Also the test flow run only in 1st attempt and when again click on test flow it's keep running and never ending again 

**To Reproduce**
1. Go to 'Schedule app select Every X Mintues trigger'
2. Add step two any action app
3. Click on Test Flow First time will succeed and when again click test flow then stuck in infinite loop 
@AbdulTheActivePiecer Please any update ?

**Comment by codeWarriors-pro** [comment]
![image](https://github.com/activepieces/activepieces/assets/114612630/8d8b4c1f-5934-473a-a7a9-bcec5eee55d8)

**Comment by abuaboud** [comment]
Hi @codeWarriors-pro 

It seems your instance is old by looking at the piece, what version are you currently using? can you try to upgrade to 0.18.2?
