### ISSUE TITLE
Retry on Latest Version doesn't work

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#3743]
**Describe the bug**

**To Reproduce**
1. Trigger any Flow
2. Rerun on Latest Version
3. Trigger payload will be empty

**Comment by GFoley83** [comment]
Just ran into this too. Looks like the input data isn't getting passed in:
![image](https://github.com/activepieces/activepieces/assets/838788/09f0d091-0a48-48a0-ab5d-7bd8310b35bb)

**Comment by abuaboud** [comment]
Hi @GFoley83 

Did you build from the main? because we didn't release this yet

**Comment by GFoley83** [comment]
No not yet. I didn't realise it was already fixed when I commented.
