### ISSUE TITLE
[BUG]: Infinite loading of Runs page

### ISSUE THREAD

**Issue by Gaket** [activepieces/activepieces#3776]
**Describe the bug**
Infinite loading of Runs page: https://cloud.activepieces.com/runs?limit=10

**To Reproduce**
1. Open Runs page
2. Get infinite loading

**Expected behavior**
I see runs of my flows

**Screenshots**
<img width="1388" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/a57d39e2-2173-4944-b45f-2309cfffef52">
<img width="1382" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/5b4c763c-5f5d-4f7f-b2f9-a34199402434">

**Additional context**
Network log shows the next error: 

{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "userPlatformId and paramId should be equal"
}

**Comment by Gaket** [comment]
The issue disappeared after logging out and logging back in. I guess it still may be worth to check it out.

**Comment by abuaboud** [comment]
Hi @Gaket 

I saw an similar issue on the community, yes please logout and login again It should be fixed.

Thank you,
Mo.
