### ISSUE TITLE
[HELP/BUG]: IDK the HTTP Request not working with Influxdb

### ISSUE THREAD

**Issue by huseyinkogo** [activepieces/activepieces#3795]
**Describe the bug**
Im not sure if its a bug or my fault. So im trying to query data from Influxdb2 database via HTTP Request.

Through the cli the following command works;

```
curl -XPOST http://10.20.2.50:5006/api/v2/query?org=evlab -sS   -H 'Accept: application/csv'   -H 'Content-type: application/vnd.flux'   -H 'Authorization: Token gFZkWpTrTE87xyAktaeDb2lx9YKfhkWvEzTYa7j4CLBJlhK5YLHP4zcWt_lDWKVCg6nZ64t36tOjEJ0vigAIYw=='   -d 'from(bucket:"ev")
        |> range(start: -5m)
        |> filter(fn: (r) => r["_measurement"] == "measurements")
        |> filter(fn: (r) => r["_field"] == "temperature" or r["_field"] == "usb_presence")
        |> filter(fn: (r) => r["device"] == "eps32-s3-van-freezer")
        |> filter(fn: (r) => r["location"] == "van")
        |> aggregateWindow(every: 1h, fn: last, createEmpty: false)
        |> yield(name: "last")'

```
Response is like;
```
,result,table,_start,_stop,_time,_value,_field,_measurement,device,location
,last,0,2024-02-01T09:47:41.617624499Z,2024-02-01T09:52:41.617624499Z,2024-02-01T09:52:41.617624499Z,29.81,temperature,measurements,eps32-s3-van-freezer,van

,result,table,_start,_stop,_time,_value,_field,_measurement,device,location
,last,1,2024-02-01T09:47:41.617624499Z,2024-02-01T09:52:41.617624499Z,2024-02-01T09:52:41.617624499Z,0,usb_presence,measurements,eps32-s3-van-freezer,van
```

I'm assume im struggling to convert the http curl command to work with activepieces.

So i have tried the following methods, but couldn't get it working,
**Screenshots**
![Screenshot from 2024-02-01 20-57-33](https://github.com/activepieces/activepieces/assets/76049382/50335931-01a6-4a67-8f97-cdd4a46be39f)
![Screenshot from 2024-02-01 20-56-26](https://github.com/activepieces/activepieces/assets/76049382/51d77d37-7748-4373-b5c7-d8c11db13c0d)

So i was getting this failed output;
`{
"response": {  
"status":400, 
"body":{"code":"invalid","message":"failed to decode request body: request body requires either query or AST"}}, 
"request":{}}
`

**Comment by kishanprmr** [comment]
@huseyinkogo Please add query after **-d** flag into **body**  and remove everything from Query Params.

Let me know if you face any error.

**Comment by huseyinkogo** [comment]
@kishanprmr 
thanks for the reply, sorry im confused.

Which approach should i go with? add the headers & Query params  OR use the Body with json

this is the current im using

```
{
  "url": "http://10.20.2.50:5006/api/v2/query?org=evlab",
  "body": "from(bucket:\"ev\")\n  |> range(start:-5m)\n  |> filter(fn:(r) => r._measurement == \"measurements\")\n  |> filter(fn:(r) => r._field == \"temperature\" or r._field == \"usb_presence\")\n  |> filter(fn:(r) => r.device == \"eps32-s3-van-freezer\")\n  |> filter(fn:(r) => r.location == \"van\")\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
  "method": "POST",
  "headers": {
    "Accept": "application/csv",
    "Content-type": "application/vnd.flux",
    "Authorization": "Token gFZkWpTrTE87xyAktaeDb2lx9YKfhkWvEzTYa7j4CLBJlhK5YLHP4zcWt_lDWKVCg6nZ64t36tOjEJ0vigAIYw=="
  }
}
```

**Comment by kishanprmr** [comment]
@huseyinkogo I think HTTP step is showing error for this body as it is not JSON.

Can you try this approch and let me know if it works.

In body field click on **(x)** button and enter your query.

![image](https://github.com/activepieces/activepieces/assets/135701940/f8c227d9-a43a-4e27-b540-37424de1918f)

**Comment by huseyinkogo** [comment]
thanks so much @kishanprmr its working now,
 
sorry how can i extract the value that is temperature from the output? 

Wanna get the number "29.31? so the value is first then the tag "temperature"

OUTPUT;

```
{
  "status": 200,
  "headers": {
    "content-type": "text/csv; charset=utf-8",
    "vary": "Accept-Encoding",
    "x-influxdb-build": "OSS",
    "x-influxdb-version": "v2.7.5",
    "date": "Thu, 01 Feb 2024 11:55:40 GMT",
    "connection": "close",
    "transfer-encoding": "chunked"
  },
  "body": ",result,table,_start,_stop,_time,_value,_field,_measurement,device,location\r\n,last,0,2024-02-01T11:50:40.941829089Z,2024-02-01T11:55:40.941829089Z,2024-02-01T11:55:40.941829089Z,29.31,temperature,measurements,eps32-s3-van-freezer,van\r\n\r\n,result,table,_start,_stop,_time,_value,_field,_measurement,device,location\r\n,last,1,2024-02-01T11:50:40.941829089Z,2024-02-01T11:55:40.941829089Z,2024-02-01T11:55:40.941829089Z,0,usb_presence,measurements,eps32-s3-van-freezer,van\r\n\r\n"
}
```

**Comment by huseyinkogo** [comment]
@kishanprmr All good, found the solution. Using the "CSV" piece works.

![image](https://github.com/activepieces/activepieces/assets/76049382/7ee116b1-f802-4936-bd91-5b4bfb5e2f26)
