### ISSUE TITLE
"Create Approval Link" => "Wait for Approval" doesn't work when there's a step in between

### ISSUE THREAD

**Issue by nickogoodwin** [activepieces/activepieces#3798]
**Describe the bug**
"Wait for Approval" only works if it's immediately following a "Create Approval Links" action, otherwise, the flow just runs to completion, skipping over the approval.

**To Reproduce**
Example Flow: 
1. Webhook Trigger
2. Create Approval Link
3. Send Slack message (with approve/deny links created in previous step)
4. Wait for Approval (This step "succeeds" regardless of whether a link is clicked or not)

**Expected behavior**
Create approval link => send it in a slack message (or email or whatever) => "Wait for Approval" should pause execution until a response is received

**Screenshots**
Flow just runs without pausing because the Slack Message step is between "Create Approval Link" and "Wait for Approval"
![image](https://github.com/activepieces/activepieces/assets/33714480/e0eea058-5531-4c2f-9afc-84f16cad5b0f)

This flow pauses and waits for approval, as expected, but is functionally useless because i can't "put" those approval links anywhere (email, slack message, etc.)
![image](https://github.com/activepieces/activepieces/assets/33714480/52a2609e-e451-4d33-bdab-4276e9c67575)

**Additional context**
_Possibly a separate issue_
I would use the Slack "Request Approval" piece instead, but it's also kinda broken... 
![image](https://github.com/activepieces/activepieces/assets/33714480/49e3e972-c771-4fe6-9c75-782e6392de83)
This error message happens because Slack needs a [required acknowledgement response](https://api.slack.com/interactivity/handling#acknowledgment_response) from AP, which it's not getting.

And aside from that error, it's also impossible to get the Approve/deny response back when Building and Testing this step. so there's no way to set up Branching when building the flow.

Response when testing (it's just the "Success" from posting the message in Slack)
![image](https://github.com/activepieces/activepieces/assets/33714480/72c7867b-6a44-4e31-a03b-fc631b6bd6e2)

Response when flow is published (This is the response I'm looking for when Building the flow, but it doesn't show up when testing, only on true Runs)
![image](https://github.com/activepieces/activepieces/assets/33714480/482b1e70-90c1-4908-a2f5-2f32df2b350c)

**Comment by abuaboud** [comment]
Hi @nickogoodwin,

Oh, yeah, I hate this experience as well. It was intended to add a branch and decide what you would like to do based on that output, but I feel it's confusing. What do you suggest?

**Comment by nickogoodwin** [comment]
If I "Create Approval Links" somewhere in the flow, then I feel like I should be able to put that "Wait for Approval" step **anywhere** in the flow, not just immediately after. You know?

Again, I'd like to send a slack message **containing** those approval links, and pause execution until they're clicked

**Comment by abuaboud** [comment]
@nickogoodwin I think i misunderstood the problem, now It's clear let me try to reproduce the issue will take look soon

**Comment by nickogoodwin** [comment]
Yeah sorry about that, I think i mentioned 2 or 3 issues in this post. Got in the weeds a bit there.

**Main Issue**
- AP Core **Approval** piece: "Wait for Approval" only works if immediately following "Create Approval Links"

**Secondary Issues**
-Slack **Approval Messages** piece:
--Activepieces not sending [Acknowledgement Response](https://api.slack.com/interactivity/handling#acknowledgment_response) to slack
--No way to create a Branch from a Slack Approval Message because testing flow does not return correct response

Should i submit a separate bug report for the Slack Approval Messages issues?

**Comment by abuaboud** [comment]
@nickogoodwin Got it, Let me take look at that, did you try latest version? there was couple of fixes related to this area but didn't test this scenario.
