### ISSUE TITLE
HubSpot Connection returns body/value must have required property 'secret_text'

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#381]
I tested it on both cloud and demo but not self hosted.

STR:
- Add HubSpot and choose action.
- Connect your account.
- On the connection popup, click Save.
- The following error will be returned.

<img width="1440" alt="Screenshot 2023-01-26 at 11 40 21" src="https://user-images.githubusercontent.com/97393596/214792626-6710c5a9-9a2a-4b68-bd55-dcfab6d09161.png">

**Comment by abuaboud** [comment]
Thank you, will be fixed in next release

**Comment by ashrafsamhouri** [comment]
@abuaboud A minot hotfix or next big release? I think it's a critical bug.
