### ISSUE TITLE
Moodle Events support

### ISSUE THREAD

**Issue by kmp8072** [activepieces/activepieces#3810]
**Is your feature request related to a problem? Please describe.**
Moodle is a popular open source LMS platform. I want to integrate different applications with Moodle but no open source platform to do this. All the solutions if any available are paid solutions only. 

**Describe the solution you'd like**
I want to perform actions to other applications like teams or slack or may be salesforce,  when a moodle event is triggered. As Moodle has events system so I hope it can be integrated as a piece in activepieces.

**Additional context**
I don't have typescript knowledge otherwise I would have done it myself and contributed to activepieces. I hope there would definitely a helping hand in integrating Moodle events as pieces. I can help understand Moodle system and its events api if anyone want to know. Thanks

**Comment by Buda9** [comment]
+1
