### ISSUE TITLE
Insert to Data Freeze on Large Payloads

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#3815]
**Describe the bug**

**To Reproduce**
1. Import the following flow
2. Run the second code piece
3. Insert to data hangs

**Solution**:

Apply some sort of lazy loading in the user interface to avoid chrome freezing.

[Random Icecream Generator.json](https://github.com/activepieces/activepieces/files/14155215/Random.Icecream.Generator.json)

**Comment by AbdulTheActivePiecer** [comment]
I did my research on things, some tools just crash their browsers when they have such large files, some don't even allow you to return such a large file while testing/running a step.
Technically what's causing our tool to take so long is prism and the highlighting we do, if we instead use Monaco as a json viewer, things will be much smoother.
