### ISSUE TITLE
[BUG]: HTTP Request not working with Influxdb

### ISSUE THREAD

**Issue by huseyinkogo** [activepieces/activepieces#3823]
reference; https://github.com/activepieces/activepieces/issues/3795

the next day of resolving/fixing the http request.

nothing was change.

getting this error;
`{"response":{"status":400,"body": {"code":"invalid","message": "failed to decode request body: request body requires either query or AST"}},"request":{}}`

**Comment by kishanprmr** [comment]
Hello @huseyinkogo ,

Can you please validate your query using curl? If it fetches required result.

**Comment by huseyinkogo** [comment]
this is the output from the cli;
 
```
 curl -XPOST http://10.20.2.50:5006/api/v2/query?org=evlab -sS   -H 'Accept: application/csv'   -H 'Content-type: application/vnd.flux'   -H 'Authorization: Token uMLXAclwehmUTgg59hxlAFw6uBAMEmW8GiW_1NBiFUgR2r3_So_rFm6NEWKqe-OmEbNdkuF9Ug85s83vzP9oDw=='   -d 'from(bucket:"ev")
        |> range(start: -5m)
        |> filter(fn: (r) => r["_measurement"] == "measurements")
        |> filter(fn: (r) => r["_field"] == "temperature" or r["_field"] == "usb_presence")
        |> filter(fn: (r) => r["device"] == "eps32-s3-van-freezer")
        |> filter(fn: (r) => r["location"] == "van")
        |> aggregateWindow(every: 1h, fn: last, createEmpty: false)
        |> yield(name: "last")'
,result,table,_start,_stop,_time,_value,_field,_measurement,device,location
,last,0,2024-02-05T12:11:10.385836988Z,2024-02-05T12:16:10.385836988Z,2024-02-05T12:16:10.385836988Z,30.31,temperature,measurements,eps32-s3-van-freezer,van

,result,table,_start,_stop,_time,_value,_field,_measurement,device,location
,last,1,2024-02-05T12:11:10.385836988Z,2024-02-05T12:16:10.385836988Z,2024-02-05T12:16:10.385836988Z,0,usb_presence,measurements,eps32-s3-van-freezer,van

```

**Comment by kishanprmr** [comment]
@huseyinkogo , can you share screenshot for HTTP step where you are passing query inside **body**?

**Comment by huseyinkogo** [comment]
![image](https://github.com/activepieces/activepieces/assets/76049382/3be32c7b-bf8c-46aa-8b69-a6bdf2ea602c)

**Comment by abuaboud** [comment]
Hi @huseyinkogo did you upgrade activepieces recently?

**Comment by huseyinkogo** [comment]
@abuaboud yes i did

**Comment by abuaboud** [comment]
@huseyinkogo sorry for a bad question.

I meant did the issue happened before upgrading or only after?

**Comment by huseyinkogo** [comment]
@abuaboud don't be sorry.

pre-update it worked as in https://github.com/activepieces/activepieces/issues/3795 after it stopped working, so i updated activepieces.

**Comment by abuaboud** [comment]
I think you are correct @JanHolger , closing this as duplicate in favor to track it here https://github.com/activepieces/activepieces/issues/3915
