### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by CPonchet** [activepieces/activepieces#3839]
Path: /developers/development-setup/local

Hey Team,

First many thanks for the hard work on the documentation. Really good to read.

In notice a small issue with the first try on local dev env, nothing big.

With the chrome, you need to deactive the "Block insecure private network requests." to make it works in [localhost to avoid CORS](https://stackoverflow.com/questions/66534759/cors-error-on-request-to-localhost-dev-server-from-remote-site).

Otherwise, the first request (http://localhost:3000/v1/flags) fails and the loading is infinite.

**Comment by abuaboud** [comment]
You are @CPonchet's hero. I encountered that a lot of times and couldn't figure out why! 🦸‍♂️

**Comment by abuaboud** [comment]
@allcontributors please add @CPonchet for bug

**Comment by abuaboud** [comment]
@CPonchet  Do you have any idea why when I close the browser and open it again, It start work again?

**Comment by CPonchet** [comment]
@abuaboud to be sure to understand your point, with or without modifying the flag in Chrome?
I had some CORS issues on my devs (python/react) because I didn't authorize the localhost url in my CORS policy on the backend (in the OPTIONS). Putting the right params in the Access-Control-Allow-Origin header in the response will allow the browser to read the response. On your cloud deployment, working well, I assume it has been done (or via your Nginx/apache/proxy).

**Comment by abuaboud** [comment]
Hi @CPonchet 

I no longer facing this issue, specially after upgrading angular / nx / esbuild, I am closing this issue for now as completed.

Please reopen if you still have the issue.
