### ISSUE TITLE
How to recover pieces from a broken dockerized instance

### ISSUE THREAD

**Issue by tradexsrl** [activepieces/activepieces#3845]
Hi , i have a broken dockerized instance , is it possible to recover the structure of the pieces created ?
please let me know

**Comment by abuaboud** [comment]
Hi @tradexsrl,

Can you please provide more details about what you are trying to do? Are you attempting to recover the flows? How did it get broken? Also, which database are you using, SQLite3 or PostgreSQL?

**Comment by tradexsrl** [comment]
Hi , i have installed activepieces stack in portainer with redis and postgres , after an auto update from watchtower to the latest , the stacks get broken , i tried to rebuild the stacks with an previous docker image from docker hub but the web ui is not loading anymore.i need to recover just the flows

**Comment by abuaboud** [comment]
Hi,


Please provide the logs in the backend, this will help us to find the problem

**Comment by tradexsrl** [comment]
where can i find the logs ? because i have two dir one is called db and one redis
in the db i have the file from postgres and in redis i have only dump.rdb
since i need to rebuild quickly the old container was destroyed and i redeploy the stacks with the image version 0.18.2
if logs are inside the activepieces container i no more extract

**Comment by tradexsrl** [comment]
this are the yml file:
version: "3.9"
services:
  redis:
    image: redis
    container_name: Activepieces-REDIS
    hostname: activepieces-redis
    mem_limit: 256m
    mem_reservation: 50m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: xxxx:yyy
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/activepieces/redis:/data:rw
    environment:
      TZ: Europe/Rome
    restart: always

  db:
    image: postgres
    container_name: Activepieces-DB
    hostname: activepieces-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: xxxx:yyy
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "zzzzzzzzzzz", "-U", "zzzzzzzzzzzzzz"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/activepieces/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: zzzzzzzzzzzzz
      POSTGRES_USER: zzzzzzzzzzzzz
      POSTGRES_PASSWORD: zzzzzzzzzzzzzzzz
    restart: always

  activepieces:
    image: activepieces/activepieces:0.18.2
    container_name: Activepieces
    hostname: activepieces
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80
    ports:
      - 8310:80
    environment:
    ## 256 bit encryption key, 32 hex character
      AP_ENCRYPTION_KEY: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz                       
    ## JWT Secret
      AP_JWT_SECRET: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
      AP_ENVIRONMENT: prod
      AP_FRONTEND_URL: https://xxxx.yyyy.com
      AP_ENGINE_EXECUTABLE_PATH: dist/packages/engine/main.js
      AP_NODE_EXECUTABLE_PATH: /usr/local/bin/node
      AP_EXECUTION_MODE: UNSANDBOXED
      AP_POSTGRES_DATABASE: activepieces
      AP_POSTGRES_HOST: activepieces-db
      AP_POSTGRES_PORT: 5432
      AP_POSTGRES_USERNAME: zzzzzzzzzzzzzzzzzzzz
      AP_POSTGRES_PASSWORD: zzzzzzzzzzzzzzzzzzzz
      AP_REDIS_HOST: activepieces-redis
      AP_REDIS_PORT: 6379
      AP_SANDBOX_RUN_TIME_SECONDS: 600
      AP_TELEMETRY_ENABLED: false
      AP_SIGN_UP_ENABLED: false
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

**Comment by abuaboud** [comment]
What If you try to run it, what the error inside container logs? this where we can help with

**Comment by tradexsrl** [comment]
When i run and try to access the web ui , nothing happend.
as i said unfortunately i have destroyed the container , cancel the image and rebuild the stack with image version 0.18.2 , so no more logs available but the old data are saved in db and redis directory , so i hope to be able to extract the flows i have built

**Comment by abuaboud** [comment]
Hi @tradexsrl,

Of course, you should find them in the flow_version table. You can find the latest version and export it.

Also, export the flows from the UI and try to make the format the same. Then, use the "import flow" option in the new UI.

But if you rebuild the stack with image version 0.18.2, why not just use the UI?

**Comment by tradexsrl** [comment]
Hi thank's for the info , I'll try to find how to extract that table...never done and I will try to import
I have rebuild the stack but since I never export from the old stack the pieces I cannot import it with ui.

**Comment by tradexsrl** [comment]
> Hi @tradexsrl,
> 
> Of course, you should find them in the flow_version table. You can find the latest version and export it.
> 
> Also, export the flows from the UI and try to make the format the same. Then, use the "import flow" option in the new UI.
> 
> But if you rebuild the stack with image version 0.18.2, why not just use the UI?

Hi , sorry for the noob question but i install a tool that should visualize the db called dbvisualizer , i have saved all the file inside db folder from the old docker stacks but what should i try to open to see the flow_version table ?
![immagine](https://github.com/activepieces/activepieces/assets/62424179/11d01c35-5214-40af-8199-1472cb0421cd)

**Comment by tradexsrl** [comment]
> Hi @tradexsrl,
> 
> Of course, you should find them in the flow_version table. You can find the latest version and export it.
> 
> Also, export the flows from the UI and try to make the format the same. Then, use the "import flow" option in the new UI.
> 
> But if you rebuild the stack with image version 0.18.2, why not just use the UI?

hi , i was able to locally install a postgresql and open the database but as you can see there is no flow_version table or at least i'm not able to find it.Please let me know
![immagine](https://github.com/activepieces/activepieces/assets/62424179/0ab8d162-e8e9-491d-9098-9b733a66bc47)

**Comment by abuaboud** [comment]
You are looking under information_schema, try to take look at public schema, You should find it there.

I am closing the issue, please reopen if your issue is not resolved.

**Comment by tradexsrl** [comment]
thank's i was able to see the pieces and rebuild them
