### ISSUE TITLE
[BUG]: pnpm fails on new piece

### ISSUE THREAD

**Issue by mariomeyer** [activepieces/activepieces#3848]
**Describe the bug**
Just after @activepieces/piece-odoo was published I had to restart my server for the authentication process to work. Before restarting it I was getting this error:

```
{
    "statusCode": 500,
    "code": "1",
    "error": "Internal Server Error",
    "message": "Command failed: pnpm init \n"
}
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by abuaboud** [comment]
Hi @mariomeyer 

Sorry for late reply, Can you please try again on latest version and let me know if you still have problem?

Please reopen if you still have this issue
