### ISSUE TITLE
npm run publish-piece not present in repo anymore .. update docs ?

### ISSUE THREAD

**Issue by jmetzger** [activepieces/activepieces#3852]
Path: /developers/sharing-pieces/community

Looks like this command:

npm run publish-piece 

is not valid anymore. Does not even exist in the tools folder in your
repo.

Any updates to that ?

npm publish --access=public ?

**Comment by kishanprmr** [comment]
Hi @jmetzger ,

publish-piece command is available inside tools/scripts/pieces folder. Are you facing any errors when executing this command?

**Comment by abuaboud** [comment]
Thank you for opening issue, as @kishanprmr stated it is still there.

I am closing this issue,  please reopen with more information so we can help.
