### ISSUE TITLE
[BUG]: Cloud Login - No autofill possible for "Email" form field of login formular

### ISSUE THREAD

**Issue by bratekarate** [activepieces/activepieces#3881]
**Describe the bug**
On the cloud login page (desktop), the "Email" form field is not autofilled by password managers.

This is caused by a missing `type` attribute on the input. If `type="text"` is added via "inspect element", autofill starts working.

**To Reproduce**
1. Go to Login Page
2. Try autofilling your credentials with a password manager (tested with "Browserpass")
4. "Email" field stays blank

**Expected behavior**
The "Email" field is autofilled.

**Screenshots**
Current behavior with autofill
![Current behavior with autofill](https://github.com/activepieces/activepieces/assets/8384845/765677f4-bac4-4e95-a5bc-0d9544a44bf7)

**Additional context**
-

**Comment by abuaboud** [comment]
We need to add `type="email"` to these two lines in html tag like placeholder.

- [Line 29 in sign-up.component.html](https://github.com/activepieces/activepieces/blob/032d19ab38750adccb532a808e3dec94a2956f5f/packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.html#L29)

- [Line 8 in sign-in.component.html](https://github.com/activepieces/activepieces/blob/032d19ab38750adccb532a808e3dec94a2956f5f/packages/ui/feature-authentication/src/lib/pages/sign-in/sign-in.component.html#L8)
