### ISSUE TITLE
Question regarding engine

### ISSUE THREAD

**Issue by gitpullmain** [activepieces/activepieces#3890]
I'm noticing performance issues when retrieving dynamic property options and during test runs. Is there a reason the engine needs to run in a sandbox? It seems that the spin up of these sandboxes and the transfer of info is what is taking the time. Could this run in a separate service or in the backend directly with asynchronous functions or threading?

**Comment by abuaboud** [comment]
Hi @gitpullmain,

Regardless of whether it's in Sandbox or Unsandboxed mode, it spins up a new process, giving it control. For instance, if there is an infinite loop in the code, it can terminate the process and halt it.

The majority of the time isn't spent on creating sandboxes; it's more about preparing the sandbox (installing npm packages), as all the pieces are npm packages.

Could you please provide concrete numbers on the time it takes to execute the code? How long does it typically take?

Also, could you please try production mode.

The sandbox gets cached after the first execution, so can you provide more information on whether this is the first request or the second one? How long does each take?

Please reopen the issue with this information.
