### ISSUE TITLE
what is ee and how to use it?

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#3929]
@abuaboud I haven’t understand the use of ee and the admin dashboard in the code part, is there any way or setting to use it in code or it just for demo and whole code is not included

**Comment by PhoenixMystique** [comment]
any help @abuaboud ?

**Comment by abuaboud** [comment]
Hi @PhoenixMystique,

Apologies for any confusion. The new website will be released soon.

It's currently just a demo, and the code is protected behind license key and the modules is not imported in community edition. Please note that I don't believe the features are useful for individuals.

It's primarily designed for SaaS, enterprises, and agencies, the new website should explain them well.

Thank you,
Mo.
