### ISSUE TITLE
[BUG]: Dropbox Temporary Link - Insufficiently Scoped

### ISSUE THREAD

**Issue by StreamlinedStartup** [activepieces/activepieces#3936]
**Describe the bug**
Trying to **Get a Temporary File Link** leads to an error of insufficient scopes. 

**To Reproduce**
1. Create a new Dropbox Text File
2. Use **Get a Temporary File Link** to retrieve a link to the newly created document

**Expected behavior**
ActivePieces should have correct scopes. Going to the App Console, like suggested by Dropbox, doesn't show Activepieces as it's for developers creating their own apps. Going to **Settings > App > ActivePieces** doesn't allow any settings changes. 

**Screenshots**

![CleanShot 2024-02-15 at 09 45 54](https://github.com/activepieces/activepieces/assets/149590126/7e056c4b-bf31-41b1-9662-4f5801f65801)

![CleanShot 2024-02-15 at 09 48 25](https://github.com/activepieces/activepieces/assets/149590126/487b98dc-657e-4d50-9bfc-d05b2dac3db0)

**Additional context**
```
{
  "response": {
    "status": 400,
    "body": "Error in call to API function \"files/get_temporary_link\": Your app is not permitted to access this endpoint because it does not have the required scope 'files.content.read'. The owner of the app can enable the scope for the app using the Permissions tab on the App Console."
  },
  "request": {
    "body": {
      "path": "/intake-2.txt"
    }
  }
}
```

**Comment by georgeantonios** [comment]
Seconding Dropbox lacking necessary permissions for ActivePieces.

Error Message:
Your app is not permitted to access this endpoint because it does not have the required scope 'sharing.write'. The owner of the app can enable the scope for the app using the Permissions tab on the App Console."

I'm trying to use API calls to set folder visibility and get a share link.

**Comment by abuaboud** [comment]
It's now approved

https://community.activepieces.com/t/dropbox-get-temporary-link-not-working/6252
