### ISSUE TITLE
Tally Integration - No Form Data

### ISSUE THREAD

**Issue by StreamlinedStartup** [activepieces/activepieces#3937]
Tally.so integration trigger works and test comes in, but there is no data beyond headers and request information. The content of the submission is not available to use in further steps. 

What am I missing? 

```
{
  "method": "GET",
  "headers": {
    "host": "my.special.host.com",
    "accept": "application/json, text/plain, */*",
    "cf-ray": "xxxxxxxxxxxxx-xx",
    "cdn-loop": "cloudflare",
    "x-real-ip": "xxx.xx.x.x",
    "cf-visitor": "{\"scheme\":\"https\"}",
    "connection": "Upgrade",
    "user-agent": "Tally Webhooks",
    "cf-ipcountry": "US",
    "accept-encoding": "gzip",
    "x-forwarded-for": "xx.xxx.xxx.xx, xxx.xx.x.x",
    "cf-connecting-ip": "35.203.251.47",
    "x-forwarded-proto": "https",
    "x-forwarded-scheme": "https"
  },
  "queryParams": {}
}
```

![CleanShot 2024-02-15 at 10 00 17](https://github.com/activepieces/activepieces/assets/149590126/208b9f74-9342-4fa9-93ba-b351f71149da)

**Comment by kishanprmr** [comment]
Hello @StreamlinedStartup ,

Can you please check webhook settings in tally form? . There will be clock sign beside webhook (Events Log) , you can click on it to check all webhook response sent.

**Comment by StreamlinedStartup** [comment]
They're sending fine, apparently. 

![CleanShot 2024-02-24 at 21 56 13@2x](https://github.com/activepieces/activepieces/assets/149590126/e622619d-300d-4784-a724-caa79d55844e)

**Comment by kishanprmr** [comment]
Hi @StreamlinedStartup , 

I am currently unable to recreate this issue. Could you please attempt to recreate this trigger step and verify if it works on your end? Additionally, providing any additional details about the form would be immensely helpful for us to accurately reproduce and address this issue.

**Comment by abuaboud** [comment]
Closing this issue, please reopen if you still face the issue.
