### ISSUE TITLE
[BUG]: the code piece fails

### ISSUE THREAD

**Issue by codeWarriors-pro** [activepieces/activepieces#3949]
I want to know is it safe to use inMemory Cache for QueueManager instead of Redis cache on production ?
![image](https://github.com/activepieces/activepieces/assets/114612630/f5eff404-ee82-4772-8ed1-992805dcc58f)
@AbdulTheActivePiecer

**Comment by abuaboud** [comment]
It's always better to use Redis in the current implementation in production mode. For example, if you shut down a server while a process is running, it doesn't retry when it's picked up again.

If your infra and usage is basic, just spin it up in the machine via docker compose up.
