### ISSUE TITLE
Issue: the code piece fails

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#3957]
Just Changed my machine and getting this error even my all configs are same i have install all dependencies ,
@abuaboud CAN YOU PLEASE HELP ME WITH THIS 
<img width="871" alt="Screenshot 2024-02-18 at 7 36 45 PM" src="https://github.com/activepieces/activepieces/assets/67161169/6bd9cff9-4658-4426-9798-1469f7f95514">

**Comment by kishanprmr** [comment]
Hi @PhoenixMystique ,

can you see /shared folder inside /package/dist folder? can you try running **npx nx reset**  and try it again?

**Comment by PhoenixMystique** [comment]
No unable to find there i have tried npx nx reset still no hopes , anything else i can try?

**Comment by kishanprmr** [comment]
Did you try npm start after this command?

**Comment by PhoenixMystique** [comment]
After removing the package lock  json  and dist folder, I haven’t use npm ci i basically reinstalled all dependencies using packege.json and then refectored all env's and run the tools/setup-dev.js by removing npm ci It Worked for me ✌🏻
