### ISSUE TITLE
Sign Up Form (Email + Password + Newsletter + Analytics)

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#40]
After the first set up, we'll ask users to enter their emails to sign up for our newsletter for product updates and contribution opportunities.

**Comment by AbdulTheActivePiecer** [comment]
This needs :
1)UI: sign up form (email and password) + confirming newsletter subscription. 
2)Backend: Sign up endpoint (email and password only)  + endpoint that will receive the email of the user and store it for us to send updates to,  @ashrafsamhouri can you let us know what you would like it to be ? google sheets for example or something else like a hubspot contact. 
3)For analytics,  @ashrafsamhouri  can you give me a list of events to track ? and I will check how google analytics cookies can help us with this, if @abuaboud  or @khaledmashaly  have any suggestions for that technically, let me know.
