### ISSUE TITLE
[BUG]: No option "Continue on failure" in "Send HTTP request" piece

### ISSUE THREAD

**Issue by valentin76c** [activepieces/activepieces#4007]
**Describe the bug**
In docker image 0.20.3 and probably also in older versions. The "Continue on failure" option is not present in the "Send HTTP request" form.

**To Reproduce**
1. Mount a docker instance from the docker compose repo. 
2. Create a new process.
3. Add a trigger.
4. Add a "Send HTTP request" piece.
5. The "Continue on failure" option is not present.

**Expected behavior**
Enable the "Continue on failure" option.
![image](https://github.com/activepieces/activepieces/assets/24937150/caced39f-639f-4c62-93b6-54f2f864ac3a)
[Link to feature](https://community.activepieces.com/t/error-handling-auto-retry-and-continue-on-fail-options/2614)

**Screenshots**
<img width="1164" alt="image" src="https://github.com/activepieces/activepieces/assets/24937150/2051f17c-a70a-44d9-9edf-1017eea4def4">

**Additional context**
I don't have a license.
I'm new to the tool, so I may have misunderstood how it works, and if so, I apologize!

**Comment by abuaboud** [comment]
Hi @valentin76c,

The failsafe option has been re-added. You are correct; there is also no need for Iceinese ActivePieces. The Community Edition is open source and free.

It should be released in around 20 minutes https://github.com/activepieces/activepieces/pull/4017
