### ISSUE TITLE
Show folder of flow in runs overview

### ISSUE THREAD

**Issue by LK511** [activepieces/activepieces#4026]
**Is your feature request related to a problem? Please describe.**
In the overview of runs is not clear from which folder the running flow comes, when i have flows with same name in different folders

**Describe the solution you'd like**
At each run in the table should be information, in which folder is located

**Describe alternatives you've considered**
Group runs by folders

**Additional context**
![image](https://github.com/activepieces/activepieces/assets/77941847/6a4603cc-efb9-4749-b722-15d545dc408a)

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/5486

Added this there
