### ISSUE TITLE
[BUG]: Send Email piece after update to 0.1.6 from 0.1.5

### ISSUE THREAD

**Issue by glani** [activepieces/activepieces#4053]
**Describe the bug**
After updating workflow (just new publish): "Cannot read properties of undefined (reading 'type')"

**To Reproduce**
Version created with 0.1.5 

update a workflow publish.

Pieces version increased.

**Expected behavior**

Backward compatibility

P.S. Guys last time you asked about how we feel about using Activepieces. We are afraid of every time even publishing workflow.
You update the patched version! And it broke all flows that use email send (after republishing).

I understand that you are working at a fast pace, however, stability should be the priority. Probably, freezing core piece versions makes sense for backward compatibility. Right now it is the way to anywhere.

**Comment by abuaboud** [comment]
Hi @glani,

Thank you for reporting that. I have fixed it in https://github.com/activepieces/activepieces/pull/4054.

I believe we need to automate the process. This GitHub action could prevent it: https://github.com/activepieces/activepieces/issues/2880.

If you don't mind, I would love to schedule a short call with you to learn more about your experience and come up with an actionable roadmap to increase stability.

I connected to you on the LinkedIn and sent you message! 


Please let me know if the still exists in 0.1.7 It should be released in 15 minutes. 
https://github.com/activepieces/activepieces/actions/runs/8086501035

**Comment by glani** [comment]
"Greeting never received" looks like I need to reconfigure all smtp auth

**Comment by glani** [comment]
Ok after the reconnection of all smtp providers (We use three providers for tehnical emails). It started working.

To let you know: tls by default was ignored, I think you can easily put to true (by default) if port is 465 or 587. It is an example how to achieve backward compatibility (Yes, definitely it will pollute the code base, but you guys are doing a great job and this could be considered an evolution of Activepieces).

Thank you, so much.

**Comment by abuaboud** [comment]
Oh, @glani, I think it would have been better to increment the minor version, which would have prevented auto-upgrade. See: https://www.activepieces.com/docs/developers/piece-reference/piece-versioning

But I still don't get why did you have to reconnect the SMTP again to make it work.

Instead of 'Use TLS,' 'Use SSL' was actually used in 0.1.5. "Secure" only works with port 465, which I assume is not the problem. I think the combination that broke is `TLS` (checkbox) being false with port 465.

Am I understanding correctly?

**Comment by glani** [comment]
Two 465 and 587(here can be mistaken) all three were broken all have to use
tls. I checked old flows, several are still on 0.1.3. I hope they will work
with new connection we will see. Good that now I know the cause.

You are right minor would have helped. I was surprised when saw breaking
changes in patch.

Thank you again for assistance.

**Comment by abuaboud** [comment]
Hi @glani,

I think it's for port 465:

Previous Behavior:
```
secure: auth.TLS === true ? true : undefined,
```

Current Behavior:
```
secure: auth.port === 465,
```

So technically, it was undefined for port 587, and there was a rejection of unauthorized access, so it was technically bypassing TLS. I never expected that would cause a breaking change.

I sent you my calendar link on LinkedIn, I am still wondering if you have 15-30 minutes I would love to hear about the database migration issues, we did some fixes and wanted to know if the experience improved there.


Thank you for all the help.
MO.
