### ISSUE TITLE
Coda.io API connection

### ISSUE THREAD

**Issue by codewulf0** [activepieces/activepieces#4066]
**Describe your use case:**
For ActivePieces users who rely on Coda for document and data management within their workflows, integrating Coda.io endpoints would be immensely beneficial. Specifically, users could automate tasks such as creating or updating documents based on triggers from other services, managing sharing and publishing settings, and manipulating data within tables. This would enable more dynamic and powerful workflows that combine the strengths of ActivePieces with the versatility of Coda documents.

**Describe alternatives you've considered:**
While users could manually perform these tasks within Coda or use a combination of other automation tools, these methods lack the efficiency and integration depth that a direct implementation within ActivePieces would offer. Other automation platforms may provide some level of integration, but a native solution within ActivePieces would ensure a smoother, more reliable experience and potentially unlock unique use cases specific to the ActivePieces ecosystem.

**Coda API documentation**
[Explore the documentation here.](https://coda.io/developers/apis/v1)

**Comment by abuaboud** [comment]
I saw someone from community posted about it here: https://coda.io/packs/activepieces-webhook-27518
