### ISSUE TITLE
[BUG]: Not able to signup or login

### ISSUE THREAD

**Issue by chiragksharma** [activepieces/activepieces#4067]
**Describe the bug**
When I click the signup with google the google auth comes but there is no response after that 
**To Reproduce**

**Screenshots**
<img width="276" alt="image" src="https://github.com/activepieces/activepieces/assets/74889769/cfb54bc0-03ec-46a1-9a41-97789831e1c2">

**Comment by abuaboud** [comment]
Sorry for this issue, can you please send your email to support@activepieces.com

I will close this ticket and will follow up on the email, Thank you so much for opening.
