### ISSUE TITLE
Make builder Header embedable in other websites with headers

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#4103]
Currently some customers have already existing headers in their website, we should try to make the header to be blended into the canvas:

1. Option to hide Logo 
2. Option to Runs / Versions

**Comment by Myo78779** [comment]
> ### ⚠️COMMENT VISIBILITY WARNING⚠️
> Comments on closed issues are hard for our team to see. If this issue is continuing with the lastest stable version of Activepieces, please open a new issue that references this one.

### I’m trying to find
