### ISSUE TITLE
[BUG]: triggers in custom pieces does not show test step. 

### ISSUE THREAD

**Issue by kritan9** [activepieces/activepieces#4175]

**Comment by abuaboud** [comment]
Hi @kritan9 

Can you post a screenshot or way to reproduce?  It's working for me

**Comment by kritan9** [comment]
<img width="947" alt="Screenshot 2024-03-15 at 9 54 12 AM" src="https://github.com/activepieces/activepieces/assets/34961118/f2c6dbb1-99ca-44c9-b77f-ef3aeb14b7df">

@abuaboud 

I am using self-hosted activepieces version:0.20.3

custom piece from npm: @growthzilla/piece-proma@0.0.14

**Comment by kritan9** [comment]
@abuaboud , is there any update on this issue?

**Comment by abuaboud** [comment]
Hi @kritan9 I will try to give it a try soon, something weird cuz it's not happening with other pieces

**Comment by abuaboud** [comment]
Hi @kritan9 

I just tested it on latest version, It seems working, can you please check again?

**Comment by kritan9** [comment]
@abuaboud, I just tried this custom piece on https://cloud.activepieces.com and it still does not show test step for triggers.

**Comment by kritan9** [comment]
I tested the trigger with another custom npm piece "@martiallabs/piece-ampeco" I found on the internet, and had the same issue. It does not show test step for trigger.

**Comment by abuaboud** [comment]
Hi @kritan9 

That's so odd I just tested on cloud and it's working, Let me ask if any of the team can reproduce

![image](https://github.com/activepieces/activepieces/assets/1812998/4d64f838-0ea3-4d21-9a1f-82ef804316f1)

**Comment by kritan9** [comment]
@abuaboud , looks like you are testing it in the action section. If you use the proma piece as the first step i.e, trigger, I cannot see the test step. Can you check it for trigger?

**Comment by kritan9** [comment]
@abuaboud, have you checked this issue in the trigger step?

**Comment by abuaboud** [comment]
Hi @kritan9,

Sorry for the late reply. I think the issue lies in using a dependency on an old framework library which doesn't contain the metadata needed to test the trigger.

Could you please sync your fork, rebuild the piece, and publish it again? It should work.

For older pieces, we performed a database migration to backfill this data. However, if you freshly installed it, I believe it currently lacks any schema conversion to the new metadata.

Please let me know if that works.

**Comment by abuaboud** [comment]
I am closing this issue.  There should be validation on the framework version and enable automatic schema migration while installing the piece, but this is for another ticket.

If it doesn't work, please reopen the issue!
