### ISSUE TITLE
[BUG]: the code piece fails

### ISSUE THREAD

**Issue by saksham-procol** [activepieces/activepieces#4182]
referencing issue #4090 

I have a follow up question..
If i didn't sync the forked repo with the upstream, how did the dependency of the piece changed . Earlier approval piece 0.1.3 was working fine with app version 0.18.0 , and if i didn't update the code base at all, how did approval piece 0.1.3 suddenly stopped supporting app version 0.18.0

**Comment by abuaboud** [comment]
Here's the corrected version:

Good question! We will soon publish detailed documentation on the `AP_PIECES_SOURCE` variable.

Hi @saksham-procol, pieces are loaded directly from npmjs; they are not inside the Docker container. In each npm package, there is a minimum and maximum supported version.

You can find the packages here: https://www.npmjs.com/search?q=%40activepieces

Although the metadata is loaded from https://cloud.activepieces.com/api/v1/pieces, the actual execution is loaded from npm, You can also specify from configuration to load only from database and install piece by piece in "My Pieces" 

https://www.activepieces.com/docs/install/configurations/environment-variables (AP_PIECES_SOURCE) variable.

**Comment by abuaboud** [comment]
Good question! We will soon publish detailed documentation on the `AP_PIECES_SOURCE` variable.

Hi @saksham-procol, pieces are loaded directly from npmjs; they are not inside the Docker container. In each npm package, there is a minimum and maximum supported version.

You can find the packages here: https://www.npmjs.com/search?q=%40activepieces

Although the metadata is loaded from https://cloud.activepieces.com/api/v1/pieces, the actual execution is loaded from npm, You can also specify from configuration to load only from database and install piece by piece in "My Pieces" 

https://www.activepieces.com/docs/install/configurations/environment-variables (AP_PIECES_SOURCE) variable.
