### ISSUE TITLE
Facebook Leads[BUG]: the code piece fails

### ISSUE THREAD

**Issue by 4m0ses** [activepieces/activepieces#4193]
**Describe the bug**
The facebook lead pieces doesn't work for both on-prem and company hosted, seems to be a bug.

**To Reproduce**
Just search for facebook lead

![image](https://github.com/activepieces/activepieces/assets/99872145/b17f2a9d-3fd8-49c1-a84e-d2a1b9b8be2b)

**Comment by abuaboud** [comment]
Hi, Facebook leads is no longer available in our cloud due to this
https://community.activepieces.com/t/facebook-revoked-our-business-verification/25

Sorry for the issue.
