### ISSUE TITLE
Add Authentication for webhook piece

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#4195]
We should add a new static dropdown here with the three options: "None," "Basic Auth," and "Header Auth."

[Link to the code](https://github.com/activepieces/activepieces/blob/22dfb3c5a62c3e58161fd5aacef6c7097017def1/packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts)

Include dynamic props to display fields depending on the selected option in the static dropdown.

In the `run` method, we should return an empty array if the authentication is not correct to avoid triggering webhooks.

[Link to the specific line of code](https://github.com/activepieces/activepieces/blob/22dfb3c5a62c3e58161fd5aacef6c7097017def1/packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts#L33)

Reference:

[How to build pieces](https://www.activepieces.com/docs/developers/overview)

**Comment by abuaboud** [comment]
We should change the name of "Catch Request" to "Catch Webhook"

**Comment by pfernandez98** [comment]
Hi @abuaboud. I'm working on this but I have 2 issues: 

1. When I try to return an error or an empty array when the authentication is bad, the webhook keeps loading forever. 
2. I'm using dynamic properties for the fields to check (ex: when the user selects Header authentication, then I show the fields Header name and Header value). The thing is: Everytime I load the flow, the value for these fields is empty. This is pretty bad for users. 

Do you have any idea on how to fix this?

**Comment by abuaboud** [comment]
@pfernandez98 Sorry just saw this, can you open the PR, I think these will be fixed in the upcoming pr and i can take it from the draft pr!
