### ISSUE TITLE
[BUG]: Multi select dropdown

### ISSUE THREAD

**Issue by ldq1220** [activepieces/activepieces#4198]
I am customizing piece and want to create a multi-selection drop-down box using the following method
![image](https://github.com/activepieces/activepieces/assets/133664795/54666546-ccd9-4ef2-af5a-b0afad74d295)

But the way it looks on the interface
![image](https://github.com/activepieces/activepieces/assets/133664795/e4714c0b-b50a-496f-b0c6-2be563ede077)

I don't know how to solve, ask for help, I would be very grateful!（I am a Chinese whose English is not very good，Please forgive me）

**Comment by kishanprmr** [comment]
Hello @ldq1220 ,

If the options for a field are fixed, you should use the [StaticMultiSelectDropdown](https://www.activepieces.com/docs/developers/piece-reference/properties#static-multiple-dropdown). However, if your field depends on another field or is dynamic, you can utilize the [Dynamic MultiSelect Dropdown](https://www.activepieces.com/docs/developers/piece-reference/properties#multi-select-dropdown). For dynamic dropdowns, ensure to pass the auth variable to the function.

**Comment by ldq1220** [comment]
Hello @kishanprmr  

Thank you for your help. Just now you mentioned two kinds of requirements, mine is to obtain dynamic data and present options. I modified the code as follows:
![image](https://github.com/activepieces/activepieces/assets/133664795/a9738006-1fe1-4766-b3a8-1d31c2c8f124)

The page is rendered like this, with an error message like this.
![image](https://github.com/activepieces/activepieces/assets/133664795/86b5562f-d1d9-41ce-bf1b-b4bb9283cb41)

I have also tried to use your official example, the same way of writing, the same problem will occur. What's wrong with my code?

**Comment by kishanprmr** [comment]
@ldq1220 ,

Thank you for the details. Could you please try restarting the page to see if it works? Additionally, could you check if the provided endpoint for options is not throwing any errors?

Also you can use inbuilt **httpClient** for HTTP request.
```
import {
  httpClient,
  HttpMethod,
  AuthenticationType,
  HttpRequest,
} from '@activepieces/pieces-common';

// inside dynamic prop
const request:HttpRequest={
  method:HttpMethod.GET,
  url:'your-url',
  authentication:{
    type:AuthenticationType.BEARER_TOKEN,
    token:auth as string
  }
}

const response = await httpClient.sendRequest(request)
```

**Comment by ldq1220** [comment]
@kishanprmr 

Thank you for your answer. Yes, I have a restart project. I first run node tools/setup-dev.js and then run npm start for restart.
Failed to run turbowatch... Failed to run Turbowatch... Error: Command failed:  nx run-many -t build --projects=pieces-gm-dataset-serach --skip-nx-cache It seems that my gm-dataset-search piece was not loaded.

![image](https://github.com/activepieces/activepieces/assets/133664795/4b678492-423f-4579-a1e4-b60dc434e8cf)
Is that the reason? My piece creation process followed the document creation, I don't know what went wrong, I am too stupid.

**Comment by ldq1220** [comment]
@kishanprmr 

According to your prompt, this situation has occurred
![image](https://github.com/activepieces/activepieces/assets/133664795/d46621f3-9f84-4085-85e9-7afa0ec927a3)

**Comment by kishanprmr** [comment]
@ldq1220 ,

Sorry there was a typo in previous command. Please run ```npx nx run-many -t build --projects=pieces-gm-dataset-search --skip-nx-cache```

**Comment by ldq1220** [comment]
@kishanprmr 

According to your prompt, this situation has occurred
![image](https://github.com/activepieces/activepieces/assets/133664795/59941c67-391b-4608-ba6d-9f27c66cb456)

**Comment by kishanprmr** [comment]
@ldq1220 , 

Now try running the server using command ```npm start```.

**Comment by ldq1220** [comment]
@kishanprmr 
It still doesn't seem to work. The same compile error appears.
![image](https://github.com/activepieces/activepieces/assets/133664795/7a1d3689-da81-46dd-886a-5d6bbb98c26f)

And the place is also very strange, the use of the Property.MultiSelectDropdown options will quote us type error prompt,But the use of the Property. StaticMultiSelectDropdown wouldn't.
![image](https://github.com/activepieces/activepieces/assets/133664795/f8925b56-9ba6-4fdd-b4ad-9e74d5f3ee89)

**Comment by ldq1220** [comment]
```import { createAction, DropdownState, Property, PropertyContext } from '@activepieces/pieces-framework';
import { httpClient, HttpMethod, AuthenticationType, HttpRequest, } from '@activepieces/pieces-common';

import { datasetSerachAuth } from '../../'
import axios from 'axios';

export const dataserSerachAction = createAction({
  // auth: datasetSerachAuth,
  name: 'dataser-serach-action',
  displayName: '知识库',
  description: '选择要搜索的知识库',
  errorHandlingOptions: {
    continueOnFailure: {
      hide: true,
    },
    retryOnFailure: {
      hide: true,
    },
  },
  props: {
    keyWord: Property.ShortText({
      displayName: '关键词',
      required: true,
    }),
    dataset: Property.MultiSelectDropdown({
      displayName: 'dataset',
      description: 'select dataset',
      required: false,
      refreshers: ['auth'],
      options: async ({ auth }) => {
        if (!auth) {
          return {
            disabled: true,
            placeholder: 'Connect your account',
            options: [],
          };
        }
        let options
        await axios({
          method: 'GET',
          url: 'https://brain-api.ztxkol.com/api/web/dataset/all/with-qa-groups',
          headers: {
            Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnJvbUJpeiI6Im9yZyIsIndheSI6InNtc2NvZGUiLCJyb2xlSWRzIjpbMV0sImNvbXBhbnlJZCI6MSwiaWF0IjoxNzEwNzQxMzExLCJleHAiOjE3MTA5MTQxMTF9.fcqtFnWzadHOOOjHKb5rjo9UkNqEVPy7yFBh9lSmWko'
          }
        }).then(res => {
          console.log('red0---', res);
          options = res.data.result.map((item: { name: string; id: number; }) => {
            return { label: item.name, value: item.id }
          })
        })
        return {
          options,
        };
      },
    }),
    time: Property.DateTime({
      displayName: 'Date and Time',
      description: 'Select a date and time',
      required: true,
      defaultValue: '2023-06-09T12:00:00Z'
    })
  },
  async run(context) {
    // Action logic here
    const response: any = {
      keyWord: context.propsValue.keyWord,
      dataset: context.propsValue.dataset,
      time: context.propsValue.time,
    }
    context.run.stop({
      response: response,
    })
    return response
  },
});
```
Here's the code. Please take a look.
I just tried to use nx run-many -t build --projects=pieces-gm-dataset-serach --skip-nx-cache and this message appeared:
![image](https://github.com/activepieces/activepieces/assets/133664795/0acbfac9-09ad-407c-aae1-fac1c04e085b)

**Comment by kishanprmr** [comment]
@ldq1220 ,

Please use this code

```
dataset: Property.MultiSelectDropdown({
			displayName: 'dataset',
			description: 'select dataset',
			required: false,
			refreshers: ['auth'],
			options: async ({ auth }) => {
				if (!auth) {
					return {
						disabled: true,
						placeholder: 'Connect your account',
						options: [],
					};
				}
				// const request: HttpRequest = {
				// 	method: HttpMethod.GET,
				// 	url: 'https://brain-api.ztxkol.com/api/web/dataset/all/with-qa-groups',
				// 	authentication: {
				// 		type: AuthenticationType.BEARER_TOKEN,
				// 		token:
				// 			'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnJvbUJpeiI6Im9yZyIsIndheSI6InNtc2NvZGUiLCJyb2xlSWRzIjpbMV0sImNvbXBhbnlJZCI6MSwiaWF0IjoxNzEwNzQxMzExLCJleHAiOjE3MTA5MTQxMTF9.fcqtFnWzadHOOOjHKb5rjo9UkNqEVPy7yFBh9lSmWko',
				// 	},
				// };

				// const response = await httpClient.sendRequest(request);
				// return {
				// 	disabled: false,
				// 	options: response.body['result'].map((item: { name: string; id: number }) => {
				// 		return {
				// 			label: item.name,
				// 			value: item.id,
				// 		};
				// 	}),
				// };
				let options: { label: string; value: string }[] = [];
				await axios({
					method: 'GET',
					url: 'https://brain-api.ztxkol.com/api/web/dataset/all/with-qa-groups',
					headers: {
						Authorization:
							'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnJvbUJpeiI6Im9yZyIsIndheSI6InNtc2NvZGUiLCJyb2xlSWRzIjpbMV0sImNvbXBhbnlJZCI6MSwiaWF0IjoxNzEwNzQxMzExLCJleHAiOjE3MTA5MTQxMTF9.fcqtFnWzadHOOOjHKb5rjo9UkNqEVPy7yFBh9lSmWko',
					},
				}).then((res) => {
					console.log('red0---', res);
					options = res.data.result.map((item: { name: string; id: number }) => {
						return { label: item.name, value: item.id };
					});
				});
				return {
					disabled: false,
					options,
				};
			},
		}),
```

**Comment by ldq1220** [comment]
@kishanprmr 
Thank you very much for your tips, I have successfully run it. But here's a hint: An unexpected error occured please contact our support
![image](https://github.com/activepieces/activepieces/assets/133664795/6613d024-baea-4dd2-9936-1baf2d30e9e2)

Even if I changed to the normal return options, still can not
```
dataset: Property.MultiSelectDropdown({
      displayName: 'dataset',
      description: 'select dataset',
      required: false,
      refreshers: ['auth'],
      options: async ({ auth }) => {
        if (!auth) {
          return {
            disabled: true,
            placeholder: 'Connect your account',
            options: [],
          };
        }
        // const request: HttpRequest = {
        // 	method: HttpMethod.GET,
        // 	url: 'https://brain-api.ztxkol.com/api/web/dataset/all/with-qa-groups',
        // 	authentication: {
        // 		type: AuthenticationType.BEARER_TOKEN,
        // 		token:
        // 			'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnJvbUJpeiI6Im9yZyIsIndheSI6InNtc2NvZGUiLCJyb2xlSWRzIjpbMV0sImNvbXBhbnlJZCI6MSwiaWF0IjoxNzEwNzQxMzExLCJleHAiOjE3MTA5MTQxMTF9.fcqtFnWzadHOOOjHKb5rjo9UkNqEVPy7yFBh9lSmWko',
        // 	},
        // };

        // const response = await httpClient.sendRequest(request);
        // return {
        // 	disabled: false,
        // 	options: response.body['result'].map((item: { name: string; id: number }) => {
        // 		return {
        // 			label: item.name,
        // 			value: item.id,
        // 		};
        // 	}),
        // };
        // let options: { label: string; value: string }[] = [];
        // await axios({
        //   method: 'GET',
        //   url: 'https://brain-api.ztxkol.com/api/web/dataset/all/with-qa-groups',
        //   headers: {
        //     Authorization:
        //       'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnJvbUJpeiI6Im9yZyIsIndheSI6InNtc2NvZGUiLCJyb2xlSWRzIjpbMV0sImNvbXBhbnlJZCI6MSwiaWF0IjoxNzEwNzQxMzExLCJleHAiOjE3MTA5MTQxMTF9.fcqtFnWzadHOOOjHKb5rjo9UkNqEVPy7yFBh9lSmWko',
        //   },
        // }).then((res) => {
        //   console.log('red0---', res);
        //   options = res.data.result.map((item: { name: string; id: number }) => {
        //     return { label: item.name, value: item.id };
        //   });
        // });
        return {
          // disabled: false,
          options: [
            {
              label: 'Option One',
              value: '1'
            },
            {
              label: 'Option Two',
              value: '2'
            }
          ],
        };
      },
    }),
```

**Comment by kishanprmr** [comment]
After making changes to code you have to refresh the page in browser. Can you try it?

**Comment by ldq1220** [comment]
@kishanprmr 
Yes Yes Yes, I refreshed the browser and tried npm start to restart. All are invalid.
I also have a question about when the axios request I wrote in the run method was invoked. I don't see the corresponding request in the browser's network.

**Comment by ldq1220** [comment]
Control console There is such an error message:
![image](https://github.com/activepieces/activepieces/assets/133664795/542d1ec4-969c-4e10-ad89-0555d1a0e201)

**Comment by ldq1220** [comment]
@kishanprmr 

The terminal has an error message:
![image](https://github.com/activepieces/activepieces/assets/133664795/703fc9b0-58b4-4871-82ce-34fdbacadbd1)

**Comment by ldq1220** [comment]
@kishanprmr 

The terminal has an error message:
![image](https://github.com/activepieces/activepieces/assets/133664795/8e73dec2-9215-4cfd-ab66-346ecd13c59d)

**Comment by ldq1220** [comment]
Hello. @kishanprmr 

Thank you very much for your help yesterday. I have solved the problem. The reason is that the @activepieces/pieces-framework dependency is not installed in the package.json file. Maybe I am too stupid or think that the official will automatically install the @activepieces/pieces-framework dependency, which leads to limited thinking. I wonder if other people will have the same problem. (There is an old Chinese saying that important things should be said three times: Thank you, thank you, thank you)!!!

**Comment by kishanprmr** [comment]
@ldq1220 ,

I'm glad you solve the problem. If you have any further questions/doubts about developing pieces, you can join our [discrod server](https://discord.com/invite/2jUXBKDdP8) for help.

Thanks.
