### ISSUE TITLE
Docs Icon to Redirect to Docs

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#421]
**Is your feature request related to a problem? Please describe.**
Sometimes, I want to reach out for activepieces app documentation but there is no link inside the builder.

**Describe the solution you'd like**
A documentation icon somewhere on the sidebar that open specific app documentation in activepieces.

**Comment by AbdulTheActivePiecer** [comment]
How about we show it as a post fix to the input, and once clicked it shows the documentation link needed ? and we add another property to a piece action/trigger prop called "documentation" which will be an optional url property.
