### ISSUE TITLE
[BUG]: the code piece fails

### ISSUE THREAD

**Issue by cocobeach** [activepieces/activepieces#4215]
**Describe the bug**
Naming of files/Due diligence Warning in sh scripts: do-1-click-setup.sh is very dangerous: installed and launched and it would not stop on ctrl-c and proceeded to write zeros on 2 Terabytes of brand new SSD hard-drive

**To Reproduce**
1. Go to '../activepieces'
2. Run "do-1-click-setup.sh"
3. Watch the most amateurish script ever written run

**Expected behavior**
You need to WARN the user this is meant to be run on a Digital Ocean instance, you need to warn the user before proceeding writing 0s all over a brand new local hard-rive. As script of such low level, needs to be concerned with environment-wide implications before overwriting files and when you try to stop it, proceed anyway with sudo credentials ruining an otherwise pristine filesystem thinking it's in another place. Yes I should have known better, but you should have made it explicit this was for a third party installation and not to DO A 1 CLICK SETUP OF ACTIVEPIECES!
In 30 years of IT this must be the most inward-looking user-unconcerned development I have seen.

**Screenshots**
![Screenshot from 2024-03-19 12-24-24](https://github.com/activepieces/activepieces/assets/128893/ff00dda8-0bcb-4a32-861a-f31215cbf3bc)

**Additional context**
If whoever writes a file knows exactly what it does and where it is supposed to run, it is not possible for a user to suck it from his thumb, especially if it calls other scripts, in an otherwise well cornered framework like Activepieces, so you either write somewhere that this script is for DIGITAL OCEAN ONLY , and not just not with an initial "do" that is by far them most confusing thing ever, DO in English does not specifically mean Digital Ocean unless one is in the known.
Also, because I must say it, some people have SSDs and writing on it just for the sake of it it's a big no-no, leave alone now it needs reinstall to bare-meta. 

You MUST WARN THE USER OF WHAT IT IS GOING ON especially at such low levels requiring SUDO. You can't have .sh scripts that inject other .sh scrips in an unstoppable sequence and not warn the user, and if something is aborted, it skips to the next step of the script regardeless, instead warning and give the option of aborting. I tried to abort when it asked to overwrite an exiting file and said no, it did continue nevertheless ruining my HD, this is awful practice, you must revise that file ASAP and add the due warning and failsafes!!

I suggest this implementation for DigitalOcean-safe-1click-setup.sh

#!/usr/bin/env bash

echo "WARNING: This script is intended for use on a fresh Digital Ocean droplet."
echo "It will make significant changes to your system, including installing packages and modifying configurations."
echo "Running this script on a non-Digital Ocean machine or a machine with existing data and configurations may lead to unexpected consequences."
echo "Please ensure that you have read the script's documentation and understand its purpose and impact before proceeding."
echo ""
read -p "Are you sure you want to continue? [y/N]: " consent
if [[ $consent != [Yy] ]]; then
    echo "User declined. Exiting script."
    exit 1
fi

echo "Step 1: Updating system packages..."
sudo apt-get update

echo "Step 2: Installing necessary packages..."
sudo apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

echo "Step 3: Adding Docker repository and installing Docker..."
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

echo "Step 4: Cloning Activepieces repository..."
git clone https://github.com/activepieces/activepieces

echo "Step 5: Running Activepieces using Docker Compose..."
docker compose -f ./activepieces/docker-compose.yml up -d

echo "Step 6: Cloning marketplace-partners repository..."
git clone https://github.com/digitalocean/marketplace-partners

echo "WARNING: The following steps will modify your firewall rules using UFW (Uncomplicated Firewall)."
echo "This may impact existing firewall configurations and potentially expose your system to security risks."
echo "Please review the firewall changes carefully and ensure they align with your security requirements."
echo ""
read -p "Do you want to proceed with the firewall modifications? [y/N]: " firewall_consent
if [[ $firewall_consent == [Yy] ]]; then
    echo "Step 7: Configuring firewall using UFW..."
    ufw default allow outgoing
    ufw default deny incoming
    ufw allow ssh
    ufw allow 8080/tcp
    ufw enable
else
    echo "Skipping firewall modifications."
fi

echo "WARNING: The next step will run the '90-cleanup.sh' script from the marketplace-partners repository. It involves a security wipe-out and overwriting of your existing free space, for security reasons, in an attempt to crush potentially persisting sensitive data."
echo "Please review the contents of this script and ensure you understand its purpose and the changes it makes to your system. "
echo "Running cleanup scripts without proper understanding may lead to data loss or system instability."
echo ""
read -p "Do you want to run the '90-cleanup.sh' script? [y/N]: " cleanup_consent
if [[ $cleanup_consent == [Yy] ]]; then
    echo "Step 8: Running cleanup script..."
    ./marketplace-partners/scripts/90-cleanup.sh
else
    echo "Skipping cleanup script."
fi

echo "Step 9: Removing droplet-agent package..."
sudo apt-get purge -y droplet-agent

echo "WARNING: The next step will run the '99-img-check.sh' script from the marketplace-partners repository."
echo "Please review the contents of this script and ensure you understand its purpose and the changes it makes to your system."
echo "Running image check scripts without proper understanding may lead to unexpected consequences."
echo ""
read -p "Do you want to run the '99-img-check.sh' script? [y/N]: " img_check_consent
if [[ $img_check_consent == [Yy] ]]; then
    echo "Step 10: Running image check script..."
    ./marketplace-partners/scripts/99-img-check.sh
else
    echo "Skipping image check script."
fi

echo "Step 11: Clearing command history..."
history -c

echo "Setup complete!"

///I hope this helps!

**Comment by abuaboud** [comment]
Ouch, this wasn't meant to be used by anyone. It was intended to automate the building of a one-click app on DigitalOcean for submission for review, but we no longer do that.

Sorry, it's not documented anywhere. We thought that would be enough and deleted it from the codebase.

**Comment by cocobeach** [comment]
> Ouch, this wasn't meant to be used by anyone. It was intended to automate the building of a one-click app on DigitalOcean for submission for review, but we no longer do that.
> 
> Sorry, it's not documented anywhere. We thought that would be enough and deleted it from the codebase.

And it would otherwise be useful to setup Digital Ocean, no to be ran locally without warning s and without visibility, because at a glance it looks like an easy way to setup docker and activepieces, I should have known better but I got lazy, yet the damage is done.
Any chance you could tell me what it changed and how to revert it? Because I stopped it after it wrote 40 gigabytes of zeros on my HD, but I suppose it was meant to erase them too?

**Comment by abuaboud** [comment]
Hii @cocobeach 

I took look here -> https://github.com/digitalocean/marketplace-partners/blob/master/scripts/90-cleanup.sh

It seems delete the unused partition only, so in that case it shouldn't delete your existing data If i understand correctly.

**Comment by abuaboud** [comment]
Hi @cocobeach 

I am not sure I understand your question, but did you take look at docker compose https://www.activepieces.com/docs/install/options/docker-compose

It might answer your question, If not can you please explain more

**Comment by cocobeach** [comment]
> Hi @cocobeach
> 
> I am not sure I understand your question, but did you take look at docker compose https://www.activepieces.com/docs/install/options/docker-compose
> 
> It might answer your question, If not can you please explain more



> Hi @cocobeach
> 
> I am not sure I understand your question, but did you take look at docker compose https://www.activepieces.com/docs/install/options/docker-compose
> 
> It might answer your question, If not can you please explain more
The do_1click_setup.sh script that wrote zeros to my disk (90-cleanup.sh) and it was part of a larger setup process for digital Ocean that made significant changes to my system without proper warnings or consent. 
The script clones the marketplace-partners repository from GitHub and runs the 90-cleanup.sh and 99-img-check.sh scripts from that repository.
The contents and purpose of these scripts are not clearly specified in the provided script, so it's difficult to determine if they are specific to Activepieces or if they make broader system-wide changes.
And I ran it locally, because the script itself inject those 2 other sh in the end without warning...
