### ISSUE TITLE
Test trigger

### ISSUE THREAD

**Issue by ldq1220** [activepieces/activepieces#4278]
Test Trigger or Use Mock Data 
How can I test the input data successfully and have an output?
![image](https://github.com/activepieces/activepieces/assets/133664795/93b2161a-3edc-463b-a2d6-0c1fe9bb2f7a)

And can be obtained in the following piece
![image](https://github.com/activepieces/activepieces/assets/133664795/87361f83-ced8-4b6c-b9d4-90057e8bb00d)

My code is like this, I did not look up the relevant information in the official document, I am not good at writing, I do not know whether the writing is correct. Solve it. Thank you very much

```

import { createTrigger, TriggerStrategy, Property } from '@activepieces/pieces-framework';

export const sessionEntryTirgger = createTrigger({
    name: 'session-entry',
    displayName: '对话入口',
    description: '当收到一条新消息时触发',
    props: {
        text: Property.ShortText({
            displayName: '起始文本',
            required: true,
        }),
    },
    sampleData: {},
    type: TriggerStrategy.WEBHOOK,
    async onEnable(context) {
        // implement webhook creation logic
    },
    async onDisable(context) {
        // implement webhook deletion logic
        return
    },
    async run(context) {
        return [context.payload.body]
    }
})
```

**Comment by kishanprmr** [comment]
Hello @ldq1220 ,

If you are creating webhook trigger for custom piece, please refer [Trigger Documentation](https://www.activepieces.com/docs/developers/piece-reference/triggers/overview). You may need to implement **onEnable** and **onDisable** function based on your custom piece API.

**Comment by ldq1220** [comment]
Thank you.  @kishanprmr 

I will read the documentation carefully, plus if I want to implement such a feature. Must we improve onEnable and onDisable? Can I go to see the source files (packages/pieces/community) which of the sample of the trigger to learn?
![image](https://github.com/activepieces/activepieces/assets/133664795/f14c95ba-ffc5-4738-8a36-163bf2f1222c)

**Comment by kishanprmr** [comment]
@ldq1220 ,

You can check tally ,beamer and typeform pieces for trigger reference.

**Comment by ldq1220** [comment]
Good morning! @kishanprmr 

Yesterday's problem has been solved, thank you for reminding me. I just need this return data to meet my needs.

```
export const sessionEntryTirgger = createTrigger({
    name: 'session-entry',
    displayName: '对话入口',
    description: '当收到一条新消息时触发',
    props: {
        text: Property.ShortText({
            displayName: '起始文本',
            required: true,
        }),
    },
    sampleData: {},
    type: TriggerStrategy.WEBHOOK,
    async onEnable(context) { },
    async onDisable(context) { },
    async run(context) {
        return [{ text: context.propsValue.text }]
    },
    async test(context) {
        return [{ text: context.propsValue.text }];
    },
})
```

However, when I click Test flow to test, why does the flow get stuck in my custom piece and not continue?
![image](https://github.com/activepieces/activepieces/assets/133664795/cc53640e-5613-4e03-9c56-2d4c1019c9c2)

**Comment by kishanprmr** [comment]
@ldq1220 ,

Can you explain what is your use case for webhook trigger? As you want to return user provided text as output.

**Comment by abuaboud** [comment]
Hi @ldq1220 

I am closing this issue, please feel free to reopen if you have any further information.
