### ISSUE TITLE
[BUG]: HTTP Post piece errors out when it should not

### ISSUE THREAD

**Issue by Gaket** [activepieces/activepieces#4295]
**Describe the bug**
HTTP Post piece seems not to work as expected in some cases.

When a specific POST request is sent with this body via Active Pieces, it returns an error:

<img width="713" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/ba9ac4f7-fbb7-44c3-a84b-e0e8e006d4ba">

```
{
  "type": "TYPE_INDIVIDUAL",
  "fields": [
    "Uid",
    "Email",
    "user_shop_str",
    "user_userType_str",
    "user_shopId_str"
  ],
  "format": "FORMAT_CSV",
  "segmentId": "{{step_2['segmentId']}}",
  "timeRange": "{{step_2['timeRange']}}"
}
```

I created a code piece that seemingly does the same thing, but it works as expected:

```
export const code = async (inputs) => {
const response = await fetch('https://api.fullstory.com/segments/v1/exports', {
    method: 'POST',
    headers: {
      'User-agent': 'fs-postman/1.0',
      'Authorization': 'Basic na1.MTc4WEZRL2FydH--redacted',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      type: 'TYPE_INDIVIDUAL',
      format: 'FORMAT_CSV',
      segmentId: inputs.segmentId,
      timeRange: inputs.timeRange
    })
  });

  if (!response.ok) {
    throw new Error(`Error: ${response.statusText}`);
  }

  return await response.json();
};
```

The unexpected server response is:
```
{
  "response": {
    "status": 400,
    "body": {
      "error": "fs/services/dex/internal/searchexport/searchexport.go:580 [(*Service).buildExportFromRequest] invalid search export type: TYPE_INVALID"
    }
  },
  "request": {}
}
```

the step input is shown as:

```
{
  "url": "https://api.fullstory.com/segments/v1/exports",
  "body": "{\"type\":\"TYPE_INDIVIDUAL\",\"fields\":[\"Uid\",\"Email\",\"user_shop_str\",\"user_userType_str\",\"user_shopId_str\"],\"format\":\"FORMAT_CSV\",\"segmentId\":\"IfoSM8oaHf63\",\"timeRange\":\"{\"start\":\"2024-03-26T15:02:22.671Z\",\"end\":\"2024-03-27T15:02:22.671Z\"}\"}",
  "method": "POST",
  "headers": {
    "User-Agent": "fs-postman/2.0",
    "Content-Type": "application/json",
    "Authorization": "Basic na1.MTc4WEZRL2FydHVyQGdldHNxdWlyZS5jb206u8+by7/jPBiPrpdyKTOTUuv+tKQzeQjf4ZeKmFCfcOgu/FG8X8SK"
  },
  "failsafe": false,
  "queryParams": {}
}
```

Is it expected that it has all these backslashes?

**To Reproduce**
Unfortunately, that's a 3-rd party service requiring auth. Let me know how can I share a token to be able to actually call the code if it helps.

**Expected behavior**
Getting the expected answer, eg:
```
{
  "status": 200,
  "headers": {
    "content-length": "94",
    "content-type": "application/json",
    "date": "Tue, 26 Mar 2024 15:00:57 GMT",
    "x-grpc-status": "0",
    "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000, h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000",
    "via": "1.1 google, 1.1 google",
    "x-fullstory-data-realm": "na1",
    "connection": "close"
  },
  "body": {
    "operationId": "U0VBUkNIX0VYUE9SVDppUU5XMGN3RjU2QzlvaF9vTG93WFB2Y1JBNU9sN19CWGdWNk9ENmNHVXhB"
  }
}
```

**Screenshots**
<img width="1338" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/91458f7b-974a-4616-8e2a-a5c1618407f0">

**Additional context**
I believe the piece used to work in previous tens of runs and only recently started to behave like this. May it be a regression? It worked on March 26 and failed on March 27.

**Comment by kishanprmr** [comment]
Hello @Gaket,

Could you please try recreating the HTTP step, considering you are using version v0.3.10 for a piece where the latest version is v0.4.3?

**Comment by abuaboud** [comment]
Hi @Gaket 

I think I saw another issue might related to it, which is now fixed.

Please reopen if you still can reproduce on latest version.
