### ISSUE TITLE
[BUG]: my first example piece (Gelato) fails to run (followed docs)

### ISSUE THREAD

**Issue by ahmad-swanblocks** [activepieces/activepieces#4323]
I am trying to create Gelato piece following the documentation here: https://www.activepieces.com/docs/developers/building-pieces/create-action

Then I ran the app and when I create connection and click on save, it raises an error as below.
Any idea please?

![Screenshot 2024-04-01 122518](https://github.com/activepieces/activepieces/assets/165162455/8db9aaeb-bd0b-4ae5-bbaa-0d978e9c8e06)

![Screenshot 2024-04-01 122519](https://github.com/activepieces/activepieces/assets/165162455/1aff126b-e54a-4d21-afa5-6e73ed7d275a)

**Comment by abuaboud** [comment]
Hi @ahmad-swanblocks 

is `gelato` in your  AP_PIECES_DEV environment variable?

**Comment by ahmad-swanblocks** [comment]
Thank you for the quick reply..
Yes, and it shows in UI, but when I try to create the connection it fails,
is there any other config I miss although I exactly followed the steps and
also tried on another machine with another developer?

**Comment by ahmad-swanblocks** [comment]
@abuaboud 
I think most probably it is a cache issue as when looking at the logs while executing (validating) the connection, it generates cache files and then it looks for the modules in the cache (e.g. \dev\cache\sandbox\NONE-apId-2gQi7cJ0Nhm7H1tJaDRRS\node_modules\@activepieces\pieces-framework") and does not find them and also the same for @activepieces\pieces-gelato

And when I go to this path, I found it empty.
Is there a way to skip the cache? or is it a known issue with known solution? Thanks!

**Comment by ahmad-swanblocks** [comment]
@abuaboud  
**Update:**
I've tried it in GitHub CodeSpaces and it works fine, but when running the app locally or on dev containers it raises the error that I mentioned.

**Comment by abuaboud** [comment]
Hi @ahmad-swanblocks 

I think it's seems permission issue, can you please run it as admin, and that should fix it, or use dev container as they are reliable.

Closing this issue, please reopen If you still face the issue.
