### ISSUE TITLE
[BUG]: activepieces fails to start with a "ENTITY_NOT_FOUND" error

### ISSUE THREAD

**Issue by 0chroma** [activepieces/activepieces#4375]
When I try to start my existing activepieces service in kubernetes, it doesn't start with the following error:
```
Error: ENTITY_NOT_FOUND
    at Object.<anonymous> (/usr/src/app/dist/packages/server/api/main.js:1:717932)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:166:62)
{"code":"ENTITY_NOT_FOUND","params":{"message":"piece_metadata_not_found projectId=ul5YDkQzj99cNZnrItt40"}}}
```

**Comment by abuaboud** [comment]
Hi @0chroma,

Thank you for reporting the issue. Let me add the steps to reproduce:

1. Changed Docker Compose to an older version.
2. Spin it up and added a schedule trigger (or any polling trigger).
3. Upgrade to 0.22.0; the error is shown in the logs.

Now, since `0.22.0`, Activepieces start to save all piece metadata of npm packages locally, but there is an initial sync where it starts copying `https://cloud.activepieces.com/api/v1/pieces`

At the same time, it tries to run a polling trigger and doesn't find the piece metadata; this is where the error occurs.

But as far as I can see, the error has no other impact. Once the initial sync is done which is fast, everything will start working normally.

Can you please confirm the impact?

**Comment by 0chroma** [comment]
yup that sounds about right in terms of how to reproduce it.

I'm finding that the service isn't starting at all though, it just hangs. For what it's worth, I have the `AP_QUEUE_MODE` variable set to `MEMORY`, and I'm using `sqlite3` as my database. Everything else should be the default settings.

**Comment by abuaboud** [comment]
Hi @0chroma,

I haven't been able to reproduce the issue so far, but I believe I know what the problem might be. Could you please pull this image `ghcr.io/activepieces/activepieces:0.23.0-rc.2` and let me know if it works?

This way, we can promote it to a stable patch release.

Thank you,
Mo.

**Comment by askthedads** [comment]
x2 on this issue using the same configuration conditions. @abuaboud, I pulled your referenced image and it appears to have properly synced as logs indicate:

`{"level":30,"time":1712610670082,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-vtiger","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670084,"pid":8,"hostname":"activepieces","name":"@netlabsrl/piece-wachat","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670087,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-webflow","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670089,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-webhook","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670092,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-wedof","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670094,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-whatsable","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670097,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-woocommerce","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670100,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-wootric","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670103,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-wordpress","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670106,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-xero","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670108,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-xml","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670111,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-youtube","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670113,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-zendesk","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670115,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-zoho-crm","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670118,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-zoho-invoice","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610670120,"pid":8,"hostname":"activepieces","name":"@activepieces/piece-zoom","msg":"Syncing piece metadata into database"}
{"level":30,"time":1712610699427,"pid":8,"hostname":"activepieces","time":"2024-04-08T21:11:39.427Z","file":"localPieceCache","msg":"Syncing pieces"}
{"level":30,"time":1712610699429,"pid":8,"hostname":"activepieces","time":"2024-04-08T21:11:39.429Z","file":"localPieceCache","msg":"Syncing pieces"}
{"level":30,"time":1712610699430,"pid":8,"hostname":"activepieces","time":"2024-04-08T21:11:39.430Z","file":"localPieceCache","msg":"Syncing pieces"}
{"level":30,"time":1712610699431,"pid":8,"hostname":"activepieces","time":"2024-04-08T21:11:39.431Z","file":"localPieceCache","msg":"Syncing pieces"}
{"level":30,"time":1712610699441,"pid":8,"hostname":"activepieces","msg":"Syncing pieces from database"}
{"level":30,"time":1712610699442,"pid":8,"hostname":"activepieces","msg":"Syncing pieces from database"}
{"level":30,"time":1712610699443,"pid":8,"hostname":"activepieces","msg":"Syncing pieces from database"}
{"level":30,"time":1712610699443,"pid":8,"hostname":"activepieces","msg":"Syncing pieces from database"}
{"level":30,"time":1712610701353,"pid":8,"hostname":"activepieces","msg":"Adding 2 repeated flows to the queue manager."}
{"level":30,"time":1712610701353,"pid":8,"hostname":"activepieces","msg":"Adding 0 renew flows to the queue manager."}
{"level":30,"time":1712610701399,"pid":8,"hostname":"activepieces","msg":"Adding 0 flow runs to the queue manager."}
{"level":30,"time":1712610701401,"pid":8,"hostname":"activepieces","msg":"Activepieces ce Edition"}
{"level":30,"time":1712610702163,"pid":8,"hostname":"activepieces","msg":"Server listening at http://0.0.0.0:3000"}`

What would be the best approach for my image tag going forward? Would `:latest` be ok to switch back to? 

Cheers.

**Comment by abuaboud** [comment]
Hi @askthedads 

Yes, you can always switch back I suggest you to switch to specific version instead of latest. 

I am planning to do a release tonight.
