### ISSUE TITLE
Matrix Protocol Action/Trigger

### ISSUE THREAD

**Issue by imbev** [activepieces/activepieces#438]
[Matrix](https://matrix.org/) is a communication protocol with over 80 million users, typically used for chat. I request an action for sending messages to a room and a trigger for receiving messages in a room.

**Comment by imbev** [comment]
SDK for Typescript https://matrix.org/sdks/#matrix-bot-sdk

**Comment by theVJagrawal** [comment]
I can takeup on this. Can you please assign me this? I'm taking this as part of my academics. It'd be helpful. 
Thank You

**Comment by MyWay** [comment]
+1 for this!

**Comment by abuaboud** [comment]
Created piece with send message, I attached the PR it's not merged yet.

**Comment by nileshtrivedi** [comment]
@abuaboud I would love to see a trigger for incoming messages in a room. Because Matrix has bridges to many messaging apps, this would allow triggering from incoming message on many platforms in one go.
