### ISSUE TITLE
[BUG]: Error running npm run start

### ISSUE THREAD

**Issue by RuanFernandes** [activepieces/activepieces#4387]
**Describe the bug**
When i create a new piece with the default name that npm create-piece command, the project gets stuck here:
![image](https://github.com/activepieces/activepieces/assets/66513496/cc570b66-0111-47f3-930a-58dc816ee53a)

**To Reproduce**
1. Run npm run start
2. Run npm create-piece after the project is running
3. Enter the piece name
4. Continue with default package name (just hit return to confirm)
5. Run npm run start

**Expected behavior**
The project should run normal

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/66513496/4a994bab-5739-4dfc-8a27-ab3499f20f1d)
![image](https://github.com/activepieces/activepieces/assets/66513496/0dea7c86-1b4e-4d3d-a8fe-54b2fc39653f)

**Comment by RuanFernandes** [comment]
Reveting changes on nx.json and deleting the created piece fixes the problem, but then i can't create a new piece

**Comment by RuanFernandes** [comment]
Update: in deploy/pulumi, if we delete the package.json, the project runs fine ^^

thanks to @abuaboud that helped me on discord

**Comment by abuaboud** [comment]
Hi @RuanFernandes 

I added to to eslintrc ignore and updated the cli, Please reopen if you face this issue again.

I couldn't reproduce it but this pr should fix it.
