### ISSUE TITLE
[BUG]: Testing Steps stopped working after upgrade to 0.23.0

### ISSUE THREAD

**Issue by Procuria** [activepieces/activepieces#4407]
**Describe the bug**
--self hosted, dockerized--
After the upgrade to 0.23.0 testing steps stopped working. I already downgraded back to 0.22.0, but have now the same issue.
The flows itself are working, only _testing_ the steps is affected.
I don't get any error messages - neither in the Docker logs, nor in the Bulls Dashboard
I tried so far using the following pieces for testing - all of them are not working for me anymore:
- Matrix
- HTTP
- PULL from Storage 

Testing for payloads of incoming webhooks is working 

**To Reproduce**
1. Go to 'New Flow' 
2. Select a trigger
3. Add one of the above mentioned steps
4. See no feedback or error

**Expected behavior**
Testing of steps should be possible

**Screenshots**
Please see the attached screencast for an exemplary run. Testing the step does not work, the flow itself works. 
No output in docker logs or Bull UI.

https://github.com/activepieces/activepieces/assets/37988494/d038e484-8a9b-498e-abca-ffe1cc937bb3

**Comment by abuaboud** [comment]
Hi @Procuria,

Could you please check the console in the browser? It looks like a websocket issue.

How did you set up the reverse proxy for the website?

If you used nginx check out this.
https://www.activepieces.com/docs/install/setup-ssl

Thank you,
Mo.

**Comment by Procuria** [comment]
@abuaboud thank you very much for your precise and rocket fast support! 
That solved it! 
I always thought I had read the release notes thoroughly - must have missed the switch to websockets. 

[For those with the same issue]
I had this old NGINX config:

````
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Host $host;
proxy_pass http://127.0.0.1:8787;
```` 
After adjusting it to the following config everything works again:

````
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
proxy_pass http://127.0.0.1:8787;
````
