### ISSUE TITLE
Nextcloud support

### ISSUE THREAD

**Issue by muhdusama** [activepieces/activepieces#4434]
**Describe your usecase.**
Adding a PDF into a specific folder imports it as a PDF in Notion

**Describe alternatives you've considered**
I can see Google Drive has this feature, but trying to stay away from Google in terms of hosting files.

**Comment by abuaboud** [comment]
Hi @muhdusama 

Can you please open it in the feature requests in the community https://community.activepieces.com/c/feature-requests/9

I am closing this ticket, as we are tracking feature requests for pieces at the community.

Thank you,
Mo.
