### ISSUE TITLE
MongoDB Integration 

### ISSUE THREAD

**Issue by Bhargav79** [activepieces/activepieces#4457]
I’m trying to migrate from N8n to active pieces. I love N8n but I don’t like that they’re not open source. 
Your product is second best for self hosting and I’m really impressed in the trajectory of it.

Some of my workflows need mongoDB integration and I couldn’t find that integration in the docs. Is this in the roadmap?

**Comment by abuaboud** [comment]
Hi @Bhargav79,

Glad that you like Activepieces. Regarding MongoDB, you can use code pieces directly. It supports npm packages.

Another way is to develop a piece and contribute it. It should be relatively easy and fast to add MongoDB.

[Link to documentation](https://www.activepieces.com/docs/developers/building-pieces/create-action)

If you can't, maybe you can list the exact actions/triggers with their properties in this ticket. Contributors usually pick things up.

I am curious which part of n8n that you stopped liking. What triggered this migration?
