### ISSUE TITLE
[Piece Request] Add Perplexity Piece

### ISSUE THREAD

**Issue by hirowa** [activepieces/activepieces#4488]
**Describe your usecase.**
Perplexity could help us with AI automations that require current context.

**Describe alternatives you've considered**
Using a SERP or scraper, but the way perplexity lays out the results is way better and can include summaries, reducing costs.

**Comment by abuaboud** [comment]
Done its released now

**Comment by hirowa** [comment]
Amazing! Thank you!
@abuaboud
