### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by nidzamdotcom** [activepieces/activepieces#4506]
Path: /developers/building-pieces/start-building

"This tutorial will guide you through the process of creating a Gelato piece from how to prepare your development environment to contributing the piece.

When you finish this tutorial you will have a piece that has an action which fetches random icecream flavor and trigger which fetches new icecream flavor created."

where is the tutorial?

**Comment by abuaboud** [comment]
Hi @nidzamdotcom,

Good point. It's the section on the left sidebar, numbered from 1 to 7.

I've also made improvements to this page in this PR: https://github.com/activepieces/activepieces/pull/4509/files

Please check the new documentation and let me know what you think: https://www.activepieces.com/docs/developers/building-pieces/start-building

I am closing this PR as done. Feel free to reopen if your question is not answered.
