### ISSUE TITLE
Arbitrary date formats in Date Helper

### ISSUE THREAD

**Issue by SFoskett** [activepieces/activepieces#4538]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use custom date strings in my workflows, for example "September 24" or "2024", rather than the standard all-inclusive date strings. Right now I use a Text Helper to split a known string but this isn't optimal.

**Describe the solution you'd like**
I would like the option to enter arbitrary date formats in the Date Helper rather than just selecting from the dropdown list. For example I could enter "MMMM DD" or "YYYY".

**Describe alternatives you've considered**
I am currently using the included "MMMM DD YYYY" and splitting it using Text Helper to obtain these but that's 1-2 extra steps.

**Additional context**
I imagine we would need some kind of bounds checking to make sure the format is clean and correct.

**Comment by SFoskett** [comment]
Actually I see that Date Helper allows you to extract units, and this works in my use case. But it's still an extra step and the "Day" component (and presumably "Month") trim the leading zero all the time, making it difficult to put it back INTO a Date Helper. Regardless, it works and it exists so I will call this solved unless someone wants to simply allow arbitrary formats.

**Comment by abuaboud** [comment]
Hi @SFoskett 

I think your case works with format date in Date helper now, I see It supports `MMMM DD YYYY`

Marking this feature as complete.
