### ISSUE TITLE
Google Calendar - Allow defining custom color to new or update event action

### ISSUE THREAD

**Issue by ikus060** [activepieces/activepieces#4540]
**Describe your usecase.**
I want activepieces to automatically update the color of my google calendar base on some conditions.

For this reason, I'm requesting a new option in Google Calendar Piece to support definition of the event color.

In google it's possible to define the color of individual events like this:
![image](https://github.com/activepieces/activepieces/assets/921251/22f6a15f-3284-4381-84c4-4441153564db)

**Describe alternatives you've considered**
N/A

**Comment by abuaboud** [comment]
This is were contributed by @javix64 

https://github.com/activepieces/activepieces/pull/4572
