### ISSUE TITLE
[BUG]: Google Sheets trigger never fires

### ISSUE THREAD

**Issue by SFoskett** [activepieces/activepieces#4565]
**Describe the bug**
I am running a self-hosted implementation of ActivePieces and use New Row Added in Google Sheets as a trigger. Unfortunately, this trigger is never actually firing for me - I can Load Data successfully and every other aspect of the Connection seems fine, but it never triggers when I add a new row, either by hand or programmatically using ActivePieces. Perhaps there is a misconfiguration in my site, or perhaps there is a bug.

**To Reproduce**
I built a New Flow just to test this with a new, blank Google Sheets spreadsheet. Everything was kept extremely simple for testing - just a single tab, two columns, etc. And the Flow is just a New Row Added trigger and output to Slack to tell me it worked. Yet it never fires, even after waiting a day and adding a few more by hand and using another ActivePieces Flow.

**Expected behavior**
I would expect it would trigger the Flow within a few minutes of a new row being added.

**Additional context**
Perhaps the issue is that my instance is self-hosted and using port 8080? Or perhaps something is broken. I assume others are using this trigger.

**Comment by abuaboud** [comment]
Hi @SFoskett 

You need to setup a public accessible url, google only accept these links when registering the webhook.

I need to double check, https maybe is required for google

**Comment by SFoskett** [comment]
Thanks for the quick response! The URL does work but is not https so perhaps that is the issue. I would post it here but don't want to expose my instance...

**Comment by abuaboud** [comment]
@SFoskett Do you have domain that you can setup it behind reverse proxy?

**Comment by abuaboud** [comment]
I think Google only accepts HTTPS URLs, closing this issue 


Please reopen if you still have any questions
