### ISSUE TITLE
DIST Build Issue 

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#4569]
from a long for me only CLOUD AND DB source only work if i change it to FILE or DB there is only webhook app list is given,
As FILE loads according to the folder in DIST file but i can't see any pices in dist file,
Can you please help me to fix it as i am building a new pices and its showing up there @abuaboud

**Comment by abuaboud** [comment]
The intended way is to change it to a file and edit the AP dev pieces environment variable mention ed in the docs.


Does this work?

**Comment by abuaboud** [comment]
You can also trigger build manually, check out this

https://www.activepieces.com/docs/developers/building-pieces/create-action#:~:text=If%20the%20build%20fails%2C%20try%20debugging%20by%20running%20npx%20nx%20run%2Dmany%20%2Dt%20build%20%2D%2Dprojects%3Dgelato.%20It%20will%20display%20any%20errors%20in%20your%20code.

**Comment by abuaboud** [comment]
@PhoenixMystique Closing this issue, please reopen if it's not fixed.
