### ISSUE TITLE
Issue Webhook hit is not wokring 

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#4574]
There is an option for a webhook URL in the environment, and I have defined my webhook URL. Next, at the AP_frontend URL, I have defined my frontend URL. I was running it on Codespace, and the ports are public. However, when I hit it, it returns a 404 page not found error. I suspected that 'api/v1/webhooks' should be called with the backend API URL, but it also didn't work.
am i doing something wrong @abuaboud ?

**Comment by abuaboud** [comment]
Can you try with /api?

**Comment by PhoenixMystique** [comment]
The app created webhook url look like this :- https://**-4200.app.github.dev/api/v1/webhooks/Lf2CsZihYcP6AnzVSgBAt
@abuaboud

**Comment by abuaboud** [comment]
I will try to unify the experience  between development and production

Try without /API and port 3000 pn development mode it should work.


In the docker image we have built we created a reverse proxy from /API to port 3000 locally.

In the development environment , this proxy doesn't exist


Closing this issue, please reopen if it does not work or if you have any more questions
