### ISSUE TITLE
[BUG]: Documentation Error

### ISSUE THREAD

**Issue by tresero** [activepieces/activepieces#4575]
**Describe the bug**
In the https://www.activepieces.com/docs/install/troubleshooting#reset-password the table is user. Not users
Also, the database is database.sqlite, not database.sqlite3

This should be updated in the documentation

**Comment by tresero** [comment]
Also, resetting doesn't work. Constantly shows Invalid email or password

**Comment by abuaboud** [comment]
Hi @tresero 

Do you have multiple users in the same instance?

**Comment by tresero** [comment]
No, I just set it up.

**Comment by abuaboud** [comment]
Does your new hashed password starts with `$2b$`?

**Comment by tresero** [comment]
No $2y$

**Comment by abuaboud** [comment]
Try to use something like that to generate the password, I will check later about `$2y$', we use below library 
```ts
import bcrypt from 'bcrypt'
const SALT_ROUNDS = 10
const password = await bcrypt.hash('22@RandomPassword', SALT_ROUNDS)
console.log(password)
````
This above example output is `$2b$10$5ShTzYKNNtIx0ZccSXDn5.6uexFoaNEGqHPrAWzhv.cd26kpCGI7e`


Also Feel free to contribute for the docs: https://github.com/activepieces/activepieces/tree/main/docs

Let me know if it works.

**Comment by tresero** [comment]
Okay, that worked. I'll update the docs as well.
