### ISSUE TITLE
[BUG]: Slack Piece's Send message to a channel action does not show a list of channels 

### ISSUE THREAD

**Issue by Gaket** [activepieces/activepieces#4598]
**Describe the bug**
Slack Piece's Send message to a channel action does not show a list of channels and doesn't work as a result.

**To Reproduce**
Steps to reproduce the behavior (seems to be Slack-connection specific):
1. Create a new flow
2. Add a Slack piece v0.5.6 or v0.5.7
3. Set Send to channel action
4. Connect to a Slack account
5. Open the Choose a channel list
6. Wait for loading
7. See the "Throws an error, reconnect or refresh the page" error

**Expected behavior**
There is a list of different channels to send messages to

**Screenshots**
This is how it looks like:
<img width="331" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/02ad4441-e33e-435a-bc82-3d703e54f57e">

Permissions were given:
<img width="581" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/fa78ea87-2165-42be-b7ba-0559b5faa6b4">

**Additional context**

I have another Slack workspace and a personal ActivePieces account where it works well.

I have tried to delete and set the Slack connection again on the work account, it didn't help.

Other actions:
"Send message to a user" - work well
"Request approval in a channel" - errors out the same way.

I looked at the response of piece-slack request, looks like the permissions are fine:
```
"auth": {
        "description": "",
        "authUrl": "https://slack.com/oauth/v2/authorize?user_scope=search:read,users.profile:write",
        "tokenUrl": "https://slack.com/api/oauth.v2.access",
        "required": true,
        "scope": [
            "channels:read",
            "channels:manage",
            "channels:history",
            "chat:write",
            "groups:read",
            "groups:write",
            "reactions:read",
            "mpim:read",
            "mpim:write",
            "im:write",
            "users:read",
            "files:write",
            "files:read",
            "users:read.email"
        ],
        "type": "OAUTH2",
        "displayName": "Connection"
    },
```

The error seems to be coming from the 
https://cloud.activepieces.com/api/v1/pieces/options call:
```
{
    "disabled": true,
    "options": [],
    "placeholder": "Throws an error, reconnect or refresh the page"
}
```

The Active Pieces app was added to the required channel, it doesn't look like the issue is bound to it.

**Comment by Gaket** [comment]
Hi! Is there any way I can help providing logs without deploying the app myself? I don't have much JS/TS experience, but I can try.

**Comment by abuaboud** [comment]
Hi @Gaket 

Can you check the suggestion here and please let me know if it fixes the issue?

https://community.activepieces.com/t/slack-send-message-to-a-channel-no-channels-in-the-dropdown/4134/4

**Comment by Gaket** [comment]
Just in case, the same issue persists with "Send a message" action when I try to select a channel:
<img width="343" alt="image" src="https://github.com/activepieces/activepieces/assets/4466100/18706c32-e712-476d-9cbe-84267f33069c">

**Comment by abuaboud** [comment]
The piece was rewritten to use Skack SDK, I didn't see this issue recently.

Please reopen if you still can reproduce
