### ISSUE TITLE
How to disable sign up / registration on selfhosted instance ?

### ISSUE THREAD

**Issue by jasek5** [activepieces/activepieces#463]
HI 
I am using docker-compose variant of selfhosted this great project.

However I am unable to find how to disable the registration/signup - since I want use it alone or with limited users (family). Could you please make it more clear in quickstart tutorial ?

Also could you point me to right direction ?

Best regards

**Comment by abuaboud** [comment]
Hi @jasek5 

I will prioritize this task and add an environment flag, with proper documentation. I plan to release tonight along with some hotfixes.

Added to the sprint and will keep you updated there.

Best Regards.

**Comment by jasek5** [comment]
> Hi @jasek5
> 
> I will prioritize this task and add an environment flag, with proper documentation. I plan to release tonight along with some hotfixes.
> 
> Added to the sprint and will keep you updated there.
> 
> Best Regards.

Thank you very much!
I will try the new release tomorrow then :)

**Comment by abuaboud** [comment]
The version 0.2.5 has been released and sign up is disabled by default, except for the first user. 

The sign up feature can be enabled or disabled by using the AP_SIGN_UP_ENABLED configuration. For more information, please refer to the documentation at https://activepieces.com/docs/install/configurations.

Closing the issue, please let me know if you have any other questiond

**Comment by jasek5** [comment]
> 

So the current solution is that if I attempt to register account with registration disabled it shows that email is used?

**Comment by abuaboud** [comment]
@jasek5 It will show signing up is disabled.
