### ISSUE TITLE
[BUG]: MailChimp errors on Audience list

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#464]
**Describe the bug**
When I connect my MailChimp account, it shows an error for the audience list.

**To Reproduce**
1. Start a flow.
2. Choose MailChimp -> New Subscriber trigger.
3. Connect your account.
4. Choose an audience, this will show an error in the dropdown.

**Expected behavior**
The Audience dropdown should show the audiences in my account instead.

**Screenshots**
<img width="1680" alt="Screenshot 2023-02-04 at 15 46 14" src="https://user-images.githubusercontent.com/97393596/216774688-f4b88dd7-ee06-4328-87db-2253b2c01ef3.png">

**Additional context**
I tried this on cloud.activepieces.com

**Comment by abuaboud** [comment]
Fixed in 0.2.5
