### ISSUE TITLE
[BUG]: Custom Google OAuth fails with insecure warning

### ISSUE THREAD

**Issue by Startouf** [activepieces/activepieces#4665]
**Describe the bug**
When trying to set up a custom Oauth login for a google form connection, Google returns a security warning.

I tried setting up a custom OAuth app because when I use the regular Oauth screen, it does not find my Google forms stored on my shared Google Drive (and owned by the Shared google drive folder / the org)

**To Reproduce**
1. Add a google form connection
2. Click on 'I would like to use my own app credentials'
3. Add a client ID and client secret from a configured OAuth credentials on GCP

**Expected behavior**
There should not be a connection error

**Screenshots**
![Screenshot 2024-05-11 at 12 01 53](https://github.com/activepieces/activepieces/assets/7388889/814a730c-323e-4dca-8266-9ae0a5483985)

**Additional context**
Using the helm chart from there https://github.com/activepieces/activepieces/pull/4084 with docker image tagged 0.25.1

EDIT : It seems to be coming from the Redirect URL that is stuck at "https://activepieces.local:80/redirect". How can I tell activepieces I'm running under a different domain for OAuth login ?

**Comment by abuaboud** [comment]
This is related to your app, ask the admin of the Google Workspace to allow the app.

Please let me know if you have any other questions,

Mo
