### ISSUE TITLE
[BUG]: Formbricks self hosted API does not work

### ISSUE THREAD

**Issue by mantis64** [activepieces/activepieces#4668]
**Describe the bug**
I am trying to use my self hosted activepieces work with my self hosted formbricks.  

**To Reproduce**
1. Go to ' flows and try and connect formbricks'
2. I generate an API from my self hosted formbricks and insert into my activepieces'
However there is a connection error and I am unable to connect formbricks and activepieces together.  

**Expected behavior**
I would expect them to be able to connect.  However presumably it is trying to connect to the actual formbricks and not my domain.  

How can I make it work with my self hosted formbricks please?

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/pull/4676

**Comment by mantis64** [comment]
Still does not work under the latest build
