### ISSUE TITLE
[BUG]: the code piece fails (Trello triggers)

### ISSUE THREAD

**Issue by AshotZaqoyan** [activepieces/activepieces#4669]
**Describe the bug**
When attempting to use the "Card Moved to list" and "New Card" triggers in the Trello integration, after filling out all the required fields and clicking "Load date", the following error occurs:

"No results found
Testing data failed. Please ensure that the settings are correct or try again."

**To Reproduce**
1. Go to the Trello integration settings.
2. Select either "Card Moved to list" or "New Card" trigger.
3. Fill out all required fields.
3.1. Added a new card and/or moved to the selected list
4. Click "Load date".
5. Observe the error message.

**Expected behavior**
After clicking "Load date", the integration should successfully load the data without any errors and display the expected results.

**Screenshots**
<img width="716" alt="Screenshot 2024-05-12 at 16 28 56" src="https://github.com/activepieces/activepieces/assets/72438085/69ede8d0-3c59-4103-afb6-c4dd76d76ce7">

**Additional context**
Before clicking "Load date", I added a new card and/or moved to the selected list (several times)

**Comment by AshotZaqoyan** [comment]
@abuaboud Hello, when will this issue be resolved?

I used to use Zapier and now I've ditched it and am using activepieces, I'm moving my automations from Zapier to activepieces, I can no longer pay Zapier for a month, please resolve this issue as soon as possible.

**Comment by abuaboud** [comment]
Hi @AshotZaqoyan,

I'm not sure when we can do it, but feel free to open a pull request.

https://github.com/activepieces/activepieces/blob/main/packages/pieces/community/trello/src/lib/triggers/newCard.ts

It should be straightforward, and it's documented here. You can run the dev environment in Codespaces:

https://www.activepieces.com/docs/developers/development-setup/codespaces

and add Trello to the environment variables:

https://www.activepieces.com/docs/developers/development-setup/getting-started#pieces-development
