### ISSUE TITLE
Loop enhancements: x times loop & introduce variables

### ISSUE THREAD

**Issue by ahmad-swanblocks** [activepieces/activepieces#4725]
**Is your feature request related to a problem? Please describe.**
In many cases, I need to run a loop of x times and for every iteration I execute an action and I need to compare the result of the action with the result of the previous iteration. 

Basically, I have two limitations: 
1. I cannot run a loop of x times unless I have a list of x items 
2. I cannot save the result of the current iteration to compare it with the next one 

**Describe the solution you'd like**
1. Allow to configure a loop with x times and no need to run on a list
2. Introduce variables to store the iteration result

**Comment by abuaboud** [comment]
I would use the storage piece with run scope to store previous Iteration, for iterations we will expose the array in this issue [https://github.com/activepieces/activepieces/issues/6070](https://github.com/activepieces/activepieces/issues/6070)<br><br>Closing this ticket, to center the tracking, feel free to reopen
