### ISSUE TITLE
Multiexport (all flows)

### ISSUE THREAD

**Issue by LK511** [activepieces/activepieces#4732]
**Is your feature request related to a problem? Please describe.**
II have many flows and I want to migrate them. Now I need to export each flow separately and import one by one.

**Describe the solution you'd like**
I would like to be able to export and import all flows which I will select import will create their directory during import to keep the same structure as exported.

**Describe alternatives you've considered**
Publish SQL script, which will be able to export all flows in their current version and import them.

**Additional context**
This will help to make a backup before some upgrade etc.

**Comment by abuaboud** [comment]
Adding this, as It's related

https://github.com/activepieces/activepieces/issues/4475

**Comment by abuaboud** [comment]
Thank you for opening issue, Included more information in the above ticket.

Closing as duplicate :D
