### ISSUE TITLE
Help is broken

### ISSUE THREAD

**Issue by KlausSchaefers** [activepieces/activepieces#4741]
**Describe the bug**
The help sie is broken

**To Reproduce**
(https://www.activepieces.com/docs/getting-started/introduction)

![image](https://github.com/activepieces/activepieces/assets/7108416/b8b66c08-30eb-4197-a73a-3b12d9cb8d43)

**Comment by abuaboud** [comment]
Hi @KlausSchaefers 

It's working fine here, which browser do yo use?

**Comment by abuaboud** [comment]
Closing this issue, please reopen if you still have the issue.
