### ISSUE TITLE
[BUG]: Configuration AP_EXECUTION_DATA_RETENTION_DAYS in .env

### ISSUE THREAD

**Issue by LK511** [activepieces/activepieces#4746]
**Describe the bug**
The value in AP_EXECUTION_DATA_RETENTION_DAYS can't be higher than 30, when I set it to 90, AP is not able to start.

**To Reproduce**
Set value AP_EXECUTION_DATA_RETENTION_DAYS in .env to 90

**Expected behavior**
It will accept properly for more than 30 days.

**Comment by abuaboud** [comment]
Marked as bug, It seems break the cron job

```ts
     schedule: {
            type: 'repeated',
            cron: `0 * */${system.getNumber(SystemProp.EXECUTION_DATA_RETENTION_DAYS)} * *`,
        },
        ```

**Comment by abuaboud** [comment]
This should be fixed by @hazemadelkhalel 

The job will run hourly, this will be merged after react merge in this pr.

So closing this pr as complete.

https://github.com/activepieces/activepieces/pull/5401
