### ISSUE TITLE
Wordpress / Discord integration

### ISSUE THREAD

**Issue by korumera** [activepieces/activepieces#475]
**Is your feature request related to a problem? Please describe.**
No, it's a feature that's missing, not an issue by itself.

**Describe the solution you'd like**
The integration of WordPress into activepieces so that a connection between Discord and WordPress is possible. It should for instant be able to notify a channel when a new blog post has been posted, or when a new member joins WordPress.

**Comment by ashrafsamhouri** [comment]
Thanks @korumera. Discord -> Send Message is already there.
I added WordPress -> New Post trigger to the roadmap here: https://github.com/orgs/activepieces/projects/5/views/1
