### ISSUE TITLE
[BUG]: 后台设置语言为中文 时，提示404错误。

### ISSUE THREAD

**Issue by jememouse** [activepieces/activepieces#4751]
[BUG]: 

后台
设置语言为中文 时，提示404错误。

**Comment by jememouse** [comment]
<img width="734" alt="SCR-20240523-kqcn" src="https://github.com/activepieces/activepieces/assets/9528120/7bf8d947-0d39-4955-8311-6479532650e0">

**Comment by abuaboud** [comment]
Thank you for reporting that, We will take look!

**Comment by abuaboud** [comment]
Hi @jememouse 

It's fixed
