### ISSUE TITLE
[Error]: Web sockets errors

### ISSUE THREAD

**Issue by id535** [activepieces/activepieces#4762]
I am having exactly the issue described here:
https://github.com/activepieces/activepieces/issues/4407

I tried reinstalling with docker and docker compose, reverse proxied with caddy then with Nginx (as per your recommendation https://www.activepieces.com/docs/install/setup-ssl) , but still have these sockets errors and and that testing circle spins forever...

Firefox can’t establish a connection to the server at wss://wss/socket.io/?EIO=4&transport=websocket.

No errors in the docker logs

Tried multiple browers too. 

This is my Nginx config
```
server {
    listen 80;
    listen [::]:80;

    server_name domain.com www.domain.com;

    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name domain.com www.domain.com;

    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;

    location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**Comment by id535** [comment]
Nevermind. Just realised it was a bug that you patched already. Git pull kept saying already up to date so I never thought to debate that...

**Comment by id535** [comment]
Nevermind I have the issue in 0.26.1 too.

**Comment by abuaboud** [comment]
Hmm that's odd 

Did you try another browser? does it show same error?

**Comment by id535** [comment]
Yes, I usually use chrome and downloaded firefox just to double check it's not a browser issue...

**Comment by abuaboud** [comment]
@id535 Do you use cloudflare or other services that is on top of the reverse proxy?

**Comment by id535** [comment]
> @id535 Do you use cloudflare or other services that is on top of the reverse proxy?

No. Also, the second time, I installed it on a separate digitalocean droplet to have a clean installation. Docker was preinstalled already. Just installed activepieces, nginx and certbot for ssl certificate. And i followed DigitalOcean's tutorial for those, so I don't think I installed it wrong or anything like that. Apart from that, nothing else. 

I am using a subdomain though. Not sure if that makes any difference as I see you have activepieces on the cloud.activepieces.com subdomain too but I thought maybe there's some extra configurations I need to do for that?

**Comment by abuaboud** [comment]
To isolate the problem, whether it's from the load balancer or Activepieces, can you try to access Activepieces directly via the IP address of the droplet and attempt to run 'Test flow'? Does it work?

**Comment by id535** [comment]
@abuaboud The websocket errors dissapeared and i get a few of these: 
`[object Object]:1 Uncaught SyntaxError: Unexpected token '<' (at [object Object]:1:1)`
But the flow test works actually
Also, if you're referring to digitalocean load balancers I don't have one.

**Comment by jridevapp** [comment]
I am getting wss failed on a fresh deploy on render too. 

WebSocket connection to 'wss://wss/socket.io/?EIO=4&transport=websocket' failed:

**Comment by abuaboud** [comment]
The code was rewritten in 0.30.0, I can not see any issue

We will release it soon next week, feel free to reopen the issue if you still can reproduce it.


Thank you,
Mo
