### ISSUE TITLE
[BUG]: body must have required property 'projectId' - statusCode: 400

### ISSUE THREAD

**Issue by jasek5** [activepieces/activepieces#478]
**Describe the bug**
Aftefter pressing a button "Start building" of my first flow nothing happens.
In logs of the backend there is an error message:
```json
[14:54:37 UTC] INFO: body must have required property 'projectId'
    reqId: "req-22"
    res: {
      "statusCode": 400
    }
    err: {
      "type": "Error",
      "message": "body must have required property 'projectId'",
      "stack":
          Error: body must have required property 'projectId'
              at defaultSchemaErrorFormatter (/usr/src/app/node_modules/fastify/lib/context.js:107:10)
              at wrapValidationError (/usr/src/app/node_modules/fastify/lib/validation.js:131:17)
              at validate (/usr/src/app/node_modules/fastify/lib/validation.js:111:12)
              at preValidationCallback (/usr/src/app/node_modules/fastify/lib/handleRequest.js:92:18)
              at handler (/usr/src/app/node_modules/fastify/lib/handleRequest.js:76:7)
              at /usr/src/app/node_modules/fastify/lib/contentTypeParser.js:191:9
              at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
              at done (/usr/src/app/node_modules/fastify/lib/contentTypeParser.js:185:14)
              at Parser.defaultJsonParser [as fn] (/usr/src/app/node_modules/fastify/lib/contentTypeParser.js:291:5)
              at IncomingMessage.onEnd (/usr/src/app/node_modules/fastify/lib/contentTypeParser.js:270:27)
      "statusCode": 400,
      "validation": [
        {
          "instancePath": "",
          "schemaPath": "#/required",
          "keyword": "required",
          "params": {
            "missingProperty": "projectId"
          },
          "message": "must have required property 'projectId'"
        }
      ],
      "validationContext": "body"
    }
[14:54:37 UTC] INFO: request completed
    reqId: "req-22"
    res: {
      "statusCode": 400
    }
    responseTime: 1.396209955215454
```
**To Reproduce**
1. Go to Flows
2. Click on Start buildings -> the button starts the loading animation, but nothing happens.
3. show logs od backend container (ie. docker container logs [OPTIONS] CONTAINER or kubectl logs <POD NAME> -n <NAMESPACE>)
4. See the error

**Expected behavior**
1. Go to Flows
2. Click on Start buildings
3. I am redirected on flow canvas

**Screenshots**
ERROR behaviour
![2023-02-05-160224_screenshot](https://user-images.githubusercontent.com/12669491/216827579-54ff24ad-c5a0-4068-b73b-b28e2bd4d0bb.png)

EXPECTED behaviour:
![image](https://user-images.githubusercontent.com/12669491/216827560-4ff85453-356b-40fc-8476-486bb2aa6aa0.png)

**Additional context**
images: 

activepieces/backend:0.2.5
activepieces/frontend:0.2.7
postgres:14
redis:7.0.7

**Comment by jasek5** [comment]
I can confirm that **image: activepieces/backend:0.2.12** works as expected, but it does not contain signup/registration disable feature.

**Comment by jasek5** [comment]
If I upgrade from **backend:0.2.12** to **backend:0.2.5** error behaviour is back and I can not even open existing flow/collections/projects etc..

**Comment by abuaboud** [comment]
Apologies for the confusion. 

The backend:0.2.5 is older compared to backend:0.2.12. 

The current version for docker compose is backend:0.2.13 and frontend:0.2.8.

I will take this feedback and propose to keep the overall version sync with backend and frontend.

 Let me know if these versions work for you. You can find the updated version on the following link: https://github.com/activepieces/activepieces/blob/main/docker-compose.yml

**Comment by jasek5** [comment]
Uff my bad - I guess that 400 was on brain :D thank you for your help and politeness

**Comment by jasek5** [comment]
> Apologies for the confusion, Version `0.2.5` is just overall version for activepieces.
> 
> The backend:0.2.5 is older compared to backend:0.2.12.
> 
> The current version for docker compose is backend:0.2.13 and frontend:0.2.8.
> 
> I will take this feedback and propose to keep the overall version sync with backend and frontend.
> 
> Let me know if these versions work for you. You can find the updated version on the following link: https://github.com/activepieces/activepieces/blob/main/docker-compose.yml

Yep these versions works as expected
