### ISSUE TITLE
[BUG]: dropdown list keeps loading

### ISSUE THREAD

**Issue by ahmad-swanblocks** [activepieces/activepieces#4793]
**Describe the bug**
When I create a simple dropdown list with static values in some action and then add the action to the workflow using the workflow designer, the list keeps loading even if the values are static (not loaded from external APIs). Sometimes the values are loaded but after a long time.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/165162455/edeb20b6-5505-49bd-9df1-87bdd1899ac2)

**Code:**

```
  paymentType: Property.Dropdown({ 
    displayName: 'Payment Type',
    description: 'Select payment type (optional)',
    required: false,
    refreshers: [],
    options: async () => {
      return {
        options: [
          { value: 1, label: 'Cash' },
          { value: 2, label: 'Credit' },
        ],
      };
    },
  })
```

**Comment by abuaboud** [comment]
Can you please try using Static Dropdown here.

https://www.activepieces.com/docs/developers/piece-reference/properties#static-dropdown


And Is there any error logs in the backend?
