### ISSUE TITLE
[BUG]: 0.26.1 crashes with "TypeError: Cannot read properties of undefined (reading 'endsWith')" on a fresh install

### ISSUE THREAD

**Issue by shapirus** [activepieces/activepieces#4802]
**Describe the bug**
I am getting the following exception in the logs on any HTTP request to freshly deployed AP 0.26.1 instance:

```
{"level":50,"time":1716898740962,"pid":8,"hostname":"activepieces-576c7d9554-88ctf","msg":"[errorHandler]: {}"}
{"level":50,"time":1716898740962,"pid":8,"hostname":"activepieces-576c7d9554-88ctf","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'endsWith')","stack":"TypeError: Cannot read properties of undefined (reading 'endsWith')\n    at /usr/src/app/dist/packages/server/api/main.js:1:800006\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:169:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:165:16)\n    at t.getServerUrl (/usr/src/app/dist/packages/server/api/main.js:1:799446)\n    at Object.<anonymous> (/usr/src/app/dist/packages/server/api/main.js:1:830962)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:169:75\n    at new Promise (<anonymous>)"},"msg":"Cannot read properties of undefined (reading 'endsWith')"}
```

Decoded json for the reader's convenience:

```
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at /usr/src/app/dist/packages/server/api/main.js:1:800006
    at Generator.next (<anonymous>)
    at /usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:165:16)
    at t.getServerUrl (/usr/src/app/dist/packages/server/api/main.js:1:799446)
    at Object.<anonymous> (/usr/src/app/dist/packages/server/api/main.js:1:830962)
    at Generator.next (<anonymous>)
    at /usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
```

**To Reproduce**
1. Try to access a freshly deployed instance of AP. See deployment details below.

**Expected behavior**
No crashes.

**Additional context**
This is deployed in Kubernetes.

Image: `ghcr.io/activepieces/activepieces:0.26.1`

Environment inside the actual pod (complete list of variables starting with `AP_`):

```
AP_FRONTEND_URL=https://activepieces-dev.zzz.yyy/
AP_POSTGRES_USERNAME=activepieces_dev
AP_POSTGRES_PASSWORD=xxx
AP_POSTGRES_DATABASE=activepieces_dev
AP_ENCRYPTION_KEY=xxx
AP_JWT_SECRET=xxx
AP_REDIS_PORT=6379
AP_ENVIRONMENT=dev
AP_TELEMETRY_ENABLED=false
AP_REDIS_HOST=redis
AP_POSTGRES_HOST=xxx
AP_API_KEY=xxx
AP_POSTGRES_PORT=5432
```

edit: all the secret values substituted with `xxx` are 64-character long strings randomly composed of the `[a-zA-Z0-9]` character set.
edit2: regenerating the secrets using the same method as the one used in `tools/deploy.sh` and recreating the database did not solve the issue. I thought maybe it didn't like my strings that had characters outside of `[a-z0-9]`, but no.

Redis version is 7.2. Postgres version is 14.7.

Web requests path:

Client -> AWS NLB -> k8s node -> Nginx ingress controller -> k8s svc routing to the AP pod -> AP's nginx -> AP backend server listening on port 3000.

**Comment by abuaboud** [comment]
Hi, You are running AP in development mode, please specify `AP_WEBHOOK_URL`

I think the long term we should remove webhook url and only use frontend url.

Closing this as completed, please reopen if it doesn't fix your issue.

**Comment by abuaboud** [comment]
You know this actually no longer needed as there is reverse proxy on dev environment for /api to redirect for an api

Please pull latest from main, I removed the variable

https://github.com/activepieces/activepieces/pull/4885
