### ISSUE TITLE
[BUG]: Storing Sample data Inside flow causing unsaved changes error. [Scooping]

### ISSUE THREAD

**Issue by epavanello** [activepieces/activepieces#4811]
**Describe the bug**
When I generate Sample data for a step (Mandatory to have test data for the next steps), for some pieces, it crashes.
I found that for example "Image to base64" complete, but the frontend seems that lost connection, as you can see from that screenshot.

**To Reproduce**
1. Generate an image from openai
2. Convert the url image to base64
3. Test the step to have sample data

**Expected behavior**
In this case there should be no errors.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/47756116/e1cc8bb4-01b4-43c5-87f6-151078fd88bf)

**Comment by abuaboud** [comment]
Hi @epavanello 

Which version are you using? How large is the image?

**Comment by epavanello** [comment]
Hi @abuaboud, I'm using the last version deployed on prem (0.26.1)

**Comment by abuaboud** [comment]
How large is the image? I think the reason is the sample data is large

**Comment by epavanello** [comment]
@abuaboud probably that's the reason, it's a base64 version of a 1024x1024 image, but I think that the platform should handle correctly this case without stop working.
When the problem occurs, I'm not able to save the flow anymore and the test data is lost

**Comment by eduinlight** [comment]
We have the same issue calling an endpoint with a large response.

**Comment by abuaboud** [comment]
Marked as bug and we will try to improve this in upcoming sprints

**Comment by anasaijaz** [comment]
Is this still open? I mean this bug is really critical. I am not able to get Image response from any API even few KBs are causing error.

**Comment by xbiggyl** [comment]
I'm having the same problem getting an ogg file from an HTTP GET request. I just can't find a way around it.

**Comment by abuaboud** [comment]
This is now fixed in version >= 0.34.2
