### ISSUE TITLE
[BUG]: GoHighLevel OAuth2 connection fails

### ISSUE THREAD

**Issue by kishanprmr** [activepieces/activepieces#4910]
**Describe the bug**
The OAuth2 connection for GoHighLevel is encountering an error, displaying: "No integration found with the ID: 6613f44dffca6b9e436e58a3."

**To Reproduce**
1. Select any action from GoHighLevel piece.
2. Click on **New Connection -> Connect**.
3. See the error.

**Expected behavior**
The OAuth2 connection should establish successfully.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/135701940/8b8d6f77-88a6-4428-a862-b0764a8ef7da)

**Comment by M2KDevelopments** [comment]
I was getting the same issue. How I solve mine is by changing the domain of the OAuth request url from 
https://marketplace.gohighlevel.com/oauth/chooselocation to 
https://marketplace.leadconnectorhq.com/oauth/chooselocation

Apparently if you is set your as White label you should use **leadconnectorhq**. 

I saw this on Highlevel's official [documentation](https://highlevel.stoplight.io/docs/integrations/a04191c0fabf9-authorization): 
https://highlevel.stoplight.io/docs/integrations/a04191c0fabf9-authorization

I hope this helps.

**Comment by RobertCekay** [comment]
I was seeing the same error and I just needed to set my app to private.

**Comment by M2KDevelopments** [comment]
Thanks for the report. Will run thorough tests and get it updated as soon
as I can.

**Comment by juanuribe-creator** [comment]
> Gracias por el informe. Haré pruebas exhaustivas y lo actualizaré lo antes posible.
> […](#)
Pudiste verlo amigo?
