### ISSUE TITLE
[Dynamic template data] Not possible to parse boolean or number values

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#4922]
Apologies if I've missed something here but from what I can tell it isn't possible to parse booleans or numbers anywhere dynamic JSON data is entered e.g with the Data Mapper piece.

The workaround is to parse all values as strings or use a code piece but just wondering if there's a built in way to handle this as the docs are empty and it seems too obvious to miss.

E.g. 

Data Mapper

![image](https://github.com/activepieces/activepieces/assets/838788/08c19b51-e306-4ee6-a83b-f19285b543f3)

Or SendGrid

![image](https://github.com/activepieces/activepieces/assets/838788/956fcf00-5edc-4454-8b0b-6684faf1275b)

**Comment by abuaboud** [comment]
Anything between the curly brackets {{ }} is Javascript, feel free to use built in js functions like Number.parse and Math.max 

It works well in data mapper piece

**Comment by GFoley83** [comment]
I can't believe I didn't realise that! Is that documented anywhere Abuaboud?
