### ISSUE TITLE
[BUG]: issue with docker

### ISSUE THREAD

**Issue by mubasharrasheed** [activepieces/activepieces#4925]
**Describe the bug**
I'm having mac and I just run docker compose -f docker-compose.dev.yml -p ap up and I see this error:

ap  | sh: 1: cross-env-shell: not found
ap exited with code 127

**To Reproduce**
1. Clone repo
2. Run sh tools/deploy.sh
3. Run docker compose -f docker-compose.dev.yml -p ap up

**Expected behavior**
Start running the application

**Comment by abuaboud** [comment]
Hi @mubasharrasheed,

The `docker-compose.dev.yml` file was for setting up the development environment, but it is no longer supported. Sorry for the confusion; I have removed it from the repository.

Please refer to the documentation for setting up the development environment using Dev Containers or a local development environment: [Development Setup](https://www.activepieces.com/docs/developers/development-setup/getting-started).

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/pull/4928
