### ISSUE TITLE
Revamp Code Editior

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#4942]
**Describe the bug**

- Set Runtime Option in The Code (Javascript / TypeScript) depend on execution mode.
- The Console / Output is not copy-able
- Clearer error on the compilation.
- The output / console take full size when switching from index.ts to package.json

**Comment by abuaboud** [comment]
Check the following:
https://activepieces.slack.com/archives/C078QLFKM0R/p1718627202572999

**Comment by BharathKumar2326** [comment]
@abuaboud I want to tackle this issue, although I'm new to the OSS contributions can you assign and help me on how to achieve this?
