### ISSUE TITLE
[BUG]: HTTP Response - No longer possible to set a response that isn't JSON

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#4956]
**Describe the bug**
I'm trying to return basic HTML as a HTTP response, which used to work. The `Content-Type` is being respected (as per #3052) but somewhere along the way it seems that the Response field will now only accept valid JSON. Using HTML , text etc. will result in the HTTP response being empty/invalid.

**To Reproduce**
Create a new flow with webhook and http response pieces
Add a `Content-Type` header with `text/html` as the value
Click the Dynamic value button at the end of the Response field to turn it into a text box
Add some text or HTML
Publish and call the webhook url with `/sync` then view response in Chrome Dev Tools, Postman etc. 
Or just test the HTTP piece and see that there's no `body` output (as shown in screenshot below)

**Expected behavior**
The response field should allow values other than JSON

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/838788/c5555acb-ca05-4bb7-a69f-470c12aeee82)

**Comment by abuaboud** [comment]
Hi @GFoley83 

@kishanprmr can you please take look soon :D

**Comment by kishanprmr** [comment]
working on it.

**Comment by abuaboud** [comment]
Thank you @kishanprmr 

It's now working for me, @GFoley83 Please upgrade to latest version of the piece (You need to remove / add the step), the instance usually sync new versions in hourly basis

**Comment by GFoley83** [comment]
Working perfectly now. Thank you very much @kishanprmr & @abuaboud.
