### ISSUE TITLE
[BUG]: Continue on Failure for Extract Text from PDF not working

### ISSUE THREAD

**Issue by dwahdany** [activepieces/activepieces#4994]
**Describe the bug**
I cannot click the button for _Continue on Failure_ for the _Extract Text_ action from PDF.

**To Reproduce**
1. Click the button _Continue on Failure_
![image](https://github.com/activepieces/activepieces/assets/86673488/57ed8450-5f5e-4062-9da4-1a5b125fc16e)
2. It reverts itself

**Expected behavior**
It should enable the option and continue on failure

**Comment by abuaboud** [comment]
This issue should no longer exist in 0.30.0, please test on a main branch or cloud or 0.30.0 as it will be released next week.

Thank you,
Mo
