### ISSUE TITLE
Replace Redis with Valkey?

### ISSUE THREAD

**Issue by nileshtrivedi** [activepieces/activepieces#5005]
Redis [switched to a source-available license](https://redis.io/blog/redis-adopts-dual-source-available-licensing/) some time ago. [ValKey](https://github.com/valkey-io/valkey) has emerged as a [prominent](https://devops.com/valkey-is-rapidly-overtaking-redis/) alternative to Redis.

I think ActivePieces should switch to ValKey as its dependency in the [docker-compose.yml](https://github.com/activepieces/activepieces/blob/main/docker-compose.yml) ?

**Comment by abuaboud** [comment]
Hi @nileshtrivedi 

It's interesting, but we will have to take look for the deployment options and If the library are compatible

**Comment by derTuca** [comment]
Valkey is basically a fork of the Redis codebase before they've changed their license so it should be compatible, juding from my work with it on other projects.

**Comment by abuaboud** [comment]
We depend on BullMq for queues, Currently, there are no plans for them to support Valley nor do we have the capacity to write our own at this time.


BullMq is still compatible with older versions, and the new license only affects cloud providers at this moment.

I am closing this issue as not planned at this moment
