### ISSUE TITLE
Data Summarizer  Piece 

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#5017]
**Describe the Bug**

Each action should accept an array of fields for processing.

**Actions and Requirements:**

1. **Count Uniques**
   - The user can specify multiple fields to count unique values.

2. **Find Maximum**
   - The user can specify multiple fields to find the maximum values.

3. **Find Minimum**
   - The user can specify multiple fields to find the minimum values.

4. **Calculate Sum**
5. **Calculate Average**
   - The user can specify a single numeric field to calculate the average.
   - A note should be added to inform the user how to handle null values in this calculation.

**Comment by tahboubali** [comment]
hello
