### ISSUE TITLE
[BUG]: Sample Data Fails to generate

### ISSUE THREAD

**Issue by IIuwuII** [activepieces/activepieces#5018]
**Describe the bug**
Sample Data fails to generate after extended wait. 

**To Reproduce**
1. Go to AskChatGPT
2. Click on Generate Sample Data
4. The sample data is not generated

**Expected behavior**
After pressing Generate Sample Data, the sample data is generated and the user is able to continue creating the flow.

**Screenshots**

Uploading Screen Recording 2024-06-30 at 11.37.43 PM.mov…

**Additional context**

**Comment by IIuwuII** [comment]
Uploading Screen Recording 2024-06-30 at 11.37.43 PM.mov…

**Comment by kishanprmr** [comment]
Hello @IIuwuII , Can you please provide screenshots/configuration for Ask ChatGPT step in your flow?

**Comment by IIuwuII** [comment]
@kishanprmr  Absolutely, thank you for the assist!

Essentially, when using the AskChatGPT or OpenRouter Pieces and attempting to generate sample data, the Generate Sample Data never loads and just spins continuously.

<img width="1512" alt="image" src="https://github.com/activepieces/activepieces/assets/61036533/3c9345aa-1dd7-4ea0-8c63-1b89109cd258">

<img width="1512" alt="image" src="https://github.com/activepieces/activepieces/assets/61036533/dfe25099-8424-4803-aba9-21e71d06ee40">

<img width="1512" alt="image" src="https://github.com/activepieces/activepieces/assets/61036533/340ec64b-1cc7-4ecd-bdfb-71470d8e4d4c">
