### ISSUE TITLE
[BUG]: the documentation search feature appears to be broken in firefox

### ISSUE THREAD

**Issue by dprice-andros** [activepieces/activepieces#5044]
**Describe the bug**
Clicking on the search text box in firefox on a page such as https://www.activepieces.com/docs/install/architecture/workers does not work. No searching is possible.

**To Reproduce**
1. Install firefox
2. navigate to https://www.activepieces.com/docs/install/architecture/workers
3. try clicking search box at the top

**Expected behavior**
I expected the search box to get focus and allow me to type some text

**Additional context**
- it does work in chrome - so I can work around it
- it seems to throw the error (in the console):
> NotSupportedError: Element.attachShadow: Unable to re-attach to existing ShadowDOM

**Comment by abuaboud** [comment]
Hi @dprice-andros 

It's seem working for me now, Do you still have this issue? If yes please reopen the issue I will forward it to mintlify
