### ISSUE TITLE
[BUG]: cannot advance past sign up screen

### ISSUE THREAD

**Issue by joshsalvi** [activepieces/activepieces#5048]
Using the latest docker image in unraid. As stated above. 

Logs:

{"level":30,"time":1719929440194,"pid":8,"hostname":"ecc6ffa204fc","name":"seedDevData","msg":"skip: not in development environment"}
{"level":30,"time":1719929440247,"pid":8,"hostname":"ecc6ffa204fc","name":"RedisSystemJob#upsertJob","jobName":"trigger-data-cleaner","msg":"Upserting job"}
{"level":30,"time":1719929440249,"pid":8,"hostname":"ecc6ffa204fc","name":"RedisSystemJob#setJobHandler","jobName":"trigger-data-cleaner","msg":"Setting job handler"}
{"level":30,"time":1719929440270,"pid":8,"hostname":"ecc6ffa204fc","time":"2024-07-02T14:10:40.270Z","msg":"Syncing pieces"}
{"level":30,"time":1719929441195,"pid":8,"hostname":"ecc6ffa204fc","name":"RedisSystemJob#upsertJob","jobName":"pieces-sync","msg":"Upserting job"}
{"level":30,"time":1719929441195,"pid":8,"hostname":"ecc6ffa204fc","name":"RedisSystemJob#setJobHandler","jobName":"pieces-sync","msg":"Setting job handler"}
{"level":30,"time":1719929441196,"pid":8,"hostname":"ecc6ffa204fc","msg":"[redisQueueManager#init] Initializing redis queues"}
{"level":30,"time":1719929441197,"pid":8,"hostname":"ecc6ffa204fc","msg":"[migrateScheduledJobs] Starting migration"}
{"level":30,"time":1719929441199,"pid":8,"hostname":"ecc6ffa204fc","msg":"[migrateScheduledJobs] Found  0 total jobs"}
{"level":30,"time":1719929441199,"pid":8,"hostname":"ecc6ffa204fc","msg":"[migrateScheduledJobs] Migrated 0 jobs"}
{"level":30,"time":1719929441216,"pid":8,"hostname":"ecc6ffa204fc","msg":"Activepieces ce Edition"}
{"level":30,"time":1719929441225,"pid":8,"hostname":"ecc6ffa204fc","name":"RedisSystemJob#upsertJob","jobName":"trial-tracker","msg":"Upserting job"}
{"level":30,"time":1719929441226,"pid":8,"hostname":"ecc6ffa204fc","name":"RedisSystemJob#setJobHandler","jobName":"trial-tracker","msg":"Setting job handler"}
{"level":30,"time":1719929441399,"pid":8,"hostname":"ecc6ffa204fc","msg":"Server listening at http://0.0.0.0:3000"}
{"level":30,"time":1719929441399,"pid":8,"hostname":"ecc6ffa204fc","msg":"\n             _____   _______   _____  __      __  ______   _____    _____   ______    _____   ______    _____\n    /\\      / ____| |__   __| |_   _| \\ \\    / / |  ____| |  __ \\  |_   _| |  ____|  / ____| |  ____|  / ____|\n   /  \\    | |         | |      | |    \\ \\  / /  | |__    | |__) |   | |   | |__    | |      | |__    | (___\n  / /\\ \\   | |         | |      | |     \\ \\/ /   |  __|   |  ___/    | |   |  __|   | |      |  __|    \\___ \\\n / ____ \\  | |____     | |     _| |_     \\  /    | |____  | |       _| |_  | |____  | |____  | |____   ____) |\n/_/    \\_\\  \\_____|    |_|    |_____|     \\/     |______| |_|      |_____| |______|  \\_____| |______| |_____/\n\nThe application started on , as specified by the AP_FRONTEND_URL variables."}
{"level":40,"time":1719929441399,"pid":8,"hostname":"ecc6ffa204fc","msg":"[WARNING]: Pieces will be loaded from source type CLOUD_AND_DB"}
{"level":30,"time":1719929441404,"pid":8,"hostname":"ecc6ffa204fc","message":"Downgrading platform to free plan","platformId":"DvGBQ91bfbJR1sLAfocvl"}
{"level":30,"time":1719929441431,"pid":8,"hostname":"ecc6ffa204fc","time":"2024-07-02T14:10:41.431Z","file":"localPieceCache","msg":"Syncing pieces"}
{"level":30,"time":1719929441431,"pid":8,"hostname":"ecc6ffa204fc","msg":"Syncing pieces from database"}
{"level":30,"time":1719929464538,"pid":8,"hostname":"ecc6ffa204fc","reqId":"req_Ra967DSfxzfbHhlqtOXaZ","req":{"method":"POST","url":"/v1/authentication/sign-up","hostname":"192.168.1.224","remoteAddress":"127.0.0.1","remotePort":37554},"msg":"incoming request"}
{"level":30,"time":1719929464602,"pid":8,"hostname":"ecc6ffa204fc","reqId":"req_Ra967DSfxzfbHhlqtOXaZ","res":{"statusCode":403},"responseTime":64.51437200047076,"msg":"request completed"}
{"level":30,"time":1719932400056,"pid":8,"hostname":"ecc6ffa204fc","time":"2024-07-02T15:00:00.056Z","msg":"Syncing pieces"}
{"level":50,"time":1719932401130,"pid":8,"hostname":"ecc6ffa204fc","error":{},"msg":"Error syncing pieces"}
{"level":30,"time":1719936000046,"pid":8,"hostname":"ecc6ffa204fc","time":"2024-07-02T16:00:00.046Z","msg":"Syncing pieces"}
{"level":50,"time":1719936001303,"pid":8,"hostname":"ecc6ffa204fc","error":{},"msg":"Error syncing pieces"}

**Comment by abuaboud** [comment]
Hi @joshsalvi 

Sorry for late response, check on 0.30.0. It's usually due to faulty JWT_SECRET, now there is validation, make sure you generate it with sh tools/deploy.sh.

I am closing this, please reopen If you have any other questions.
