### ISSUE TITLE
Twitter Piece Create Tweet

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#505]
Actions:
**- Create tweet**

**Comment by ashrafsamhouri** [comment]
@kanarelo @abuaboud What's this blocked by?

**Comment by kanarelo** [comment]
@ashrafsamhouri I think its because twitter now requires payment for api access... Not really sure, but we need an account for testing...

**Comment by ashrafsamhouri** [comment]
@kanarelo Thanks, I'll check what's required by Twitter then

**Comment by nileshtrivedi** [comment]
Can perhaps use puppeteer in headless mode to post tweet. This is what I did for [aicombinator](https://github.com/aicombinator/bot).

**Comment by DawgZter** [comment]
The basic tier provides free api access albeit with less functionality

**Comment by abuaboud** [comment]
Created Create Tweet Piece
