### ISSUE TITLE
Mattermost bot is not working

### ISSUE THREAD

**Issue by raqibnur** [activepieces/activepieces#5054]
Mattermost bot account no longer works; I believe OAuth2 is the best solution. I used OAuth2 with Zapier and everything worked fine.
![image](https://github.com/activepieces/activepieces/assets/46986623/a1d3c83d-a482-423f-998d-5ecdaa41804a)

**Comment by abuaboud** [comment]
Hi @raqibnur 

Can you please post on community.activepieces.com and please copy the output from step output :D 

I will close this ticket, as it will get more exposure there  

Thank you for again!
