### ISSUE TITLE
[BUG]: when i created a loop flow i faced the problem

### ISSUE THREAD

**Issue by Asfak00** [activepieces/activepieces#5066]
![image](https://github.com/activepieces/activepieces/assets/108581106/ecdb9416-4610-4be6-ad99-fb8e6aa4aa38)

the branch gone overlapping in the loop shape.

**Comment by abuaboud** [comment]
Hi @Asfak00 

I think you are using very old version, Just to confirm are you are on the version 0.29.0? 

You can check from the docker image name or Platform Admin (If you are on old version, this won't be there)
