### ISSUE TITLE
[CLARIFICATION]: Redis env vars

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#5089]
The current docs (as of v0.29.1) no longer reference `AP_REDIS_URL`:
https://github.com/activepieces/activepieces/blob/0.29.1/docs/install/configurations/environment-variables.mdx

I can see that from this commit an update was made so not sure if it's just a syntax error or if it was actually removed:
https://github.com/activepieces/activepieces/commit/1ccf21f3828c7b8c31dff564bebb2d863c8be556#diff-723aaefd84bd3348bda2f2d3b39858132fe2bd4dc442aad1a8a9399c2752a553L40

Also, can you please clarify:
1. Is it necessary to set `AP_QUEUE_UI_ENABLED` and `AP_QUEUE_MODE` if `AP_REDIS_URL` is set?
2. From what I can tell `AP_QUEUE_UI_USERNAME` and `AP_QUEUE_UI_PASSWORD` are both required when `AP_QUEUE_UI_ENABLED`
 is `true` but the docs don't reflect this.
3. I can't find the AP queue UI linked from anywhere inside AP? Is it behind a paywall?

**Comment by abuaboud** [comment]
Yea it's syntax error, do you mind open pr to fix it?

No the queue is not behind paywall, It's documented there and hosted on the backend
https://www.activepieces.com/docs/install/troubleshooting

**Comment by GFoley83** [comment]
PR opened. 

However I've noticed now that the Bull queue UI is broken for me. I'll open a separate issue.
