### ISSUE TITLE
How to config webhook url correctly?

### ISSUE THREAD

**Issue by takuyasatoyama** [activepieces/activepieces#5090]
Path: /developers/piece-reference/triggers/webhook-trigger

Hello.
I am going to test web hook trigger.
When I send post request to webhook url on postman, I want to get response from run(context).
Response looks like [{message : "This is test response"}]
How to get webhook url?
How to config webhook url to the trigger of webhook pieces?
Good luck.

**Comment by kishanprmr** [comment]
Hello @takuyasatoyama ,

Inside the run function, you can access incoming webhook data using ```context.payload.body``` and retrieve the webhook URL using ```context.webhookUrl```.

**Comment by takuyasatoyama** [comment]
Thank you @kishanprmr 
I know about context.webookUrl and I built.
But I don't know how to test whether I built that correctly or not.
Thanks for your attention again.
Please help me.

**Comment by kishanprmr** [comment]
To test the webhook trigger, install [ngrok](https://ngrok.com/) on your system and execute ngrok http 4200 in your terminal. Capture the generated URL from the ngrok CLI and replace AP_FRONTEND_URL variable in the .env file with it.

**Comment by abuaboud** [comment]
I am closing this issue, please let us know If you have any other questions.
