### ISSUE TITLE
[BUG]: Selfhosted sign up screen is misleading

### ISSUE THREAD

**Issue by mks-h** [activepieces/activepieces#5097]
**Describe the bug**
The sign-up screen on a selfhosted instance looks like if it is a sign up for a cloud Activepieces account. 

I believe the cause is the newsletter chechbox, as well as ToS and privacy policy warning. These are unusual for a selfhosted installation.

**To Reproduce**
Start a new selfhosted instance with `AP_SIGN_UP_ENABLED=false` environment variable.

**Expected behavior**
Some sort of clarification that you are creating a local accout.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/51861383/ee1ab8e5-d457-43ce-b57d-1c33b285eb8d)

**Comment by matt-gribben** [comment]
Have to agree the sign up process for a self hosted system is a bit weird. It's very unclear if you are signing up for a purely local account or if your account information is also shared with the cloud platform.

**Comment by abuaboud** [comment]
Nothing is shared with the cloud, It's a bug with the flag that hides it in the community edition.

It should be already fixed in the react version un the next release 0.30.0
