### ISSUE TITLE
[REQUEST] Shopify Blog Integration

### ISSUE THREAD

**Issue by josephchoi-1** [activepieces/activepieces#5100]
Currently, there is no seamless process to create and publish blogs on Shopify directly from data stored in Google Sheets with the help of ChatGPT. Manually transferring content between these platforms is time-consuming and prone to errors.

I've love to have an integration workflow that enables automatic blog creation on Shopify from data in Google Sheets via ChatGPT. This workflow would extract content from Google Sheets, use ChatGPT to generate or refine the blog post, and then publish it on Shopify.

**Comment by abuaboud** [comment]
Hi @josephchoi-1 


Can you please post it on community.activepieces.com under the feature request, as
We will keep issues to track planned work


Thank you,
Mo
