### ISSUE TITLE
[BUG]: Bull Board UI not loading on self-host w/ official AP docker image

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#5103]
**Describe the bug**
Visiting the Bull Board UI at `https://< site >/api/ui` whilst self-hosting on v0.21.1, using the official AP docker image (not locally built) results in multiple errors in the console and the page failing to load. I've not tested other versions of the AP images.

**To Reproduce**
1. Deploy AP v0.21.1 image from Docker Hub
2. Go to `https://< site >/api/ui` and enter the username and password
3. Confirm that the page is stuck saying "loading..." with multiple errors in the console.

**Expected behavior**
To see the Bull Board UI, as shown on https://www.activepieces.com/docs/install/troubleshooting

**Screenshots**

![image](https://github.com/user-attachments/assets/2300bd5e-ae59-4cdc-9f5f-574e1efe957b)

![image](https://github.com/user-attachments/assets/93721cbc-36f4-4d1a-9577-8c919fed1f30)

**Comment by hazemadelkhalel** [comment]
The issue has been fixed and It will be a part of the next released 

Thank you for reporting the bug.

**Comment by d4mr** [comment]
Hi! could you please link to the fix commit/PR? I think we are running into the same problem and some reference would help @hazemadelkhalel

**Comment by hazemadelkhalel** [comment]
@d4mr 

Hi!, here is the link [https://github.com/activepieces/activepieces/commit/0471d2626937cae53ca396d2950992a003902da8](url)

**Comment by abuaboud** [comment]
@d4mr You can use this RC: https://github.com/activepieces/activepieces/releases/tag/0.30.0-rc.4

**Comment by hazemadelkhalel** [comment]
@d4mr this is the fix commit: https://github.com/activepieces/activepieces/commit/0471d2626937cae53ca396d2950992a003902da8
