### ISSUE TITLE
[BUG]: openAI piece continues to make API requests after flow has completed/failed

### ISSUE THREAD

**Issue by robbo21982** [activepieces/activepieces#5122]
**Describe the bug**
Self hosted 0.29.1
OpenAI piece continues to make repeated API calls after the flow has completed/failed. 
The flow has a loop with multiple OpenAI pieces in. At iteration 243 one of the pieces failed but the workflow completed as I received a notification email that is set to send at the end. 
continue in failure and retry on failure are both off. 
Once the final email had been sent, the flow continued to make API calls to OpenAI. 
Checked the run history and shows failed at iteration 243 on an OpenAI piece so the flow should not have completed and the software doesn’t think it has completed. 

No further API requests should be made after flow has completed/failed.

**Comment by kishanprmr** [comment]
Hello @robbo21982 ,

Can you please provide flow template for it to reproduce the issue?

**Comment by robbo21982** [comment]
[NEW HNF Pinterest Robolly Automation.json](https://github.com/user-attachments/files/16261970/NEW.HNF.Pinterest.Robolly.Automation.json)

**Comment by abuaboud** [comment]
I couldn't reproduce the issue today on the latest version, are you sure the key is not used anywhere or the count is correct 

Please reopen if it's still there
