### ISSUE TITLE
Encryption Key documentation

### ISSUE THREAD

**Issue by BigHoss** [activepieces/activepieces#5133]
Path: /install/configurations/environment-variables

i get errors with encryption key length and i cant find any information about what's the correct one

**Comment by abuaboud** [comment]
Hi @BigHoss 

You can generate one using Open SSL it's hex 16 https://github.com/activepieces/activepieces/blob/main/tools/deploy.sh

Do you mind open a pr to update the docs?

**Comment by yossev** [comment]
On it, will be fixed asap.
