### ISSUE TITLE
[BUG]: Cache conflicts with rebuilding of the Engine

### ISSUE THREAD

**Issue by hazemadelkhalel** [activepieces/activepieces#5163]
**Describe the bug**
In development mode, making changes and quickly refreshing the frontend before building the engine can cause issues. 

**To Reproduce**
1. Make any change in any file.
2. Refresh the frontend quickly before building.
3. [Do this multiple times if it doesn't happen the first time.]
4. See the logs

**Screenshots**
![image](https://github.com/user-attachments/assets/293c5290-6e25-4896-9273-3c9a14726c46)

**Comment by abuaboud** [comment]
@hazemadelkhalel It's fixed by you now :D
