### ISSUE TITLE
[BUG]: Google drive - New file not triggering in all cases.

### ISSUE THREAD

**Issue by MindTheMonkey** [activepieces/activepieces#5173]
**Describe the bug**
When using google drive desktop for Mac app, dragging new files into a folder will not trigger the New file trigger. However doing the exact same procedure but dropping the files in the same folder opened on google drive in your browser will trigger the event. Also manually triggering the test for you activepiece will see files coming from the desktop app. It just wont ever activate the trigger.

**To Reproduce**
1. Set up a activepiece with google drive new file as trigger.
2. Install https://www.google.com/drive/download/ on Mac
3. Locate folder and drop new files (from outside of google drive , so its technically a new upload)
4. Trigger will never activate

**Expected behavior**
In browser if you go to https://drive.google.com/drive/u/1/folders/123456-FOLDER-ID-HERE
and drop the same files. Then one by one they will trigger your piece. 

**Additional context**
This might be expected behaviour but then it should be clearly documented as 
1. It took me a lot of time to figure out what was wrong
2. It means that I need to instruct end users that they can not use desktop app if they want automation to be triggered.

**Comment by abuaboud** [comment]
Hi @MindTheMonkey,

I believe it depends on how Google Drive uploads the file. Activepieces polls the Google API for new files every X minutes (typically 5-15 minutes), depending on the instance setup.

I don't see any issues with the polling API or any settings that we can change in our side.

I am closing this issue due no action can be taken from our side, but please feel free to reopen it if you can confirm that, after the desktop app shows the files as uploaded, you can see them on the web as well.

Thank you,
Mo.
