### ISSUE TITLE
Sign In Page is redirecting to Sign up page

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#5179]
Hello Team 
Please anyone can help with this 
i am running the project with docker and env using compose file and on sign-in page it is redirecting to the signup page unable to debug any help

**Comment by PhoenixMystique** [comment]
and its only happing when ruinning with docker compose if using npm run serve:frontend then all works fine

**Comment by abuaboud** [comment]
What are the steps to reproduce? Is this clean installation? did you register before?

**Comment by abuaboud** [comment]
Closing as I can not reproduce the issue
