### ISSUE TITLE
[BUG]: activepieces.com pieces page bug

### ISSUE THREAD

**Issue by hugh-codes** [activepieces/activepieces#5184]
**Describe the bug**
The required fields on a piece's action are the inverse of what they should be. [For example](https://www.activepieces.com/pieces/actualbudget) the actualbuget import transactions fields Account ID, and Date should be required. The other fields are not required.

**To Reproduce**
1. Go to 'https://www.activepieces.com/pieces/actualbudget'
2. Click on import transactions 
3. compare field properties to [/packages/pieces/community/actualbudget/src/lib/actions](https://github.com/activepieces/activepieces/blob/main/packages/pieces/community/actualbudget/src/lib/actions/import-transactions.ts) 
4. See required fields don't match

**Expected behavior**
A pieces actions at www.activepieces.com/pieces should have the correct fields labelled as required

**Screenshots**
![image](https://github.com/user-attachments/assets/e95fb287-a386-475f-ac60-452198c03ba9)

**Comment by abuaboud** [comment]
I think @AbdulTheActivePiecer fixed it.

Thank you for reporting the bug, closing as complete.
