### ISSUE TITLE
Branches or conditional statements (if/else)

### ISSUE THREAD

**Issue by crazyTweek** [activepieces/activepieces#519]
**Is your feature request related to a problem? Please describe.**
Example: If you create a Web request to an API you want to respond based on the return value. Choosing one flow for successful requests or another if it fails. This is also relevant for other pieces (ex Code piece, choose SMS piece or email piece, based on severity or other return values)

**Describe the solution you'd like**
A solution similar to Zapiers paths would be awesome (https://zapier.com/blog/zapier-paths-conditional-workflows/).
Otherwise an if module as n8n provides. (https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.if/#branch-execution-with-if-and-merge-nodes)

**Describe alternatives you've considered**
An alternative would be creating an own piece that handles the logic or do it in a code piece. But this would completely destroy the principles of Activepieces as there are no additional pieces afterwards possible

**Additional context**

<img width="679" alt="Bildschirm­foto 2023-02-10 um 08 43 03" src="https://user-images.githubusercontent.com/6828237/218031982-dc5635d8-4a7f-48a7-b4ff-3fb914a90feb.png">
<img width="283" alt="Bildschirm­foto 2023-02-10 um 08 43 37" src="https://user-images.githubusercontent.com/6828237/218032103-5b87f59a-73a2-4d23-933d-0a06d92e8124.png">

**Comment by abuaboud** [comment]
Thank you for submitting the Issue, I will get back to you soon in this ticket.

**Comment by abuaboud** [comment]
@allcontributors please add @crazyTweek for ideas

**Comment by AbdulTheActivePiecer** [comment]
We are going to make the compare operators  + grouping of conditions similar to Zapier's

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer 

Conditional is done but we are going to support (AND/OR) groups in this sprint, and release the feature in the next week.
