### ISSUE TITLE
codeclimate

### ISSUE THREAD

**Issue by MichaelHinrichs** [activepieces/activepieces#5203]
**Describe your usecase.**
full repo analysis and and test coverage functionality.
https://developer.codeclimate.com/#overview

**Describe alternatives you've considered**

**Comment by abuaboud** [comment]
Hi @MichaelHinrichs 

Thank you for opening issue, we only use issues to track existing pieces bug (specially core), for feature requests.

Please use the community feature requests https://community.activepieces.com/c/feature-requests/9

I am closing this issue.

Regards,
Mo.
