### ISSUE TITLE
Codacy

### ISSUE THREAD

**Issue by MichaelHinrichs** [activepieces/activepieces#5205]
**Describe your usecase.**
analysis, health, coverage, security, and report functionality
https://api.codacy.com/api/api-docs#codacy-api

**Describe alternatives you've considered**

**Comment by abuaboud** [comment]
Hi @MichaelHinrichs 

Thank you for opening issue, we only use issues to track existing pieces bug (specially core), for feature requests.

Please use the community feature requests https://community.activepieces.com/c/feature-requests/9

I am closing this issue.

Regards,
Mo.
