### ISSUE TITLE
CodeScene

### ISSUE THREAD

**Issue by MichaelHinrichs** [activepieces/activepieces#5206]
**Describe your usecase.**
analyses and code-coverage API functionality.
https://api.codescene.io/v2/docs/index.html#/

**Describe alternatives you've considered**

**Comment by abuaboud** [comment]
Hi @MichaelHinrichs 

Thank you for opening issue, we only use issues to track existing pieces bug (specially core), for feature requests.

Please use the community feature requests https://community.activepieces.com/c/feature-requests/9

I am closing this issue.

Regards,
Mo.
