### ISSUE TITLE
circleci

### ISSUE THREAD

**Issue by MichaelHinrichs** [activepieces/activepieces#5217]
**Describe your usecase.**
https://circleci.com/docs/api/v2/index.html

**Describe alternatives you've considered**

**Comment by abuaboud** [comment]
Hi @MichaelHinrichs 

Thank you for opening issue, we only use issues to track existing pieces bug (specially core), for feature requests.

Please use the community feature requests https://community.activepieces.com/c/feature-requests/9

I am closing this issue.

Regards,
Mo.
