### ISSUE TITLE
Youtube New video

### ISSUE THREAD

**Issue by Applesaucesomer** [activepieces/activepieces#522]
**Is your feature request related to a problem? Please describe.**
I want to get discord notifications when particular youtube accounts upload a video or go live

**Describe the solution you'd like**
Activity (going live or upload) on a particular youtuber’s account > notification in a particular channel in discord

**Describe alternatives you've considered**
Currently utilizing https://pingcord.xyz

**Additional context**

**Comment by abuaboud** [comment]
@allcontributors please add @Applesaucesomer for ideas

**Comment by korumera** [comment]
I would love this feature as well :)

**Comment by kanarelo** [comment]
@ashrafsamhouri @abuaboud  This feature needs direction on how to handle it, because the it might have more than one way to solve it. E.g there is a PubSubSub & RSS feed. I will skip this until more information is provided on how to solve it.

**Comment by kanarelo** [comment]
- The primary blocker is youtube api quota
- Youtube has 10k points per day and each search consumes 100 points, that mean if we do polling they block us.
- The alternative is to do via RSS feeds
- https://www.youtube.com/feeds/videos.xml?channel_id=UCgImnA993V_2IbQ9seYNEzA
- We already have RSS feed piece , But this links take while from youtube to upload.

**Comment by abaza738** [comment]
Should be up when #755 merges
