### ISSUE TITLE
Issue when creating new piece

### ISSUE THREAD

**Issue by aedris0** [activepieces/activepieces#5226]
I followed the documentation [docs](https://www.activepieces.com/docs/developers/building-pieces/piece-definition) to create a new piece and ran the project in a local development environment. The new piece appears on the front end, but when added as an action and tested, I receive the following error:

Error: Cannot find module '@activepieces/piece-gelato'

**Comment by abuaboud** [comment]
Hi @aedris0 

Do you mind push the code to your branch and give us link? So we can reproduce.

Thank you for reporting the bug

**Comment by aedris0** [comment]
Hello @abuaboud,

Thanks for your reply.

We identified the issue: it occurs when running the application on Windows. However, when we tested it on Linux, it worked fine.
