### ISSUE TITLE
[BUG]: resuming flow run from webhook fails when flow has required props

### ISSUE THREAD

**Issue by no10xcoder** [activepieces/activepieces#5235]
**Describe the bug**

I'm trying to use `context.run.pause` with `PauseType.WEBHOOK`. 

The pausing works fine and it generates a webhook URL, but when triggering the webhook URL it looks like it's validating the piece input again,  which I don't think should happen when ExecutionType is RESUME, the validation then makes the run fail. 

The reason I think it's validating the props is because the error is 

`{\"file\":[\"Expected file url or base64 with mimeType, but found value: (truncated)\"]}`, and file is the name of one of my required props.

**To Reproduce**
1. Create a piece that uses `context.run.pause` with `PauseType.WEBHOOK`, make sure the piece has a required prop. Return the webhook URL so that you can easily view it in the UI.
2. Run the flow
3. Visit the webhook URL
4. Watch the flow fail

**Expected behavior**
The flow should continue when calling the webhook URL, not fail. It should not do anything with the props since the resuming has nothing to do with the flow run input.

**Comment by anasbarg** [comment]
Ok so I created the following piece action:

```ts
import { createAction, Property } from '@activepieces/pieces-framework';
import { ExecutionType, PauseType } from '@activepieces/shared';

export const ask = createAction({
  name: 'ask',
  displayName: 'ask',
  description: 'asks a user a question',
  props: {
    question: Property.LongText({
      displayName: 'Question to ask',
      required: true,
    }),
  },
  async run(context) {
    if (context.executionType === ExecutionType.BEGIN) {
      const question = context.propsValue.question;
      const answerUrl = context.generateResumeUrl({ queryParams: {} })
      context.run.pause({
        pauseMetadata: {
          type: PauseType.WEBHOOK,
          response: {
            question,
          }
        }
      });
      return {
        answerUrl // http://localhost:4200/api/v1/flow-runs/yNVpRfqt6XZCpPhHrOU5c/requests/x-_Nm-W5u_oWvTFODOPhY?answer=1234
      }
    } else {
      return {
        answer: context.resumePayload.queryParams['answer'],
      }
    }
  },
});
```
which has a required `question` parameter and uses `context.run.pause` with `PauseType.WEBHOOK` .. I ran the flow and visited the `answerUrl` returned with a query param `answer=1234` and the flow didn't fail .. am I missing something in the reproduction of this issue?

**Comment by abuaboud** [comment]
I am closing this as triggers now generates link, I will track the truncation in separate issue.
