### ISSUE TITLE
Dynamic list of properties

### ISSUE THREAD

**Issue by tpatel** [activepieces/activepieces#524]
# **Is your feature request related to a problem? Please describe.**

The integration of apps with variable parameters is not possible.

# **Describe the solution you'd like**

I would like to create a dynamic list (created asynchronously) of text properties based on one static property.

This is a similar idea that the option list that updates its values based on the `refreshers` property, except it's about creating dynamically other properties (instead of the value of the own property).

# **Describe alternatives you've considered**

An alternative would be to create a type of property that is a list of key/values. This would put some work on the end user who would have to put the right keys though.

# **Additional context**

There are two use cases that I will describe here: an image-automation api, a spreadsheet.

## **Image automation api**

The user should be able to enter a string (template ID). This would trigger an API call that would retrieve the list of available properties.

Example 1: When entering the id for this template, the UI should offer the option for the user to enter the properties `content_text`, `avatar_background_image`...
<img width="400" alt="Screenshot 2023-02-10 at 17 29 57" src="https://user-images.githubusercontent.com/494686/218145132-4a1d5b21-a6a7-47b7-a692-71ceaa1b0b21.png">

Example 2: When entering the id for this template, the UI should offer the option for the user to enter the properties `image_background_image`, `button_text`...
<img width="400" alt="Screenshot 2023-02-10 at 17 34 33" src="https://user-images.githubusercontent.com/494686/218145506-c99b16c3-d08d-4465-ab75-aa592a7130b9.png">

## **spreadsheet**

The user should be able to select a spreadsheet sheet with a static property. This would trigger an API call that would retrieve the list of columns that could be made available as properties.

**Comment by abuaboud** [comment]
@allcontributors please add @tpatel for ideas

**Comment by abuaboud** [comment]
The backend part is merged, we need to finish the frontend part.

Will mark this closed once it's merged

**Comment by abuaboud** [comment]
Now it's merged to main
