### ISSUE TITLE
[BUG]: the code editor fails

### ISSUE THREAD

**Issue by Meenaesh** [activepieces/activepieces#5249]
**Describe the bug**
When I try to add code editor to my flow to create custom integrations , the code editor doesn't allow me to type my code.
I have opened in both modes . the editor doesn't work.

**To Reproduce**
1. Go to search bar and search code
2. Click on 'code '
3. Scroll down 

**Expected behavior**
I expected to see an editor that alllows me to input my code

**Screenshots**
![Uploading Capture.JPG…]()
![Uploading 22.JPG…]()
![Uploading Capture.JPG…]()

**Additional context**

**Comment by abuaboud** [comment]
Hi @Meenaesh 

Can you update the images, they don't work

**Comment by Meenaesh** [comment]
![Capture](https://github.com/user-attachments/assets/2161e0e9-9c8a-47b3-bc8a-5a1c8176196a)
![22](https://github.com/user-attachments/assets/7ce9c8be-f90d-4ce5-afc2-47dd0357d7a7)

**Comment by Meenaesh** [comment]
> Hi @Meenaesh
> 
> Can you update the images, they don't work

yah sure .

**Comment by Meenaesh** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/175828797/354823391-2161e0e9-9c8a-47b3-bc8a-5a1c8176196a.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTYzODMsIm5iZiI6MTcyMjY5NjA4MywicGF0aCI6Ii8xNzU4Mjg3OTcvMzU0ODIzMzkxLTIxNjFlMGU5LTljOGEtNDdiMy1iYzhhLTVhMWM4MTc2MTk2YS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDQxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWVhMGUxMDAwM2NhN2NiNzNlNjJmYjUwZWQ4YmQxYmQ0MDNlNTY5NzAxYjIxMjlhYWI5ZmNkNTY0OTIyYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jo8HVQSmsM0eJD3eUImCcN-i_e7bMYacfF4bZRUok-k) ![22](https://private-user-images.githubusercontent.com/175828797/354823413-7ce9c8be-f90d-4ce5-afc2-47dd0357d7a7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTYzODMsIm5iZiI6MTcyMjY5NjA4MywicGF0aCI6Ii8xNzU4Mjg3OTcvMzU0ODIzNDEzLTdjZTljOGJlLWY5MGQtNGNlNS1hZmMyLTQ3ZGQwMzU3ZDdhNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDQxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGRmODIzMjQzMWQ4MmY1ZmRhNGNiMDg3ZTg0ZmNjYmI3ODU2ZTg2NjRlNGIxOGVjNzczOTZkMjM5NjM2ODliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N8GFjWY_1ELPOJe-boHZDeLxTKIBcdmTXekI-QP4IIM)

here you go

**Comment by abuaboud** [comment]
The whole UI is now rewritten to react, marking this as fixed,

https://github.com/activepieces/activepieces/pull/5135

Should be fixed with the react release
