### ISSUE TITLE
[BUG]: design mode issue in case of json cascading field (refresher for other fields)

### ISSUE THREAD

**Issue by ahmad-swanblocks** [activepieces/activepieces#5259]
**Describe the bug**
While developing a piece, I encountered a specific requirement where the dropdown refresher depends on a JSON field. It works fine during the initial configuration, and the flow executes properly. However, when I edit the flow piece configuration, I lose all the cascaded configurations. Is there a way to fix this, or should I consider a different approach for developing the cascaded dropdown for the JSON field?

Please note all the cascading examples use dropdown list as the cascading field (the refresher).

Thanks!

**Comment by ahmad-swanblocks** [comment]
@abuaboud Thanks for considering this issue.
BTW, I've just worked on a fix but I don't have permission to open a PR to contribute.

Basically, the fix is for the refreshable components like dynamic Property and refreshable dropdown to prevent change events from triggering on init, i.e. to ensure it fires only in the user change.

**Comment by abuaboud** [comment]
Can you please test on the react version at the main, since the whole area is now rewritten to react 

Please reopen the issue if it is there.
