### ISSUE TITLE
RSS feed new item in feed refresh interval

### ISSUE THREAD

**Issue by aryanrajseo** [activepieces/activepieces#5262]
Hi, currently using RSS feed to send an email via gmail when a new item in feed is added however the refresh interval seems to be slower than zapier and there is a delay. Wonder if it is possible to have a faster interval or manual timing to get it refreshed every 1min or 5min.

**Comment by abuaboud** [comment]
You can configure it from `AP_TRIGGER_DEFAULT_POLL_INTERVAL` for self hosted instance, for cloud It's fixed at this moment.

https://www.activepieces.com/docs/install/configuration/environment-variables
