### ISSUE TITLE
Manual Run Flow

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#527]
**Is your feature request related to a problem? Please describe.**
Triggers that run flow manually.

**Describe alternatives you've considered**
Using Webhook trigger with test flow, but It doesn't get logged in the runs, It matter because runs are great for auditing.

Requested in the discord channel.

**Comment by nileshtrivedi** [comment]
I'd love to see this. This would become relevant when flows become super-easy to create (for eg: with integration of a natural language parser like ChatGPT) which will lead to users invoking this for one-off tasks, without having to schedule them or set up a webhook trigger.

**Comment by nileshtrivedi** [comment]
I don't understand the updates on this. Is this Blocked or Completed? Couldn't find a matching PR for this either.
