### ISSUE TITLE
Possible dropdown to change connection environment (base url)

### ISSUE THREAD

**Issue by Trayshmhirk** [activepieces/activepieces#5279]
I have built a piece for ChargeKeep payment services. We have about 2 more environments which we would like to also integrate. Our current integration url is https://beta.chargekeep.com, and we would also like to have the same integration for https://crm.chargekeep.com, without having to build two seperate pieces, since the triggers and actions would be the same.

We would like, if possible, to be able to change the base url the user connects to via a dropdown, when they want to connect to ChargeKeep. For example, after a user clicks to connect, there should be two inputs, one, a dropdown, with options to choose which environment to connect to (BETA, or CRM), then the other option for the api key.

If this would be a possible feature to add, we would be grateful. Else, we would like if you could help us suggest an alternative to this integration.

Best regards,
Frank Micheal.

**Comment by abuaboud** [comment]
@Trayshmhirk 

Can you please change the authentication to use CustomAuth and include the StaticDropdown with values?
https://www.activepieces.com/docs/developers/piece-reference/authentication#custom

I am closing this issue as It's possible to make, please let me know If you have any questions.
