### ISSUE TITLE
[BUG]: HTTP piece JSON body malformed

### ISSUE THREAD

**Issue by Ozak93** [activepieces/activepieces#5284]
When POSTing a JSON body with nested JSON object(s), it results in encoding the body twice. 

see attached JSON for context
[Output (5).json](https://github.com/user-attachments/files/16512010/Output.5.json)

and this is my HTTP piece JSON body:
![image](https://github.com/user-attachments/assets/1e0159c7-c3eb-4974-9ec6-a2d3f5001bd8)

This issue is happening on HTTP piece version 0.5.0, in my old flows using HTTP piece 0.3.x the above JSON body works fine!

**Comment by Ozak93** [comment]
I tried to downgrade the HTTP piece's version thanks to @abuaboud 's instructions, and the JSON payload malformation did not occur on HTTP piece version 0.3.10! 
I tested it with another flow's webhook, Here's an image of the received payload
![image](https://github.com/user-attachments/assets/9bb9db96-b01f-4aa7-a41b-ea13fee0281e)

**Comment by Ozak93** [comment]
This is what the received payload looks like when sent via HTTP piece version 0.5.0

![image](https://github.com/user-attachments/assets/d81c8efe-ecf7-4181-9e8c-ff8e48149c9f)

**Comment by abuaboud** [comment]
This should be fixed in 0.30.0
