### ISSUE TITLE
Make the new React UI fully Open Source

### ISSUE THREAD

**Issue by alexandrudanpop** [activepieces/activepieces#5285]
React UI should not depend on EE shared. Making the UI fully open source will attract contributions and benefit the project in the long run.
This EE-Shared dependency is 99% TypeScript types that could be moved to Shared.

@abuaboud, let me know if you need help with this task after React is merged to main.

![image](https://github.com/user-attachments/assets/ef03b599-6088-4615-8949-f28e4d9292cf)

**Comment by abuaboud** [comment]
Closing in favor of

https://github.com/activepieces/activepieces/issues/3473
