### ISSUE TITLE
Change required tags on chargekeep piece actions.

### ISSUE THREAD

**Issue by Trayshmhirk** [activepieces/activepieces#5317]
![Screenshot (805)](https://github.com/user-attachments/assets/4867e07e-8349-41f6-afbc-19067492d58e)
![Screenshot (806)](https://github.com/user-attachments/assets/294eda4f-187e-46bd-8019-45f296d7477d)

I would like to have the required tags on the input fields on these actions changed to match the required fields in the actions. Currently, only a few fields are tagged as required, but on this page, a couple more are shown as required also. Although this is not the case when using the actions and it causes no issues, i would prefer for this page to reflect the actions as is.

Best regards,
Frank Micheal.

**Comment by kishanprmr** [comment]
Hello @Trayshmhirk ,

This issue has been resolved. Now, only props with `required: true` in the code will display the 'required' tag.
