### ISSUE TITLE
[BUG]: React - navigation to flows when using browser back and forward button

### ISSUE THREAD

**Issue by alexandrudanpop** [activepieces/activepieces#5329]
**Describe the bug**
Navigating to a flow, then clicking browser back button works fine. But I can't click forward button to go back to the flow I've been previously. Navigating should not remove that route from browser history.

**To Reproduce**
1. Go to a flow
2. Click on the browser back button
3. Click on the browser forward button -> button is disabled

**Expected behavior**
I can navigate with forward button to previous flow

**Screenshots**
![image](https://github.com/user-attachments/assets/05400d32-a3a6-472b-8e7f-e6f1e14add27)

**Additional context**

**Comment by abuaboud** [comment]
Should be fixed
