### ISSUE TITLE
[BUG]: .env public ? Why ?

### ISSUE THREAD

**Issue by aryasoni98** [activepieces/activepieces#535]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="711" alt="Screenshot 2023-02-12 at 1 58 41 AM" src="https://user-images.githubusercontent.com/18515597/218279827-0f338567-1719-4edf-8a66-f0aa6c3b85b2.png">

**Additional context**

**Comment by abuaboud** [comment]
That's suppose to be an example, It's written in the documentation that you should change these values if you are deploying for production, but we will add comment there to clarify.

**Comment by abuaboud** [comment]
I think the better scenario would be rename it to .env.example and create a shell script that generates random secrets in one of the deployment steps.

What do you think?
