### ISSUE TITLE
[BUG]: Unable to disable sign ups

### ISSUE THREAD

**Issue by michaeladams** [activepieces/activepieces#5357]
**Describe the bug**
In the docs, it states that you can use the AP_SIGN_UP_ENABLED env flag to enable sign ups. (And I assumed you could turn them off by setting it to false, maybe incorrectly?)
https://www.activepieces.com/docs/install/configurations#enabling-sign-up

This no longer seems to be the case from 0.28, as per breaking changes:
https://www.activepieces.com/docs/about/breaking-changes#0-28-0

> The SIGN_UP_ENABLED environment variable, which allowed multiple users to sign up for different platforms/projects, has been removed. It has been replaced with inviting users to the same platform/project. All old users should continue to work normally. 

My use case is to be able to entirely disable sign-ups, as in lock the system down to logins only.

Not sure if this is actually a regression, or the docs need to be reworded.

**To Reproduce**

Toggle the SIGN_UP_ENABLED flag to false, set sandboxed/privledge mode as per docs, and restarting the docker-container

**Expected behavior**
Sign ups to be disabled

**Comment by abuaboud** [comment]
Hi @michaeladams 

The signed up is disabled after the first user sign up, then it's by invitation only from the platform admin, please note the invited users will be also be admins, and have same privilege, as the permission module is not available in community edition.

So as long you don't invite anyone, no one can sign up for your instance, (they will get an error message when signing up)

Feel free to reopen, If you have any other questions.
