### ISSUE TITLE
Using activepieces as a standalone package

### ISSUE THREAD

**Issue by thxi** [activepieces/activepieces#5390]
Hi there,

I'm working on a small personal project and was wondering if it's possible to use Activepieces as a standalone package within my own codebase.
My workflow is quite simple (get email -> run some code -> send email), and I want to know if it is possible to do something like `import {some_trigger, some_action} from activepieces` in my project without the full deployment.

Is this feasible, and if so, could you provide some guidance on how to set it up? Thanks in advance!

**Comment by abuaboud** [comment]
Hi @thxi 

We don't officially support it (in way that we document how to use it), but people have done it before https://github.com/aicombinator/bot

All pieces are npm packages, you can import them and try to use them.

https://www.npmjs.com/search?q=%40activepieces

Regards,
Mo.
