### ISSUE TITLE
[BUG]: React - Runs table is loaded twice

### ISSUE THREAD

**Issue by alexandrudanpop** [activepieces/activepieces#5430]
**Describe the bug**
Runs table flickers (is loaded twice).

**To Reproduce**
1. Login to https://beta.activepieces.com
2. Click on Runs
3. The table flickers (loads data twice)

**Expected behavior**
The table does not flicker.

**Screenshots**
![image](https://github.com/user-attachments/assets/537f2703-4781-4cd0-b6a5-094107f2e597)

**Comment by abuaboud** [comment]
Fixed
