### ISSUE TITLE
FILE VAR is not working in docker images

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#5432]
When setting pieces source to FILE in env when running docker image its not working even i have tried to add npx run many to build all packages in the docker file itself still it not working @abuaboud is there any other way to sync it with my local DB

**Comment by abuaboud** [comment]
You can install the pieces from the project settings in the user interface, FILE variable is not meant to used in docker image / production and should be only used for development.

[Activepieces Documentation - Setting Piece Source](https://www.activepieces.com/docs/install/configurations/environment-variables#setting-piece-source)

From the documentation:
```
These are the different options for the AP_PIECES_SOURCE environment variable:

FILE: Intended for local development only. This option loads pieces directly from local files. For production environments, please consider using other options, as this one supports only a single version per piece.

DB: This option loads pieces that are manually installed in the database from “My Pieces” or the Admin Console in the EE Edition. Pieces are loaded from npm, which supports multiple versions per piece, making it suitable for production.

You can also set AP_PIECES_SYNC_MODE to OFFICIAL_AUTO, which will update the metadata of pieces periodically.
```

I am closing this ticket, please let me know If you have any other questions.

Regards,
Mo.
