### ISSUE TITLE
[BUG]: base64 input doesn't work for FILE field

### ISSUE THREAD

**Issue by kishanprmr** [activepieces/activepieces#5473]
**Describe the bug**
The FILE property currently supports either a public URL or Base64-encoded data as input. However, providing Base64 data results in the error message: 'Expected file URL or Base64 with MIME type.'

**To Reproduce**
1. Set up a flow with the 'New Email' Gmail trigger and pass the attachment data to the 'Read File as Base64' file helper action.
2. Upload the Base64 file data from the second step to Google Drive using the 'Upload File' action.
3. See error.

**Expected behavior**
File handling should be consistent throughout the all pieces. This error might occur because the file helper provides Base64 data without a MIME type, while the FILE field expects Base64 data with a MIME type formatted as `data:${mimeType};base64`.

**Comment by abuaboud** [comment]
https://community.activepieces.com/t/uploaded-gmail-attachment-to-google-drive-with-mimetype/5658/7
