### ISSUE TITLE
Test Code doesn't work

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#55]
When running the code action through the full code editor, It won't work.

Steps to Reproduce
- Create New Collection
- Create New Flow
- Add Code Action
- Open full code editor
- Click Test Code

**Comment by AbdulTheActivePiecer** [comment]
The issue here is that it still used the camel case notation for the object returned from /execute-code, so it was accessing undefined properties, will be solved after we merge [front-end-rewrite](https://github.com/activepieces/activepieces/tree/front-end-rewrite).

**Comment by AbdulTheActivePiecer** [comment]
https://github.com/activepieces/activepieces/commit/e7c61f0ffdaaf8edd002ddd1fa8279fd599201b5
