### ISSUE TITLE
[BUG]: Dev container cannot load pieces - bad decrypt

### ISSUE THREAD

**Issue by hugh-codes** [activepieces/activepieces#5502]
**Describe the bug**
Bad decrypt error when loading different pieces in dev container. 

[20:28:36 UTC] ERROR: error:1C800064:Provider routines::bad decrypt
[API]     reqId: "req_SFvoTgHSGGTcL4Tk9CJ3n"
[API]     req: {
[API]       "method": "GET",
[API]       "url": "/v1/app-connections?limit=99999&projectId=Mw4UR9d2vcEyk1MWGVOYx",
[API]       "hostname": "localhost:4200",
[API]       "remoteAddress": "127.0.0.1",
[API]       "remotePort": 36658
[API]     }
[API]     res: {
[API]       "statusCode": 500
[API]     }
[API]     err: {
[API]       "type": "Error",
[API]       "message": "error:1C800064:Provider routines::bad decrypt",
[API]       "stack":
[API]           Error: error:1C800064:Provider routines::bad decrypt
[API]               at Decipheriv.final (node:internal/crypto/cipher:199:29)
[API]               at Object.decryptObject (/workspace/dist/packages/server/api/main.js:12286:27)
[API]               at decryptConnection (/workspace/dist/packages/server/api/main.js:30283:45)
[API]               at /workspace/dist/packages/server/api/main.js:30190:38
[API]               at Array.forEach (<anonymous>)
[API]               at Object.<anonymous> (/workspace/dist/packages/server/api/main.js:30189:18)
[API]               at Generator.next (<anonymous>)
[API]               at fulfilled (/workspace/node_modules/tslib/tslib.js:166:62)
[API]       "library": "Provider routines",
[API]       "reason": "bad decrypt",
[API]       "code": "ERR_OSSL_BAD_DECRYPT"
[API]     }

**To Reproduce**
Steps to reproduce the behaviour:

1. Apple M1 ARM / Silicon Chip
2. Checkout master
3. Run dev container
4. Run npm start
5. Try to load Google-Sheets

**Expected behavior**
Pieces load without bad decrypt error

**Additional context**
I ran into this issue around Jul 26, 2024.
I suspect it might be because I'm running it on an mac with a silicon chip.
Any help is greatly appreciated :)

**Comment by hugh-codes** [comment]
Potentially related https://github.com/activepieces/activepieces/issues/5157

**Comment by abuaboud** [comment]
Thank you for opening

Yes It's the same, closing this thread and replying on the original thread.
