### ISSUE TITLE
AssemblyAI Piece

### ISSUE THREAD

**Issue by Swimburger** [activepieces/activepieces#5528]
**Describe your usecase.**
A piece that lets you use AssemblyAI's Speech AI models, transcribe, audio intelligence, LLMs with LeMUR.

I work for AssemblyAI and would be happy to contribute this piece.

**Comment by abuaboud** [comment]
That would be awesome, check our docs to build a piece.

Please let me know if you have any feedback

**Comment by Swimburger** [comment]
@abuaboud here you go!
