### ISSUE TITLE
[BUG]: React - Connection Creation issue with custom OAuth

### ISSUE THREAD

**Issue by jasonfill** [activepieces/activepieces#5555]
**Describe the bug**
When attempting to create a connection to Slack or Asana (both have a custom OAuth setup in my installation), the provider OAuth window pops up, everything looks good - but clicking the authorize button does not illuminate the save button in Activepieces. This works just fine if using the non-custom OAuth provider such as Github for example. 

**To Reproduce**
1. Add the settings for custom OAuth for a connection
2. Attempt to create a connection
3. Save button does not illuminate, but the Connect/Disconnect link changes

**Expected behavior**
Expected to be able to create a connection using custom OAuth settings.

**Screenshots**
![2024-09-10_05-02-17](https://github.com/user-attachments/assets/090c49cd-300b-4349-8ce2-37678066705b)

**Additional context**
It is possible that the custom OAuth was setup incorrectly on my side, however if that is the case it seems like an error should appear rather than the UI not working. 

This was found running with `0.30.0-rc.8`

**Comment by AbdulTheActivePiecer** [comment]
Hello @jasonfill, thank you for reporting this issue, this problem was solved with https://github.com/activepieces/activepieces/pull/5564

**Comment by AbdulTheActivePiecer** [comment]
let me build an rc and then I will close this issue with a link to it.

**Comment by AbdulTheActivePiecer** [comment]
here you go https://github.com/activepieces/activepieces/releases/tag/0.31.0-rc.1, let us know if you face any problems.
