### ISSUE TITLE
After latest update activepieces doesn't start and throw this eerror

### ISSUE THREAD

**Issue by tradexsrl** [activepieces/activepieces#5575]
i'm using docker enviroment but i get this error:
2024/09/11 08:30PM 30 | pid=8 hostname=activepieces name=seedDevData msg=skip: not in development environment 
2024/09/11 08:30PM 30 | pid=8 hostname=activepieces name=RedisSystemJob#upsertJob jobName=logs-cleanup-trigger msg=Upserting job 
2024/09/11 08:30PM 30 | pid=8 hostname=activepieces name=RedisSystemJob#upsertJob jobName=trigger-data-cleaner msg=Upserting job 
2024-09-11T18:30:34.820Z 30 | pid=8 hostname=activepieces msg=Syncing pieces 
2024/09/11 08:30PM 30 | pid=8 hostname=activepieces name=RedisSystemJob#upsertJob jobName=pieces-sync msg=Upserting job 
2024/09/11 08:30PM 30 | pid=8 hostname=activepieces msg=[redisQueueManager#init] Redis queues initialized 
2024/09/11 08:30PM 30 | pid=8 hostname=activepieces msg=[setupBullMQBoard] Queue UI is disabled 
2024/09/11 08:30PM 50 | pid=8 hostname=activepieces err={"type":"Error","message":"{\"message\":\"AP_ENCRYPTION_KEY is either undefined or not a valid 32 hex string.\",\"docUrl\":\"https://www.activepieces.com/docs/install/configurations/environment-variables\"}","stack":"Error: {\"message\":\"AP_ENCRYPTION_KEY is either undefined or not a valid 32 hex string.\",\"docUrl\":\"https://www.activepieces.com/docs/install/configurations/environment-variables\"}\n    at /usr/src/app/dist/packages/server/api/main.js:1:115748\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:166:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"} msg=[Main#main] 

AP_ENCRYPTION_KEY is already define as a 32 hex chars 
please let me know

**Comment by igalg99** [comment]
I got the same problem. I asked chatgpt and it told me : " contains non-hexadecimal characters (H, g, o, etc.). You need to replace it with a valid hexadecimal string. " 
so I have replaced it with a different key and it solved the problem but introduced a different problem. all the connections I had are gone and I could not add any new connections.
I have downgraded to version 28 but still not connections. I then put back the original  encryption key and then everything went back to a working state. I will probably stay on that version until I see there is some more robust solution to this problem.

**Comment by abuaboud** [comment]
Hi @igalg99 and @tradexsrl how are you generating keys? what is the format?

**Comment by abuaboud** [comment]
Cointext: https://github.com/activepieces/activepieces/issues/4810

**Comment by abuaboud** [comment]
I will replace the validation from:

```
    const isValidHexKey = encryptionKey && /^[A-Fa-f0-9]{32}$/.test(encryptionKey)
```
to 
```
    const isValidHexKey = encryptionKey && /^[A-Za-z0-9]{32}$/.test(encryptionKey)

```

**Comment by abuaboud** [comment]
I am not sure If that would fix your issue, I assumed everyone generated the keys using openssl command we provided, which seems not the case.

Does the above validation cover your keys?

**Comment by abuaboud** [comment]
Please upgrade to 0.30.1, I am releasing it in 30 minutes, It shouldn't show the error and If you used the same old key, It should show the connections.

Otherwise try to revert for old keys, If lost the only option is to truncate app_connections table sadly

**Comment by abuaboud** [comment]
0.31.0 is now released

**Comment by tradexsrl** [comment]
i solved going back to 0.29 , key ii'm not sure it was generated via an online tool or via the bitwarden generator
i will try with 0.31

**Comment by tradexsrl** [comment]
with 0.31 everythings is working ok as expected.
i have notice much more time to start up and being able to login 
docker image is cut in half size respect 0.29

**Comment by igalg99** [comment]
I finally had a chance to check. I can confirm that with 0.31.all is working fine as intended .
Thank you for the quick resolution!
