### ISSUE TITLE
[BUG]: Add AssemblyAI CDN logo

### ISSUE THREAD

**Issue by Swimburger** [activepieces/activepieces#5585]
**Describe the bug**
The AssemblyAI piece references the logo via this URL: https://cdn.activepieces.com/pieces/assemblyai.png

I'm attaching the color logo in SVG and PNG format for your convenience.

![profile](https://github.com/user-attachments/assets/c583a698-a8dc-4487-93c8-60aac78e6909)
<img width="500" alt="profile@2x" src="https://github.com/user-attachments/assets/24e4a7d5-4b22-4c18-85e1-c94e7c6b6f1c">

**Comment by abuaboud** [comment]
Sorry for this issue, It's now fixed.
