### ISSUE TITLE
[BUG]: Validation of dynamic fields is not working in react

### ISSUE THREAD

**Issue by rSnapkoOpenOps** [activepieces/activepieces#5589]
**Describe the bug**
Validation of dynamic fields is not working in react, which was working in angular

To reproduce you can open **Convert CSV to JSON** piece
![image](https://github.com/user-attachments/assets/4bc9fd05-eae2-41c5-9374-d2a891cacda0)

As I understand this is caused by Type.any() in  `form-utils.tsx`

```
        case PropertyType.DYNAMIC:
          propsSchema[name] = Type.Record(Type.String(), Type.Any());
          break;
```

**Comment by abuaboud** [comment]
It's older issue (https://github.com/activepieces/activepieces/issues/5589), that need to be fixed.

It would very great, We are open for contributions here as changing the schema of the form is non trivial 

I will close the older ticket and keep this one, and we should also find a way to validate on the backend.
