### ISSUE TITLE
Implement Dynamic Lists in Components

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#56]
Components Like Slack, have an option to select channel, such dropdown need to be refreshed.

The frontend should call backend to fetch the new options.

Steps to Reproduce:
- Create New Collection
- Create New Flow
- Add Slack Action
- The channel list should be dynamic depends on authentication.

**Comment by AbdulTheActivePiecer** [comment]
This is solved in [front-end-rewrite](https://github.com/activepieces/activepieces/tree/front-end-rewrite).

**Comment by AbdulTheActivePiecer** [comment]
https://github.com/activepieces/activepieces/commit/e7c61f0ffdaaf8edd002ddd1fa8279fd599201b5
