### ISSUE TITLE
[BUG]: the code piece fails, consumes sometimes too large amount of memory

### ISSUE THREAD

**Issue by LK511** [activepieces/activepieces#5637]
**Describe the bug**
When I open code to fullscreen, it sometimes consume too many memory (more than 6GB)

**To Reproduce**
1. Go to Flow
2. Click on code piece
3. Scroll down to code and open to fullscreen
4. Write some code longer than 100 rows and wait few minutes
5. It consumes all free memory

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/593880cd-f666-48c4-9669-ce07b0ec3970)

![image](https://github.com/user-attachments/assets/a82962e1-04f2-414e-ab72-183f753e2268)

**Additional context**
My code is handling Array of JSON objects, only writing code consumes too many memory

**Comment by abuaboud** [comment]
Hi @LK511 

The frontend has been rewritten to react from angular this screen no longer exists in the latest version (from 0.30.0)

We also replaced the code editor library with a code mirror which is a lightweight


Closing this ticket, feel free to reopen if you have questions
