### ISSUE TITLE
[PIECE]: Banner Bear Piece

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#564]
An Image generation tool for JPG/PNG/PDF Generation.

Current functionality
- Introduce image generation from template.

**Comment by abuaboud** [comment]
Great work! I took a look and noticed that the feature described in https://github.com/activepieces/activepieces/issues/524 could be applied here. I plan to prioritize that ticket and complete it as soon as possible, so that we can use the feature. What are your thoughts on this?

**Comment by kanarelo** [comment]
@abuaboud I think I need to read through that issue again to understand it. Will give you an answer tonight. Thanks

**Comment by kanarelo** [comment]
@abuaboud just noticed I never got back to you. Anyway, I am not really sure of dynamic properties works for bannerbear or complicates it, because, it means, we may need to have a form for every layer in the design... I have pushed what I have worked on so far
