### ISSUE TITLE
Request to change the logo image of Sperse piece

### ISSUE THREAD

**Issue by Trayshmhirk** [activepieces/activepieces#5641]
![Screenshot (873)](https://github.com/user-attachments/assets/dd15274d-8318-4dac-8563-281a296bbcb6)

Hi,

Please, i would like to request that the piece logo image be changed to the actual logo of Sperse.

Here's a reference link to the actual logo:
https://images.crunchbase.com/image/upload/c_pad,f_auto,q_auto:eco,dpr_1/rmvgb5mcek0cefrnjjk6

Thanks.

**Comment by kishanprmr** [comment]
@Trayshmhirk I will add new logo for the piece. Thank you!!

**Comment by Trayshmhirk** [comment]
Hi @kishanprmr,
This is a reminder on this issue.
I am yet to see the changes for the logo image for the Sperse piece.
I would appreciate it, if this is corrected whenever you are able to.

Thanks.

**Comment by kishanprmr** [comment]
Hi @Trayshmhirk ,

The logo is updated for (Sperse piece)[https://www.activepieces.com/pieces/sperse].
