### ISSUE TITLE
Request to change the logo image of Linka piece

### ISSUE THREAD

**Issue by Trayshmhirk** [activepieces/activepieces#5664]
Hi,

Please, i would like to request that the piece logo image be changed to the actual logo of Linka.ai.

Here's an image link to the actual logo image of the Linka piece:
https://media.licdn.com/dms/image/v2/D560BAQGjPk-Big48BQ/company-logo_200_200/company-logo_200_200/0/1701202981083/joinlinka_logo?e=2147483647&v=beta&t=4Uovs_kcCXFa8wAI4Cj1w8FkCPivbPsWAJUtus4rihc

Thanks.

**Comment by kishanprmr** [comment]
Hello @Trayshmhirk ,

The logo is updated for [linka piece](https://www.activepieces.com/pieces/linka).
