### ISSUE TITLE
[BUG]: Typing a space in the piece search causes the step become draggable

### ISSUE THREAD

**Issue by cezudas** [activepieces/activepieces#5674]
**Describe the bug**

**To Reproduce**
1. Create/Edit any flow
2. Click “Replace” an existing step (action node, make sure you don’t select the trigger node)
3. In the Piece search modal type a space in the search input at any time
4. Notice the modal closes unexpectedly and node to be “replaced” suddenly becomes turns to dragging state (mimicking user holding down on left click)

**Expected behavior**
Search input value is updated to reflect the empty space, no other side effect is perceived by the user (modal stays open).
Typing an empty space in the piece search view does not break when user adds a new piece.

**Screenshots**

https://www.loom.com/share/1640bf892cc64b4b8b7c7454c09d1ce5?sid=18f99730-507b-41e4-9606-fb37a57b67fc

**Comment by AbdulTheActivePiecer** [comment]
Hello @cezudas, funnily enough, this issue was fixed and I am about to do a release for it 😂, so I will add the link to the release once I do it and link it here, cheers. 

PR that fixed this: https://github.com/activepieces/activepieces/pull/5683

**Comment by AbdulTheActivePiecer** [comment]
here you go https://github.com/activepieces/activepieces/releases/tag/0.32.4
