### ISSUE TITLE
User friendly code window to modify code

### ISSUE THREAD

**Issue by LK511** [activepieces/activepieces#5686]
**Is your feature request related to a problem? Please describe.**
In versions before 0.30 there was possible to open code to fullscreen, now it is not possible, will you fix it?, this feature was very friendly

**Describe the solution you'd like**
Add a button to open code in a large window to easily read and modify code

**Describe alternatives you've considered**
Stay using version 0.29

**Additional context**
Version 0.29
![image](https://github.com/user-attachments/assets/8acfab36-1517-41e3-adf9-5fabecb1fa88)

New version
![image](https://github.com/user-attachments/assets/6115ed54-7a95-4f7b-aaca-2eb7c11432b2)

**Comment by abuaboud** [comment]
I would summarize the current issue with this screen:
- The Code cannot be resized vertically (It only shows 40 line of code)
- There is no code console

**Comment by Ozak93** [comment]
Yes please these options are quite useful when writing code.

**Comment by abuaboud** [comment]
The Code editor should expand vertically to it's content, and the logs is now showing up.

I am closing this ticket as done.
https://github.com/activepieces/activepieces/pull/6144
