### ISSUE TITLE
[BUG]: Regression? Google sheets - insert row - isn't allowing the mapping of values which makes it completely broken

### ISSUE THREAD

**Issue by elviskahoro** [activepieces/activepieces#5689]
When adding the Google Sheets - Insert Row step, the values field that should show up so that we can map how we want the data inserted doesn't show up at all. Here's a loom:

https://www.loom.com/share/49853ce7668c4c249bd4ad08301288f9

**Comment by kishanprmr** [comment]
Hello @elviskahoro, could you please try to reconnect and see if the issue still persists? Also, do you have any headers in the first row of the sheet?

**Comment by elviskahoro** [comment]
> Hello @elviskahoro, could you please try to reconnect and see if the issue still persists? Also, do you have any headers in the first row of the sheet?

It was breaking both when I had headers and also didn't. I think I figured out the repro though. If the sheet isn't named Sheet1 then it breaks. @kishanprmr

**Comment by abuaboud** [comment]
This has been complete rewritten, Please let us know If you still have issues.
