### ISSUE TITLE
[BUG]: Feasible to re-run from the "Flow Runs" page, but it's really unclear how one can do that from within the page of the failed run

### ISSUE THREAD

**Issue by elviskahoro** [activepieces/activepieces#5711]
I didn't even know you could re-run a failed workflow. I was re-doing the event trigger from my event gateway not from within the app until I discovered re-run.

**Comment by abuaboud** [comment]
This what we call a great feedback

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer
