### ISSUE TITLE
[BUG]: Gmail Send Mail Crashes Server

### ISSUE THREAD

**Issue by jasonfill** [activepieces/activepieces#5742]
**Describe the bug**
I created a simple flow that send an email using the Gmail piece and when it is run it crashes the server and "Killed" is added to the logs with no additional information. Ironically, the email actually sends but the flow is stuck in the Running state and server dies.

**To Reproduce**
1. Create a new flow
2. Add the Gmail piece
3. Choose to send an email
4. Configure the email settings.
5. Run the flow
6. Watch server crash and see a "Killed" message in logs.

**Expected behavior**
The flow to run without killing the server. If there is an error have the flow error, if not have it move from Running state to the completed state. 

**Screenshots**

**Additional context**
It is particular concerning that a bug in the flow could actually bring down the entire server rather than just failing the flow run.

**Comment by abuaboud** [comment]
I think it's related to worker terminate specially in dev environment, this should be fixed, please let me know if it still happens on latest version
