### ISSUE TITLE
[BUG]: BullMQ UI 404

### ISSUE THREAD

**Issue by jasonfill** [activepieces/activepieces#5749]
**Describe the bug**
The BullMQ UI no longer loads at `/api/ui/` as outlined in the [documentation](https://www.activepieces.com/docs/install/configuration/troubleshooting#runs-with-internal-errors-or-scheduling-issues). 

**To Reproduce**
1. Run Activepieces
2. Attempt to load the UI.
3. You will see a 404 error where the UI used to load. 

**Expected behavior**
The BullMQ ui to load.

**Screenshots**
Response when loading `/api/ui/`
```json
{
"statusCode": 404,
"error": "Not Found",
"message": "Route not found"
}
```

**Additional context**

**Comment by abuaboud** [comment]
@hazemadelkhalel can you please take look hehe :D

**Comment by hazemadelkhalel** [comment]
@jasonfill 
Hello jsonfill,
Can you show me your ```/packages/server/api/.env``` file

**Comment by abuaboud** [comment]
Hi @jasonfill 

Can you please test on latest version? and reopen If you still face any issues
