### ISSUE TITLE
[BUG]: Developer environment uses a very high number of file watchers

### ISSUE THREAD

**Issue by HoldYourWaffle** [activepieces/activepieces#5764]
**Describe the bug**
`npm start` uses just under 150.000 file watchers on my system, that seems excessive.

**To Reproduce**
1. Follow the [local dev env instructions](https://www.activepieces.com/docs/developers/development-setup/local)
2. Check the amount of file watches. I used [inotify-info](https://github.com/mikesart/inotify-info) on my Linux box.

**Expected behavior**
Less watchers.

**Screenshots**
![image](https://github.com/user-attachments/assets/ce78c9ab-7195-46eb-83ba-e50d05e572e8)

**Additional context**
Raising the limit on a Linux box [isn't difficult](https://watchexec.github.io/docs/inotify-limits.html), but this vibes like a misconfiguration somewhere.

**Comment by hazemadelkhalel** [comment]
I tried reproducing it again and following your steps, but it gave me fewer watchers than you and a reasonable number.

I believe VS Code itself causes a large number of watchers. For example, when I tried a smaller project, it gave about 20k watchers, and for Cursor AI, it showed 50k watchers on Activepieces.

So, I'll close the PR for now, but if you can reproduce the issue again, feel free to reopen it, and I'll look into fixing it.

![image](https://github.com/user-attachments/assets/986a35d5-2311-4f0f-bd28-fce1ae53151a)

**Comment by HoldYourWaffle** [comment]
@hazemadelkhalel I just pulled the latest main branch, but the issue seems to still be there :(
This is on a headless Debian box with pretty much nothing else running on it.

I noticed that your screenshot only has 4 nodebprocesses, with 980, 635, 232 and 45 watchers. On my system I get the same numbers, but with three additional 48.848-watcher processes and without the 232 watcher process.
