### ISSUE TITLE
[BUG]: can not connect AiTable

### ISSUE THREAD

**Issue by hudzik** [activepieces/activepieces#5845]
![Screenshot 2024-10-15 at 19-08-39 Builder Activepieces](https://github.com/user-attachments/assets/e6570c1f-8e00-452e-ae8d-ad579c4dc824)

I've tried several times.
Can not make it work
zapier work and also other automation systems

**Comment by kishanprmr** [comment]
Hello @hudzik , If you are using cloud version of AITable, use "https://api.aitable.ai" as instance URL in connection dialogbox.
