### ISSUE TITLE
[BUG]: Sub Flow Response throwing error

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#5858]
**Describe the bug**
When using `Sub Flows (Return Response)` for a flow that starts with `Sub Flows (Callable Flow)`, the following error is always thrown:
`{"message":"Please ensure the first action in the flow is Callable Flow"}`

Apologies if I'm misunderstanding how to use this. The blog post doesn't cover responses and there's no documentation.

I'm self-hosting on v 0.34.2.

**To Reproduce**
1. Import the flow JSON below or create a new flow with both pieces mentioned above and run it.

**Expected behavior**
Data should be returned

**Screenshots**
![image](https://github.com/user-attachments/assets/b333f7ce-900f-446d-ac2e-8d87753ba8bd)
![image](https://github.com/user-attachments/assets/3164a74c-2e6c-4573-a2a6-7b37882a0f47)

**Additional context**
Sample flow to import:

```json
{
  "created": "1729145219165",
  "updated": "1729145219165",
  "name": "Untitled",
  "description": "",
  "tags": [],
  "pieces": [
    "@activepieces/piece-subflows"
  ],
  "template": {
    "displayName": "Untitled",
    "trigger": {
      "name": "trigger",
      "valid": true,
      "displayName": "Callable Flow",
      "type": "PIECE_TRIGGER",
      "settings": {
        "pieceName": "@activepieces/piece-subflows",
        "pieceVersion": "~0.0.6",
        "pieceType": "OFFICIAL",
        "packageType": "REGISTRY",
        "input": {
          "exampleData": {
            "test": 123
          }
        },
        "inputUiInfo": {
          "customizedInputs": {}
        },
        "triggerName": "callableFlow"
      },
      "nextAction": {
        "name": "step_1",
        "type": "PIECE",
        "valid": true,
        "settings": {
          "input": {
            "response": "{{trigger['data']['test']}}"
          },
          "pieceName": "@activepieces/piece-subflows",
          "pieceType": "OFFICIAL",
          "actionName": "returnResponse",
          "inputUiInfo": {
            "customizedInputs": {}
          },
          "packageType": "REGISTRY",
          "pieceVersion": "~0.0.6",
          "errorHandlingOptions": {
            "retryOnFailure": {
              "value": false
            },
            "continueOnFailure": {
              "value": false
            }
          }
        },
        "displayName": "Return Response"
      }
    },
    "valid": true
  },
  "blogUrl": ""
}
```

**Comment by abuaboud** [comment]
Can you please try to upgrade to `0.34.3`

**Comment by GFoley83** [comment]
@abuaboud I've tested on `0.34.4` and that seems to work fine. The "Wait for Response" when calling the sub flow works as expected. 

However, when I use the "Test Flow" functionally in the sub flow, it just hangs forever. Whereas before the recent update, that part worked fine.

**Comment by GFoley83** [comment]
Sorry abuaboud, after some more testing, I'm still seeing issues when calling a sub flow and waiting for it to complete. It seems the "Wait for Response" flag is being ignored. I can see under Runs that the sub flow is executing successfully but the calling flow (a webhook trigger called with `/sync`) just skips over it.

I've attached two sample flows:
[Webhook - Is Email Disposable.json](https://github.com/user-attachments/files/17431772/Webhook.-.Is.Email.Disposable.json)
[Sub Flow - Is Email Disposable.json](https://github.com/user-attachments/files/17431775/Sub.Flow.-.Is.Email.Disposable.json)

**Comment by baramofme** [comment]
I am also experiencing the same error.

I'm self-hosting on v 0.34.7

The subflow is made up of only a callable trigger and a callable response block.

![image](https://github.com/user-attachments/assets/8d300581-6701-4daa-aed6-949b5fda6c61)

**Comment by shawnbure** [comment]
Same here - latest version:

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/2dc40e08-bce1-4f74-b4e0-df8f48dde070">

**Comment by snoopybubu** [comment]
same issue after pulling the latest image an hour ago. had to replace all my callable piece with webhook 😡😡😡😡

**Comment by shawnbure** [comment]
Yeah I am currently replacing the pieces with webhooks.

**Comment by abuaboud** [comment]
Hi @shawnbure , @snoopybubu , @baramofme , @GFoley83 

It's now has been fixed, sorry for that.
