### ISSUE TITLE
Builder Canvas

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#5885]
**Describe the bug**
1- Larger Flows is not centered anymore
2- Lines become zigzag If you zoom in/out of the builder (from browser zoom).
3- Clicking on step on right side, make the sidebar cover the step

**Comment by AbdulTheActivePiecer** [comment]
As an addition:

1) Add ability to select nodes and copy paste them.

2) Notes.

3) Disable/Enable step.

**Comment by AbdulTheActivePiecer** [comment]
All three bugs Mo wrote are now fixed, and the three additions I added will be put as separate issues.
