### ISSUE TITLE
[BUG]: Webhook is written as Weebhook

### ISSUE THREAD

**Issue by korumera** [activepieces/activepieces#589]
**Describe the bug**
When chosing a new trigger that (webhook, or the webhook of discord for example). It says Weebhook instead of Webhook. 

**To Reproduce**
1. Go to https://cloud.activepieces.com/flows/, create a new flow (or an existing one)
2. Click on add a Webhook, and it shows Weebhook on the piece it self and the settings panel. 
3. See error.

**Expected behavior**
It should say Webhook.

**Comment by abuaboud** [comment]
This issue made my day :joy: , Pushed the fix will be released with the next release. (Usually Wednesday)
