### ISSUE TITLE
[BUG]: the delay piece fails

### ISSUE THREAD

**Issue by anasaijaz** [activepieces/activepieces#5892]
**Describe the bug**
Delay pieces does not work in a loop after several iterations

**To Reproduce**
Add delay in the loop

**Expected behavior**
delay should work and the next piece should play

**Screenshots**
![image](https://github.com/user-attachments/assets/36350668-1a48-4297-adb2-47fe4166c5f9)

**Comment by abuaboud** [comment]
@anasaijaz Do you have flow json to reproduce the issue?

**Comment by abuaboud** [comment]
Can you please test again and let me know If it's fixed, I made a relevant update there
