### ISSUE TITLE
Change Webhook Trigger 

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#59]
The Webhook Trigger should static link on the interface (Currently it's showing that there is dynamic link that will be generated), with the following format `api_url/flows/FLOW_ID/webhook`

Please add a note this link will only works for deployed collections.

**Comment by AbdulTheActivePiecer** [comment]
This is solved in [front-end-rewrite](https://github.com/activepieces/activepieces/tree/front-end-rewrite).

**Comment by AbdulTheActivePiecer** [comment]
https://github.com/activepieces/activepieces/commit/e7c61f0ffdaaf8edd002ddd1fa8279fd599201b5
