### ISSUE TITLE
If I have more than 100 points, this piece doesn't function.

### ISSUE THREAD

**Issue by kanrun-digital** [activepieces/activepieces#5943]
https://github.com/activepieces/activepieces/blob/1fb93d340aad90718390481fee577c2e353f1fe2/packages/pieces/community/google-my-business/src/lib/triggers/new-review.ts#L90

**Comment by abuaboud** [comment]
How does this fail @kanrun-digital ? This fetch latest 100 every 5-15 minutes, do you have more than 100 new reviews in 5-15 min?

**Comment by kanrun-digital** [comment]
No, you don't understand. I have many businesses in my Google account, and
these restrictions don't allow me to select them. So, as an example, there
is a McDonald's with 1500 locations, and you have a limit of only the first
100 locations.

**Comment by abuaboud** [comment]
I think you are looking to edit this line then

https://github.com/activepieces/activepieces/blob/1fb93d340aad90718390481fee577c2e353f1fe2/packages/pieces/community/google-my-business/src/lib/common/common.ts#L69

But the maximum page size is 100 to the google, so you need to write the pagination logic to keep iterate next page
