### ISSUE TITLE
[BUG]: Code Piece - Console Missing

### ISSUE THREAD

**Issue by cderamos-2ct** [activepieces/activepieces#5975]
**Describe the bug**
Since the New UI conversion, the console is now missing from the code piece. We can no longer test our code for bugs.

**To Reproduce**
See Image: ![image](https://github.com/user-attachments/assets/0afb9656-b082-40a8-a37b-a7811d44b51b)

**Expected behavior**
Return to old UI console tests.

**Comment by abuaboud** [comment]
added back by @AbdulTheActivePiecer 

![image](https://github.com/user-attachments/assets/6e4f65c5-965a-4177-8405-89108b03089b)
