### ISSUE TITLE
[BUG]:Password Authentication Failed for PostgreSQL User "postgres" on Local Setup

### ISSUE THREAD

**Issue by Mutai-Gilbert** [activepieces/activepieces#6006]
**Describe the bug**
While trying to run Active Pieces locally using Docker, I encountered a `password authentication failed for user "postgres"`error. This issue occurs when running the setup steps provided in the repository.

**To Reproduce**
1. Clone the repository
`git clone https://github.com/activepieces/activepieces.git
cd activepieces
`
2. Run the deployment script.
`sh tools/deploy.sh
`
3. Start the containers.
`docker compose -p activepieces up
`
4. Install ngrok and expose port 8080:
`ngrok http 8080
`
5. Update the `AP_FRONTEND_URL` environment variable in `.env` with the `ngrok URL`.

**Expected behavior**
The application should start without authentication errors.

**Actual behavior**
Received the following error in the logs: `password authentication failed for user "postgres"`.

**Screenshots**

![iScreen Shoter - Code - 241107222342](https://github.com/user-attachments/assets/036214fd-9e0f-46f5-919c-aa0f707891a5)

**Additional context**
Logs:

Environment Details:

Docker version: 4.26.1 (131620)

**Comment by abuaboud** [comment]
It means that the first time you set up the database, a password was created. However, when the `.env` file was regenerated, a new password was set, which no longer matches the original one.

To resolve this, you can perform a hard reset and delete the existing database by running:

```bash
docker compose down --volumes
```
