### ISSUE TITLE
[BUG]: Update issue

### ISSUE THREAD

**Issue by sayem314** [activepieces/activepieces#6022]
After updating from 0.34.9 to 0.34.11, I’m getting a 401 error that doesn’t automatically log me out, and there’s no option to log out manually either. This error persists on the main browser, but works in incognito mode.

<img width="958" alt="Screenshot 2024-11-11 at 5 34 41 PM" src="https://github.com/user-attachments/assets/1aacabb6-fc29-400a-a829-5c150374b1c6">

**Comment by m3nu** [comment]
I'm seeing the same error after updating. Only solution was to clear all cookies and localStorage.

<img width="932" alt="Screenshot 2024-11-11 at 11 36 58" src="https://github.com/user-attachments/assets/11c4de94-ce35-4e9f-a27f-7d352bfd1b65">

**Comment by abuaboud** [comment]
Hi @sayem314 

Seems like the JWT expired or the JWT secret changed, what @m3nu suggested is correct.

Thank you,
Mo.

**Comment by sayem314** [comment]
@abuaboud correct approach would be to redirect users to login page. This error page is gonna confuse less technical users.

401 > Redirect > Login ✅
401 > Error > Clear browser data 🚫
