### ISSUE TITLE
[BUG]: Google Calendar New Event Incomplete Sample

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#606]
**Describe the bug**
I can't use all data from Google Calendar New Event.

**To Reproduce**
Use the output coming out from Google Calendar, fields like description and attendees are missing.

**Expected behavior**
I published the flow and received this object.

`{
  "kind": "calendar#event",
  "etag": "\"3353108762590000\"",
  "id": "3pfpm2kp0vvjhgknavdc3admlg",
  "status": "confirmed",
  "htmlLink": "https://www.google.com/calendar/event?eid=M3BmcG0ya3AwdnZqaGdrbmF2ZGMzYWRtbGcgYXNoQGFjdGl2ZXBpZWNlcy5jb20",
  "created": "2023-02-16T13:33:01.000Z",
  "updated": "2023-02-16T13:33:01.295Z",
  "summary": "I'm someone",
  "description": "sadasd\nsadas\nda\ns\ndsdas",
  "location": "dasdasdsa, R. dos Funcionarios, 260 - Altônia, PR, 87550-000, Brazil",
  "creator": {
    "email": "ash@activepieces.com",
    "self": true
  },
  "organizer": {
    "email": "ash@activepieces.com",
    "self": true
  },
  "start": {
    "dateTime": "2023-02-16T18:30:00+03:00",
    "timeZone": "Asia/Amman"
  },
  "end": {
    "dateTime": "2023-02-16T19:30:00+03:00",
    "timeZone": "Asia/Amman"
  },
  "iCalUID": "3pfpm2kp0vvjhgknavdc3admlg@google.com",
  "sequence": 0,
  "attendees": [
    {
      "email": "ashrafperformance@gmail.com",
      "responseStatus": "needsAction"
    },
    {
      "email": "ash@activepieces.com",
      "organizer": true,
      "self": true,
      "responseStatus": "accepted"
    }
  ],
  "hangoutLink": "https://meet.google.com/iom-zbdz-avn",
  "conferenceData": {
    "entryPoints": [
      {
        "entryPointType": "video",
        "uri": "https://meet.google.com/iom-zbdz-avn",
        "label": "meet.google.com/iom-zbdz-avn"
      },
      {
        "entryPointType": "more",
        "uri": "https://tel.meet/iom-zbdz-avn?pin=5533225904907",
        "pin": "5533225904907"
      },
      {
        "regionCode": "FR",
        "entryPointType": "phone",
        "uri": "tel:+33-1-87-40-38-79",
        "label": "+33 1 87 40 38 79",
        "pin": "743112429"
      }
    ],
    "conferenceSolution": {
      "key": {
        "type": "hangoutsMeet"
      },
      "name": "Google Meet",
      "iconUri": "https://fonts.gstatic.com/s/i/productlogos/meet_2020q4/v6/web-512dp/logo_meet_2020q4_color_2x_web_512dp.png"
    },
    "conferenceId": "iom-zbdz-avn"
  },
  "reminders": {
    "useDefault": true
  },
  "eventType": "default"
}`

**Comment by OsamaHaikal** [comment]
Hello, Thank you for the good description of this issue

I reproduced it on the cloud environment and this is the output I got

```{
  "kind": "calendar#event",
  "etag": "\"3353287269084000\"",
  "id": "106airjlg8l0h7qaeg6nuag4ri",
  "status": "confirmed",
  "htmlLink": "https://www.google.com/calendar/event?eid=MTA2YWlyamxnOGwwaDdxYWVnNm51YWc0cmkgZWUub3NhbWFoYWlrYWxAbQ",
  "created": "2023-02-17T14:18:06.000Z",
  "updated": "2023-02-17T14:20:34.542Z",
  "summary": "test event with attendee",
  "description": "description",
  "creator": {
    "email": "ee.osamahaikal@gmail.com",
    "self": true
  },
  "organizer": {
    "email": "ee.osamahaikal@gmail.com",
    "self": true
  },
  "start": {
    "date": "2023-02-17"
  },
  "end": {
    "date": "2023-02-18"
  },
  "transparency": "transparent",
  "iCalUID": "106airjlg8l0h7qaeg6nuag4ri@google.com",
  "sequence": 0,
  "attendees": [
    {
      "email": "------------------com",
      "responseStatus": "needsAction"
    },
    {
      "email": "ee.osamahaikal@gmail.com",
      "organizer": true,
      "self": true,
      "responseStatus": "accepted"
    },
    {
      "email": "--------------------------.com",
      "responseStatus": "needsAction"
    }
  ],
  "reminders": {
    "useDefault": false
  },
  "eventType": "default"
}
```

I think google don't return the fields if they are null

@ashrafsamhouri @abuaboud

**Comment by abuaboud** [comment]
Thank @OsamaHaikal  for checking it out, I think the main issue that is description field is not showing up in auto complete because the description is not in the sample data, can you please open pr to update the sample data with one you provided in the comment?

**Comment by OsamaHaikal** [comment]
Got you, sure i will :+1:
