### ISSUE TITLE
[BUG]: Wrong dependencies versions for built pieces to pack and install on a production instance

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#6134]
**Describe the bug**
When you are running Activepieces locally and try to build a piece to pack it and upload it to your production instance, the package.json of that built piece will use dependencies from the local instance instead of npm.

**To Reproduce**
1. Create a piece 
2. Run Activepieces with npm start.
3. Run nx build pieces-{your piece name}
4. Go to the piece location in /dist/packages/pieces/...
5. Check the piece package.json it will have ":link/..." for dependencies versions like the engine, instead of an npm package version.

**Expected behavior**
The built piece must use the npm packages versions instead.

**Comment by abuaboud** [comment]
Verify does not happen on the cli
