### ISSUE TITLE
[BUG]: Piece name should be validated for installing .tgz pieces

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#6135]
**Describe the bug**
when you install a piece through .tgz, the piece name can't be any string, it must be a valid npm package name.

**To Reproduce**
1. Try installing a piece with the name having spaces like "testing piece" and it will fail.
2. Switch it to "testing-piece" and it will work

**Expected behavior**
When you are installing a piece, we must validate the piece name to valid npm package name

**Comment by abuaboud** [comment]
We auto detect the name now, so this should no longer be issue
