### ISSUE TITLE
[BUG]: Redirection won't work if the url doesn't start with https://

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#6141]
**Describe the bug**
Webhook redirection won't work if the url doesn't start with https://

**To Reproduce**
1.Use this template: https://cloud.activepieces.com/templates/kbqauGeBM6imdF51qJcbH
2.Publish the flow and try hitting the webhook endpoint with /sync.

**Expected behavior**
Redirection should work whether the user adds https:// at the start or not, or at least add a note that the user must add that, if you want to allow http://.

**Comment by abuaboud** [comment]
Fixed in [https://github.com/activepieces/activepieces/pull/6255/files](https://github.com/activepieces/activepieces/pull/6255/files)
