### ISSUE TITLE
[BUG]: Ordering tables breaks pagination

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#6143]
**Describe the bug**
Currently ordering tables that have columns coming from a join, like counting the number of flows created for a project in the projects table inside the platform admin dashboard, breaks the pagination, this is stopping us from making our tables much more useful when viewing data, filters are not enough.

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/6228
