### ISSUE TITLE
Add The Ability to Terminate Running Flows

### ISSUE THREAD

**Issue by Ozak93** [activepieces/activepieces#6203]
Hello,

It would be very useful to have a "stop" or "terminate" button in the flows page for running flows.

Why would this feature be needed? Well consider my scenario, You're looping over a Google Sheet with 10,000+ rows and using chatGPT to perform an action on each row. You face an edge case and need to update the prompt used by chatGPT piece but you can't stop the flow!.

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/4302

**Comment by zjawj** [comment]
模型越多，选择越多！ 💡https://code.mayoubang.cn  免费 AI 代码工具，多种模型满足你的各种编程需求！
