### ISSUE TITLE
[BUG]: Airtable baseurl fetches from the Drip API

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#621]
**Describe the bug**
The Airtable common baseUrl fetches from api.getdrip.com instead of api.airtable.com.

Doesn't appear to break anything in any manner, however, just something I spotted while looking at some trigger examples

**To Reproduce**
You can see the error here: https://github.com/activepieces/activepieces/blob/main/packages/pieces/apps/src/lib/airtable/common/index.ts

**Expected behavior**
it to fetch from the Airtable API

**Screenshots**

**Additional context**

**Comment by abuaboud** [comment]
Thank you, It's slipped in the review process.

Assigned to @AbdulTheActivePiecer to remove it.

**Comment by AbdulTheActivePiecer** [comment]
Cheers @ShayPunter , thankfully I didn't use it as Airtable's base url, us having boilerplate, will prevent this from happening soon.
