### ISSUE TITLE
[BUG]: Exponential back off for retry on failure is at max 32 seconds, we should make it at least 1 and a half mintues

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [activepieces/activepieces#6242]
**Describe the bug**
Retry on failure is supposed to help those who are using services that have rate limiting, but 32 seconds at max, is not enough to bypass the regular 1 minute interval services have like Google sheets: https://developers.google.com/sheets/api/limits

**To Reproduce**
Create any flow that inserts into Google sheets and make it insert 1000 rows and you will see what I mean.

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/6155
