### ISSUE TITLE
Simplify Docker Container

### ISSUE THREAD

**Issue by AmadeusGraves** [activepieces/activepieces#627]
**Is your feature request related to a problem? Please describe.**
I am currently using CasaOS as a docker container manager and I have noticed that to install activepieces in docker is a bit complex, since it requires several containers connected in the same docker network to work. 

This is offered by n8n and I think it is a drawback for activepieces. 

**Describe the solution you'd like**
Wouldn't it be better to be able to install activepieces with only one container?

**Comment by abuaboud** [comment]
I agree with you, and I will provide some background for the team.

It's worth noting that CasaOS and RailwayApp do not offer support for Docker Compose. As a result, users are required to individually deploy and configure each Docker container, which can make the process more complex.

Let me discuss it with the team and see what is the best way to do it.

**Comment by abuaboud** [comment]
Currently, the activepieces are contained in a single Docker, but Redis and Postgres are kept separate. If you import it directly into CasaOS, the networks should function automatically. Additionally, I have renamed the services to correspond with the container names.

I am also going to ask them if they can list activepieces on their app store.
