### ISSUE TITLE
File Helper: Check File Type

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#6320]
We need to add new action to File Helper Piece, to check if File has certain mime type, It should be multi select with popular predefined types.<br><br>[https://github.com/activepieces/activepieces/tree/301294b0013143e2b3582aeff59fc1caf52faadc/packages/pieces/community/file-helper/src/lib/actions](https://github.com/activepieces/activepieces/tree/301294b0013143e2b3582aeff59fc1caf52faadc/packages/pieces/community/file-helper/src/lib/actions)<br><br>Tutorial to make piece: [https://www.activepieces.com/docs/developers/building-pieces/overview](https://www.activepieces.com/docs/developers/building-pieces/overview)<br><br>Use case: [https://community.activepieces.com/t/how-to-filter-attachment-and-choose-only-pdf/7135](https://community.activepieces.com/t/how-to-filter-attachment-and-choose-only-pdf/7135)

**Comment by ChineseHamberger** [comment]
I'll try this issue
