### ISSUE TITLE
Google Calendar New Event or Updated Trigger

### ISSUE THREAD

**Issue by khaledmashaly** [activepieces/activepieces#68]
Trigger on Google Calendar when new event or updated (except deleted) is created.

Property:
- Google OAuth2

Acceptance Criteria:
- Prefer Webhooks over Polling
- Sample Data is provided.

**Comment by OsamaHaikal** [comment]
test

**Comment by abuaboud** [comment]
@OsamaHaikal Now I can assigned it to you finally, Thank you for contributing for activepieces
