### ISSUE TITLE
[Webhooks] Clickup Webhooks Triggers

### ISSUE THREAD

**Issue by khaledmashaly** [activepieces/activepieces#71]
Trigger:
- TaskCreated
- Task Updated
- Task Deleted
- Task Comment Posted
- Task Comment Updated

Property:
- Clickup OAuth2

Acceptance Criteria:
- Prefer Webhooks over Polling
- Sample Data is provided in the trigger.

**Comment by ashrafsamhouri** [comment]
@abuaboud I think this card is wrong, the name is a trigger but type is action, can you correct it please?

**Comment by kanarelo** [comment]
@ShayPunter are you working on this? let me know...

**Comment by ShayPunter** [comment]
@kanarelo happy for you to do this piece, going to work on getting the Trello piece shipped in for this release :)
