### ISSUE TITLE
Hubspot Trigger Contact Added

### ISSUE THREAD

**Issue by khaledmashaly** [activepieces/activepieces#72]
- on create:
  - [update settings][settings]
  - [create subscription][create]
- on run: [verify signature][sign]
- on destroy: [delete subscription][delete]

useful info
- Webhook URL must be served over HTTPS ([source][https])

[https]: https://developers.hubspot.com/docs/api/webhooks#:~:text=The%20URL%20that%20HubSpot%20will%20send%20webhook%20notifications%20to.%20This%20URL%20must%20be%20served%20over%20HTTPS.%C2%A0
[settings]: https://developers.hubspot.com/docs/api/webhooks#manage-settings-via-api
[delete]: https://developers.hubspot.com/docs/api/webhooks#delete-a-subscription
[create]: https://developers.hubspot.com/docs/api/webhooks#create-subscriptions-via-api
[sign]: https://developers.hubspot.com/docs/api/webhooks/validating-requests

**Comment by kanarelo** [comment]
@abuaboud kindly assign
