### ISSUE TITLE
Mastodon Piece

### ISSUE THREAD

**Issue by gwenwindflower** [activepieces/activepieces#725]
Hi there! I'd love to have a Mastodon and/or more general ActivityPub piece! As the Fediverse continues to takeoff, I think this would be a powerful way to do a lot of cool stuff.

My specific use case is to take my RSS feeds and automatically post them to Mastodon. It's really easy to create an application in Mastodon with granular permissions keys that you could add to Activepieces, just need the AP side!

Thanks for listening, and keep up the great work with this amazing product!

**Comment by abuaboud** [comment]
Thank you for raising the issue!  I have moved it to the pieces board.

We have been receiving numerous requests lately, but we are working hard to create as many pieces as possible. 🙌 Hopefully, contributors can also pick this up and join in on the fun! 

Let's keep the pieces flowing! 🌟

**Comment by gwenwindflower** [comment]
sweet! i may try to contribute this if i can find a better JS'er to pair with.

**Comment by abuaboud** [comment]
I finally got sometime to work on this, opened a pr will let you know when it's merged.
