### ISSUE TITLE
[BUG]: Raspberry Pi Docker Deployment Issues

### ISSUE THREAD

**Issue by agrrajag** [activepieces/activepieces#737]
**Describe the bug**
Unable to deploy the docker image on a Raspberry Pi

**To Reproduce**
1. Follow steps to deploy the docker image on a Pi
2. Receive the following error: no matching manifest for linux/arm/v7 in the manifest list entries

**Expected behavior**
Successful Deployment

My Raspberry Pi is a 32bit ARMv7 rev 4

**Comment by abuaboud** [comment]
It's released now (0.3.5)
