### ISSUE TITLE
Port 3000 on Docker-Compose

### ISSUE THREAD

**Issue by agrrajag** [activepieces/activepieces#738]
Attempted to deploy Activepieces on my docker instance which also hosts Grafana (using its default port of 3000). I received an error that a port was already in use when Activepieces install was in progress. I looked through the Docker-Compose and noticed it had 3000:3000 listed as an exposed port. Discord support mentioned this could be removed from the compose file.

I am opening this issue to remove the 3000:3000 port from the docker-compose file if it is not needed to be exposed.

**Comment by abuaboud** [comment]
It's released now (0.3.5)
