### ISSUE TITLE
[BUG]: Several page not found on the 'Pieces example' page

### ISSUE THREAD

**Issue by Jalict** [activepieces/activepieces#741]
**Describe the bug**
All the links on the example page results in 'Page not found'
https://www.activepieces.com/docs/contributing/building-pieces/examples 

**To Reproduce**
1. Go to 'https://www.activepieces.com/docs/contributing/building-pieces/examples' 
2. Click "New Form Submission on Typeform" or similiar
3. Results in "Page not found"

**Expected behavior**
Page appears

**Screenshots**
None

**Additional context**
None

**Comment by abuaboud** [comment]
Thank you for reporting that, fixed it!
