### ISSUE TITLE
[BUG]: Docker compose with .env

### ISSUE THREAD

**Issue by kurktchiev** [activepieces/activepieces#743]
**Describe the bug**
I am trying to deploy without the use of an .env file in Portainer. This seems to not work on the activepieces image

**To Reproduce**
1. try to deploy stack by passing in the ENV variables
2. redis and postgres containers get the correct ENV vars
3. activepieces container crashes because it does not read the ENV vars

**Comment by abuaboud** [comment]
@kurktchiev, what error did you receive before the crash?

To confirm, have you executed the command "sh tools/deploy.sh"? It creates environment variables.

**Comment by kurktchiev** [comment]
no i am grabbing the docker compose and loading the .env file as regular ENV variables (with the correctly generated values for token, password, etc etc etc)

**Comment by abuaboud** [comment]
@kurktchiev Can you please provide the docker compose logs when it crashes?  I am not able to reproduce it locally

**Comment by abuaboud** [comment]
@kurktchiev I see the issue now.

I think you removed `env_file: .env` in activepieces by mistake, So it no longer reads from `.env` file

Look here at line: 13
https://github.com/activepieces/activepieces/blob/main/docker-compose.yml#L13

**Comment by kurktchiev** [comment]
all that does is to tell docker to load the ENV vars from the file. I am omitting that and passing in the variables with `-e` instead. Is the activepieces container assuming the existance of a loaded .env file in the container? seems thats the case based on behavior

**Comment by kurktchiev** [comment]
ok this looks to be a double edge bug lol, portainer is not loading the .env file in and seemingly the activepieces container is relying on being able to load from said file

**Comment by abuaboud** [comment]
@kurktchiev lol sorry I reopened the bug, but If you are passing the variables via -e It should be working fine, but what kind of error do you get on the docker logs? that would help a lot to find the root issue

**Comment by kurktchiev** [comment]
docker itself did not throw errors, but activepieces did. basically saying that it could not load the TOKEN, ENCRYPTION etc variables. I got around the problem by getting the env file done the way portainer wants it: it has to be named `stack.env`

**Comment by kurktchiev** [comment]
yes i sorted it out, which is why i closed the bug :)
