### ISSUE TITLE
API Webhook Trigger Library

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#746]
**Is your feature request related to a problem? Please describe.**
Webhooks like Clickup/Github follow a specific pattern, and can be automated.

**Describe the solution you'd like**
These APIs (clickup/github etc) may be automated by 
- Providing the webhook API endpoint
- Choosing the list of events to bind to
- Providing context like name, description, which can be callables.
- Testing the connection and providing a sample data

**Additional context**
- onEnable, subscribe to event
- onDisable, unsubscribe from event
- When the webhook endpoint is hit, check if its a verification check, otherwise, process the data, store if need be and then return result

**Comment by abuaboud** [comment]
Thank you for suggesting that.

I understand your point of view, but most of the logic for creating webhook connectors lies in the subscribe and unsubscribe HTTP requests, which are specific to each service.

While a library could help little bit with the organizing the code, it may not provide significant value beyond that.

I am going to close the issue, feel free to reopen.
