### ISSUE TITLE
XML - JSON Library/Piece

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#747]
**Is your feature request related to a problem? Please describe.**
There is a need for XML - JSON Parser

**Describe the solution you'd like**
- Provided a schema, or not, the piece should try to generate a JSON object and return it.
- It may observe an xml endpoint and trigger on change
- May take in a JSON and return an XML (optional)
- Methodology can be used to create a `Property.Xml` field

**Additional context**
- Maybe used to read swagger XML files.

**Comment by abuaboud** [comment]
We have related piece, where it take json and return xml [#1054](https://github.com/activepieces/activepieces/pull/1054/files)
