### ISSUE TITLE
Properties: Field Validation

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#771]
**Is your feature request related to a problem? Please describe.**
Theres a need for validation at property level.

**Describe the solution you'd like**
On creation of a property, there needs to be an option to provide, either a callback that can do the validation, or do the validation under the hood. 
The callable is a better option, as it can be easier to implement.

Otherwise, the input depending on type can provide its means of validation;
- for text, regex
- for number, max, min value
- for date/time, date/time format
etc

**Describe alternatives you've considered**
Validation inside the action/trigger is possible, but repetitive.

**Comment by abuaboud** [comment]
We should also check for dynamic values such as multi dropdown, for example It should be an array.

**Comment by abuaboud** [comment]
At present, our system allows each input to have a dynamic value, which can reference another variable. However, the complexity arises as these values remain unknown until the execution of the flow.

Given the system's design, which relies on variables from previous steps, we're compelled to validate these dynamic inputs at runtime, with clear error messages if validation fails.

We need an extendable validation system to handle basic validation and optional validation in proper way.

1. **ShortText**
   - Basic Validation: Check if the input is a string.
   - Optional Validation: 
     - `EmailAddress()`: Validates if the input is a valid email address.
     - `URLAddress()`: Checks if the input is a valid URL.
     - `NonEmpty()`: Verifies that the string is not empty.

Example:
```typescript
Property.ShortText({
	displayName: string;
	description: string | undefined;
	validationRules: [MinLength(5), EmailAddress()],
	required: boolean;
})
```

2. **Checkbox**
   - Basic Validation: Check if the input is a boolean.

3. **StaticDropdown**
   - Basic Validation: Checks if the selected item is in the predefined list.

4. **Dropdown**
   - Basic Validation: Check if the selected item is in the dynamically generated list.
   - Optional Validation: 
     - `RequiredField()`: Makes sure a selection is made.

5. **DateTime**
   - We should make also take UNIX timestamps  

7. **MultiSelectDropdown**
   - Basic Validation: Checks if the selected item is in the predefined list and the type is An Array

8. ***Number**
Validation already exists

**Comment by OsamaHaikal** [comment]
@abuaboud
