### ISSUE TITLE
Enhancement: Update schedule trigger 'cron' to be more user-friendly 

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#775]
**Is your feature request related to a problem? Please describe.**
To better help non-tech savvy users, it would be a good idea to update the Schedule cron to something more user-friendly.

**Describe the solution you'd like**
I propose we rename the cron area to "Run every...", and then in the selection box, we enable them to enter a number, and then have a dropdown next to it with Minute, Hour, Day, Week, and Month.

In addition, we could perhaps have a switch so users can toggle between cron or the more user-friendly 'run every...'

**Describe alternatives you've considered**
As a short-term gain to making it more user-friendly, we could perhaps have a link on there linking to a cron creator.

**Comment by abuaboud** [comment]
It's currently planned to be released in next week:

https://github.com/activepieces/activepieces/issues/711
