### ISSUE TITLE
Uploading media to WordPress?

### ISSUE THREAD

**Issue by nigelp** [activepieces/activepieces#784]
This field requires the ID of the image on WordPress, which requires uploading it using another endpoint first. Thanks.

![activepieces3](https://user-images.githubusercontent.com/97901/224428796-689aca96-ad7e-4e83-b167-2b71ab1179e7.png)

**Comment by sysads** [comment]
One of the key features for SEO is having a featured image, so it would be plus if we can reference a featured image via a URL link to image hosted on a server.

**Comment by nigelp** [comment]
Good to see this still being bounced around. Images are a crucial part of the WordPress blog post process. There must be an API which can serve free images from stock image sites like Pixabay, freeimages.com or pexels.com etc?
