### ISSUE TITLE
Google Scopes

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#802]
We need to modify the scopes of the Google Pieces into the following:

(Please do some testing to make sure the new scopes are sufficient for our triggers/actions in these pieces)

- Google Sheets
Change "https://www.googleapis.com/auth/drive" to ".../auth/drive.readonly"

- Gmail.
Change to ".../auth/gmail.modify"

- Google Calendar.
Change to ".../auth/calendar.events" and ".../auth/calendar.readonly"

**Comment by abuaboud** [comment]
@ashrafsamhouri we also need `https://www.googleapis.com/auth/calendar.readonly` for calendar.

**Comment by ashrafsamhouri** [comment]
@abuaboud Sure, I modified the original issue. Are you sure calendar.events won't do it?

**Comment by abuaboud** [comment]
> @abuaboud Sure, I modified the original issue. Are you sure calendar.events won't do it?

Yes as we are reading list of calendars in the dropdown.
