### ISSUE TITLE
Scope: StaticMultiSelect

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#803]
**Is your feature request related to a problem? Please describe.**
I would love if the user can change/modify the scope that the Keys they provide match.

**Describe the solution you'd like**
Sometimes, a user may have several (pairs of) API keys for security purposes. Example, one for reading mail only and another for sending.

As it is, when you define your `auth` property for pieces, you need to provide a scope array. The provided array can (should?) be the full list of scope, and allow the user to select the scope they need at time of making connection.

**Describe alternatives you've considered**
The alternative is to provide the list of narrowed down scopes.

can help solve #802

**Comment by abuaboud** [comment]
Related to your feature request, it would be great if users could modify the scope for the keys they provide. However, asking the user to select the required scopes could be confusing and cause issues.

For instance, with Google Sheets trigger, the Google Drive list files scope is required to construct the options in dropdown, which may not be straightforward for the user to understand. 

As a workaround, users can provide their own app credentials and edit the pieces at their own responsibility. 

For now, I am going to close the issue, but feel free to reopen it later.
