### ISSUE TITLE
[BUG]: Google blocks gmail connection

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#807]
**Describe the bug**
It appears Google blocks the OAuth request to Gmail due to the application requiring sensitive data.

**To Reproduce**
1. Make a new flow
2. Set the gmail 'new email' trigger
3. Connect a new google account
4. Popup should say 'google blocked access'

**Expected behavior**
A connection should be made to the google account without issues

**Screenshots**
https://youtu.be/Osmim-nWsyk

**Additional context**
Attempting to make automation that will send received emails into a discord channel.

Worth noting the google account is a google workspace account.

**Comment by abuaboud** [comment]
We are working on getting our app verified, but they take too long.

**Comment by abuaboud** [comment]
This should be fixed
