### ISSUE TITLE
Piece: Google Business Profile 

### ISSUE THREAD

**Issue by TheLoop705** [activepieces/activepieces#812]
**Describe your usecase.**
I want to select a business profile and create a trigger when a new review is posted. Then send the review to a Model like davinci with a prompt and reply to the review with the response from ChatGPT.

**Describe alternatives you've considered**
Zapier:
1. New Review in Google My Business
2. Send Prompt in OpenAI
3. Create Reply in Google My Business
![Screenshot 2023-03-15 145851](https://user-images.githubusercontent.com/26556639/225331632-21283aea-6d39-41d0-a19b-215a10e5be88.png)

**Comment by TheLoop705** [comment]
You can assign this to me

**Comment by abuaboud** [comment]
@TheLoop705, I have assigned you the use case. 

Please let me know if you require any assistance or have any feedback.  You can ping me on contribution channel at Discord, I am very active there.

**Comment by dongphuchaitrieu** [comment]
I'd love to see this piece on AP. Please work on it!

**Comment by ashrafsamhouri** [comment]
Closed in favor of https://github.com/activepieces/activepieces/issues/1891
