### ISSUE TITLE
Drag and drop pieces on a flow

### ISSUE THREAD

**Issue by sabuto** [activepieces/activepieces#838]
**Is your feature request related to a problem? Please describe.**
Unable to reorder pieces

**Describe the solution you'd like**
I think the ability to be able to drag and drop pieces in order to reorder them would be a good idea

**Describe alternatives you've considered**
Currently the only way is to delete and readd

**Comment by webserviceXXL** [comment]
+1

Would also really like to see this feature. Had several cases where moving a piece within the flow, would save a lot of time. Attached a screenshot of the last case. After building the flow, I recognized that I will need a condition before posting the data to the database. But then I would need to do all the setup for the HTTP request again. :(

![Screenshot-AP-get battle results-Arc-20230501_1547@2x](https://user-images.githubusercontent.com/3533300/235460659-cc73e1f2-22d7-4bb4-abd3-0ffd96721507.jpg)

**Comment by buttonsbond** [comment]
yes, the ability to move your steps around would be mighty useful - I had to start over with a flow as I was unable to do this. You have to think very carefully about the order of things, so easy to forget something.

**Comment by webserviceXXL** [comment]
> I had to start over with a flow as I was unable to do this. You have to think very carefully about the order of things, so easy to forget something.

That's exactly the same problem I have. I'm seriously wondering how other users manage this. Can't believe that they re-create the pieces again and again without being annoyed and commenting here. 🤔

**Comment by ashrafsamhouri** [comment]
Sorry about all your wasted energy redoing the steps. We're discussing this for the next sprints (2 - 3 weeks later). Please let us know if you have more info or use cases that need to be covered with this feature!
