### ISSUE TITLE
Anniversary Cron; For Birthdays/Holidays and Billing

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#842]
**Is your feature request related to a problem? Please describe.**
There is a need for crons that happen every month (on the same date) or yearly on the same date.

**Describe the solution you'd like**
Anniversary cron follows the anniversary billing model, which means the date of the month of the effective date except as provided in this definition. For example, if the effective date is July 15, 2023, then the anniversary billing date is the 15th of the month. If the anniversary billing date is a day in a month that does not exist in each month (e.g., the 31st), then the anniversary billing date will be the last day of the month. 

For example, if the anniversary billing date is the 31st, then in February, April, June, September, and November, the anniversary billing date will be February 28 or 29, depending on the year, and the 30th for April, June, September, and November.

So, the cron can either follow the "monthly" or "yearly" models. The yearly model happens on the same day every year, much like birthdays.

**Describe alternatives you've considered**
I have considered a cron that runs every day, but runs the check as the algorithm above

**Additional context**

**Comment by abuaboud** [comment]
As far as I know you can specify date in unix, for example  `0 0 15 1 *` this means `At 12:00 AM, on day 15 of the month, only in January`

If it's common use case we can add it as an action in the new schedule piece.

https://github.com/activepieces/activepieces/pull/833

What do you think?

**Comment by abuaboud** [comment]
I am going to close the issue as it is already supported in the cron expression trigger. If it is a common requirement, we might consider adding a specific trigger in the schedule piece for it.
