### ISSUE TITLE
[BUG]:  Test flow failed on a Mac because isolate - it's not a binary

### ISSUE THREAD

**Issue by Sofianebenabdallah** [activepieces/activepieces#846]
**Describe the bug**
 I try to launch locally on a Macbook Air M2, with docker it works fine, but if I launch the project manually I got this error when I try a trigger : [21:14:36 UTC] ERROR: [7Ja2TLVT2EUeeVppu8w57] Error executing flow
    err: {
      "type": "Error",
      "message": "Command failed: /Users/sofianebenabdallah/Documents/GitHub/activepieces/packages/backend/src/assets/isolate-arm --box-id=99 --cleanup\n/bin/sh: /Users/sofianebenabdallah/Documents/GitHub/activepieces/packages/backend/src/assets/isolate-arm: cannot execute binary file\n",
      "stack":
          Error: Command failed: /Users/sofianebenabdallah/Documents/GitHub/activepieces/packages/backend/src/assets/isolate-arm --box-id=99 --cleanup
          /bin/sh: /Users/sofianebenabdallah/Documents/GitHub/activepieces/packages/backend/src/assets/isolate-arm: cannot execute binary file

              at ChildProcess.exithandler (node:child_process:419:12)
              at ChildProcess.emit (node:events:512:28)
              at ChildProcess.emit (node:domain:489:12)
              at maybeClose (node:internal/child_process:1098:16)
              at Socket.<anonymous> (node:internal/child_process:456:11)
              at Socket.emit (node:events:512:28)
              at Socket.emit (node:domain:489:12)
              at Pipe.<anonymous> (node:net:316:12)
      "code": 126,
      "killed": false,
      "signal": null,
      "cmd": "/Users/sofianebenabdallah/Documents/GitHub/activepieces/packages/backend/src/assets/isolate-arm --box-id=99 --cleanup"
    }

**Comment by Sofianebenabdallah** [comment]
@TxOne Thank you. HoW can i fix it ?

**Comment by TxOne** [comment]
I fixed it, but i don't know why.
try docker-compose.dev.yml

**Comment by abuaboud** [comment]
I'm sorry for not replying sooner. We use a tool called "isolate" to keep our code separate. 

To use run the project in development mode, you need to have "isolate" installed on your computer. 

We suggest to use the Dev Container or any of following methods listed there.
https://www.activepieces.com/docs/contributing/development-setup/local-development

Feel free to reopen, If you still have issue.
