### ISSUE TITLE
Add a delay  - seconds, minutes, days 

### ISSUE THREAD

**Issue by Sofianebenabdallah** [activepieces/activepieces#847]
**Is your feature request related to a problem? Please describe.**
Currently, we have a feature to add a delay in seconds but with a limit of 5 minutes. This limit is not flexible enough for my use case, where I want to be able to set a delay in seconds, minutes, or days.

**Describe the solution you'd like**
I would like to have the ability to set a delay in seconds, minutes, or days, with no limits on the maximum value. This will allow me to send reminders after a specified amount of time, such as sending a follow-up email after 3 days if the original email has not been read.

**Describe alternatives you've considered**
A user suggested using another flow with a trigger every minute to follow up on unread emails, but this is not user-friendly for the end user. I would prefer a more intuitive and streamlined solution integrated into my current system.

**Additional context**
This feature would be useful for automating follow-up tasks and improving my workflow.

**Comment by AbdulTheActivePiecer** [comment]
We will keep the < 5 minutes delays as they are, if a delay goes longer we will change its state to "paused".

**Comment by nileshtrivedi** [comment]
I am starting to experiment with this. My plan is to add two new actions to the delay piece: `delayFor` and `delayTill`. The first one is like the current delay but without the 5 minute limit. `delayTill` will take a future timestamp. I'd be keeping the existing `delay` action so as to not break any existing flows, but that should be deprecated.

**Comment by IanKnighton** [comment]
For us, it would be handy to be able to delay a launch of a workflow by a number of seconds. 

We have a mono repo with several independent services. While they all have completely independent Workflows, they all try and create a tag. If we have a change that will trigger multiple at once, there becomes a race condition as to who will actually get the tag without it being a duplicate. 

I'm currently looking at just adding a `sleep` action of some sort, but that seems very hacky.
