### ISSUE TITLE
Webhook trigger return value

### ISSUE THREAD

**Issue by brasilikum** [activepieces/activepieces#863]
**Is your feature request related to a problem? Please describe.**
I would like to give some feedback to the system calling the webhook.

**Describe the solution you'd like**
Allow me to specify an arbitrary object to return via the response body.

**Describe alternatives you've considered**
There could also be an "execution_id" returned on calling the webhook, with which the calling system can consult the status of the execution.
Upside: This works better for long running tasks.
Downside: Complexity. Many systems allow you to do GET requests and act on it's result. They don't allow you to implement what is basically a async task management system.

**Additional context**
I brought this up in the discord chat in the context of an RSS filter I would like to build, where the external system consults activepieces, which looks up an external RSS feed and returns a filtered list of RSS entires

**Comment by abuaboud** [comment]
Great suggestion! It should be an optional feature.

Currently, all flow executions go through a queue, which allows us to throttle the number of executions. However, in this case, we would need to skip the queue, and we would no longer be able to control the amount of traffic the worker can handle.

Another implementation detail to consider is how the response should look in the builder. One suggestion is to create a response piece and use it to return the response. The downside is that it might not be a straightforward experience and may require some frontend work to restrict the response only when there is a sync webhook.

I'll leave this ticket open for others to join the discussion.

**Comment by AbdulTheActivePiecer** [comment]
This is now unblocked.
