### ISSUE TITLE
Allow usage of puppeteer in a piece

### ISSUE THREAD

**Issue by nileshtrivedi** [activepieces/activepieces#870]
**Is your feature request related to a problem? Please describe.**
I'd like to automate actions on websites that do not offer an API. 

**Describe the solution you'd like**
[Puppeteer](https://pptr.dev/) is an NPM package that lets Javascript control a browser. I'd like to be able to create pieces that make use of puppeteer to perform actions on sites in a real browser session. Typically, this browser would be a chromium instance running on a server in headless mode (no visible GUI).

**Describe alternatives you've considered**
None.

**Additional context**
A similar tool is [Playwright](https://playwright.dev).

**Comment by abuaboud** [comment]
Adding notes from our discussion in discord.

The current issue today is with webpack and code piece, I think we should get rid of webpack and use pnpm for node_modules caching.

**Comment by Arffeh** [comment]
My vote is for Playwright
