### ISSUE TITLE
column trigger of new row in google sheets.

### ISSUE THREAD

**Issue by sengerr** [activepieces/activepieces#884]
**Is your feature request related to a problem? Please describe.**
Google sheets , specific column - new row item and column as a trigger (example is when we split data coming in from stripe or square [customer name splits to  "customer"  then "name"] Trigger on the "Name" column

**Describe the solution you'd like**
When the allow a specific column of a new row to be a trigger, for example if the "Name" or if 2 flows fill in a google sheet, when there is a sum in this column complete a new flow.

**Describe alternatives you've considered**
Zapier and Make

**Additional context**
=split(INDIRECT(ADDRESS(ROW(),COLUMN()-1)) ," ") used on the Stripe "Customer Name"
When Name is triggered add them to zoom as a registrant.

**Comment by abuaboud** [comment]
Hi @sengerr, I think it would be possible to add a branch piece after new row trigger and decide whether to continue or do nothing based on the column value.

Would this solve the problem?

**Comment by abuaboud** [comment]
Closing the ticket due inactivity, feel free to reopen
