### ISSUE TITLE
User Experience - Data Editing

### ISSUE THREAD

**Issue by sengerr** [activepieces/activepieces#888]
**Is your feature request related to a problem? Please describe.** 
Add drag and drop style or drop down choices for data actions: stop, proceed, if else casing, filter and delay for non-techincal users. This is to capture users that struggle with coding or speaking geek,

**Describe the solution you'd like**
 Filtering inbound data so a specific data set, allow flow to proceed or stop... (bonus component: and if stopped add to a stop log)

An example is for sales:
Data coming in from stripe or square is items sold:
- If sold item = shirt - trigger flow shirts
- if sold item = pants -trigger flow pants

My example is for zoom participants if they buy friday, sat or sunday they get added to specific google sheet tab so we can eject non payers from the event.

**Describe alternatives you've considered**
Manual export and imports

**Additional context**
When the sales come it, only action based on specific stripe or square data

Simplify the

**Comment by abuaboud** [comment]
I think branch piece can solve this problem: https://www.activepieces.com/docs/pieces/flow-controls/branch

Please check it out and let me know what do you think
