### ISSUE TITLE
[BUG]: the code piece fails

### ISSUE THREAD

**Issue by raghav39** [activepieces/activepieces#909]
**Describe the bug**
Flow is getting stuck in an infinite loop after adding slack piece

**To Reproduce**
1. Create a new flow with webhook as an entry point
2. Add second block as slack block
3. Config of the slack block: Message to user, choose user name, inside message choose integration as slack

**Expected behavior**
Slack message should be sent

**Screenshots**
<img width="340" alt="Screenshot 2023-03-28 at 6 57 03 PM" src="https://user-images.githubusercontent.com/11975721/228253257-14878668-651c-41bc-9f6f-ad962a17c8a7.png">

**Additional context**

**Comment by abuaboud** [comment]
Update: found way to reproduce it let me check what's going on.

**Comment by abuaboud** [comment]
The issue exists only at cloud.activepieces.com, I will announce this issue which I finish setup status.activepieces.com.

Thank you for reporting!
