### ISSUE TITLE
Moving Experience Enhancement

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#928]
In this video: https://app.birdeatsbug.com/sessions/gBWUc-Z2AE0DL7zPW8xEnCpLsGDNuAmFDDrBDSgGLuZA
The flow disappeared suddenly and had to be recentered to be discovered again.

It happened several time with this person but I'm unsure how to reproduce it.

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer Could you reproduce this?
