### ISSUE TITLE
Enhancement: HTTP Request Timeout & Return Response Code

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#931]
**Is your feature request related to a problem? Please describe.**
Not a problem, just looking to build an uptime monitoring service from within Activepieces

**Describe the solution you'd like**
Adding the following to HTTP Request:
- Timeout (if it doesn't get a response from the site within X seconds)
- Returning status code from the site by default

**Describe alternatives you've considered**
An alternative solution I can implement would be some code which would do the request and parse it accordingly

**Comment by bibhuty-did-this** [comment]
@abuaboud I would like to take this up.

**Comment by bibhuty-did-this** [comment]
> http piece to not fail on error

@abuaboud 
Just confirming my understanding here. You want me to send an empty response in case the request fails right?

**Comment by abuaboud** [comment]
> > http piece to not fail on error
> 
> @abuaboud Just confirming my understanding here. You want me to send an empty response in case the request fails right?

I think instead of throwing an error, if this option is turned on, we can try and catch it and return it as response to prevent http piece from failing.

**Comment by bibhuty-did-this** [comment]
Adding [document](https://axios-http.com/docs/req_config) for future reference if needed
