### ISSUE TITLE
Private Pieces

### ISSUE THREAD

**Issue by Willianwg** [activepieces/activepieces#943]
**Describe the solution you'd like**
It would be awesome if we could create private pieces.

**Comment by khaledmashaly** [comment]
Here are some possible approaches

### approach 1
- import custom pieces as npm tar.gz archives
- use `pnpm link` to install pieces during flow runs
- pros
    - pieces are private
    - no need to publish to npmjs.com
- cons
    - no easy way to share custom pieces with other users (maybe we can create a marketplace?)

### approach 2
- import custom pieces as public npm packages published to npmjs.com
- use `pnpm add` to install pieces during flow runs
- pros
    - pieces can be developed once and shared with multiple users
- cons
    - pieces must be published to npmjs.com
    - pieces are not private

**Comment by nileshtrivedi** [comment]
Another potential way to model private piece is to describe a collection of incoming and outgoing webhooks which serve the role of triggers and actions respectively.

**Comment by jmls** [comment]
The cons for approach #2 are not entirely correct

You could support private npm registries , then both the cons are removed

**Comment by abuaboud** [comment]
@jmls We will support private registries later, for now the public one is released and it can be imported from clicking on dashboard avater and specify the npm package.

https://www.activepieces.com/docs/contributing/building-pieces/publish-piece
