### ISSUE TITLE
[BUG]: Google sheets randomly unauthenticating, making the trigger no longer work

### ISSUE THREAD

**Issue by ShayPunter** [activepieces/activepieces#946]
**Describe the bug**
The Google Sheets piece periodically randomly unauthenticates me, making the piece not trigger

**To Reproduce**
1. Setup a Google API key
2. Input it into google sheets trigger
3. Let the trigger run
4. It'll randomly unauthenticate (might have to wait a bit though)

**Expected behavior**
I would expect it to remain authenticated so the flow can continue to run

**Additional context**
logs: https://gist.github.com/ShayPunter/5665a77e554ce2e4ec4f226fde56dc4d

**Comment by abuaboud** [comment]
@ShayPunter Let's me debug this, I will leave one running for over an hour.

**Comment by ShayPunter** [comment]
@abuaboud thanks, its worth noting I have a self-hosted instance as that could effect the testing
