### ISSUE TITLE
Postgresql Piece

### ISSUE THREAD

**Issue by Arffeh** [activepieces/activepieces#957]
**Describe your usecase.**
Postgresql Piece to perform queries, or retrieve data to send to the next piece in the flow.

Bonus points if this can be done over an SSH tunnel to access non-exposed postgres hosts (a common scenario)

**Comment by Immortalin** [comment]
@abuaboud when is this hitting production? I don't see Postgres available as trigger piece on Activepiece cloud.

**Comment by abuaboud** [comment]
@Immortalin Currently postgres support actions only.

Please open new issue with your usecase for the trigger.

I will add it to the board 😁
