### ISSUE TITLE
Curl Piece

### ISSUE THREAD

**Issue by Arffeh** [activepieces/activepieces#961]
**Describe your usecase.**
Having a more advanced piece like curl for when it's required, with the full breadth of options available, for full customization of headers etc.

Returning the exit code means being able to branch based on if an error code happened, or to abort the flow entirely.

This piece would be more of a fallback piece, when no other piece is suitable.

**Comment by abuaboud** [comment]
I think HTTP piece today covers these options, closing feel free to reopen.
