### ISSUE TITLE
Docker Piece

### ISSUE THREAD

**Issue by Arffeh** [activepieces/activepieces#963]
**Describe your usecase.**
Connect to a docker socket to perform tasks, such as:

- Start container
- Stop container
- cleanup specific volumes/containers (good with schedule trigger)

Would allow for doing things like doing a oneshot container on a schedule, or starting a container on a webhook (!)

**Comment by abuaboud** [comment]
This out of the scope, as currently activepieces is not desktop application.

If you want to run this on the server, It could be done in SSH piece, once it's done
