### ISSUE TITLE
Time Condition Piece

### ISSUE THREAD

**Issue by Arffeh** [activepieces/activepieces#964]
**Describe your usecase.**
Being able to change flow execution based on the time of the day would be great.

For example, running through a flow that executes each hour to process stuff, however if it's past 6PM, go through a different second half.

**Comment by abuaboud** [comment]
There is already schedule trigger, wouldn't adding branch condition after It and ignore the execution if the condition met solve this issue? 

If it's very common case, I would vote to extend the schedule piece to that usecase, but I can't see it's common.

What do you think?

**Comment by Arffeh** [comment]
Hello there,

I was hoping to avoid having to have two duplicate monstrously huge flows, and remembering to actually update both. It makes it simpler to have one flow with a branch in the middle.
Like for example one flow, I need to perform one single extra action to a generated file whenever it's pulled prior to 9PM.
Having to clone the entire workflow feels cludgy instead of just having a time condition to shim in one extra step.

**Comment by abuaboud** [comment]
I mean without cloning, you could make it trigger every hour and do the branch piece to check wether to continue or not.
